### ISSUE TITLE
No module named pip

### ISSUE THREAD

**Issue by SBillion** [sdispater/poetry#1004]
- [x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19.1 Tessa
- **Poetry version**: 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/SBillion/fd5be58af06d345ca09f3e907bb8be0f

## Issue
I just installed poetry from the get-poetry script and try to make it work. I'm using python3.7 . When I tried to add a package, I got this:

 ```
Command ['/home/seb/.cache/pypoetry/virtualenvs/poetry-demo-_YOEyiNj-py3.7/bin/python', '-m', 'pip', 'install', '--no-deps', '-U', 'markupsafe==1.1.1'] errored with the following output: 
/home/seb/.cache/pypoetry/virtualenvs/poetry-demo-_YOEyiNj-py3.7/bin/python: No module named pip
```

**Comment by drunkwcodes** [comment]
Please revert and `apt install python3-pip` first.

**Comment by mozartilize** [comment]
or recreate your virtualenv, just experienced this issue days ago, hope this help

**Comment by SBillion** [comment]
Deleting virtualenv for recreate helped me

**Comment by yadygarovadt** [comment]
Hi, I'm still running in this issue after venv reconfiguration and reinstallation of pip3 on debian machine.
Python version: 3.7

**Comment by a-berg** [comment]
Hi, having this exact problem with poetry when I try to use python 3.8 instead of python 3.6.9 (the default in Ubuntu).
May it be related to ensurepip being disabled for Debian and Ubuntu systems?

**Comment by arainboldt** [comment]
I'm having this problem on MacOS 11.14.6, poetry 1.1.4. Running poetry install builds the venv fine, but then if I try to remove or update an installed package I get the error No module named pip. I've deleted and re-built the venv 4 times already today. not sure what the issue is.

**Comment by supern8ent** [comment]
I had this problem in GitLab CI when I upgraded from python 3.7 to 3.8. The solution was to clear the CI runner caches.

**Comment by realyashnag** [comment]
In my case, the poetry install command kept failing inside the docker container because of this. Turns out the existing `.venv` directory was not being ignored when building the docker image. Adding it to `.dockerignore` worked just fine.
