### ISSUE TITLE
how to modify PS1 with poetry shell?

### ISSUE THREAD

**Issue by whoizit** [sdispater/poetry#1006]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

how to modify PS1 while I run poetry shell?
I try to do PS1="(poetry env) $PS1" poetry shell but it not helps

**Comment by nuno-andre** [comment]
It seems that you're going through #571 

Besides the foregoing, you can simply modify `activate` script. And if you only need to prepend some parenthesized string to current PS1, `--prompt` venv's argument will do it for you. In your example:

```
    python -m venv path/to/folder --prompt "poetry env"
```
