### ISSUE TITLE
Add a clarification to the example from README

### ISSUE THREAD

**Issue by vovanz** [sdispater/poetry#102]
The [Dependency resolution](https://github.com/sdispater/poetry#dependency-resolution) section in README gives an example, where `pipenv` fails with `Could not find a version that matches pbr!=0.7,!=2.1.0,<1.0,>=0.6,>=2.0.0` and poetry resolves this dependency by installing `pbr (0.11.1)`.

I do not understand, how is `0.11.1` a solution, it does not satisfies `>=2.0.0` requirement.

I think that an explanation why is `0.11.1` a good solution should be added to the README.

Also, it would be very interesting to read a detailed description of how exactly `poetry` resolves dependencies.

**Comment by sdispater** [comment]
Yes, that's something that came up before so I might as well do it.

But basically:

oslo.utils==1.4.0 requires:

- pbr (>= 0.6, != 0.7, < 1.0) - oslo.i18n (>= 1.3)

So, poetry will take the latest version of oslo.i18n which requires:

- pbr (!= 2.1, >= 2.0)

Poetry will detect the conflict and backtrack oslo.i18n to version 2.1.0 which requires:

- pbr (>= 0.11, < 2.0)

This is compatible with the requirements of oslo.utils and pbr==0.11.1 will be installed

**Comment by emddudley** [comment]
I too was confused by the `README`, and it took me a few tries to understand your explanation here. I think the key is:

> Poetry will detect the conflict and backtrack

Perhaps you should lead this statement about how poetry can automatically resolve conflicts between transitive dependencies. Then follow with the `oslo.utils` example, demonstrating the difference between tools that do and do not do this resolution.

**Comment by sdispater** [comment]
The README has been updated with a breakdown of what poetry does in this particular case.
