### ISSUE TITLE
Choose different wheel files for different platforms / Wildcards for file dependencies

### ISSUE THREAD

**Issue by huynh91** [sdispater/poetry#1028]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hi, 
I have a library packaged in wheel files:
- For Linux:   mylib-0.1.0-cp36-cp36m-linux_x86_64.whl
- For Windows: mylib-0.1.0-cp36-cp36m-win_amd64.whl

How should the pyproject.toml file look like? My attempt (not working): 

```
mylib = {file = "../pkg/python/mylib-0.1.0-cp36-cp36m-linux_x86_64.whl", platform="linux"}
mylib = {file = "../pkg/python/mylib-0.1.0-cp36-cp36m-win_amd64.whl", platform="windows"}
```
I think this can be solved by allowing wildcards in file name: 
```
mylib = {file = "../pkg/python/mylib-0.1.*.whl"}
```
Is this option (or something similar) available? 
Thanks.

**Comment by drunkwcodes** [comment]
Maybe relates to #558.

So you have a wheel archive directory, and want to install a package available in the directory regardless of its target platform?

Do you mean like this? https://stackoverflow.com/questions/48183160/how-to-pip-install-whl-on-windows-using-a-wildcard

**Comment by huynh91** [comment]
Yes, that's exactly what I want. Currently I use pip for that.
