### ISSUE TITLE
Poetry doesn't resolve on MacOs Mojave

### ISSUE THREAD

**Issue by wilfredinni** [sdispater/poetry#1047]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOs Mojave
- **Poetry version**: 0.12.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/wilfredinni/8e51c186d7b352d506933380349c7c7a

## Issue

`poetry update` command doesn't work on my Mac. Just stay in `resolving dependencies`. My machine with Manjaro Linux, a 7 years old laptop, resolves in 8 seconds the same pyproject.tom.

**Comment by tuchandra** [comment]
Tried this out because I'm also running Mojave on my Mac, but I wasn't able to repro. I got the following output:

```
Package operations: 24 installs, 0 updates, 0 removals

Writing lock file

  - Installing pytz (2019.1)
  - Installing sqlparse (0.3.0)
  - Installing appdirs (1.4.3)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.1.0)
  - Installing click (7.0)
  - Installing django (2.2)
  - Installing entrypoints (0.3)
  - Installing mccabe (0.6.1)
  - Installing more-itertools (7.0.0)
  - Installing pluggy (0.9.0)
  - Installing py (1.8.0)
  - Installing pycodestyle (2.5.0)
  - Installing pyflakes (2.1.1)
  - Installing six (1.12.0)
  - Installing toml (0.10.0)
  - Installing black (19.3b0)
  - Installing coverage (4.5.3)
  - Installing django-debug-toolbar (1.11)
  - Installing flake8 (3.7.7)
  - Installing mistune (0.8.4)
  - Installing psycopg2-binary (2.8.2)
  - Installing pytest (4.4.1)
  - Installing python-decouple (3.1)
```

I am on Poetry 0.12.11, though; what happens if you downgrade? Perhaps a bug was introduced in the newest release.

**Comment by wilfredinni** [comment]
@tuchandra the first time I install the dependencies I have no problem either. Can you try to use `poetry update` and see what happens now? Thank you.

**Comment by tuchandra** [comment]
Running it again works fine:

```
Updating dependencies
Resolving dependencies... (0.3s)

Nothing to install or update
```

:/

**Comment by wilfredinni** [comment]
Removed Poetry, all the virtualenvs and cleaned the cache folder, then reinstalled it. All is good now.

**Comment by hangtwenty** [comment]
@wilfredinni sounds about right

Here is a related issue, which may offer a bit of explanation (TLDR has to do with cachecontrol/filelock libs)

https://github.com/sdispater/poetry/issues/832#issuecomment-480708729

**Comment by hangtwenty** [comment]
@wilfredinni  Since this seemingly is not about OS, and since there are known resolutions, could you  edit the ticket title and/or close the ticket?

**Comment by wilfredinni** [comment]
> @wilfredinni Since this seemingly is not about OS, and since there are known resolutions, could you edit the ticket title and/or close the ticket?

Sure.
