### ISSUE TITLE
How to use Poetry for a Django project

### ISSUE THREAD

**Issue by fab10m** [sdispater/poetry#1050]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I can't figure out how to use Poetry for a Django project with custom (not third party) apps. Suppose we have a typical Django project structure:
```
[projectname]/
├── [projectname]/
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── [app-1]/
│   ├── __init__.py
│   ├── models.py
│   ├── views.py
│   ├── urls.py
├── [app-2]/
│   ├── __init__.py
│   ├── models.py
│   ├── views.py
│   ├── urls.py
├── [app-n]/
│   ├── __init__.py
│   ├── models.py
│   ├── views.py
│   ├── urls.py
└── manage.py
```
What should I do to use poetry to manage project dependencies?
Or maybe poetry is designed to manage single app, but not a whole project?

Thanks,
Fabio

**Comment by drunkwcodes** [comment]
You can try to add a `pyproject.toml` next to the `setup.py`.

https://poetry.eustace.io/docs/pyproject/

**Comment by AlexOQ** [comment]
I usually run `poetry init` next to `manage.py`.
