### ISSUE TITLE
PEP-517 build does not match poetry.lock

### ISSUE THREAD

**Issue by ipmb** [sdispater/poetry#1052]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14.4
- **Poetry version**: 0.12.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ipmb/7acf540e1bad06c4812ad329326c0ad3

## Issue

If I try to `pip install .` a project with this [`pyproject.toml`](https://gist.github.com/ipmb/7acf540e1bad06c4812ad329326c0ad3) I get the error:

> ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.1 which is incompatible.

`poetry.lock` is correctly pinned to `urllib3==1.24.2`, but pip installs `urllib3==1.25.1`.

Should I expect the pip build-system to use dependencies from `poetry.lock` or can it only work against the dependencies as defined in the `pyproject.toml`?

**Comment by sdispater** [comment]
Pip only understands build systems specified in `pyproject.toml` and has no notion of what's inside `poetry.lock`
