### ISSUE TITLE
Programmatic API to access information of a Poetry project

### ISSUE THREAD

**Issue by uranusjr** [sdispater/poetry#1053]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I’m wondering whether there is a (Python) API available to use Poetry as a whole, or to access information in a project? Specifically, I am interested in reading `poetry.lock` and feed it into other tools. I realise it is a TOML file, but I would hope there is a more reliable way than to reverse-engineer the format.

**Comment by vlcinsky** [comment]
I am not aware of any API but when we created small utility to convert `pyproject.toml` and `poetry.lock` into `requirements.txt` declaring versions and hashes (this is probably close to what `poetry export` offers in version 1.0 which is in alfa now), it was quite straightforward to read directly from toml.

**Comment by dbanty** [comment]
I don't think there's a documented API anywhere, but the code is very well written and super usable!  Maybe someone will put some docs together for those of us who need to do some more advanced stuff.  I have used poetry programmatically a bit in some of my build scripts, here's something that might be useful:

```python
import os
from pathlib import Path

from poetry.poetry import Poetry

poetry = Poetry.create(Path(os.getcwd()))  # main object representing Poetry for your app
locker = poetry.locker  # Object used to create/manage the lock file
repository = locker.locked_repository()  # Will lock your project if it's not yet, then give you a Repository

repository.packages  # This is a list of poetry.packages.Package, use them however you need them
```

**Comment by sdispater** [comment]
The idea is to make Poetry usable as a library, to interact with projects built with it or to use part of it in a different context. I don't plan on restricting it.

However, I don't consider the API of the internals of Poetry quite stable yet. Some features are still being improved and changed  and the internal parts are sometimes modified to make these changes possible.

**Comment by uranusjr** [comment]
Thanks for the response! Some projects like to keep the Python API internal, so I figured I should ask first before using it, for ressurance. I would dig into the Python code and figure out what can do.

**Comment by sethatron** [comment]
Could we look into re-opening this? Poetry could be very powerful for automating the creation of development environments inside of remote environments like Kubernetes. My team is building an automation platform in EKS and it would be great if I could use Poetry to build out the required libraries within the docker container from within Python

**Comment by orgroman** [comment]
I agree, I think this issue should be reopened.
Poetry offers the ability to create plugins but without documentation to poetry API it's harder for the developers.
In my case, I want to extend poetry to support workspaces such as monorepo and have similar capabilities to yarn changeset.
I can't do any of it without knowing how to use poetry API.

**Comment by ZMarouani** [comment]
Trying to create an integration test to run at the end of a Gitlab pipeline to verify dependencies consistency between multiple used projects , would have been very interesting to use a Poetry Api , I upvote reopening this issue
