### ISSUE TITLE
Recursive dev-dependencies

### ISSUE THREAD

**Issue by sybrenstuvel** [sdispater/poetry#1055]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

TL;DR: it would be great if we could say "include the dev-dependencies of package X as dev-dependency of this package"

We're working on a larger project that consists of a handful of Python projects. We have a base project that provides the framework (called 'Pillar'), and the rest of the functionality is made as several smaller projects that serve as extensions to the framework. The unit tests for these extensions should be using the same dev-dependencies as the framework itself.

We currently have `pyproject.toml` files like this. In the Pillar framework:
```
[tool.poetry.dependencies]
python = "~3.6"
Flask = "~1.0"

[tool.poetry.dev-dependencies]
pytest = "~4.4"
responses = "~0.10"
```

In an extension:
```
[tool.poetry.dependencies]
python = "~3.6"
pillar = {path = "../pillar"}
pyjwt = "~1.7"
```

It would be perfect if we could have a declaration like this in the extension, to make it pick up the dev-dependencies of the Pillar framework:

```
[tool.poetry.dev-dependencies]
pillar = {path = "../pillar"}
```

**Comment by sdispater** [comment]
This would make things more complex in the Poetry codebase for something that I see as an edge case so it's unlikely to ever be implemented.
