### ISSUE TITLE
`poetry exit` to safely exit the virtualenv

### ISSUE THREAD

**Issue by darrenleeweber** [sdispater/poetry#1057]
Add a `poetry exit` command to exit a poetry shell; do so safely when the poetry shell is not active already.  Since `exit` will exit a bash shell when a `poetry shell` is not active, it's "dangerous".  At present, there are issues asking for some form of "marker" that a poetry shell is active (i.e. there seems to be no easy way to tell whether or not a poetry shell is active without issuing another `poetry shell` to get poetry feedback about it).  A `poetry exit` command is an additional feature that provides a safe exit, regardless of whether a `poetry shell` is active or if the status of it is visible.

**Comment by Victor-Savu** [comment]
I'm not sure if it helps, but what I find myself doing is:
```
source $(poetry env info -p)/bin/activate
```
using the preview version of poetry. This activates the virtualenv in my current shell which gives me the prompt indicator as well as the option to call `deactivate` as with any virtual environment.

**Comment by hangtwenty** [comment]
Related to @Victor-Savu ‘s comment: #571

**Comment by hangtwenty** [comment]
I could see the utility in your suggestion @darrenleeweber ; though maybe, “poetry shell --exit”? I don’t think it needs another top-level command. Then if Poetry-subshell was not already active, it can print a warning, but still exit-0-OK.

**Comment by carlosperate** [comment]
I would like this feature as well, either `poetry shell --exit`, `poetry env exit`, or something along those lines would do.
