### ISSUE TITLE
Does Poetry have an equivalent of `gui_script` type entry point in setup.py?

### ISSUE THREAD

**Issue by tovop** [sdispater/poetry#1059]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
Does Poetry have an equivalent of `gui_script` type entry point in setup.py? I am using that for an entry point to launch a desktop app (gui) without the additional console window.

Poetry is awesome. Thanks!

**Comment by drernie** [comment]
FYI, even though this is stale I had the same question.

Normally I run my GUI (KivyMD+Trio) app on macOS with:
```
poetry run python quiltsync/main.py
```
I tried call that via cli_script:
```
[tool.poetry.scripts]
quiltsync = "quiltsync.main:run"
```
After `poetry install` the `run` function gets invoked properly.
I can even see the app icon in the dock, but it just hangs without actualizing bring up the GUI.

Is there any simple reason why this doesn't work?

**Comment by evadeflow** [comment]
Same. I previously had this in my `pyproject.toml` file:

```
[project.gui-scripts]
tryphop = "tryphop.__main__:main"
```

Running `pip install -e .` would create an entry point script containing (the moral equivalent of) the following in my virtualenv:

```python
#!C:\Users\evadeflow\projects\python\tryphop\venv\Scripts\pythonw.exe
import re
import sys
from tryphop.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

What it actually does is create a `tryphop.exe` *binary* that wraps invocation of the above script. I don't do much development on Windows, so I'm not clear on what sorcery is involved here. In case it helps poetry devs, here's a very 'Windows-y'-looking bit of XML contained in the wrapped binary:

```
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>PAPADDINGXXPAD
```

 I've been able to work around the lack of direct support for GUI scripts in poetry by creating a script called `trypgui.py` with contents that are nearly identical to what's shown above:

```
#!pythonw.exe
import re
import sys
from tryphop.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

and then adding this line to `pyproject.toml`:

```toml
[tool.poetry.scripts]
tryphop = "tryphop.trypgui:main"
```

This works for my purposes, as this is a personal project that I never intend to distribute. Obviously, it would be better if poetry supported this directly. I'm probably not the right person to submit a PR, but I'd be happy to test any fix that somebody more knowledgeable on the Windows side might care to suggest.

I do recommend that this ticket be re-opened or recreated as a specific feature request: this is definitely something poetry should support...
