### ISSUE TITLE
`poetry run` fails when provided argument containing quoted string

### ISSUE THREAD

**Issue by chrahunt** [sdispater/poetry#1066]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 0.12.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [link](https://gist.github.com/chrahunt/6e289256d7fc3d84acfd8171b6184254)

## Issue

When running a script (defined in pyproject.toml), if any argument contains a quoted portion with spaces then the subcommand fails.

```
$ poetry run hello
hello from main
$ poetry run hello '"hello world"'
  File "<string>", line 1
    import sys; from importlib import import_module; sys.argv = ['hello', 'hello
                                                                               ^
SyntaxError: EOL while scanning string literal
```

Re-running with verbose output is not possible:

```
$ poetry -vvv run hello '"hello world"'

[FileNotFoundError]
[Errno 2] No such file or directory: 'run': 'run'

run <args> (<args>)...

$ poetry run -vvv hello '"hello world"'

[FileNotFoundError]
[Errno 2] No such file or directory: '-vvv': '-vvv'

run <args> (<args>)...
```

**Comment by chrahunt** [comment]
Still relevant.

**Comment by finswimmer** [comment]
Is this the same like #1302 which might be fixed soon by https://github.com/sdispater/poetry/pull/1550?

**Comment by chrahunt** [comment]
Yes, same issue. Thanks @finswimmer.
