### ISSUE TITLE
Allow building sdist and wheel with different files

### ISSUE THREAD

**Issue by Cito** [sdispater/poetry#1067]
Poetry has an `include` setting in pyproject.toml that allows specifying additional files to be included in the distribution (e.g. tests, docs, config files). This works, but it seems what you specify here will be included in *both* the source distribution and the wheel.

A common practice is to put stuff like tests into the source distribution only, but not into the wheel. You can achieve this with distutils by putting this additional stuff into MANIFEST.in which will be used only for the source distribution. I currently see no way to achieve the same with poetry. Can this be added as a feature? Or am I overlooking something?

**Comment by sdispater** [comment]
Like I said in #1109, I plan on making the packages section of the pyproject.toml file support specifying the format for which the package should be included (no format meaning all of them).

```python
[tool.poetry]
# ...
packages = [
    { include = "my_package" },
    { include = "tests", format = "sdist" },
]
```

**Comment by sdispater** [comment]
This has been added in #1133
