### ISSUE TITLE
Cannot deactivate virtualenv activated by poetry shell

### ISSUE THREAD

**Issue by hemanta212** [sdispater/poetry#1068]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch (WSL)
- **Poetry version**: 0.12.14, 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When the virtualenv is created there is not deactivate script in the bin folder. 

          $ poetry init
          $ poetry shell # makes the virtualenv and activates it
          $ which python # output -> /home/h/.cache/pypoetry/virtualenvs/neovim-0u1dB-Kx-py3.7/bin/python
          $ deactivate  # deactivate no such command

I updated to preview 1.0.0a2  and did everything again but it didn't fix the issue. 

However I might add that manually activating the virtualenv by source activate does work
     
            $ source /home/h/.cache/pypoetry/virtualenvs/neovim-0u1dB-Kx-py3.7/bin/activate
            (neovim-0u1dB-Kx-py3.7) $ deactivate # deactivate is recognized and bash autocompletes it

Is there any diffrence in poetry shell and sourcing bin/activate processes?

**Comment by hangtwenty** [comment]
A bit related to #571, you may be interested in that as well

**Comment by hangtwenty** [comment]
@hemanta212 if using “poetry shell” it is opening a subshell where the virtualenv is active. To exit that you exit the subshell: “exit” (ie normal shell exit)

For the case of changing your shell’s virtualenv in-place, see #571 regarding “source $( ... small command to get path to poetry virtualenv activate script ...)”

**Comment by aalok-sathe** [comment]
Can there be any indication of an active `poetry` subshell? It is confusing to still be a subshell even after deactivating the `venv`, and one can lose track and accidentally close, say, a screen session or a remote connection over ssh by issuing `Ctrl-D`
