### ISSUE TITLE
Poetry does not respect the `develop = false` option when installing from git/http

### ISSUE THREAD

**Issue by a-musing-moose** [sdispater/poetry#1080]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu Linux 19.04
- **Poetry version**: 0.12.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Related to but different from: https://github.com/sdispater/poetry/issues/1073

We have a private library we install from Github, this library was written with the aid of Poetry and as such has _no_ `setup.py`. 

Installation fails when pip 19.1 is installed due to Poetry attempting to install it in _editable_ mode. 

In this instance editable mode is not desired or needed. I noted that for directory based installed you can specify `develop = false` to have poetry install in a non-editable mode. But this does not appear to be an option when installing from git/http.

**Comment by abn** [comment]
@a-musing-moose this should work with `poetry-0.12.16` and `pip-19.1.1`. Assuming the following example matches the scenario you have described.

```
$ poetry --version
Poetry 0.12.16
$ poetry run pip --version
pip 19.1.1 from /home/abn/.cache/pypoetry/virtualenvs/poetry-issue-1080-py3.7/lib64/python3.7/site-packages/pip (python 3.7)
$ poetry add --git git@github.com:abn/cafeteria.git cafeteria

Updating dependencies
Resolving dependencies... (1.8s)

Writing lock file


Package operations: 3 installs, 0 updates, 0 removals

  - Installing pyyaml (3.13)
  - Installing six (1.12.0)
  - Installing cafeteria (0.19.0-dev 6dc1422)
```

**Comment by Danmou** [comment]
This is still an issue with Poetry 0.12.17. The cause is [line 229 in pip_installer.py](https://github.com/sdispater/poetry/blob/f4803e91bca440e6f4af6ad54e396d01c024a76f/poetry/installation/pip_installer.py#L229):

    pkg.develop = True

In my opinion it would make a lot more sense if this was changed to `False`. I can't think of a reason why you would need to install a freshly cloned git repo in editable mode. Not all packages work when installed in editable mode.

**Comment by abn** [comment]
@Danmou I have proposed a fix that will, for now, respect the `develop` flag. Personally, I agree that `develop` in `Package` should default to `False`. However, this will be a breaking change and better proposed in another issue/pull.

**Comment by 0anton** [comment]
Not sure why this is closed. The issue is still there in the current poetry 1.0.5.
