### ISSUE TITLE
Clarify, whether poetry uses only the given repository, or whether it uses Pypi as a fallback

### ISSUE THREAD

**Issue by HolgerPeters** [sdispater/poetry#1089]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

#559 gives me the impression that the described config replaces pypi as the source repository and not just provides a mirror.

https://poetry.eustace.io/docs/repositories/#install-dependencies-from-a-private-repository makes it sound as if it is a fallback by using "also".

> From now on, Poetry will also look for packages in your private repository.

**Comment by dbanty** [comment]
Adding a source still uses PyPI as a fallback. I haven’t looked at the code, but I use a private repo with Peotry in multiple projects and can confirm it treats it like an extra-index-url. It will try your private repo first for all packages, then fall back to PyPI.

**Comment by HolgerPeters** [comment]
Ah, I now found the corresponding discussion on whether this is the desired functionality #331 

I would say this ticket can be closed because the current logic is properly described then.
