### ISSUE TITLE
Can't install packages that have dots in their names

### ISSUE THREAD

**Issue by uyar** [sdispater/poetry#109]
The package is found but can not be installed. The dot is replaced with a dash and then the package with the dashed name can't be found. For example:
```bash

$ poetry add wheezy.web
Using version ^0.1.485 for wheezy.web

Updating dependencies
Resolving dependencies.........


Package operations: 1 install, 0 updates, 0 removals

Writing lock file

  - Installing wheezy-web (0.1.485)
                                                                                
[VenvCommandError]                                               
Command ['pip', 'install', '--no-deps', '-r', '/tmp/wheezy-web-0.1.485l7n3up  
cmreqs.txt'] errored with the following output:                               
Collecting wheezy-web==0.1.485 (from -r /tmp/wheezy-web-0.1.485l7n3upcmreqs.  
txt (line 1))                                                                 
  Could not find a version that satisfies the requirement wheezy-web==0.1.48  
5 (from -r /tmp/wheezy-web-0.1.485l7n3upcmreqs.txt (line 1)) (from versions:  
 )                                                                            
No matching distribution found for wheezy-web==0.1.485 (from -r /tmp/wheezy-  
web-0.1.485l7n3upcmreqs.txt (line 1))                                         
```

The same thing happens with `zope.interface` so I'm guessing this goes for all packages that have dots in their names.

**Comment by jacebrowning** [comment]
`poetry` appears to be changing dots to dashes. I specifically renamed one of my packages on PyPI (`coverage.space` => `coverage-space`) because I noticed that dotted names we're going to cause a bit of trouble in TOML.

**Comment by sdispater** [comment]
I will look into this.

It should not change dots to dashes since dots are accepted inside package names.

**Comment by jacebrowning** [comment]
This also affects a dependency's dependencies:

```
$ poetry --version
Poetry 0.10.0-alpha.0

$ poetry add drf-yasg==1.4.0
...
- Installing ruamel-yaml (0.15.37)

[VenvCommandError]
Command ['pip', 'install', '--no-deps', '-r', '/var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/ruamel-yaml-0.15.37powk8ptereqs.txt'] errored with the following output:
Collecting ruamel-yaml==0.15.37 (from -r /var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/ruamel-yaml-0.15.37powk8ptereqs.txt (line 1))
  Could not find a version that satisfies the requirement ruamel-yaml==0.15.37 (from -r /var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/ruamel-yaml-0.15.37powk8ptereqs.txt (lin
e 1)) (from versions: )
No matching distribution found for ruamel-yaml==0.15.37 (from -r /var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/ruamel-yaml-0.15.37powk8ptereqs.txt (line 1))
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

where the correct name is `ruamel.yaml`.

**Comment by bertjwregeer** [comment]
I am currently running into this issue as well:

```
Riley:pyramidtesting xistence$ poetry install
Installing dependencies from lock file


Package operations: 2 installs, 0 updates, 0 removals

  - Installing zope.interface (4.5.0)
                                                                                                                                                                                                                                 
[VenvCommandError]                                                                                                                                                                                                
Command ['pip', 'install', '--no-deps', '-r', '/var/folders/jy/3csvdt_s3ys8sdn_123w89t00000gp/T/zope-interface-4.5.0xz2icqzdreqs.txt'] errored with the following output:                                                      
Collecting zope-interface==4.5.0 (from -r /var/folders/jy/3csvdt_s3ys8sdn_123w89t00000gp/T/zope-interface-4.5.0xz2icqzdreqs.txt (line 1))                                                                                      
  Could not find a version that satisfies the requirement zope-interface==4.5.0 (from -r /var/folders/jy/3csvdt_s3ys8sdn_123w89t00000gp/T/zope-interface-4.5.0xz2icqzdreqs.txt (line 1)) (from versions: 4.4.0, 4.4.1, 4.4.2)  
No matching distribution found for zope-interface==4.5.0 (from -r /var/folders/jy/3csvdt_s3ys8sdn_123w89t00000gp/T/zope-interface-4.5.0xz2icqzdreqs.txt (line 1))                                                              
                                                                                                                                                                                                                                 
install [--no-dev] [--dry-run] [-E|--extras EXTRAS]
```

I was able to work around this by installing it manually using:

```
poetry run pip install zope.interface==4.5.0
```

**Comment by jacebrowning** [comment]
@sdispater I installed `0.9.1` but it doesn't seem to have this fix. Please confirm. ✌️

**Comment by sdispater** [comment]
@jacebrowning I just tested on `0.9.1` and it works fine on my end.

**Comment by zh0uquan** [comment]
I am trying with toml file but it gives me a version error:
```
[tool.poetry.dependencies]
python = "^3.5"
delegator.py = { git = "https://github.com/kennethreitz/delegator.py.git", branch = "master"}
```

**Comment by sdispater** [comment]
@zh0uquan You have to put quotes around `delegator.py`:

```toml
[tool.poetry.dependencies]
python = "^3.5"
"delegator.py" = { git = "https://github.com/kennethreitz/delegator.py.git", branch = "master"}
```

**Comment by bertjwregeer** [comment]
@tblazina 

`poetry add dask -E complete`

Will add `dask` with extras of "complete", and this will appear in your pyproject.toml file:

```
dask = {version = "^1.1",extras = ["complete"]}
```

**Comment by tblazina** [comment]
@bertjwregeer, exactly what I was looking for. I didn't realize from the documentation that this is how one uses the extra flag.  Thanks a lot!

**Comment by medley56** [comment]
I believe the behavior of replacing periods with hyphens is still an issue in Poetry 1.2.2.

I just ran 
```
poetry add aws-cdk-aws-s3objectlambda-alpha
```
and got the resulting string added to my pyproject.toml
```
aws-cdk-aws-s3objectlambda-alpha = "^2.50.0a0"
```
If I change the - to a . Poetry cannot find the package on PyPI.

**Comment by clintonroy** [comment]
```
poetry add aws-cdk.aws-s3objectlambda-alpha
```

works for me. Please, always be super specific in bug reports, give exact strings, and exact errors.

**Comment by medley56** [comment]
@clintonroy 

It does work. I'm not arguing that but @sdispater said in this thread on May 17, 2018 that Poetry should _not_ be replacing periods with hyphens. I'm pointing out that Poetry is still replacing periods with hyphens and that the solution of quoting the dependency in pyproject.toml does not fix it as @sdispater suggested on Jan 3, 2019.

**Comment by neersighted** [comment]
Poetry is now writing the canonical name of a package to pyproject.toml instead of a pretty name. Unlike before, where this caused bugs, Poetry reads the name as a canonicalized name as well. This is not a bug, and the information in this issue is well out of date. This is one of many reasons that requesting support/clarification in an old issue can be fraught -- I would encouraging opening a new issue if you think you have encountered a bug in the future, as you'll get more engagement/visibility there as well.

**Comment by medley56** [comment]
@neersighted Thanks! That makes sense. The good news is that now when people find this thread, they'll also find your comment!

**Comment by neersighted** [comment]
This issue is only tangentially related to what you are experiencing, @janbaykara. If you are experiencing a package that will not run/lock correctly, please reproduce it in a clean container or VM and provide a step by step reproduction (with project files) and complete verbose mode (`-vvv`) command output as a bug report.
