### ISSUE TITLE
What style is used for cli?

### ISSUE THREAD

**Issue by Webysther** [sdispater/poetry#1090]
I saw the style is very similar to composer, looks great and i want to use in my projects! Great job!

- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

**Comment by jacebrowning** [comment]
This CLI is build using https://github.com/sdispater/cleo.
