### ISSUE TITLE
Can't add local package

### ISSUE THREAD

**Issue by paymog** [sdispater/poetry#1091]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: osx 10.14.4
- **Poetry version**: 0.12.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/paymog/5b23c8273b3349c747ab39c04d80d6af

## Issue

My company publishes a private package called pysolvvy. One of our projects, the one in the gist above, uses this package. I've been working on the pysolvvy repo and I'd like to add the local version before pushing so that I can perform some testing. Luckily, poetry seems to support this with `poetry add <package> --path <path to package>`. However,  when I execute that I get an error:

```
 ❮❮❮ poetry add pysolvvy --path ../../pysolvvy/dist/pysolvvy-3.3.0.tar.gz -vvv
Using virtualenv: /Users/paymahn/solvvy/ml-pipeline/intent/venv

[ValueError]
Package pysolvvy is already present

Exception trace:
 /Users/paymahn/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/paymahn/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/paymahn/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/paymahn/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/paymahn/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /Users/paymahn/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /Users/paymahn/.poetry/lib/poetry/console/commands/add.py in handle() at line 63
   raise ValueError("Package {} is already present".format(name))
```

It seems adding a local package isn't supported if that package already exists. It would be great if the existing package could be overwritten by the local one when this command is executed.

**Comment by chrahunt** [comment]
`poetry add` currently fails adding any package with any options (`--git`, `--path`, `--extras`, `--optional`) if the package is already in the dependencies you are trying to add it to (dependencies or dev-dependencies). If this behavior is changed (no opinion either way) then it should be changed for all of them.

**Comment by paymog** [comment]
So is the solution to remove it and then add from local?
