### ISSUE TITLE
Ability to override excludes from vcs

### ISSUE THREAD

**Issue by mwchase** [sdispater/poetry#1094]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
Use case: Using Poetry with a generated Python codebase.

I have a project with the following basic structure:
```
.
├── README.rst
├── input-to-code-generator
│   └── ...
├── pyproject.toml
├── src
│   └── project
│       ├── __init__.py
│       └── generated code...
└── tests
    ├── __init__.py
    └── test_project.py
```
(I tested this without a src dir as well, and the results were the same).

I wanted to avoid tracking the same code in two forms, and relying on the code generator to build via poetry, so I did the following:

- Poetry is configured (or rather, left in the default configuration) to rely only on the generated code.
- Only the input is tracked in the vcs; the src directory is ignored.

According to my tests on little toy git repositories, the only reason this is working for me at all is that I'm not using git. In case mercurial gets supported, I'd like either some way to override the "this directory is excluded by the vcs" behavior, or guidance for a better way to accomplish the above.

I realize this is a niche use case, but I haven't encountered any problems with my setup so far, so it would be nice to have insurance against future breakage.

**Comment by mwchase** [comment]
I switched to using pre-commit hooks and (the equivalent of) a makefile target to avoid using the ignores, so this isn't relevant to my use case any more.

**Comment by mwchase** [comment]
It's been a week, and I've changed my mind. I really am not liking having generated files in source control, so this is a feature I would like to have.

**Comment by mwchase** [comment]
The most workable solution is to have config to turn off the checking for vcs excludes entirely. This would give basically the same experience as using a non-supported vcs.

**Comment by finswimmer** [comment]
Hello,

i'm not sure if I understand what you are trying to do. But there is an option to define explicit what should be included in a package: https://poetry.eustace.io/docs/pyproject/#include-and-exclude

Wildcards are supported. What ever matches the values in `include` will be included, despite of it is in the .gitignore or not.

**Comment by mwchase** [comment]
I'm testing this out and looking at the source, and it looks to me like exclude takes precedence over include, and it doesn't matter whether the exclude is explicit in the pyproject.toml, or generated from the .gitignore.

If I try to build a project structured like this (tracked source that compiles to Python, ignored package directory, explicitly including the package directory in the pyproject.toml file makes no difference either way) then the build fails:
```
$ poetry build
Building no-src-dir (0.1.0)
 - Building sdist
 - Built no-src-dir-0.1.0.tar.gz


[ModuleOrPackageNotFound]
No file/folder found for package no-src-dir
```

**Comment by finswimmer** [comment]
Could you please provide a complete example of your `.gitignore`, the `pyproject.toml` and the expected content of your sdist package based on the given folder structure in your first post?

Have you tested it also with the latest preview- release?

**Comment by mwchase** [comment]
Let's see what I can put together...
```
$ poetry --version
Poetry version 1.0.0b4
```
I have two project trees for this.
```
.
├── .gitignore
├── README.rst
├── fake-build-src
│   └── no_src_dir
│       └── __init__.py
├── no_src_dir
│   └── __init__.py
├── pyproject.toml
└── tests
    ├── __init__.py
    └── test_no_src_dir.py
```
.gitignore: `/no_src_dir`
pyproject.toml:
```
[tool.poetry]
name = "no-src-dir"
version = "0.1.0"
description = ""
authors = ["Max W Chase <max.chase@gmail.com>"]
include = ["no_src_dir"]  # This line has no effect

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
Similarly, for with a src directory:
```
.
├── .gitignore
├── README.rst
├── fake-build-src
│   └── src_dir
│       └── __init__.py
├── pyproject.toml
├── src
│   └── src_dir
│       └── __init__.py
└── tests
    ├── __init__.py
    └── test_src_dir.py
```
.gitignore: `/src`
pyproject.toml:
```
[tool.poetry]
name = "src-dir"
version = "0.1.0"
description = ""
authors = ["Max W Chase <max.chase@gmail.com>"]
include = ["src"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
The notional build system here is just copying the contents of fake-build-src. In actual practice, those files would be for example written in http://coconut-lang.org/ or as input to some other kind of code generator.

If I comment out the gitignores, then `poetry build` succeeds, and if I don't, then it fails with the above error.

**Comment by finswimmer** [comment]
Try using globs in the include line, like this:

```
include = ["no_src_dir/**/*"]
```

**Comment by mwchase** [comment]
`include = ["no_src_dir/**/*"]` and `include = ["src/**/*"]` work.
