### ISSUE TITLE
Maybe utils/env.py should really split stdout and stderr up accordingly.

### ISSUE THREAD

**Issue by xiamubobby** [sdispater/poetry#1097]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate. *(I have seen related but not from the exact same perspective)*
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Windows10**: 
- **0.12.15**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

In utils/env.py, Poetry collects several sorts of system/environment information via subprocesses with communicate(encode(str)). Many have reported issues of suffering JSONDecodeError here. As most of them dug further for the root cause case by case, I think the code is potentially not so proper when calling for the splitting of stdout and stderr.
Here is the original code from my copy of Poetry, installed from pip:
`            if input_:
                p = subprocess.Popen(
                    cmd,
                    stdin=subprocess.PIPE,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    **kwargs
                )
                output = p.communicate(encode(input_))[0]`
As we can see if we do feed stderr with subprocess.STDOUT, the error messages will be mixed into the actual outputs. Regarding that Poetry quite often calls json.loads on the output, whenever there is error logs, the stdout(with stderr mixed in) is not a proper Json by any means.
In my case, It is like this:
`(b'The system cannot find the path specified.\r\n{"implementation_name": "cpython", "implementation_version": "3.6.2", "os_name": "nt", "platform_machine": "AMD64", "platform_release": "10", "platform_system": "Windows", "platform_version": "10.0.16299", "python_full_version": "3.6.2", "platform_python_implementation": "CPython", "python_version": "3.6", "sys_platform": "win32", "version_info": [3, 6, 2, "final", 0]}\r\n', None)`
Which obviously corrupts the upcoming json.loads()
While, suggested, maybe we should be adopting it like this. (Though in the current code, it never cares about the stdout, which is fine, but we do need to eliminate error logs out of the stdout)

After I have changed it to:
`            if input_:
                p = subprocess.Popen(
                    cmd,
                    stdin=subprocess.PIPE,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE, #or None the later codes do not care about it
                    **kwargs
                )
                output = p.communicate(encode(input_))[0]`
I can get:
`(b'{"implementation_name": "cpython", "implementation_version": "3.6.2", "os_name": "nt", "platform_machine": "AMD64", "platform_release": "10", "platform_system": "Windows", "platform_version": "10.0.16299", "python_full_version": "3.6.2", "platform_python_implementation": "CPython", "python_version": "3.6", "sys_platform": "win32", "version_info": [3, 6, 2, "final", 0]}\r\n', b'The system cannot find the path specified.\r\n')` if with PIPE
and
`(b'{"implementation_name": "cpython", "implementation_version": "3.6.2", "os_name": "nt", "platform_machine": "AMD64", "platform_release": "10", "platform_system": "Windows", "platform_version": "10.0.16299", "python_full_version": "3.6.2", "platform_python_implementation": "CPython", "python_version": "3.6", "sys_platform": "win32", "version_info": [3, 6, 2, "final", 0]}\r\n', None)` if with None

Which definitely in my opinion makes more senses, as no matter if we do care about the stderr or not, it will not damage the upcoming parsing codes.

Please suggest if any better approach could be engaged.
Please don't redirect it to that why b'The system cannot find the path specified.\r\n pops up, it might be the issue with my Anaconda or Windows, it might be the issue with Poetry, It's just not what i am talking now, since whatever gets thrown as an err, JSONDecodeError happens. Which is mostly what we don't want to have. Also afaik this part is embedded firmly inside the commands mechanism of Poetry, trying to do things with try catch with some kind of alternative logic is not even realistic, and heavily not encouraged impov. (It won't solve any problem any way since we are using Poetry from CLI not Python context, and those system information is critical, not dodge-able.)

Thanks!

**Comment by Imaclean74** [comment]
hi @xiamubobby - this is related to my recent PR #1075 - which addresses why we get JSONDecodeError instead of the actual error from the child process. The core issue is that the non-zero return code wasn't processed properly. Once it is - then the merged output no longer gets passed to json decode. That doesn't mean it might not be cleaner to separate STDOUT and STDERR. However, that does seem to be a standard pattern with subprocess usage. Perhaps @sdispater can opine?

**Comment by Imaclean74** [comment]
oh - and relevant issue #1074

**Comment by xiamubobby** [comment]
Hi @Imaclean74  Thank you for the detailed explanation and the code fix.
Yes I agree that the current approach is common and proper.
For me I lately came to solving my problem by eliminating the root cause, not related to Poetry anyway.
Let's stick to your PR and I will close the issue as is.
