### ISSUE TITLE
Add support for non pure python projects

### ISSUE THREAD

**Issue by sdispater** [sdispater/poetry#11]
We should have a way to build non pure-python projects (from instance if they need to build C extensions).

**Comment by feluxe** [comment]
Hi!

Does this work with poetry?

**Comment by sdispater** [comment]
Thanks for your interest in poetry!

Yes, it works even though it's not currently documented because I do not know if it will stay this way since it relies on adding kwargs to the setup.py.

Anyway, it you want to test this, you have to specifiy a build script in your `pyproject.toml`:

```toml
[tool.poetry]
build = 'build.py'
```

that will define a `build` function that will add the necessary build keyword arguments to the call to `setup()` in the generated `setup.py`.

An example of this is in my [pendulum](https://github.com/sdispater/pendulum) project:

* [`pyproject.toml`](https://github.com/sdispater/pendulum/blob/1.x/pyproject.toml)
* [`build.py`](https://github.com/sdispater/pendulum/blob/1.x/build.py)

**Comment by salotz** [comment]
Here is an example for building a cython module https://github.com/ADicksonLab/geomm/blob/master/build.py.

**Comment by shimil** [comment]
Hey @sdispater, I love Poetry! 
We want to adopt it as part of our tech stack, but consider support for C extensions an important feature. Can we count on continued support for it?

Many thanks

**Comment by AlJohri** [comment]
How can I use this `build.py` idea for external Cython dependencies? Currently I want to install (from source) the [`spaCy`](https://github.com/explosion/spaCy) package. I have to currently resort to using `poetry run` to achieve this.

```
# install non-cython dependencies
poetry install

# install spaCy from source using `build_ext`
git clone https://github.com/explosion/spaCy.git spaCy
poetry run python spaCy/setup.py build_ext --inplace
poetry run pip install -e spaCy
```

**Comment by zoj613** [comment]
> How can I use this `build.py` idea for external Cython dependencies? Currently I want to install (from source) the [`spaCy`](https://github.com/explosion/spaCy) package. I have to currently resort to using `poetry run` to achieve this.
> 
> ```
> # install non-cython dependencies
> poetry install
> 
> # install spaCy from source using `build_ext`
> git clone https://github.com/explosion/spaCy.git spaCy
> poetry run python spaCy/setup.py build_ext --inplace
> poetry run pip install -e spaCy
> ```

you could bundle these steps as one Makefile command?

**Comment by AlJohri** [comment]
@zoj613 and I've certainly done exactly that (see screenshot). but I wish I could specify `spaCy` as a git project directly in the `pyproject.toml` with some markers specifying that the cython extension needs to be built. is there anyway to do this?

<img width="1825" alt="Screen Shot 2019-12-20 at 1 01 41 PM" src="https://user-images.githubusercontent.com/2790092/71280342-ea03c100-2328-11ea-9575-dd4126152dc8.png">

**Comment by zoj613** [comment]
> @zoj613 and I've certainly done exactly that (see screenshot). but I wish I could specify `spaCy` as a git project directly in the `pyproject.toml` with some markers specifying that the cython extension needs to be built. is there anyway to do this?
> 
> <img alt="Screen Shot 2019-12-20 at 1 01 41 PM" width="1825" src="https://user-images.githubusercontent.com/2790092/71280342-ea03c100-2328-11ea-9575-dd4126152dc8.png">

does it not build and install the cython packages by default when you install `spaCy`?

**Comment by AlJohri** [comment]
It doesn’t, it says that it can’t find the version presumably because it can’t run “python setup.py egg_info”.

For some reason when pip tries to install it, it installs it on some sort of isolated environment without Cython which is why it fails to parse the setup.py.

I tried forking as you suggested but couldn’t figure out how to get past the Cython not found issue. I can post a dockerized example if you’re interested in debugging further.

**Comment by AlJohri** [comment]
@zoj613 in case you're curious, I found the root case was that the spaCy package has a pyproject.toml without the build dependencies defined: https://github.com/explosion/spaCy/issues/4829

**Comment by teknico** [comment]
We're also using this feature in [tinydecred](https://github.com/decred/tinydecred/) with Cython. Any chance in stabilizing it? Thanks.

**Comment by abn** [comment]
@teknico I'd recommend creating a new issue detailing short-commings of the current implementations with as much details as possible please. We are already aware of a few issues. Including #1516.

**Comment by geronm** [comment]
**salotz** said:

> Here is an example for building a cython module https://github.com/ADicksonLab/geomm/blob/master/build.py.

This comment seems to have fallen out of date.

I think this tag (`v0.1.7`) in the repo gives a stable reference with working build.py: https://github.com/ADicksonLab/geomm/tree/v0.1.7

**Comment by zoj613** [comment]
I have a build.py I use in my own project and it works just fine: https://github.com/zoj613/OccuSpytial/blob/master/build.py

**Comment by zoj613** [comment]
I have a mordern approach that avoids using an explicit setup.py file. It contains a build script that takes wheel building into account. See: https://github.com/zoj613/htnorm/blob/main/build.py
