### ISSUE TITLE
Reproducible sdist builds

### ISSUE THREAD

**Issue by zpah** [sdispater/poetry#1102]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
Poetry (v0.12.15) makes different sdist archives by each build command invoke. It`s poor.

Would be great if poetry generated reproducible sdists for concrete SCM commits (with identical checksums!).
In my setup.py-based projects i achieve this behaviour by setuptools.command.sdist substitution, where:
- use bz2 archiver (gzip store current timestamp in archive)
- sort archive items by path
- assign owner/group of tar items to root:root
- assign archive items timestamps from SCM (Mercurial, Git) commit metadata

**Comment by drunkwcodes** [comment]
Can it be done with gzip and without root?

**Comment by zpah** [comment]
> Can it be done with gzip and without root?

1. Poetry use gzip.GzipFile in command sdist:  https://github.com/sdispater/poetry/blob/cb6491415f59742f06f0ca322ec546b88aa412ef/poetry/masonry/builders/sdist.py#L56
   Option mtime, for example, can be involed:
   `gzip.GzipFile("test.txt.gz", mode="wb", mtime=stable_timestamp_from_scm)`.
   It will provide stable archive checksum.
2. Without root ?! I mean any stable predictable uid/gid for all sdist tar-archive items!
 Poetry already does it. It add sdist items with uid/gid assigned to 0/0.
 User and group 'root:root' (uid=0, gid=0) in this case was good neutral candidat. For this purpose the privileges of the superuser are not required during archive creation.

**Comment by Natureshadow** [comment]
Will poetry be changed to create reproducible sdist builds any time soon?

**Comment by abn** [comment]
@Natureshadow The linked PR should resolve this.

**Comment by zpah** [comment]
Not will. Python became rotted. Migrate to Rust.
