### ISSUE TITLE
catch and hold ConnectionError untill all Repositories are tested

### ISSUE THREAD

**Issue by marco-silva0000** [sdispater/poetry#1105]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

It would be useful if instead of raising ConnectionError when the repository is offline, poetry would try to get the package from other available reppos in the Pool.

Currently If any of the repositories is attempted and fails with a connection error it will stop the process with a failure. My proposal is to catch the exception(logging a warning in the process) until all of the repo pool is tried, and raise the connection error if it can't find the package anywhere.

As a workaround I believe I can use a different pyproject.toml file for different environments, but this has other problems. 

My specific use case is to use devpy as a pypi proxy on a local network to speedup installs.
witch is useful while developing with docker as you often need to recreate the virtualenv and reinstall everything. Its also a good way to expand on options so that you can integrate with the CI env more easily.

I looked into the code and I think I can work on this issue.
This may relate to #595, but I don't think its the same problem.

**Comment by mellon85** [comment]
This can cause issues in case a package shadows a package in another repository tried later. This can happen as overtime those names can be added to pypi and you might drag in code you don't expect.

**Comment by marco-silva0000** [comment]
sorry @mellon85 , but I didn't understand the problem you raised. This feature request is not related do package finding, it's just to keep searching if the repository server is down.

currently if a package is not found in one repository, it will be searched on the others, but if one of them is offline, the exception will be raised and the operation stopped.

**Comment by mellon85** [comment]
@marco-silva0000 

> server-1: package A
> server-2: package B

assume package A and package B have the same name but they are different packages.
If in the pool I have both servers and server-1 is not found it will get it from server-2. This kind of behavior might take A or B.

Every server added to the pool should mask the other servers content.
By what I understood of your setup I would actually suggest having a local devpi instance (can't be unreachable) and use the replica feature of devpi or just use it as a inheriting index for your local one.

**Comment by marco-silva0000** [comment]
I think that is a different problem, and one that should be fixed in some other way. colliding names are not something that should happen, unless you are using a custom variation of a module.

I think that a new feature request should be opened to tackle that problem, and I suggest an implementation similar to what pipenv does:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "http://pypi.home.kennethreitz.org/simple"
verify_ssl = false
name = "home"

[dev-packages]

[packages]
requests = {version="*", index="home"}
maya = {version="*", index="pypi"}
records = "*"
```

I don't think that every server should mask the other servers content.
One of the biggest use cases of devpi is to manage a private package library in a team, with the ability of every team member using the same version of the packages, so a local instance of devpi wont work here. This is also the best way you can integrate your custom packages with CI.

also, if I use a local devpi, I would still need 2 pyproject files, one with the local repo and other for production
