### ISSUE TITLE
Add option for `install` command to run only installer, not builder

### ISSUE THREAD

**Issue by MisterKeefe** [sdispater/poetry#1107]
- [✓] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [✓] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

As part of the `poetry install` process, `poetry` runs an `EditableBuilder` after the `Installer`. This means that, in addition to installing the dependencies, the current directory is also installed in editable mode, via `pip install -e`. 

It would be nice to have the option to _only_ run the installer, rather than the installer + builder -- perhaps via a flag such as `--no-build` (I have a branch to this effect and am happy to raise a PR). 

A concrete use-case for the above would be as follows: I have a project with several cythonisable `.py` files. I am using a custom `setup.py` to cythonise the code when `setup.py install` is run, so that when the module itself is installed elsewhere the end user gets the cythonised version of the code. 

`poetry` respects the custom `setup.py`, which is great, but for development purposes I actually don't want to cythonise the code with `poetry install`, just install the dependencies from the lock file. 

Currently I am getting around this with a shell script which just removes all compiled files from the directory, but this is a manual process. 

If I were able to pass a flag to `poetry install` which specified that only the installer would be run, then the script would be unnecessary. 

I am not sure how idiosyncratic this use-case is, but it seems to me that it might more generally be nice to have the behaviour of running `pip install -e` at the end of installing dependencies be optional, rather than mandatory.

**Comment by mwchase** [comment]
I believe the "no-root" option on the `develop` branch does this, or something similar.

**Comment by MisterKeefe** [comment]
Ah, yes, perfect! I'll just wait for the next release, then. Should I close this issue?
