### ISSUE TITLE
Include tests is poetry's sdist

### ISSUE THREAD

**Issue by jayvdb** [sdispater/poetry#1109]
I am starting the process of packaging poetry for openSUSE  [here](https://build.opensuse.org/package/show/home:jayvdb:coala:test-rig/python-poetry), and notice that the sdist doesnt contain tests, and the GitHub archive doesnt contain `setup.py` .  As a result, there is no single versioned tarball which can be used to build *and* test poetry.  I need to unpack both to have a usable poetry for building a testable rpm.

The easiest way to solve this is to include the tests in the poetry sdist.

**Comment by eli-schwartz** [comment]
I have just run into the same issue on Arch Linux, and this makes it difficult to package any software released using poetry.

**Comment by eli-schwartz** [comment]
@jayvdb By the way, are you aware of the similar packaging issue in #866?

**Comment by jayvdb** [comment]
I wasn't aware of it.  Thanks for the heads-up.  Anyone looking to workaround some of these packaging problems with pyproject.toml projects , I found @dephell to work quite well, and the maintainer is very responsive .

**Comment by eli-schwartz** [comment]
Odd coincidence -- I'm actually attempting to package dephell as of yesterday. :p
Once that is done I am going to check out how feasible it is to add build-depends on python-dephell for poetry projects, and use dephell convert on the github sources (with testsuite) to generate a setup.py.

**Comment by sdispater** [comment]
I plan on making the [`packages`](https://poetry.eustace.io/docs/pyproject/#packages) section of the `pyproject.toml` file support specifying the format for which the package should be included (no format meaning all of them).

```toml
[tool.poetry]
# ...
packages = [
    { include = "my_package" },
    { include = "tests", format = "sdist" },
]
```
