### ISSUE TITLE
The "poetry shell" command does not activate virtualenv

### ISSUE THREAD

**Issue by carlosperate** [sdispater/poetry#1118]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave
- **Poetry version**: 0.12.16
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

<details>
<summary>pyproject.toml</summary>

<pre>
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# Poetry settings
[tool.poetry]
name = "ubittool"
version = "0.5.0"
description = "Tool to interface with the BBC micro:bit."
authors = ["Carlos Pereira Atencio <carlosperate@embeddedlog.com>"]
license = "MIT"
homepage = "https://carlosperate.github.io/ubittool/"
repository = "https://github.com/carlosperate/ubittool/"
documentation =  "https://carlosperate.github.io/ubittool/"
readme = "README.md"
keywords = ["microbit", "micro:bit", "bbcmicrobit", "ubittool"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Topic :: Education",
    "Topic :: Software Development :: Embedded Systems",
]

[tool.poetry.dependencies]
python = "^3.5"
IntelHex = "^2.2.1"
uflash = ">=1.1.0,<1.2.1"
pyocd = "0.19.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
PyInstaller = "^3.3"
# PyOCD needs this as a setup_requires, for some reason 'pipenv install' in
# Travis doesn't pick it up and PyOCD fails to install or run
setuptools_scm = "*"
# Linting
black = {version = "19.3b0", python = "^3.6" }
flake8 = "*"
flake8-bugbear = {version = "*", python = "^3.5" }
flake8-builtins = "*"
flake8-docstrings = "*"
# Tests
pytest = "*"
pytest-cov = "*"

[tool.poetry.scripts]
ubit = 'ubittool.__main__:main'

# Black settings
[tool.black]
line-length = 79
target-version = ['py35']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # Above this line are defaults and below are project specific
  | ignoreme
)/
'''
</pre>
</details>

Additional info:
```
$ poetry config --list
settings.virtualenvs.create = true
settings.virtualenvs.in-project = false
settings.virtualenvs.path = "/Users/microbit-carlos/.local/share/virtualenvs"
repositories.test.url = "https://test.pypi.org/simple/"
repositories.testpypi.url = "https://test.pypi.org/legacy/"
```

## Issue

Running `poetry shell` does not seem to spawn a shell with the virtual environment activated.

```
$ pyenv local 3.7.3

$ poetry shell -vvv
Virtualenv ubittool-py3.7 already exists.
Using virtualenv: /Users/microbit-carlos/.local/share/virtualenvs/ubittool-py3.7
Spawning shell within /Users/microbit-carlos/.local/share/virtualenvs/ubittool-py3.7

$ python -m pip --version
pip 19.0.3 from /Users/microbit-carlos/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip (python 3.7)

$ exit

$ source /Users/microbit-carlos/.local/share/virtualenvs/ubittool-py3.7/bin/activate

(ubittool-py3.7) $ python -m pip --version                                                           
pip 19.0.3 from /Users/microbit-carlos/.local/share/virtualenvs/ubittool-py3.7/lib/python3.7/site-packages/pip (python 3.7)

(ubittool-py3.7) $ deactivate

$ poetry run python -m pip --version
pip 19.0.3 from /Users/microbit-carlos/.local/share/virtualenvs/ubittool-py3.7/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by seansfkelley** [comment]
Duplicate of #571.

**Comment by carlosperate** [comment]
Thanks @seansfkelley, I'll close this one then.
