### ISSUE TITLE
Add option to install the package in non-editable mode

### ISSUE THREAD

**Issue by schmir-at-bb** [sdispater/poetry#1120]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

It would be nice to have a way to install the package in non-editable mode. 'poetry install' always installs the package itself in editable mode. Having it installed in non-editable mode would be useful to have a self-contained virtualenv, that could then be packaged via fpm or be used inside a docker container.

A workaround at the moment is to use the `install --no-root` flag, build a sdist or wheel and install that with pip.

**Comment by sdispater** [comment]
The idea is similar to some mentioned in #537 so closing this issue
