### ISSUE TITLE
Dependency of children not resolved when extras after version 

### ISSUE THREAD

**Issue by philippegr** [sdispater/poetry#1138]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  in a docker from python:3.7-strech
- **Poetry version**: we checkout master at docker build, issue has been around for at least the past few days
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Line that cause the issue `dask = {version = "^1.2",extras = ["complete"]}`

## Issue
This issue is related to the way [dask ](http://docs.dask.org/en/latest/install.html) gets installed. The default pip command is `pip install dask` corresponds to "most common uses of Dask", to have the complete set dependency with pip `pip install dask[complete]`, this corresponds to a use case of the -E option as stated in this [issue](https://github.com/sdispater/poetry/issues/109#issuecomment-460764863)

Step to reproduce the problem:

1. `poetry add dask -E complete` --> new line in pyproject .toml `dask = {version = "^1.2",extras = ["complete"]}`
2. in python, try `from dask.distributed import Client`
This will fail on a missing tblib library.
3. But if you run `pip install dask[complete]`, pip detects that tblib and psutil (among others) are not installed --> so the dependency resolution done by poetry was incomplete

What is potentially happening: 
Per [this file from Dask] (https://github.com/dask/dask/blob/a6abe3ca75179a7264a15de043335e6dbed684ea/setup.py#L10-L17) it appears that poetry does indeed find the first level dependency of `dask[complete]` but not the second level (dependencies of the dependencies).

[edit: nope incorrect statement below]
~Interestingly it seems that switching the order of version and extras in the pyproject.toml (for `dask = {extras = ["complete"], version = "^1.2"}` does fix this issue~

**Comment by sdispater** [comment]
It seems to be working on my end.

Could you provide a complete `pyproject.toml` or execute the `install` command in debug mode (`-vvv`) after deleting the lock file to see what happens?

**Comment by philippegr** [comment]
You are right! Trying to have an MVP I overshoot it, my latest comment on the order matters is incorrect. I updated my initial post
However, the bug seem to exist no matter the order of the keywords for dask

Here is the [pyproject.toml](https://gist.github.com/philippegr/1290026b82596d0289bd4613268e74a1)

And here is the [output of install -vvv](https://gist.github.com/philippegr/223c8e0a84e7a5cc69ea2e73ca31aa16)
Interesting bits are at the end IMO where it states that psutil has been skipped, which is one of the package that makes the `from dask.distributed import Client` complain and one of the  package `pip install dask[complete]` (run after `poetry install`) would brought along

**Comment by sdispater** [comment]
Commit 426dbdc should fix the issue.

The problem was the circular dependency between `dask` and `distributed` which caused Poetry to drop dependencies when building the dependency graph.

The fix will be available in the next bugfix release.

**Comment by philippegr** [comment]
Thank you very much for your super quick fix. 
Will test it as soon as the next preview is out :-)
