### ISSUE TITLE
Support tilde expansion in config.toml

### ISSUE THREAD

**Issue by laggardkernel** [sdispater/poetry#1146]
Could tilde `~` expansion be supported in `config.toml`, which also makes the conf file more portable.

```bash
[settings]
virtualenvs.path = "~/.local/share/virtualenvs"
```

It will be much better if environment expansion is supported as well.

**Comment by abn** [comment]
This seems to be duplicated by #1149. Should be resolved by #1158.

**Comment by brycedrennan** [comment]
Since the other similar issue has votes we should consolidate discussion on #1149
