### ISSUE TITLE
Installation succeeds but new project fails

### ISSUE THREAD

**Issue by wozniakty** [sdispater/poetry#1154]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 0.12.16
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Can't even create a new project

## Issue

Installation seemed to succeed, but on any new project i get the following:
```
poetry new test-poet -vvv

[ImportError]
cannot import name 'Type'

Exception trace:
 C:\Users\twozniak\.poetry\lib\poetry\_vendor\py3.5\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 C:\Users\twozniak\.poetry\lib\poetry\console\application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 C:\Users\twozniak\.poetry\lib\poetry\_vendor\py3.5\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 C:\Users\twozniak\.poetry\lib\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 C:\Users\twozniak\.poetry\lib\poetry\_vendor\py3.5\cleo\commands\base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 C:\Users\twozniak\.poetry\lib\poetry\_vendor\py3.5\cleo\commands\command.py in execute() at line 107
   return self.handle()
 C:\Users\twozniak\.poetry\lib\poetry\console\commands\new.py in handle() at line 15
   from poetry.layouts import layout
 C:\Users\twozniak\.poetry\lib\poetry\layouts\__init__.py in <module>() at line 1
   from typing import Type
```

Will try installing via pip as a workaround

**Comment by wozniakty** [comment]
More information: I was able to actually run the new poetry command _from_ my pipenv environment.  So I went to a pipenv project on python 3.7.3 and did `pipenv run poetry new project-name` and it worked.

**Comment by wozniakty** [comment]
Actually, I solved the issue.  I had both python 3.5 and 3.7 on my windows machine, and somehow it seems like Poetry was using the 3.5 version but running with code that expected 3.7?  I'm not really a huge expert in python versioning so Idk for sure, but ultimately making sure python was defaulted to 3.7.3 solved my problem.

**Comment by stephsamson** [comment]
Closing this issue since it's been resolved.
