### ISSUE TITLE
Git dependencies are installed every time (even when rev is specified)

### ISSUE THREAD

**Issue by LouisTrezzini** [sdispater/poetry#1157]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro and macOS High Sierra
- **Poetry version**: 0.12.16
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/LouisTrezzini/9a9b02c5bf961bea66cd455e01625d5a

## Issue

When specifying git dependencies, the package is reinstalled every time I run `poetry install` or `poetry update`. This happens even if I specify a revision.

This is not expected, considering poetry uses a lock file. We would expect that the specific commit of the git dependency would be resolved during `update` and written to the lock file. Then installation would be reproducible and would skip updating the package if the correct commit is already installed.

Right now this is painful, because the git dependency is pretty slow to install every time (and it slows down our CI a lot)

Thanks for building poetry, this tool is awesome!

**Comment by abn** [comment]
@LouisTrezzini try using the full revision hash. When a package is installed the full hash is resolved and stored as the installed package `source_reference`. When checking if the package needs updating the equality check fails, causing poetry to flag this package as requiring an update.

```diff
- fastText = { git = "https://github.com/facebookresearch/fastText.git", rev = "6dd2e11" }
+ fastText = { git = "https://github.com/facebookresearch/fastText.git", rev = "6dd2e11b5fe82854c4529d2a58d699b2cb182b1b" }
```

**Comment by LouisTrezzini** [comment]
Many thanks for you quick answer and bugfix!
