### ISSUE TITLE
Add an explicit message for outdated packages which cannot be updated

### ISSUE THREAD

**Issue by Batalex** [sdispater/poetry#116]
Hi,
First of all I would like to congratulate you for building Poetry. I have really enjoyed it so far.

I would like to suggest an enhancement to the update feature regarding the caret requirement safety.

I realized this morning after some struggling that I could not update pandas with poetry from 0.22 to 0.23 because of the `pandas = "^0.22.0"` requirement in `pyproject.toml` added with `poetry add pandas` some time ago.

The update command (0.9.0) is quite silent of this matter until verbosity is set on `-vvv`:
```
$ poetry update -vv
Virtualenv train-base-py3.6 already exists.
Updating dependencies
Resolving dependencies

Nothing to install or update

Writing lock file
```
A terminal output similar to `poetry show -o` would clear some confusion here.

I would gladly try to work on a PR if the feedback is positive.

**Comment by m-aciek** [comment]
Color red/yellow of version in `show --outdated` output shows if version "breaks" specifiers (red) or can be updated without changing specifiers (yellow).

But when dependency version comes from specifier of another dependency (so said dependency version is of second-row dependency), it will be shown just as it would be first-row dependency specified in my `pyproject.toml`.

For example for now if you have `requests` in your dependencies (which doesn't use the newest `urllib3` yet), you will get:
```
$ poetry show --outdated
urllib3               1.24.2   1.25.1   HTTP library with thread-safe connection pooling, file post, and more.
```

IMHO flag to differ such cases from cases of direct version specifiers would help a lot.

@Batalex could you reopen this issue?

**Comment by Batalex** [comment]
@m-aciek sure!
