### ISSUE TITLE
Cannot clear "all" caches

### ISSUE THREAD

**Issue by thejohnfreeman** [sdispater/poetry#1162]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.0a3

## Issue

`poetry cache clear --all` still expects a cache name (and there seems to be no commands for listing cache names).

```
$ poetry cache clear --all

[CannotParseArgsException]
Not enough arguments (missing: "cache").
```

**Comment by thejohnfreeman** [comment]
Judging from [this comment](https://github.com/sdispater/poetry/issues/728#issuecomment-451004596), there is a cache named `pypi` that has to be given. Perhaps the help message could be improved instead?

**Comment by Alexander171176** [comment]
Is it possible to explain to people using a code example ?? 
for example:
poetry cache clear PyPi --all
Delete 86 entries? (yes/no) [yes] yes
yes.
