### ISSUE TITLE
Add support "maintainers" in pyproject.toml and generated files

### ISSUE THREAD

**Issue by Caligatio** [sdispater/poetry#1169]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

setuptools supports the "maintainer" and "maintainer_email" metadata values in setup.py and I have some tooling that makes use of this pair of values.  It would great if poetry could add support for these two in a fashion similar to how "authors" in pyproject.toml gets converted into "author" and "author_email" in the generated metadata.

In case you're wondering how this metadata is used, "author" is used to denote the owner of a package whereas maintainer is used to denote individual(s) with write access.

**Comment by stephsamson** [comment]
#1175 fixes this issue.
