### ISSUE TITLE
source-compiled package installation order and dependency resolution

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#117]
If a project from github has setup.py which depends on another project, "poetry install" will fail to resolve them both. You need to install everything else first, then add the project compiled from the source, then install it after. Not sure how one can deal with it in a package manager.
For me, it was torch and torchaudio packages:
[tool.poetry.dependencies]
torch = "^0.4.0"
torchaudio = { git = "https://github.com/pytorch/audio.git", branch = "master" }

**Comment by sdispater** [comment]
In this case, you will have to `poetry add torch` first since to execute the `setup.py` of `torchaudio` you need `torch`.

For now, there is no way around it.

**Comment by bertjwregeer** [comment]
If the authors of `torchaudio` implemented [PEP518](https://www.python.org/dev/peps/pep-0518/) then `pip` version `10` or higher would automatically install `torch` before building the wheel for `torchaudio`.

Not sure if that would solve the problem for installing from git, but PEP518 is specifically about solving the problem of making sure the build env contains all of the right dependencies.

**Comment by buriy** [comment]
@bertjwregeer yes, then pip could install torch, avoiding the poetry package manager completely, which isn't also a good idea.
@sdispater problem is that then I've no way to distribute a package to be installed with poetry with both those dependencies included into pyproject.toml ...
Maybe we could include requirements hinting to this syntax, like this?
torchaudio = { git = "https://github.com/pytorch/audio.git", branch = "master"**, requires = "torch"** }

**Comment by bertjwregeer** [comment]
@buriy no, pip would only install `torch` to be able to build `torchaudio` (It does this in a temporary build environment) it would not install `torch` into the environment that `torchaudio` is to be installed in, that would still be poetry's job.

**Comment by sdispater** [comment]
Closing this since Poetry now installs dependencies in the proper order, i.e. the most deeply needed dependencies will be installed first.

**Comment by tombh** [comment]
This doesn't seem to work with [sktime](https://github.com/alan-turing-institute/sktime/blob/main/setup.py)'s dependency on Cython. I guess it must be for a different reason?
