### ISSUE TITLE
Support for LiClipse (PyDEV) IDE?

### ISSUE THREAD

**Issue by ankostis** [sdispater/poetry#1170]
I googled a bit an did not find any hints on the support of *poetry* for LiClipse(PyDEV), while *pipenv* is already supported by that IDE.
- Does anybody have a clue?

**Comment by stephsamson** [comment]
@ankostis As far as I know @sdispater does not have any plans in the horizons for devoting time to this. Perhaps you could submit an issue to the author(s)/maintainer(s) of PyDEV instead [in this repo](https://github.com/fabioz/Pydev).

**Comment by ankostis** [comment]
For those visitors wanting to follow up on this, i submitted the request in [PyDev#998](https://www.brainwy.com/tracker/PyDev/).
