### ISSUE TITLE
Docker multi-stage build Dockerfile best practices

### ISSUE THREAD

**Issue by hozn** [sdispater/poetry#1178]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I continue to try to replace our pip/setuptools-based system with poetry, but hit a new snag when it comes to how we build our Docker images.

Here's the basic pattern we use for our Docker images, in a build and a deploy stage:
1. (build)  Resolve all dependencies and build wheels for them
2. (build) Build the actual project as a wheel too
3. (deploy) Take all of those wheels we built and install them into a lightweight image (that has no build tools)

Here's how this translates into a Dockerfile:

```
# ---------------------------------------------------------------------------------------
# BUILD
# ---------------------------------------------------------------------------------------

FROM gitlab.example.com:4567/namespace/build-base:py37-1.0.4 as builder

RUN mkdir -p /build/wheels

# This is separated out to take advantage of caching
ADD requirements.txt /tmp/requirements.txt

RUN pip3.7 wheel --trusted-host pypi.example.com  \
    --wheel-dir=/tmp/python-wheels --index-url http://pypi.example.com/simple/ \
    -r /tmp/requirements.txt

ADD . /src
WORKDIR /src

RUN pip3.7 wheel --find-links /tmp/python-wheels --trusted-host=pypi.example.com --wheel-dir=/build/wheels .

# ---------------------------------------------------------------------------------------
# DEPLOY
# ---------------------------------------------------------------------------------------

FROM gitlab.example.sec:4567/namespace/deploy-base:py37-1.0.0 as deploy

WORKDIR /opt/app

# Copy the already-built wheels
COPY --from=builder /build/wheels /tmp/wheels

# Install into main system python.
RUN pip3.7 install --no-cache-dir /tmp/wheels/* && rm -rf /tmp/wheels

CMD ["myproject-server"]
```

How do I do this with poetry?  -- in the most short-sighted form, I'd like to know how to collect all dependencies as wheels in order to match this pattern.

However, my real requirement here is just to have separate build and deploy stages where the deploy image has no python (or lower-level) build-related tools installed (but does have pip) and simply takes artifacts from the build image.

(I suppose one idea would be to treat the entire virtualenv from the build stage as an artifact?  That seems a little dirty, but provided the base OS images were the same, might work?)

**Comment by dojeda** [comment]
I too have this exact use case (the short-sighted one: use an intermediate image to generate wheels); I could not find how to do this with poetry. I haven't been able to create wheels of all dependencies, but creating a wheel of my main package does work with `poetry build --format wheel`.

**Comment by hozn** [comment]
Yeah, this and a couple other issues caused us to switch back to good-old pip/setuptools, which at least provides the flexibility to support our development workflow -- if a bit less elegant.

**Comment by dpraul** [comment]
We've had relatively good success copying virtualenvs between images with pip. I'm just beginning to see if we can transition to poetry - we've just been using it for small utilities right now but we're using the following code to do what you're describing:

```Dockerfile
FROM python:3.7.4-slim as python-base
ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_PATH=/opt/poetry \
    VENV_PATH=/opt/venv \
    POETRY_VERSION=0.12.17
ENV PATH="$POETRY_PATH/bin:$VENV_PATH/bin:$PATH"

FROM python-base as poetry
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        # deps for installing poetry
        curl \
        # deps for building python deps
        build-essential \
    \
    # install poetry - uses $POETRY_VERSION internally
    && curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python \
    && mv /root/.poetry $POETRY_PATH \
    && poetry --version \
    \
    # configure poetry & make a virtualenv ahead of time since we only need one
    && python -m venv $VENV_PATH \
    && poetry config settings.virtualenvs.create false \
    \
    # cleanup
    && rm -rf /var/lib/apt/lists/*

COPY poetry.lock pyproject.toml ./
RUN poetry install --no-interaction --no-ansi -vvv

FROM python-base as runtime
WORKDIR /app

# you can use the following line if you need poetry available in your deploy image
# COPY --from=poetry $POETRY_PATH $POETRY_PATH
COPY --from=poetry $VENV_PATH $VENV_PATH
COPY . ./

ENTRYPOINT ["python", "-m", "app"]
```

Haven't figured out a clean way to work with prod vs. dev dependencies

**Comment by hozn** [comment]
Thanks, @dpraul , this is a very helpful reference.

**Comment by dpraul** [comment]
No problem! Disclaimer: not heavily tested, so YMMV. Open on suggestions for how to improve it

**Comment by abersheeran** [comment]
https://github.com/Docker-s-IMAGES/no-pypoetry

```dockerfile
FROM abersh/no-pypoetry as requirements

FROM python:3.7

# ... yourself commands

COPY --from=requirements /src/requirements.txt .

RUN pip install -r requirements.txt

# ... yourself commands
```

You can use this multi-stage Dockerfile to ensure that you don't need to install a poetry in your final image. This can reduce the installation of many useless dependencies.

**Comment by foosinn** [comment]
Hey,

I found this solution for me to work best:

```Dockerfile
FROM python:3.9-alpine AS builder
WORKDIR /app
ADD pyproject.toml poetry.lock /app/

RUN apk add build-base libffi-dev
RUN pip install poetry
RUN poetry config virtualenvs.in-project true
RUN poetry install --no-ansi

# ---

FROM python:3.9-alpine
WORKDIR /app

COPY --from=builder /app /app
ADD . /app

RUN adduser app -h /app -u 1000 -g 1000 -DH
USER 1000

CMD /app/.venv/bin/python -m hookrelay
```

Ticks all my boxes:

* no need for a requirements file
* the virtualenv is managed by poetry
* no poetry in the final image
* application and venv contained in one folder
* python application can not write to its files or the virtualenv

Just make sure to use the same path in the builder and the final image, virtualenv uses some hardcoded paths.

**Comment by neersighted** [comment]
Thanks for bumping this -- the pattern you describe here is another one to polish and roll up into the work described at #6398 (which is mostly about containers despite ostensibly being not specific to them, as containers are usually the only place install into system site-packages comes up).

**Comment by foosinn** [comment]
@alexpovel thanks for you input. I've updated some points where i fully agree.

thanks a lot!

**Comment by max-pfeiffer** [comment]
I provide two docker images that you can use as builder base for multistage builds. They also contain an example application which demonstrates multistage builds with Poetry:

- https://github.com/max-pfeiffer/python-poetry
- https://github.com/max-pfeiffer/uvicorn-gunicorn-poetry

I aim for the best practices there. Please check them out and leave a comment if you have additional suggestions.

**Comment by willbush** [comment]
@foosinn  thanks that helped me a lot. I had to modify the adduser / addgroup lines, and personally modified mine for flask.

```Dockerfile
FROM python:3.10-alpine AS builder

WORKDIR /app

ADD pyproject.toml poetry.lock /app/

RUN apk add build-base libffi-dev

RUN pip install poetry
RUN poetry config virtualenvs.in-project true
RUN poetry install --no-ansi

FROM python:3.10-alpine
WORKDIR /app

COPY --from=builder /app /app
ADD . /app

# Create a new group `app` with Group ID `1000`.
RUN addgroup --gid 1000 app
# Create a new user `app`, sets home directory to `/app`, User ID `1000`, in
# the group `app`. The `-DH` option results in a system account.
RUN adduser app -h /app -u 1000 -G app -DH
# Change the user for subsequent commands in Dockerfile to the user with ID
# `1000`.
USER 1000

CMD ["/app/.venv/bin/gunicorn", "--bind", ":80", "app:app"]
```
