### ISSUE TITLE
Installing hurry-filesize (0.9) fails with VenvCommandError: No matching distribution found

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#118]
For install of news-please package ( #95 ), with local .venv which is python3.6 :
  - Installing hurry-filesize (0.9)
[VenvCommandError]                                                                                
Command ['pip', 'install', '--no-deps', '-r', '/tmp/hurry-filesize-0.9itkt20w9reqs.txt'] errored with the fol  
lowing output:                                                                                                 
Collecting hurry-filesize==0.9 (from -r /tmp/hurry-filesize-0.9itkt20w9reqs.txt (line 1))                      
  Could not find a version that satisfies the requirement hurry-filesize==0.9 (from -r /tmp/hurry-filesize-0.  
9itkt20w9reqs.txt (line 1)) (from versions: )                                                                  
No matching distribution found for hurry-filesize==0.9 (from -r /tmp/hurry-filesize-0.9itkt20w9reqs.txt (line  
 1))  

Poetry
======

 * Version: 0.10.0-alpha.0
 * Python:  3.5.3

Virtualenv
==========

 * Python:         3.6.2
 * Implementation: CPython
 * Path:           /Projects/newsloader/.venv

System
======

 * Platform: linux
 * OS:       posix

**Comment by buriy** [comment]
P.S. The correct package name is "hurry.filesize"

**Comment by buriy** [comment]
(This is another instance of #109 )

**Comment by bertjwregeer** [comment]
Could you try this patch: https://github.com/sdispater/poetry/pull/115

I believe that fixes the issue.

**Comment by bertjwregeer** [comment]
This can be closed now that #115 is merged.
