### ISSUE TITLE
poetry version

### ISSUE THREAD

**Issue by etijskens** [sdispater/poetry#1182]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I want to bump versions from within a python script that handles my project management workflow.
my script calls

            i = ArgvInput(['poetry','version',rule])
            Application().run(i)
which under the hood creates a VersionCommand and executes handle() on it :
    def handle(self):
        version = self.argument("version")

        version = self.increment_version(self.poetry.package.pretty_version, version)

        self.line(
            "Bumping version from <comment>{}</> to <info>{}</>".format(
                self.poetry.package.pretty_version, version
            )
        )

        content = self.poetry.file.read()
        poetry_content = content["tool"]["poetry"]
        poetry_content["version"] = version.text

        self.poetry.file.write(content)
whereas 
       > poetry version minor 
works exactly as expected and uses exactly the same code, my script does not update the version number in the pyproject.toml file. In the debugger I see that poetry_content above is correctly updated, but content remains unchanged. Actually content["tool"]["poetry"] and poetry_content refer to different python objects. How comes? Any help is welcome

**Comment by etijskens** [comment]
this code line 

    content["tool"]["poetry"]["version"] = version.text

does also NOT modify content..

**Comment by brno32** [comment]
Can you share more of your code? I'm unsure of where `ArgvInput` comes from so I couldn't run your example.

If you just need to bump the version via a python script, this worked for me

``` python
import subprocess
subprocess.run(['poetry','version', 'minor'])
```

**Comment by etijskens** [comment]
Hi,
Thanks for considering this. Your solution obviously works but It looks a bit overkill to run  python code via subprocess, so I thought to use the api of poetry.

It must be sth subtle inside tomlkit. I copied the lines from VersionCommand.handle

        version = self.argument("version")

        version = self.increment_version(self.poetry.package.pretty_version, version)

        self.line(
            "Bumping version from <comment>{}</> to <info>{}</>".format(
                self.poetry.package.pretty_version, version
            )
        )

        content = self.poetry.file.read()
        poetry_content = content["tool"]["poetry"]
        poetry_content["version"] = version.text

        self.poetry.file.write(content)


The only thing I adapted  is the read and write instructions, to make sure they read/write the appropriate file. When I debug the poetry code as in your version. The line
        poetry_content["version"] = version.text
does modify the content variable, as expected. However, in my version the poetry_content variable seems to be a copy, and consequently the content varable is not updated by that line. Debuging did not help to find out why I am getting a copy …
By the way, I managed to update the version in this way by using the toml package rather then using tomlkit, but then the formatting of the pyproject.toml gets lost.

I ll try to set up a small code that reproduces the problem and ship it to you - maybe tomorrow

Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 26 Jun 2019, at 07:45, brno32 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you share more of your code? I'm unsure of where ArgvInput comes from so I couldn't run your example.

If you just need to bump the version via a python script, this worked for me

import subprocess
subprocess.run(['poetry','version', 'minor'])

**Comment by etijskens** [comment]
Hi,
here is a reproducible test-code.
The script poetry_version.py is in principle equivalent to “poetry version patch”. It is using poetry 0.12.16 installed with pip install poetry. The command line command “poetry version patch” is also using poetry 0.12.16, installed in the recommended way on the poetry website. (Curl …)
T
he start version of a-test-project is “0.1.0”

> cd issue1182/a-test-project/
/Users/etijskens/software/dev/workspace/micc/issue1182/a-test-project

(testet) etijskens@etijskens@local [544] ~/software/dev/workspace/micc/issue1182/a-test-project
> python ../poetry_version.py
start
Bumping version from 0.1.0 to 0.1.1 # the message is correct

(testet) etijskens@etijskens@local [547] ~/software/dev/workspace/micc/issue1182/a-test-project
> cat pyproject.toml
[tool.poetry]
name = "a-test-project"
version = “0.1.0” # but the file is not updated (because the content variable in poetry/console/commands/version.py VersionCommand.handle() is not updated on executing the line “poetry_content["version"] = version.text")
description = "test_cli_with_project_name()"
authors = ["Engelbert Tijskens <engelbert.tijskens@uantwerpen.be<mailto:engelbert.tijskens@uantwerpen.be>>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/a-test-project"
homepage = "https://github.com/etijskens/a-test-project"

keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
cookiecutter = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4.2"

[tool.poetry.scripts]
#my-script = 'my_package:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

(testet) etijskens@etijskens@local [548] ~/software/dev/workspace/micc/issue1182/a-test-project
> poetry version patch
Bumping version from 0.1.0 to 0.1.1 # again the message is correct

(testet) etijskens@etijskens@local [549] ~/software/dev/workspace/micc/issue1182/a-test-project
> cat pyproject.toml
[tool.poetry]
name = "a-test-project"
version = “0.1.1” # this time the file is updated.
description = "test_cli_with_project_name()"
authors = ["Engelbert Tijskens <engelbert.tijskens@uantwerpen.be<mailto:engelbert.tijskens@uantwerpen.be>>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/a-test-project"
homepage = "https://github.com/etijskens/a-test-project"

keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
cookiecutter = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4.2"

[tool.poetry.scripts]
#my-script = 'my_package:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

(testet) etijskens@etijskens@local [550] ~/software/dev/workspace/micc/issue1182/a-test-project
>


Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 26 Jun 2019, at 07:45, brno32 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you share more of your code? I'm unsure of where ArgvInput comes from so I couldn't run your example.

If you just need to bump the version via a python script, this worked for me

import subprocess
subprocess.run(['poetry','version', 'minor'])

**Comment by etijskens** [comment]
In the mean time I tested your subprocess.run approach - successfully.
Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 26 Jun 2019, at 07:45, brno32 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you share more of your code? I'm unsure of where ArgvInput comes from so I couldn't run your example.

If you just need to bump the version via a python script, this worked for me

import subprocess
subprocess.run(['poetry','version', 'minor'])

**Comment by Ryuno-Ki** [comment]
Dear Mr. Tijskens,
would it be possible to use [code fences](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for better readability?
You can activate syntax highlighting for Python this way :-)

**Comment by etijskens** [comment]
the issue may be closed. It is probably caused by a resource that is not freed appropriately, due to the way the tests are set up. (though I haven't pinned it completely, yet).

**Comment by etijskens** [comment]
I finally tracked down the source of this error. I create my projects with  Cookiecutter. The template file for pyprojects contains a [tool.poetry.scripts] section AFTER the [build-system] section. when running E.g. ``poetry --version patch`` the version stringiest is NOT updated, but pyproject.toml is rewritten and now the [tool.poetry.scripts] section appears BEFORE the [build-system] section. Running  ``poetry --version patch`` a second time then updates the version string correctly. If I had gotten a warning that the pyproject.toml file is not in order, because, apparently, all [poetry.tool.<whatever>] sections must appear consecutively, I would not have lost three frustrating days tracking this problem. 

I suggest 
- that the documentation makes reference that sections should appear grouped with a reference to the  syntax of pyproject.toml files
- that tomlkit would warn on such issues, or circumvents it. An easy way around the problem is to have tomlkit to read the file and write it back to correct the order, and then read it back in...

I hope this helps other people experiencing this problem.

**Comment by adithyabsk** [comment]
@etijskens I ran into a very similar bug when using poetry.lock which seems to also required the build-system to be the last section in the pyproject.toml
