### ISSUE TITLE
Poetry doesn't work If you have no local .venv folder but have pygame==1.9.1release in system python folder

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#119]
[ValueError]         
Unable to parse "=1.9.1release".  
Exception trace:
 /usr/local/lib/python3.5/dist-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /usr/local/lib/python3.5/dist-packages/poetry/console/application.py in do_run() at line 84
   return super(Application, self).do_run(i, o)
 /usr/local/lib/python3.5/dist-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /usr/local/lib/python3.5/dist-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /usr/local/lib/python3.5/dist-packages/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /usr/local/lib/python3.5/dist-packages/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /usr/local/lib/python3.5/dist-packages/poetry/console/commands/install.py in handle() at line 35
   self.poetry.pool
 /usr/local/lib/python3.5/dist-packages/poetry/installation/installer.py in __init__() at line 55
   installed = self._get_installed()
 /usr/local/lib/python3.5/dist-packages/poetry/installation/installer.py in _get_installed() at line 509
   return InstalledRepository.load(self._venv)
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/installed_repository.py in load() at line 22
   repo.add_package(Package(name, version, version))
 /usr/local/lib/python3.5/dist-packages/poetry/packages/package.py in __init__() at line 52
   self._version = Version.parse(version)
 /usr/local/lib/python3.5/dist-packages/poetry/semver/version.py in parse() at line 151
   raise ValueError('Unable to parse "{}".'.format(text))

Poetry
======

 * Version: 0.10.0-alpha.0
 * Python:  3.5.3

Virtualenv
==========

 * Python:         3.5.3
 * Implementation: CPython
 * Path:           /home/buriy/.cache/pypoetry/virtualenvs/newsloader-py3.5

System
======

 * Platform: linux
 * OS:       posix

**Comment by jacebrowning** [comment]
@buriy Are you sure this exception is not simply caused by "1.9.1release" failing to conform to the versioning scheme (https://www.python.org/dev/peps/pep-0440/)?

**Comment by sdispater** [comment]
Yes, `1.9.1release` is not a supported version format. However it seems that it was installed before in your environment without any problem, maybe with `pip`?

**Comment by buriy** [comment]
@sdispater @jacebrowning  yes I guess so, it was "pygame===1.9.1release" in system python folder.
Which is apparently checked only when poetry creates its own virtualenv for a project (is it created with --use-system-packages ?).
So: Poetry might give a warning, but it shouldn't break operations when seeing an incorrect version in system python folder.
