### ISSUE TITLE
Support implicit namespace PEP 420

### ISSUE THREAD

**Issue by GiovanniCardamone** [sdispater/poetry#1199]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Hello, in PEP 420 (https://www.python.org/dev/peps/pep-0420/) 
there is specification for structuring vendor/package project 

(a short and more exaustive example is here: https://packaging.python.org/guides/packaging-namespace-packages/)

Currently using python 3.7.3 i generated this project with command:

`poetry new folder_name --name vendor_name.project_name`

```
[tool.poetry]
name = "vendor_name.project_name"
version = "0.1.0"
description = ""
authors = ["Giovanni Cardamone <hidden>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

as you can see the name for project is following the pep 420 specification `vendor_name.project_name`, but the folder structure is wrong

```
.
├── README.rst
├── pyproject.toml
├── tests
│   ├── __init__.py
│   └── test_vendor_name_project_name.py
└── vendor_name_project_name
    └── __init__.py
```

according with PEP 420, should be:
```
.
├── README.rst
├── pyproject.toml
├── tests
│   ├── __init__.py
│   └── test_vendor_name_project_name.py
└── vendor_name
    └── project_name
        └── __init__.py
```

also trying generate project using path definition
`poetry new folder_name --name vendor_name/project_name`

gave me this error:
```
[FileNotFoundError]
[Errno 2] No such file or directory: '/Users/step/Workspace/test/folder_name/vendor_name/project_name'
```

manually create folder and re-run the command gave me this error:
```
[FileNotFoundError]
'/Users/step/Workspace/test/folder_name/vendor_name/project_name'
```

- Thanks.

**Comment by Orderline** [comment]
Also, if it's used in this way, some changes will be needed, i will list them above:

in `pyproject.toml` this must be include:
```
[tool.poetry]
packages = [
    { include = 'vendor_name/project_name' },
]
```

in the `tests/test_vendor_name_project_name.py` file the import must be changed
from: `import vendor_name_project_name`
to: `import vendor_name.project_name`

that's it.

making this changes manually allows me to use implicit namespaces

**Comment by GiovanniCardamone** [comment]
Also, if it's used in this way, some changes will be needed, i will list them above:

in `pyproject.toml` this must be include:

```
[tool.poetry]
packages = [
    { include = 'vendor_name/project_name' },
]
```

in the `tests/test_vendor_name_project_name.py` file the import must be changed
from: `import vendor_name_project_name`
to: `import vendor_name.project_name`

that's it.

making this changes manually allows me to use implicit namespaces

**Comment by sdispater** [comment]
Implicit namespaces are supported, but the `new` command does not support it and it's unlikely that it's ever going to change. Implicit namespaces packages are not common enough to warrant adding a layout for it in the `new` command.

That being said, if someone is willing to do a PR for it we will gladly review it.
