### ISSUE TITLE
Poetry can't read its own pyproject.lock

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#120]
$ .venv/bin/poetry install -vvv
Installing dependencies from lock file
                                              
[ValueError]                   
Could not parse version constraint: !=3.0* 

Poetry versions tried:
0.9.0, 0.9.1

Apparently at this entry in pyproject.lock :
[[package]]
python-versions = ">=2.7,!=3.0*,!=3.1*,!=3.2*"
description = "Python bindings for 0MQ"
optional = false
platform = "*"
version = "17.0.0"
category = "dev"
name = "pyzmq"

I have this in my pyproject.toml, it installs pyzmq package:
[tool.poetry.dev-dependencies]
notebook = "^5.5"

**Comment by sdispater** [comment]
Yes it's fixed in 0.10.0a0.

However `>=2.7,!=3.0*,!=3.1*,!=3.2*` is not a valid constraint it should be `>=2.7,!=3.0.*,!=3.1.*,!=3.2.*`.

It just so happens that the new semver library I wrote handles this by removing the non-compliant part and makes it work.
