### ISSUE TITLE
Caret requirements ^0 allowed only 0.0.x versions

### ISSUE THREAD

**Issue by b0g3r** [sdispater/poetry#1203]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **macOS 10.14.5**: 
- **0.12.16**: 
- **[pyproject.toml](https://gist.github.com/b0g3r/fd95eeac9536cb7fc28abd8547bc7aba)**: 

## Issue
If I use caret version specifier with one zero: `^0` then I receive version `0.0.xx` in the lock file. But if I set `^0.8.1` then I receive `0.8.1`. Why? The [documentation](https://poetry.eustace.io/docs/versions/#caret-requirements) says that `^0` is a equivalent for `  >=0.0.0 <1.0.0`

**Comment by b0g3r** [comment]
This behavior appears after `poetry lock`, but if I use `poetry update wemake-python-styleguide` then lock file looks correct for caret requirements.

**Comment by jacebrowning** [comment]
The documentation also say s that `^0.2.3` is equivalent to  `>=0.2.3 <0.3.0`, so I think what you're seeing is expected. Which version do expect `^0.8.1` to install?

**Comment by b0g3r** [comment]
But what about `^0`? Why this install 0.0.x, not 0.x.x?
