### ISSUE TITLE
How to specify multiple PEP 508 markers using the != operator?

### ISSUE THREAD

**Issue by MarkKoz** [sdispater/poetry#1211]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

For multiple platforms I know I can do something like 

```toml
foo = [
    { version = "^1.0.0", platform = "a" },
    { version = "^1.0.0", platform = "b" }
]
```

But how can I specify `!=` instead of `==` that Poetry uses? It's not feasible to manually write out all other platform besides the ones I want to ignore and the syntax above is cumbersome enough as is.

**Comment by sdispater** [comment]
Specifying arbitrary environment markers, including negative ones, is supported in the `1.0.0` latest prerelease (see #1142). You can start using the prereleases is you want to have this feature
