### ISSUE TITLE
Adding a dependency with --git or --path doesn't add a newline to pypoetry.toml in 0.12.17

### ISSUE THREAD

**Issue by Heliozoa** [sdispater/poetry#1219]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.2 LTS
- **Poetry version**: Poetry 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Heliozoa/2291a453d00abcfcf8e6515b76c71fcc

## Issue
The gist is a result of running the following commands in 0.12.7
```bash
poetry init
poetry add pendulum --git https://github.com/sdispater/pendulum.git
poetry add my-package --path ../my-package/
```
After the first add, the empty line between poetry.dependencies and poetry.dev-dependencies is gone. The second one causes an error because the dev-dependency table now starts on the same line as the second dependency.

I remember it working very recently so I tried both 0.12.16 and the preview version 1.0.0a4. It issue is present in 1.0.0a4 but not 0.12.16.

Thanks for your work on poetry!

**Comment by wy193777** [comment]
Same problem here with 0.12.17.

**Comment by pwoolvett** [comment]
In develop branch, which uses `tomlkit`:
By changing https://github.com/sdispater/poetry/blob/aa2cc9b58b9ce869c0625463197e4799aca84c2e/poetry/console/commands/add.py#L54 into
```
        from tomlkit.items import InlineTable, Trivia
        from tomlkit.container import Container
```

and https://github.com/sdispater/poetry/blob/aa2cc9b58b9ce869c0625463197e4799aca84c2e/poetry/console/commands/add.py#L97 into
```
            constraint = InlineTable(Container(), Trivia(), new=True)
```

the issue goes away: the default function call used `Trivia(trail="")` instead. 

I'd be happy to make a PR with the fix...
