### ISSUE TITLE
Maximum recursion depth exceeded with manimlib

### ISSUE THREAD

**Issue by jsandovalc** [sdispater/poetry#1222]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). (it took too long and had to stop it).

- **OS version and name**: Debian GNU/Linux 10.0
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

https://gist.github.com/jsandovalc/90adb4b16e1b760360700f8b8494a00b

## Issue
I just created a new project to test poetry and a library a need. I executed `poetry new manim-test` and then `poetry add manimlib`.

I'm getting as output:

```
Using version ^0.1.10 for manimlib

Updating dependencies
Resolving dependencies... (6.0s)
                                    
[RecursionError]     
maximum recursion depth exceeded  
                                    
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

Thanks for any help.

**Comment by sdispater** [comment]
I think this is similar to #1238. Closing this issue to track the resolution progress in only one place.
