### ISSUE TITLE
subprocess.run AttributeError occurred in Python 3.4

### ISSUE THREAD

**Issue by debugtalk** [sdispater/poetry#1223]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

**Environment**

* Poetry version: 0.12.17
* Python version: 3.4.8
* OS: Ubuntu 16.04.6 LTS in travis ci

https://travis-ci.org/HttpRunner/HttpRunner/jobs/557941936

## Issue

**Description**

AttributeError occurred in Python 3.4, because [the subprocess.run() function only exists in Python 3.5 and newer](https://stackoverflow.com/questions/40590192/getting-an-error-attributeerror-module-object-has-no-attribute-run-while).

```bash
$ poetry install -v
                                          
[AttributeError]           
'module' object has no attribute 'run'  
                                          
Exception trace:
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/console/commands/env_command.py in initialize() at line 18
   current_env = Env.get(self.poetry.file.parent)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/utils/env.py in get() at line 227
   return VirtualEnv(prefix, base_prefix)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/utils/env.py in __init__() at line 483
   self._base = Path(self.run("python", "-", input_=GET_BASE_PREFIX).strip())
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/utils/env.py in run() at line 539
   return super(VirtualEnv, self).run(bin, *args, **kwargs)
 /home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/poetry/utils/env.py in run() at line 373
   output = subprocess.run(
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
The command "poetry install -v" failed and exited with 1 during .
```

**How to Reproduce**

View the detail logs in [travis CI job](https://travis-ci.org/HttpRunner/HttpRunner/jobs/557941936).

**Comment by bertjwregeer** [comment]
Python 3.4 was EOL 2019-03-18. See here: https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by pbzweihander** [comment]
I think [this commit](https://github.com/sdispater/poetry/commit/eb3bdd4396af2fcf61000f7a3f3d201f08101880#diff-16b63823cc41a393ccd32f81bdcdeff5) solved this issue!

**Comment by debugtalk** [comment]
>Python 3.4 was EOL 2019-03-18. See here: https://devguide.python.org/devcycle/#end-of-life-branches

@bertjwregeer I agree. Thus the README should say Poetry supports 2.7 and 3.5+😁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
