### ISSUE TITLE
Runtime ContextualVersionConflict error with setuptools after installing project dependencies

### ISSUE THREAD

**Issue by sangaline** [sdispater/poetry#1226]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [n/a] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `Linux 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux`
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://pastebin.com/raw/LLmpq71Y

## Issue

The `poetry install` command completes without errors, but a `ContextualVersionConflict` error is raised when trying to run a command within the project. It looks like poetry is installing setuptools version 40.8.0, but tensorboard requires at least 41.0.0.

```
Traceback (most recent call last):
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 40.8.0 (/project/.venv/lib/python3.7/site-packages), Requirement.parse('setuptools>=41.0.0'), {'tensorboard'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/.venv/bin/science", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 40.8.0 (/project/.venv/lib/python3.7/site-packages), Requirement.parse('setuptools>=41.0.0'), {'tensorboard'})
```

**Comment by jacebrowning** [comment]
How did you install Poetry? The recommended installation method should keep Poetry's dependencies separate from your project: https://github.com/sdispater/poetry#installation

**Comment by sangaline** [comment]
I tried 1) using the recommended installer script, 2) using the system package manager, and 3) installing it using pip with pyenv. This is part of a docker build, so it's a fresh install each time and the different attempts shouldn't be interfering with each other.

**Comment by jcastagneri** [comment]
I was also running into this problem. I installed poetry by the supported method, and hat a `setuptools` version error when trying to load an entrypoint script. The following is a workaround:

1. Delete the virtual environment and the `poetry.lock` file
2. Remove all dependencies from your `pyproject.toml`
3. Run `poetry install` with against the `pyproject.toml` file that carries no dependencies
4. Add back in your dependencies with `poetry add tensorflow-gpu`, etc

This worked for me. I suspect there is a bug related to the order of installs. When I add dependencies before installing my package (and therefore the entrypoints), I get the error. If I install the package first, I'm able to build the environment.

**Comment by mitsuse** [comment]
This issue seems to be due to venv's setuptools. I tried a workaround (`poetry run pip install -U setuptools` before `poetry install`) and fixed the issue, but I think that the desirable fix is that poetry avoids taking the version of venv's setuptools  into consideration.

**Comment by mitsuse** [comment]
The exception seems to be caused by pip, but pip doesn’t fail for installation of `tensorboard==2.0.0` which requires `setuptools>=41.0.0` on a venv environment with  incompatible versions of `setuptools`. For installation of tensorflow-gpu==1.14`, pip doesn't fail but warns.

c.f.https://github.com/pypa/pip/blob/19.2.3/src/pip/_vendor/pkg_resources/__init__.py#L258-L300

**Comment by mitsuse** [comment]
While executing `pip install`, changing the version of setuptools possibly breaks dependencies, so I think `poetry run pip install -U setuptools && poetry install` is a correct currently and unfortunately. In that sense, I agree this:

> I suspect there is a bug related to the order of installs.
> 
> https://github.com/sdispater/poetry/issues/1226#issuecomment-513311134
