### ISSUE TITLE
Poetry still fails to install in Docker

### ISSUE THREAD

**Issue by fralik** [sdispater/poetry#1227]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, Docker with python:3.7
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/fralik/26a0797e1cd940c89e871bccabcad982

## Issue
I believe this is a similar issue to #512. That issue is marked as resolved, however I still see the error.

I am trying to use poetry in Docker with a custom packaging scheme (see my [pyproject.toml](https://gist.github.com/fralik/26a0797e1cd940c89e871bccabcad982) file). If I build a package locally with `poetry build`, then I can see that Poetry finds modules and packages them successfully.

However, once I try to build a Docker image I get this exception:
```
[ValueError]                        
/app/src/sensortag does not contain any element  
                                                   
Exception trace:
 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)

 /root/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)

 /root/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)

 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)

 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py in execute() at line 107
   return self.handle()

 /root/.poetry/lib/poetry/console/commands/install.py in handle() at line 61
   builder = EditableBuilder(self.poetry, self._env, NullIO())
 /root/.poetry/lib/poetry/masonry/builders/builder.py in __init__() at line 48
   includes=self._package.include,

 /root/.poetry/lib/poetry/masonry/utils/module.py in __init__() at line 62
   PackageInclude(self._path, package["include"], package.get("from"))
 /root/.poetry/lib/poetry/masonry/utils/package_include.py in __init__() at line 16
   self.check_elements()

 /root/.poetry/lib/poetry/masonry/utils/package_include.py in check_elements() at line 40
   "{} does not contain any element".format(self._base / self._include)
```
My Dockerfile is provided as well.

If I remove `packages` from `pyproject.toml`, then everything installs fine in docker.

**Comment by brycedrennan** [comment]
You're trying to install the sensortag package but haven't included it's code in the docker image.

**Comment by bufke** [comment]
Is there a better solve than adding the code to the docker image? Consider the Docker Compose getting started [page](https://docs.docker.com/compose/gettingstarted/).

Here we install packages (with pip) before the code is added to the image. Often times in development, the code is just mounted after build. However this can't be done with Poetry if the pyproject.toml references a package, which is often necessary for packaging.

**Comment by bufke** [comment]
Adding `--no-root` to poetry install seems to fix this without needing to copy the source. This allows Docker builds to better cache a project that's in development where source frequently changes but packages do not.

**Comment by Edwardp17** [comment]
@bufke I'm working on a project that requires similar logic and came across this thread. If i'm understanding correctly, adding `--no-root` would no install the developing package into the environment - what would be the benefit of that? Caching for Docker makes sense, but then the package is not able to be imported and used in the environment?
