### ISSUE TITLE
Installing "less than" dependency fails to find the package

### ISSUE THREAD

**Issue by MadWombat** [sdispater/poetry#1229]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OS X Mojave. Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
- **Poetry version**: Poetry 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
https://gist.github.com/MadWombat/a9cf58d94bc0a683c2138dad04a3e8a4

Installing a dependency for Django LTS works fine with pip, but fails with poetry

with pip:

```
~/project/> pip3 install 'Django<1.12'
Collecting Django<1.12
  Downloading https://files.pythonhosted.org/packages/70/22/237da71dc112f2bba335c18380bc403fba430c44cc4da088824e77652738/Django-1.11.22-py2.py3-none-any.whl (6.9MB)
     |████████████████████████████████| 7.0MB 3.9MB/s 
Collecting pytz (from Django<1.12)
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Installing collected packages: pytz, Django
Successfully installed Django-1.11.22 pytz-2019.1
```

with poetry:

```
~/project> poetry add 'Django<1.12'
                                    
[PackageNotFound]    
Package [Django<1.12] not found.  
                                    
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

**Comment by sdispater** [comment]
At the moment, you have to do it like so:

```bash
poetry add "django:<1.12"
```

The notation you are using will be supported in the `1.0.0` verson (see #1221)
