### ISSUE TITLE
add alias 'po' or 'poe' for poetry 

### ISSUE THREAD

**Issue by jessekrubin** [sdispater/poetry#1232]
I use poetry for several projects and like it quite a bit. Everywhere I use it (windows or linux) I alias/make-a-bat-file-2-alias poetry to 'po' or 'poe'

I like typing 3/4 less characters and it fits the package's motif as you/one could claim that it is a reference to edgar allan poe.

**Comment by bertjwregeer** [comment]
I associate "po" with https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html which are translatable files for gettext, I would not recommend using that name.

**Comment by justinmayer** [comment]
IMHO this should remain the way it is, with users aliasing as they please. For example, Fish shell users could use:

    abbr -a po poetry

I think individual users should use their own shell-level aliases instead of making any shortened versions of `poetry` within the project itself.
