### ISSUE TITLE
Local config.toml files or local-config options per directory.

### ISSUE THREAD

**Issue by jessekrubin** [sdispater/poetry#1234]
I would like to be able to have poetry hide and manage some venvs and/or use a predefined venv, or create the venv in project if it doesn't exist, or have nothing to do with a virtualenv for other projects. Right now I find myself having to `poetry config somesetting t/f` all the time and I would like to be able to config on a directory basis.

**Comment by justinmayer** [comment]
Per-project configuration is already on the roadmap: https://github.com/sdispater/poetry/issues/618

Ergo, I believe this duplicate issue should be closed.

**Comment by jessekrubin** [comment]
Who is Ergo?

**Comment by justinmayer** [comment]
“Ergo” means “therefore” or “consequently”. https://en.wiktionary.org/wiki/ergo
