### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jondot** [sdispater/poetry#124]
Watching all the commotion over at reddit and social, I just passed by to say thanks.

Coming from over 20 years of polyglot development, being part of the Ruby, Node and Go communities, just as it happens now for Python - I've seen - from the front row, rubyforge/gem/bundler/etc. shape up, and then npm and the amazing yarn move to fix many of npm's shortcomings (I've been using Node as early as 0.1x's), Rust/cargo shape up with @wycatz leading the way, and then the whole Go community effort to resolve dependency management which I've learned a ton from. 

All this time, I always thought Python had so much breakage, and it stopped me from _using_ Python (I hold the opinion that a language that doesn't have a great package manager and dependency resolution isn't worth spending time with) - be it the Python 2 and 3 community brainsplit, and then the various ways to package and maintain dependencies that didn't work for me most of the time, making the hours on top of hours of building a packaging solution legitimate again (I've never had called spending time on a build process "legitimate" since my C++ days).

Here I was reading Kenneth's post, leading to the Reddit thread and the poetry reference (I guess I was exposed to all of this in the reverse order!). Leaving all the drama aside, and thinking about "what do I get out of each of these projects, really", I tried Poetry, flit, hatch (I already use Pipenv, and I wouldn't say I'm super happy with it because that's not a workflow I'm used to - it might be perfect for real Pythonistas, not fake ones like me :) ).

Going over poetry - everything felt "right". Finally I was thinking: someone *did it*.

In fact, I kept thinking "I wish this tool also consolidated all user scripts, like npm/yarn does - which always was a one-up over bundler for me". Before even fully reading the README, I decide to start working on it.

Diving into the code, I bumped into the fact that - poetry already does this.

At this point - I had to stop and say thanks.

Please don't let all the discussions / politics stop you. If there's one thing I wish - is for this tool to continue to exist, because for me, it is _finally_ how packaging should look like. 

Thanks

**Comment by maxcountryman** [comment]
Kenneth's responses to competing efforts to solve this problem have been disheartening to say the least. I hope that others are able to look beyond the celebrity of one person and judge the tools for their various merits. To that end I feel that the particular approach Poetry takes, analogous to something like Cargo in the Rust world, is nearing something ideal and deserves to be seen as such. So thank you for your efforts here--it's really appreciated and much needed.

**Comment by moigagoo** [comment]
I would just like to chime in and share the same sentiment as @jondot. I've tried Pipenv and was _not_ exited at all. As a Windows user, I could help feeling discriminated.

When I discovered Poetry and tried it for a few minutes, it just clicked instantly. Even at the early stage it is today, it's already good enough for my projects, and I've already moved some of them to Poetry; couldn't be happier.

I don't know if I count as a true Pythonista, by I've been coding in Python for almost a decade now. Poetry feels much more pythonic than anything I've tried.

So, @sdispater , please accept another huge thank you!

P.S. What's the story with Kenneth's responses everyone's talking about? Could you please give a link to the post, just for information?

**Comment by bertjwregeer** [comment]
@moigagoo this thread on Reddit: https://www.reddit.com/r/Python/comments/8jd6aq/why_is_pipenv_the_recommended_packaging_tool_by/

Don't spend too much time on this nonsense though, pipenv like poetry is just another tool to add to your tool belt, the drama surrounding tooling is a little insane.

**Comment by flying-sheep** [comment]
Once #210 is fixed I think I’ll try out poetry. I’m pretty happy with flit, but poetry seems to have a few convenience features I’d like :smiley:

**Comment by pawamoy** [comment]
> In fact, I kept thinking "I wish this tool also consolidated all user scripts, like npm/yarn does - which always was a one-up over bundler for me". Before even fully reading the README, I decide to start working on it.

> Diving into the code, I bumped into the fact that - poetry already does this.

When you say "user scripts", it's a reference to the "scripts" section of `package.json` right? Like they are meant to replace a Makefile or else?

Well, Poetry's scripts are not the same thing. Poetry's `scripts` section is named "scripts" like setuptools'  entry point `console_scripts`. These scripts result in executable file on your PATH upon installation. They are not meant to be run within your development environment as shortcut commands.

I actually **did not** read the source code of Poetry so please, correct me if I'm wrong!!

**Comment by jondot** [comment]
You're right, I'm still using poetry exclusively for everything so I managed to get more sense under what poetry scripts are; and no they are not what I thought :).
So this means I'd still love for poetry to replace my `Makefile` in every project!

**Comment by pawamoy** [comment]
For reference: https://github.com/sdispater/poetry/pull/591 :slightly_smiling_face:
