### ISSUE TITLE
Poetry UserWarning: warn_ungrouped_named_tokens_in_collection

### ISSUE THREAD

**Issue by zachliu** [sdispater/poetry#1244]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

```
/home/zach/project/.venv/lib/python3.7/site-packages/poetry/version/requirements.py:170: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
  VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
/home/zach/project/.venv/lib/python3.7/site-packages/poetry/version/requirements.py:173: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'marker' on And expression collides with '_original_end' on contained expression
  MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
```
I've been seeing the above warning messages while using `poetry` commands such as
```
poetry install
poetry run
poetry shell
```
I `pip` installed `poetry 0.12.17` in my `Python 3.7.0` virtual environment.

**Comment by addyess** [comment]
I saw this in a completely different package

**Comment by amarshall** [comment]
Seems to be an issue with pyparsing 2.4.1, as reverting it to 2.4.0 no longer shows the warning.

**Comment by zachliu** [comment]
@amarshall Confirmed! Reverted to `pyparsing==2.4.0` the warning messages disappeared. Now the question is why :thinking:

**Comment by Skufler** [comment]
Got the same issue, but there isn't `pyparsing` in dependencies. Here is my `pyproject.toml` 
```
[tool.poetry.dependencies]
python = "^3.7.0"
asyncio = "^3.4"
aiohttp = "^3.4"
motor = "^2.0"
umongo = "^1.0"
pyyaml = "^3.13"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
mypy = "^0.650.0"
wemake-python-styleguide = "^0.5.1"
pytest-mock = "^1.10"
pytest-asyncio = "^0.9.0"
pytest-aiohttp = "^0.3.0"

**Comment by zachliu** [comment]
@Skufler Could you double check your `poetry.lock` file?

**Comment by Cgironalas** [comment]
Just ran some tests, it seems like doing `pip install poetry==0.12.16` installs `pyparsing==2.4.1`. I'd guess it installs the same version with `poetry==0.12.17`

**Comment by Skufler** [comment]
@zachliu 
Yes, you can check by yourself 
[lock.txt](https://github.com/sdispater/poetry/files/3423559/lock.txt)

**Comment by zachliu** [comment]
`pyparsing 2.4.1` has been removed from pypi :laughing:

**Comment by henriklindgren** [comment]
> `pyparsing 2.4.1` has been removed from pypi laughing

Yeah :) 2.4.1.1 is 2.4.1, see https://github.com/pyparsing/pyparsing/releases/tag/pyparsing_2.4.1.1

**Comment by zachliu** [comment]
> > `pyparsing 2.4.1` has been removed from pypi laughing
> 
> Yeah :) 2.4.1.1 is 2.4.1, see https://github.com/pyparsing/pyparsing/releases/tag/pyparsing_2.4.1.1

`pyparsing 2.4.1.1` still causes this warning :man_facepalming:

**Comment by nekokatt** [comment]
Can also confirm. Due to how my project's CI pipelines work, I am getting about thirty of these mangled with my other output each time my pipelines run :sweat_smile: 

```
/code/hikari/.nox/format_check/lib/python3.7/site-packages/poetry/version/requirements.py:170: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
  VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
/code/hikari/.nox/format_check/lib/python3.7/site-packages/poetry/version/requirements.py:173: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'marker' on And expression collides with '_original_end' on contained expression
  MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
```

**Comment by paulmcg-iio** [comment]
Pyparsing 2.4.2 (pushed to PyPI this evening) disables these warnings by default

**Comment by zachliu** [comment]
Pinned Pyparsing to 2.4.2 in my lock file. Everything is hunky-dory. Thank you guys.

**Comment by rzuckerm** [comment]
Pyparsing 2.4.2 is not solving this problem for me:
```
/usr/local/lib/python3.6/dist-packages/poetry/version/requirements.py:170: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
/usr/local/lib/python3.6/dist-packages/poetry/version/requirements.py:173: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'marker' on And expression collides with '_original_end' on contained expression
```
Here's my pyproject.toml:
```
[tool.poetry.dependencies]
python = ">=2.7, != 3.0.*, != 3.1.*, != 3.2.*, != 3.3.*"
selenium = "^3.14"
future = "^0.16.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0.6"
pylama = {version = "^7.6", python = ">= 3.4" }
pylint = { version = "^2.2", python = ">= 3.4" }
pytest-cov = "^2.6"
black = { version = "18.9b0", python = ">= 3.6" }
sphinx = { version = "^2.0", python = ">= 3.5" }
mock = "^1.3.0"
```
This is in my poetry.lock:
```
[[package]]
category = "dev"
description = "Python parsing module"
marker = "python_version >= \"3.5\""
name = "pyparsing"
optional = false
python-versions = ">=2.6, !=3.0.*, !=3.1.*, !=3.2.*"
version = "2.4.2"
```

**Comment by zachliu** [comment]
> Pyparsing 2.4.2 is not solving this problem for me:
> 
> ```
> /usr/local/lib/python3.6/dist-packages/poetry/version/requirements.py:170: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
> VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
> /usr/local/lib/python3.6/dist-packages/poetry/version/requirements.py:173: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'marker' on And expression collides with '_original_end' on contained expression
> ```
> 
> Here's my pyproject.toml:
> 
> ```
> [tool.poetry.dependencies]
> python = ">=2.7, != 3.0.*, != 3.1.*, != 3.2.*, != 3.3.*"
> selenium = "^3.14"
> future = "^0.16.0"
> 
> [tool.poetry.dev-dependencies]
> pytest = "^3.0.6"
> pylama = {version = "^7.6", python = ">= 3.4" }
> pylint = { version = "^2.2", python = ">= 3.4" }
> pytest-cov = "^2.6"
> black = { version = "18.9b0", python = ">= 3.6" }
> sphinx = { version = "^2.0", python = ">= 3.5" }
> mock = "^1.3.0"
> ```
> 
> This is in my poetry.lock:
> 
> ```
> [[package]]
> category = "dev"
> description = "Python parsing module"
> marker = "python_version >= \"3.5\""
> name = "pyparsing"
> optional = false
> python-versions = ">=2.6, !=3.0.*, !=3.1.*, !=3.2.*"
> version = "2.4.2"
> ```

What about `pyparsing 2.4.0`?
