### ISSUE TITLE
Poetry breaks when a package that has jsonschema as dependency is removed

### ISSUE THREAD

**Issue by DavidBord** [sdispater/poetry#1252]
- **OS version and name**: macOS 10.14.1
- **Poetry version**: 0.12.17

## Issue
poetry add moto -D
poetry show
poetry remove moto -D
poetry show

This error is received:

[ModuleNotFoundError]  
No module named 'jsonschema'        
                                      
show [--no-dev] [-t|--tree] [-l|--latest] [-o|--outdated] [-a|--all] [--] [<package>]

**Comment by sdispater** [comment]
As far as I know this can only happen if you install Poetry in the same virtualenv as the project your are managing with it, which is not supported.
