### ISSUE TITLE
restrict dependencies by operating system

### ISSUE THREAD

**Issue by espositofulvio** [sdispater/poetry#126]
### Feature request

Add the ability to restrict dependencies by operating systems.

#### Rationale

I couldn't find any docs about how to achive this in poetry, but sometimes there are optional dependencies that may be installed only on specific operating systems, for example uvloop is not windows compatible, so having something like:

```
uvloop = { version = "^0.9.0", sys_platform != "windows" }
```

can come handy

**Comment by jacebrowning** [comment]
I think this is a duplicate of https://github.com/sdispater/poetry/issues/21.

**Comment by espositofulvio** [comment]
@jacebrowning Yes you are right, I couldn't find the issue. Sorry, I'll close this.
