### ISSUE TITLE
Support GnuPG signing

### ISSUE THREAD

**Issue by ovalseven8** [sdispater/poetry#127]
First of all, thanks for this cool project! :)

When I look at package and dependency managers, one of the first things I search for is if it's supporting verifying of signed packages.

Security is a sensitive topic, so it would be cool if `poetry` would _optionally_ support verifying signes packages.

**Comment by bertjwregeer** [comment]
Great post by @dstufft on the topic: https://caremad.io/posts/2013/07/packaging-signing-not-holy-grail/

Post regarding twine and PGP signing: https://github.com/pypa/twine/issues/157

David Fischer also has an article that describes the issue with PGP signing: https://www.davidfischer.name/2012/05/signing-and-verifying-python-packages-with-pgp/

Verifying signed packages, even optionally, doesn't make a whole lot of sense unless you trust the public key. There is no central authority. 

Warehouse the new PyPI implementation deemphasises PGP support: https://github.com/pypa/warehouse/issues/3356

I don't think there is a lot of value in verifying signatures, even optionally TBH.

**Comment by techtonik** [comment]
Verifying signatures protects from data tampering, but as long as https on PyPI is not broken, and site doesn't allow modifications of the previous versions, it should be fine.

**Comment by prokopst** [comment]
IIRC some companies actually are required (besides many things) to sign their own, private packages to get a security certification to be complaint to work with XYZ corporation working with sensitive data. But I guess such companies don't use Python anyway...

**Comment by sdispater** [comment]
I have no plan on adding this to Poetry at the moment.
