### ISSUE TITLE
Pytest config

### ISSUE THREAD

**Issue by hound672** [sdispater/poetry#1276]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hello, can I write settings for pytest (for example) in pyproject.toml? I've tried the next one to put in pyproject.toml, but it does not work:

`[tool.pytest]`
`addopts = "--cov=JWTAuth -v -rxXs"`

**Comment by jacebrowning** [comment]
The Poetry project does not provide technical support for usage of `pyproject.toml`, which is a Python standard and not Poetry-specific.

Your question should be directed to the pytest maintainers: https://github.com/pytest-dev/pytest/issues/1556
