### ISSUE TITLE
Poetry doesn't honor python version constraint in setup.py

### ISSUE THREAD

**Issue by mbelang** [sdispater/poetry#1287]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Debian Stretch inside docker, reproduced on Arch Linux
- **Poetry version**: 0.12.17
- **pyproject.toml file**: https://gist.github.com/mbelang/67dbee8217164fd0fa57bdff52f29775

## Issue
It seems that poetry doesn't honor the following constraint:
```python
if sys.version_info[0] >= 3:
    install_requires = ['Flask>=0.10.1', 'python3-openid>=2.0']
    extra['use_2to3'] = True
else:
    install_requires = ['Flask>=0.3', 'python-openid>=2.0']
```
Link to source: https://github.com/mitsuhiko/flask-openid/blob/master/setup.py#L30

In the gist pyproject.toml, airflow is installing Flask which installs flask-openid. If I do not maually add `python3-openid = "^3.1"` in my pyproject.toml, poetry installs `python-openid==2.2.5` which is only compatible with python 2.

**Comment by spumer** [comment]
Same issue for ﻿﻿﻿﻿https://github.com/python/typing/blob/master/typing_extensions/setup.py#L67

And as a result this broke package installation with `AttributeError: type object 'Callable' has no attribute '_abc_registry'` like here https://github.com/aws/chalice/issues/1050

**Comment by sdispater** [comment]
This issue has been reported before and the gist of it is: this is not an issue with Poetry. Checking the Python version programmatically is not recommended and [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) should be used. Poetry does not execute the `setup.py` file, for security reasons, and as such cannot see the dependencies.

You should report the issue upstream.

**Comment by mbelang** [comment]
Fair enough but I thought poetry was using pip under the hood and pip install does honor the dependency?

**Comment by sdispater** [comment]
@mbelang This is true for installing the packages but not for resolving the dependencies.
