### ISSUE TITLE
Add support for local fallback package source

### ISSUE THREAD

**Issue by badrobit** [sdispater/poetry#1289]
It would be useful for environments where development can occur with an internet connection but deployments are on isolated systems that a fall back of a local "path" can be defined (could even be project wide) so that if the desired package(s) cannot be found and pulled from the online original source a backup local location can also be provided to be checked.

**Comment by a-recknagel** [comment]
Is this the same as https://github.com/sdispater/poetry/issues/14 ?

**Comment by badrobit** [comment]
no this would be different in that it is not an offline or local package repository but a folder where the wheel or arc files downloaded from a pip download command could be stored. this way poetry could still be leveraged on systems that have to be fully isolated aka no network connection (think higher end embedded platforms)

**Comment by a-recknagel** [comment]
So similar to `pip install --find-links=<some_url_or_directory>`? There is https://github.com/sdispater/poetry/issues/558 that asks for that, more or less. Does it cover your use case?

**Comment by badrobit** [comment]
@a-recknagel it is similar except this would add it as a "fallback" method so that the same pyproject.toml could be used for both offline (deployment) and online (development usage) to act in the same manner as a pypi like repository but an offline fall back that would hopefully allow for something to the effect of the following install behavior: 

1. Check online packages per the default methodology 
2. if the response to all online repositories is no connection or an install flag of something like --offline is found during the poetry install or poetry update commands use the provided offline archive (link) location.

That would allow a little bit more flexibility in that it wouldn't force the user to select a source but rather allow them to define a fallback location if the normal source (aka pypi) fail.

**Comment by allen-chin** [comment]
From what I can see for #558, if you just change the order of the sources, would that have the behavior that you want?
