### ISSUE TITLE
poetry export --extras does not export sub-dependencies

### ISSUE THREAD

**Issue by tommilligan** [sdispater/poetry#1293]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [ x I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.0b1

## Issue

#1285 introduced a regression.

When exporting groups specified by the `--extras` flag, sub-dependencies of these extra optional packages are not exported.

**Comment by hvdklauw** [comment]
Not sure if it is 100% related, but when you have a dependency with extra's in your pyproject.toml and you export it to a requirements.txt file the extras argument get's added to the dependency itself:

pyproject.toml
```
django-anymail = {version = "^6.0", extras = ["sparkpost"]}
django-phonenumber-field = {version = "^3.0", extras = ["phonenumbers"]}
```

Then when I do a `poetry export -f requirements.txt` the output is:

```
...
phonenumbers==8.10.17; extra == "phonenumbers" \
    --hash=sha256:b913023be4f99a210038efd3cef5212b3d11fdf7829a0b75a0031cff3eae2d9e \
    --hash=sha256:e9752dda6abb076d528d954d16c8bc7f8682df6f42c837862d0dea88c7667908
...
sparkpost==1.3.6; extra == "sparkpost" \
    --hash=sha256:75d1a408c7a581377ac9cc2cfef1de1249e49cb631921033cc3ff115b08c2c81 \
    --hash=sha256:abaf5045d04d821f9c29c965d97173f52f6acc2051debca6f122ea7456cc1733
...
```

Which then when I try to pip install it results in:
```
Ignoring phonenumbers: markers 'extra == "phonenumbers"' don't match your environment
Ignoring sparkpost: markers 'extra == "sparkpost"' don't match your environment
```

```

**Comment by tommilligan** [comment]
This is unrelated - please could you open a new issue? Bisected that the issue was introduced somewhere between 442ff52 and e987f01, which was before #1285 was merged.

**Comment by hvdklauw** [comment]
Ok, someone mark my comment as off topic :)

**Comment by stephsamson** [comment]
#1294 resolves this issue.
