### ISSUE TITLE
Some references not updated

### ISSUE THREAD

**Issue by thebigmunch** [sdispater/poetry#13]
There are still references to ``poet`` vs ``poetry`` in the README. And the CLI help still refers to ``poetry.toml`` vs ``pyproject.toml``.

**Comment by briancappello** [comment]
For people unfamiliar with history of the projects (like me), what's the difference between the two? Is `poetry` a kind of v2 of `poet`? I wonder if it would be helpful to put a short blurb at the bottom of the `poetry` readme, and/or one at the top of `poet`'s readme, explaining a bit about their relationship, if poetry is indeed the successor to `poet`?
