### ISSUE TITLE
JSONDecodeError on 0.12.17

### ISSUE THREAD

**Issue by BramVer** [sdispater/poetry#1308]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux on 4.19.66
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Can't generate a `pyproject.toml` file

## Issue
I've gone through the issues but cannot find anything that fixes the JSONDecodeError I keep having, regardless of the poetry version I'm using.  
People have seemed to gotten lucky with deleting their `~/.cache/pypoetry` folder, but that has 0 effect for me.  
I've tried this on version 0.12.15 and 0.12.16 as well, same issue.

0.12.17 is supposed to have the fix to this issue (or at least be more descriptive when something goes wrong), but to no avail.  

**Note:** Poetry is giving this error regardless of where it's run (existing project or new project).  

To give you an overview of what goes wrong, I also included a clean install:
```bash
# In folder ~/dev/test

# Removing current version to start clean
➜  test sudo pacman -R poetry
checking dependencies...

Packages (1) poetry-0.12.17-1

Total Removed Size:  22.46 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/1) removing poetry                                                                                                                                                                       
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

# Installing latest Poetry version
➜  test sudo pacman -S poetry 
resolving dependencies...
looking for conflicting packages...

Packages (1) poetry-0.12.17-1

Total Installed Size:  22.46 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                                                                              
(1/1) checking package integrity                                                                                                                                                            
(1/1) loading package files                                                                                                                                                                 
(1/1) checking for file conflicts                                                                                                                                                           
(1/1) checking available disk space                                                                                                                                                         
:: Processing package changes...
(1/1) installing poetry                                                                                                                                                                     
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

➜  test poetry new tester
Invalid -W option ignored: invalid module name: 'yaml'
                                             
[JSONDecodeError]             
Expecting value: line 1 column 1 (char 0)  
                                             
new [--name NAME] [--src] [--] <path>

# Removing all cache related to poetry
➜  test rm ~/.cache/pypoetry -rf

➜  test poetry new tester       
Invalid -W option ignored: invalid module name: 'yaml'
                                             
[JSONDecodeError]             
Expecting value: line 1 column 1 (char 0)  
                                             
new [--name NAME] [--src] [--] <path>

➜  test poetry --version 
Invalid -W option ignored: invalid module name: 'yaml'
Poetry 0.12.17

➜  test poetry new tester -vvv
Invalid -W option ignored: invalid module name: 'yaml'
                                             
[JSONDecodeError]             
Expecting value: line 1 column 1 (char 0)  
                                             
Exception trace:
 /usr/lib/poetry/poetry/_vendor/py3.6/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /usr/lib/poetry/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /usr/lib/poetry/poetry/_vendor/py3.6/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /usr/lib/poetry/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /usr/lib/poetry/poetry/_vendor/py3.6/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /usr/lib/poetry/poetry/_vendor/py3.6/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /usr/lib/poetry/poetry/console/commands/new.py in handle() at line 50
   ".".join(str(v) for v in current_env.version_info[:2])
 /usr/lib/poetry/poetry/utils/env.py in version_info() at line 135
   return tuple(self.marker_env["version_info"])
 /usr/lib/poetry/poetry/utils/env.py in marker_env() at line 151
   self._marker_env = self.get_marker_env()
 /usr/lib/poetry/poetry/utils/env.py in get_marker_env() at line 496
   return json.loads(output)
 /home/bram/.pyenv/versions/3.6.7/lib/python3.6/json/__init__.py in loads() at line 354
   return _default_decoder.decode(s)
 /home/bram/.pyenv/versions/3.6.7/lib/python3.6/json/decoder.py in decode() at line 339
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 /home/bram/.pyenv/versions/3.6.7/lib/python3.6/json/decoder.py in raw_decode() at line 357
   raise JSONDecodeError("Expecting value", s, err.value) from None

new [--name NAME] [--src] [--] <path>
```

Has anyone got an idea of how to continue with this?  
All of my projects are just completely halted until I get this working again.

**Comment by Hartorn** [comment]
Weird, I don't this error anymore after updating to 0.12.17
Did you remove cache and then update the version ?
Else, you could try in a whole new virtual env to make sure

**Comment by BramVer** [comment]
Very weird indeed, all issues seem fixed for other people, or they at least have some kind of workaround.  

I have toyed around with some different setups to know where it comes from, and I've found 1 occurence where I had no issue.  

The following all **don't work** for me;
1. Uninstall Poetry, remove `~/.cache/pypoetry` completely and reinstalling.
1. Creating new venv, setting `config settings.virtualenvs.in-project` to false
1. (**python3.6.7**) Remove poetry package from the system package manager, going into a new venv, and installing poetry from pip
1. (**python3.7.4**) Remove poetry package from the system package manager, going into a new venv, and installing poetry from pip 

This, however, did work;
1. Install poetry through pip system-wide.

As a command, I ran `poetry new test -vvv` each time so inaccuracies in some `pyproject.toml` wouldn't be the case.  

The problem here, is of course that I have no desire to install packages through pip for my entire system, especially if there's a community package already pushing the correct and latest stable version.  

I hope this provides more insight.

**Comment by brycedrennan** [comment]
when in an environment that poetry isn't working can you please provide the output of
`which poetry`
and 
`pip freeze`

**Comment by BramVer** [comment]
```bash
➜  test which poetry
/usr/bin/poetry
➜  test pip freeze
Invalid -W option ignored: invalid module name: 'yaml'
➜  test 
```

Now, generating this information led to some funky behaviour.  
I think I'm closer to finding a solution;

First I removed the system-wide installed pip package, and to my surprise poetry worked again! My guess is the `pip uninstall poetry` removed some other cache folder I'm not aware of (I remove `~/.cache/pypoetry`). **Could this be the case?**  
After I navigated to my project and executed `poetry update` to get the latest versions, it gave the same `JSONDecodeError`, and every subsequent poetry call wherever, generated the same error again.  

Here is a link to the project's `pyproject.toml` file, maybe something in there triggers an incorrect setting in poetry? Not sure what happens.
https://gist.github.com/BramVer/001c11362b656aa04c2e09d84a30ff7a

**Comment by brycedrennan** [comment]
It looks like your python environment is messed up since pip isn't even working (see error when you run `pip freeze`). 

This appears unrelated to poetry.

**Comment by BramVer** [comment]
For some reason that session could not get out of the virtualenv the usual way (ie. running `source ~/.bashrc`), so that python and pip version were the isolated ones in the new test venv I just created for this purpose.  

Starting a new session and running `pip freeze` outputs this:
```bash
➜  test which python
/usr/bin/python
➜  test pip freeze          
Invalid -W option ignored: invalid module name: 'yaml'
3to2==1.1.1
aniso8601==6.0.0
appdirs==1.4.3
applib==1.2
arandr==0.1.10
asn1crypto==0.24.0
aspy.yaml==1.2.0
attrs==19.1.0
Automat==0.7.0
bcrypt==3.1.7
Beaker==1.10.1
black==19.3b0
btrfsutil==1.1.1
CacheControl==0.12.5
cached-property==1.5.1
cachy==0.2.0
cffi==1.12.3
cfgv==2.0.1
chardet==3.0.4
cleo==0.6.8
Click==7.0
cmdln==2.0.0
CodeIntel==2.0.0
colorama==0.4.1
constantly==15.1.0
cryptography==2.7
cupshelpers==1.0
decorator==4.4.0
deluge==2.0.3
distro==1.4.0
Django==2.2.4
docker==4.0.2
docker-compose==1.24.1
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
entrypoints==0.3
esprima==4.0.1
flake8==3.7.8
Flask==1.1.1
Flask-Admin==1.5.3
Flask-Caching==1.7.1
flask-restplus==0.12.1
Flask-Script==2.0.6
GeoIP==1.3.2
Guake==3.6.3
gufw==18.10.0
gunicorn==19.9.0
html5lib==1.0.1
hyperlink==19.0.0
identify==1.4.3
idna==2.8
importlib-metadata==0.19
incremental==17.5.0
Inflector==2.0.12
iotop==0.6
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.2
lensfun==0.3.2
libclang-py3==3.9.0
lockfile==0.12.2
louis==3.10.0
Mako==1.0.14
MarkupSafe==1.1.1
mccabe==0.6.1
msgpack==0.6.1
nodeenv==1.3.3
npyscreen==4.10.5
numpy==1.17.0
packaging==19.1
pacman-mirrors==4.14.2
pandas==0.24.2
paramiko==2.6.0
pastel==0.1.1
pbr==5.4.2
Pillow-SIMD==5.3.0.post1
pip-autoremove==0.9.1
pkginfo==1.5.0.1
ply==3.11
powerline-status==2.7
psutil==5.6.3
PTable==0.9.2
py==1.8.0
pyaml==19.4.1
pyasn1==0.4.6
pyasn1-modules==0.2.6
pycairo==1.18.1
pycodestyle==2.5.0
pycparser==2.19
pycups==1.9.74
pycurl==7.43.0.3
pyflakes==2.1.1
PyGObject==3.32.2
PyHamcrest==1.9.0
pylev==1.3.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.2
PyQt5==5.13.0
PyQt5-sip==4.19.18
pyrsistent==0.14.11
pyte==0.8.0
python-box==3.4.2
python-dateutil==2.8.0
python-libtorrent==1.1.13
python-xapp==1.6.0
python-xlib==0.24
pytz==2019.2
pyxdg==0.26
PyYAML==5.1.1
ranger-fm==1.9.2
redis==3.2.1
rencode==1.0.6
requests==2.22.0
requests-toolbelt==0.8.0
retry==0.9.2
sayml==1.0.6
service-identity==18.1.0
setproctitle==1.1.10
shellingham==1.3.1
six==1.12.0
speedtest-cli==2.1.1
SQLAlchemy==1.3.3
sqlparse==0.2.4
stackprinter==0.2.3
stevedore==1.30.0
team==1.0
texttable==1.6.2
thefuck==3.29
toml==0.10.0
tomlkit==0.5.5
trash-cli==0.17.1.14
Twisted==19.2.1
ueberzug==18.1.3
ufw==0.36
urllib3==1.25.3
virtualenv==16.1.0
virtualenv-clone==0.5.3
virtualenvwrapper==4.8.2
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
Werkzeug==0.15.2
WTForms==2.2.1
wxPython==4.0.6
zipp==0.5.2
zope.cachedescriptors==4.3.1
zope.interface==4.6.0
```

**Comment by brycedrennan** [comment]
You've still got that message `Invalid -W option ignored: invalid module name: 'yaml'`

**Comment by brycedrennan** [comment]
For now still looks like you have a non-standard python setup.  We can re-open if you figure out whats going on with pip that's making it throw errors.

**Comment by BramVer** [comment]
Fair enough, I thought I knew the culprit for this message, but that doesn't seem to be the case.  
I'll report back if I'm able to find/fix this, thanks for now.

**Comment by BramVer** [comment]
This was on my part indeed, unrelated to Poetry.  
It was due to a packageinstall from pip for a user that went wrong somehow. It was installed and usable but pip couldn't uninstall it.  
This is fixed now, sorry about that.

**Comment by brycedrennan** [comment]
Thanks for the update!

**Comment by timbury** [comment]
@BramVer I'm happy it's fixed but would you mind describing how you found it and how you fixed it? If yu still remember. ;-) Thanks!
