### ISSUE TITLE
poetry doesn't support pypy

### ISSUE THREAD

**Issue by toppk** [sdispater/poetry#1319]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Is there intent on supporting released or beta released versions of pypy?  Currently looking at the poetry.utils.helpers there is use of typing.NoReturn which was added to python 3.5.4 which is beyond pypy 3.5.3 support, and pypy 3.6 beta series doesn't yet include that.

Currently other projects are using this preview version of poetry, so at the moment any CI setup including pypy will always fail.  (project in question is tomlkit, who have already started to depend on new poetry features).

I'm curious if there's a stance on supporting pypy, so I can advice tomlkit how to proceed.

**Comment by toppk** [comment]
Just a funny though, I was trying to submit a bug fix to tomlkit, because of an issue I was encountering in poetry, because they also use poetry, I'm hitting this new issue.   

If you want to see the tomlkit bug that is causing issues for my poerty use see the following report.     https://github.com/sdispater/tomlkit/pull/60

**Comment by Caligatio** [comment]
I think this is closed with #1320?

Admittedly I'm a bit confused by the PR because the rest of the codebase does type hinting by comment (Python 2 friendly) whereas that file is Python3 only...

**Comment by brycedrennan** [comment]
@Caligatio which file are you talking about?

**Comment by Caligatio** [comment]
I don't know what I thought I saw but all the type hinting is Python 2 friendly.  Sorry about that!

**Comment by toppk** [comment]
I'm not a pypy user myself, but I'll set it up and check it out.   It would be nice if poetry would confirm that their intent is to support the current release of pypy.  If so I can add it to your test coverage.

**Comment by reversefold** [comment]
I'm having similar issues with clikit https://github.com/sdispater/clikit/issues/7 as I need to use Python 3.5.2, which doesn't have all of the values in typing that 3.5.7 does. With poetry 1.0.0b1 I'm still getting the NoReturn import error, unfortunately. Will this fix be release any time soon?
