### ISSUE TITLE
ValueError: '=' alignment not allowed in string format specifier in show.py

### ISSUE THREAD

**Issue by oakkitten** [sdispater/poetry#1323]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Raspbian GNU/Linux 10 (buster)
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/oakkitten/d003258493a887fde9906c6faaac946e

## Issue

Edit: just noted that I'm running a more late version than “the latest”, not sure what to do 🙄

Run

    $ poetry new woo
    $ cd woo
    (edit pyproject.toml to remove the test dependency and add `pendulum = "*"`, see gist)
    $ poetry install
    $ poetry show -o -vvv

Get

    Using virtualenv: /home/oakkitten/.cache/pypoetry/virtualenvs/woo-2dsX_qwR-py3.7

    [ValueError]
    '=' alignment not allowed in string format specifier

    Traceback (most recent call last):
      File "/home/oakkitten/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 132, in run
        status_code = command.handle(parsed_args, io)
      File "/home/oakkitten/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 119, in handle
        status_code = self._do_handle(args, io)
      File "/home/oakkitten/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 167, in _do_handle
        return getattr(handler, handler_method)(args, io, self)
      File "/home/oakkitten/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
        return self.handle()
      File "/home/oakkitten/.poetry/lib/poetry/console/commands/show.py", line 177, in handle
        color, name, name_length - len(install_marker), install_marker

The variables in this last line are respectively `'cyan', 'pendulum', 0, ''`.

Not sure why the line numbers are different but it's [this code](https://github.com/sdispater/poetry/blob/master/poetry/console/commands/show.py#L153-L155), the issue being that `name_length - len(install_marker)` computes to `0` and python fails to interpret it as width (see [this issue](https://bugs.python.org/issue27772)).

Note that there are more of `{:{}}` in the code.

**Comment by K900** [comment]
Still an issue.

**Comment by bertjwregeer** [comment]
As noted in https://github.com/sdispater/poetry/issues/1605, this is still an issue.

**Comment by playpauseandstop** [comment]
Happens to me as well, providing more details.

- **OS version and name:** `python:3.7.5-slim-buster` Docker image
- **Poetry version:** 1.0.0b5
- **Link of a Gist with the contents of your pyproject.toml file:** https://gist.github.com/playpauseandstop/4efcf7d77db1df616dcea3e065e51935

The traceback is similar to what shared in issue description.
