### ISSUE TITLE
Spawns a shell within the virtualenv

### ISSUE THREAD

**Issue by nikaro** [sdispater/poetry#134]
It would be nice to have a command `poetry shell` that acts like `pipenv shell`, instead of having to `source ~/.cache/pypoetry/…/bin/activate`.

**Comment by bertjwregeer** [comment]
`poetry run <your shell binary here>`?

**Comment by nikaro** [comment]
Perfect! I didn't think to test that…

**Comment by NotAFile** [comment]
I'd like to see this reopened. It would be neat to have this as a convenient shortcut. After all, poetry already knows what my shell is, so why do I need to tell it again?

**Comment by nikaro** [comment]
I reopen and let @sdispater decide what to do of this.

**Comment by bertjwregeer** [comment]
@NotAFile how does poetry already know what your shell is?

**Comment by NotAFile** [comment]
@bertjwregeer through the `SHELL` environment variable

**Comment by bertjwregeer** [comment]
@NotAFile which may or may not be set, and may or may not be set to the correct shell...

**Comment by NotAFile** [comment]
@bertjwregeer Sure. Alternatives would have to be found for Windows. It's probably worth looking at how similar projects handle this. For *NIX I don't see anything wrong with using $SHELL. It's set by your shell, and if your shell doesn't know what shell it is, perhaps you have bigger problems...

Even then, if someone has an extremely weird setup where SHELL is somehow not the shell, it's not like the trusty normal "run" command wouldn't still be there.

**Comment by tadeoos** [comment]
Hey, this is being implemented - check out #198 :)

**Comment by cauebs** [comment]
This feature is being worked on in #201 and I'll happy to hear your feedback. If you know something about Windows and are willing to help, I'd like to be able to know how to properly detect the correct shell, if it's not `cmd`, and if it's working at all! Any feedback is appreciated :)

**Comment by ethanhs** [comment]
@caubs, re better Windows support, the best option is to use what pipenv patched pew to do https://github.com/pypa/pipenv/blob/master/pipenv/patched/pew/_win_utils.py. Sadly you have to enumerate all processes to find your parent :/

**Comment by cauebs** [comment]
`poetry shell` is now available in version 0.11

**Comment by NotAFile** [comment]
Awesome! Poetry is now my tool of choice.
