### ISSUE TITLE
poetry build error [KeyError]

### ISSUE THREAD

**Issue by HttpTesting** [sdispater/poetry#1355]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

version: 0.12.17
Poetry build error:
[KeyError]
'version'

ruamel.yaml = "0.16.5"

![image](https://user-images.githubusercontent.com/52555913/64324313-b8285200-cff8-11e9-981c-6982ecdff528.png)
![Uploading image.png…]()

ruamel.yaml = "0.16.5" 
=>
'ruamel': {'yaml': '0.16.5'}},

**Comment by HttpTesting** [comment]
add

**Comment by sdispater** [comment]
You need to put quotes around "ruamel.yaml" otherwise it will be considered as a dotted key. The error is not clear but this has been improved in the `1.0.0` preview releases, so you might want to try them out.
