### ISSUE TITLE
Is there a way to identify that one is in a poetry shell after entering it?

### ISSUE THREAD

**Issue by swquinn** [sdispater/poetry#1362]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I was looking through the documentation and the issues, and even skimmed through the code some and could not find an answer to this. Out of the box if I install Poetry (either using `curl` or `pip install`) and then run `poetry install`, the shell that gets created doesn't have any sort of identifier indicating that I'm in the shell, e.g.

```
$ poetry install
$ poetry shell
Spawning shell within <snip>/Library/Caches/pypoetry/virtualenvs/myproject-py3.7
bash-3.2$ 
```

On the other hand, `pipenv` prefixes the shell with the name of the project, e.g.
```
$ pipenv install
$ pipenv shell
Launching subshell in virtual environment…
(myproject) bash-3.2$
```

Am I missing something?

**Comment by oakkitten** [comment]
Duplicate of #571.

**Comment by swquinn** [comment]
@oakkitten thanks, but am I correct in my understanding that everything suggested in that thread seems to be an extra step that the individual installing `poetry` is responsible for adding? It wasn't clear when I was looking through it whether or not the lack of a shell name prefix was actually being fixed as part of poetry.

**Comment by oakkitten** [comment]
That issue is still open so it's a bug that hopefully will be eventually fixed; if you run the workaround as suggested by the top comment you should get the prefix in your shell.

The prefix is just a visual cue, anyway. You can see whether you are using the correct env by running `which python`

**Comment by swquinn** [comment]
Thanks for the explanation @oakkitten! Even if the prefix is just a visual cue it is useful. I'll close this issue seeing as it is covered by #571.
