### ISSUE TITLE
Can't resolve `futures` when adding `google-ads`

### ISSUE THREAD

**Issue by henribru** [sdispater/poetry#1378]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 1903
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/henribru/ebfcdd8e7b9aabba0b12d9c815286e5f 

## Issue

When running `poetry add google-ads`, resolution fails with the following error: https://gist.github.com/henribru/dcacd674f69b1b04f349c17ae133a93d

The problem seems to be due to the fact that `google-ads` depends on `google-api-core` which depends on `futures`, but only for Python versions below 3.2 (this is the specification in their `setup.py`: `'futures >= 3.2.0; python_version < "3.2"'`). I'm not quite sure why it's specified as below 3.2 when `futures` is only available for Python 2 and `google-api-core` requires either 2.7 or 3.4 and above anyway, and maybe this is the cause of the problem? But it still seems surprising to me that it can't resolve the dependency in my case, since `futures` isn't required in the `^3.4` case.

**Comment by Nitori-** [comment]
To anyone who runs into this in the future, adding a dependency like this seems to function as a workaround:

```
futures = { version = "^3", python = "~2.7" }
```

I think that somehow "tricks" the dependency resolution algorithm into narrowing down the scenarios where it thinks it needs to install the `futures` package.
