### ISSUE TITLE
Support cygwin

### ISSUE THREAD

**Issue by vab2048** [sdispater/poetry#1383]
Currently when attempting to install on cygwin I get:

`RuntimeError: Could not find poetry-0.12.17-cygwin.sha256sum file`

Suggestion for feature request is to support cygwin. 

If this is not on the roadmap please close this ticket.

**Comment by ali5h** [comment]
can we reopen this?

**Comment by Lucas-C** [comment]
As a workaround:

    sed -i 's/platform = sys.platform/platform = "win32"/' get-poetry.py

This will alter the `_make_lib` function there: https://github.com/python-poetry/poetry/blob/master/get-poetry.py#L571

**Comment by paconte** [comment]
I have the same error on a mac book when I run: `poetry self update --preview`

**Comment by neersighted** [comment]
@paconte To go from Poetry 1.1 to 1.2-preview, you will have to reinstall with `install.python-poetry.org`. Additionally, I'm wondering how you got a Cygwin-related error on macOS -- did you maybe comment on the wrong issue?

**Comment by paconte** [comment]
You are right, it is a different error but related with the platform. When I run `poetry self update --preview`I get this error:

```
  RuntimeError

  Could not find poetry-1.2.0a2-darwin.sha256sum file
```

**Comment by neersighted** [comment]
You'll need to use the installer at `install.python-poetry.org` to update -- Poetry 1.1 cannot self-update to 1.2-preview.

**Comment by paconte** [comment]
You are right. Thank you. I have seen the deprecation of get-poetry.py

**Comment by pinakee97** [comment]
> You'll need to use the installer at `install.python-poetry.org` to update -- Poetry 1.1 cannot self-update to 1.2-preview.

Hey i am very new to programming. Could you please educate me on how can we install poetry using install.python-poetry.org

**Comment by finswimmer** [comment]
>  Could you please educate me on how can we install poetry using install.python-poetry.org

https://python-poetry.org/docs/master/#osx--linux--bashonwindows-install-instructions

**Comment by adam-grant-hendry** [comment]
> > Could you please educate me on how can we install poetry using install.python-poetry.org
> 
> https://python-poetry.org/docs/master/#osx--linux--bashonwindows-install-instructions

@finswimmer Your  main docs still reference using

```python
PS> poetry self update --preview
```

and the warning

> The previous get-poetry.py and install-poetry.py installers are now deprecated. If you are currently using them you should migrate to the new, supported, installer through https://install.python-poetry.org.

is unclear. People are thinking they can use

```python
PS> poetry self update --preview
```

successfully if they have first installed with the PowerShell and curl commands accessing `https://install.python-poetry.org`.

Instead, you need to say

> The previous get-poetry.py and install-poetry.py installers are now deprecated. If you are currently using them you should migrate to the new, supported, installer through https://install.python-poetry.org.
>
> To do so, on MacOS/Linux, use

```python
$ curl -sSL https://install.python-poetry.org | python3 - --preview
```

> and on Windows

```python
PS> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py - --preview
```

This information is hidden in the `Configure the installation` section of your documentation and belongs under the `Update Poetry` section instead.

It doesn't make sense to a newcomer to look at the configuration sections, which is why you're getting all the bug reports.

**Comment by adam-grant-hendry** [comment]
Please also note that unless you want Poetry installed to the default location (on Windows, this is `%APPDATA%`), set the following environment variables before running the PowerShell command:

```
POETRY_HOME = Path to poetry install folder
POETRY_CACHE = Path to cache folder
```

You can also set these variables for virtual environment creation control:

```
POETRY_VIRTUALENVS_CREATE = true/false
POETRY_VIRTUALENVS_IN_PROJECT = true/false
```

**Comment by neersighted** [comment]
@adam-grant-hendry I recently rewrote the install docs, please open a new issue if you think they're unclear on the 1.2 installer migration.

**Comment by adam-grant-hendry** [comment]
> @adam-grant-hendry I recently rewrote the install docs, please open a new issue if you think they're unclear on the 1.2 installer migration.

Thank you very much! (I was just noting for posterity)
