### ISSUE TITLE
Managing semver vs pep440

### ISSUE THREAD

**Issue by bersace** [sdispater/poetry#1389]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

When managing version with poetry, one get simple semver versionning. It's fine. Final dist follows PEP440. It's fine too. That would help scripting to have a way to read version either as semantiq version or PEP440.

I suggest that `poetry version` has two display options:

- `--quiet` which show only version number
- `--pep440` to convert semver to PEP440.

For example, with a project whose version is 2.0.0-alpha.0:

``` console
$ poetry version --quiet
2.0.0-alpha.0
$ poetry version --quiet --pep440
2.0.0a0
```

What do you think of this ?

**Comment by stephsamson** [comment]
I think this is a good idea but we should probably think of a different command because `poetry version` is a command that bumps the version of your project by patch number.

What do you think @sdispater and @brycedrennan?

**Comment by bersace** [comment]
@stephsamson `poetry version` without any argument nor option shows current version. This is why I suggest this. I didn't found other project inspection command. I think that would be great to ship `poetry info` or something like that to query name, description, etc. from Makefiles or shell scripts.

**Comment by stephsamson** [comment]
@bersace maybe we're misunderstanding each other but when I run `poetry version` *only* without any arguments or options, it bumps the version.

You can also read the [source code here](https://github.com/sdispater/poetry/blob/bf3e43ce02195cefb666012f6b6a0e324e115917/poetry/console/commands/version.py#L15).

**Comment by bersace** [comment]
@stephsamson : I'm based on 1.0.0b1 : https://github.com/sdispater/poetry/blob/develop/poetry/console/commands/version.py#L10
