### ISSUE TITLE
No command to delete the venv for a project.

### ISSUE THREAD

**Issue by funkybob** [sdispater/poetry#1421]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I started a project, then realised I'd used the wrong command [new and init are confusingly similar] so wanted to clean up before going forward.

However, there's no command to delete the virtualenv for a given project.

I searched the ticket history, found reference to a now defunct 'poetry env' set of sub-commands, and other tickets that all "solved' the problem by explaining how to manually determine the location of the venv and manually removing it.

Surely this is better managed as a command option in poetry itself?

**Comment by KelSolaar** [comment]
If you are using the preview version you can actually issue `poetry env remove 2.7`  and the Python 2.7 virtual environment associated with your current project will be deleted.

**Comment by funkybob** [comment]
Any idea when these features will be released?

**Comment by KelSolaar** [comment]
@funkybob: That is a question for the maintainers, but if you issue `poetry self:update --preview` it will update to the 1.0.0b1 version which does handle that!

**Comment by funkybob** [comment]
I'll settle with "fixed in future release".

Thanks for the response.
