### ISSUE TITLE
Package pandas is already present

### ISSUE THREAD

**Issue by folt** [sdispater/poetry#1424]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu
- **Poetry version**: 0.12.12
- **Link of a Gist with the contents of your pyproject.toml file**: https://gist.github.com/folt/0138d9081ed4d84a009c2af083b6088a

## Issue
```
(.venv) qqq@good:~/work/www$ poetry add pandas -vvv
Using virtualenv: /home/folt/work/www/.venv
                                     
[ValueError]          
Package pandas is already present  
                                     
Exception trace:
 /home/folt/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/folt/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/folt/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/folt/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/folt/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/folt/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/folt/.poetry/lib/poetry/console/commands/add.py in handle() at line 63
   raise ValueError("Package {} is already present".format(name))
```
I am trying to install pandas package
But poetry gives an error.
Through the `pip install pandas` command, everything works

**Comment by sdispater** [comment]
The `pandas` package is already present in your `pyproject.toml` file: https://gist.github.com/folt/0138d9081ed4d84a009c2af083b6088a#file-poetry-L57

If you want to install your packages, you must run `poetry install`

**Comment by santiagobasulto** [comment]
Shouldn't this be just a warning? (Package already present, skipping).
