### ISSUE TITLE
suggestion: add a more ergonomic binary name: pt/poet/ptr/pte

### ISSUE THREAD

**Issue by jondot** [sdispater/poetry#143]
Somewhat nitpicking, but poetry is rather hard to type :)

I've alias `pt` to poetry and it made a ton of difference.

Dropping this here in case many others happen to have the same experience but don't have the time to bring it up :)

**Comment by xsduan** [comment]
Also, it might be nice to have npm-like command alises, such as `pt rm` for `poetry remove` and `pt i`/`pt a` for `poetry add`.

Admittedly it's just 5 characters so it's not the most urgent request but I'm so used to using `npm rm` and `npm i` it kind of throws me off sometimes lol

**Comment by sdispater** [comment]
I think `poetry` is a reasonable name and you still have the option to create an alias for it if need be. So, no, I don't plan on changing the executable name.
