### ISSUE TITLE
fish completions file path is likely wrong in help/documentation

### ISSUE THREAD

**Issue by jnik-aarhus** [sdispater/poetry#1436]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hello :)
It looks like completions for `fish` have moved directory since the documentation was created. Per the [`fish` documentation](https://fishshell.com/docs/current/index.html#completion), they now reside in `/usr/share/fish/completions/` (a bit dependent on installation). As such, the command is more likely to be

`poetry completions fish > /usr/share/fish/completions/poetry.fish`
 
which causes access problems :)

**Comment by justinmayer** [comment]
Hi @jnik-aarhus. For future reference, it would have been a bit easier to help you if had you linked to the [Poetry shell completion documentation](https://poetry.eustace.io/docs/#enable-tab-completion-for-bash-fish-or-zsh) to which your issue ostensibly refers. In any case, you wrote:

> Per the [`fish` documentation](https://fishshell.com/docs/current/index.html#completion), [the completions] now reside in /usr/share/fish/completions/

The relevant section of those docs — [Where to Put Completions](https://fishshell.com/docs/current/index.html#completion-path) — makes it very clear that `/usr/share/fish/completions/` is for "completions shipped with Fish", which is therefore not an appropriate location for tools like Poetry to store their completions. While the Fish shell documentation suggests that `/usr/share/fish/vendor_completions.d` be used by "third-party software vendors to ship their own completions for their software", `/usr/share/fish` doesn't exist in some environments (e.g., macOS `brew`'d Fish), and `/usr/share/` is owned by root and is thus associated with the access problems you mentioned in your issue description.

Running `echo $fish_complete_path` will show you all the paths that completions can be placed and be recognized by Fish. Of all the items in that list on my system, the `~/.config/fish/completions/` path that's mentioned in the existing Poetry documentation is indeed the most appropriate path for Poetry completions.

I hope this helps clarify things for you. Assuming it does, would you please save Poetry maintainers some time and close this issue?

**Comment by jnik-aarhus** [comment]
Hello,

Thank you very much for your comprehensive answer!
I realised this after opening this issue, and I apologise for my confusion. I'll close this issue, and again, thank you for taking the time to answer me.

**Comment by justinmayer** [comment]
Glad you found it helpful. Cheers! 😁
