### ISSUE TITLE
Packages are present multiple times in "requirements.txt" file.

### ISSUE THREAD

**Issue by KelSolaar** [sdispater/poetry#1438]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/colour-science/colour/blob/ffeccd121792a5141ccf5f5c6cfc38804016af7d/pyproject.toml

## Issue

When I use `poetry export -f requirements.txt --without-hashes --dev --extras "optional plotting" -o requirements.txt`, the **requirements.txt** file ends up with two times the dependencies: https://github.com/colour-science/colour/blob/13c1b407b85296a2504d5617e760317adfc07c1e/requirements.txt#L38

This is obviously invalid and breaks applications using the file. I'm assuming the dependencies from Python 2.7 and 3.7 are being collected at the same time. Note that `poetry show` also lists the two sets of dependencies.

For now, I'm using `poetry run pip freeze | grep -v "github.com/colour-science" > requirements.txt`

**Comment by finswimmer** [comment]
This is a duplicate of #1434 and is fixed by #1610.
