### ISSUE TITLE
Can't connect to a websocket (poetry only)

### ISSUE THREAD

**Issue by fly1ngDream** [sdispater/poetry#1443]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 5.3.1-arch
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/fly1ngDream/e4b74177570870e54da627069585d1a0

## Issue

Application is a simple chat using django-channels and celery (just tried to substitude Pipenv with poetry for my old app). While managing my deps using Pipenv, everything is OK and i have no issues at all. But while using poetry with exactly same deps list, server can't find websocket via its route and get this error.

 ```
[06/Oct/2019 22:13:46] "GET /chat1/ HTTP/1.1" 200 8842
Not Found: /ws/chat/chat1/
[06/Oct/2019 22:13:47] "GET /ws/chat/chat1/ HTTP/1.1" 404 2607
```

Pipenv output:
```
HTTP GET /chat1/ 200 [0.07, 127.0.0.1:51086]
WebSocket HANDSHAKING /ws/chat/chat1/ [127.0.0.1:51090]
WebSocket CONNECT /ws/chat/chat1/ [127.0.0.1:51090]
```

Here is this app: https://github.com/fly1ngDream/channels-chat (After commit that start using poetry for deps management, sockets became broken). I had tried to use beta version of poetry, but it didn't help

**Comment by Jamim** [comment]
Hi @fly1ngDream,

I see that output formats are quite different, so I assume that in case of `poetry` you are running it with `runserver` which knows nothing about the `ASGI_APPLICATION` setting in your config and in case of `pipenv` you are running your application in some different way.

However, if you really need some help, please provide clear steps to reproduce the issue.

**Comment by fly1ngDream** [comment]
@Jamim yea, but i start server exactly the same way. Obviously, server can't recognize ASGI. To reproduce you should start server via `runserver`, start redis server (`redis-server`) and start celery worker (`celery worker -A config -l info`) in a `django` directory. Than create new chat room and try to connect to it.

**Comment by Jamim** [comment]
@fly1ngDream I've tried what you described with `pipenv` using code from `master^` and it leads to the same results that you got with `poetry`.

**Comment by fly1ngDream** [comment]
@Jamim Weird. Ill try it again later and give a comment

**Comment by fly1ngDream** [comment]
Recreated pipenv virtualenv and got same issue. Obviously, poetry is not the source of this issue

**Comment by fly1ngDream** [comment]
The issue was: i installed the `django-channels` dependency which has nothing in common with the `channels` one
