### ISSUE TITLE
install and uninstal Poetry on Windows

### ISSUE THREAD

**Issue by jeremy886** [sdispater/poetry#145]
Hi, thanks for making this tool. I'm not very familiar with developing processes and still learning about it.

I can't tell if Poetry supports Windows from the documentation but I tried it anyway and it worked! 

Great news. Maybe make it explicit in the docs? I think Poetry can easily become more popular if it can attract a tiny fraction of Windows users. (For example, I'm a teacher, 90% of my students use Windows and 100% of my school) I use both though.

I installed Poetry this way and it was installed to the Python directory in my home directory (Windows).
`curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`

What is the recommended way to uninstall it?

I find Poetry interesting and definitely will explore it further.

Thanks.

**Comment by jeremy886** [comment]
Thanks Victor-Savu. It worked.

Out of curiosity I tried `pip install poetry` again and got massive influx of packages (shown when I did `pip list`). I used pip-autoremove to save the day. One thing I like about poetry is that it can remove an installed package and its dependencies (pip/conda can't do it) but I don't think I could use poetry to remove itself. 

Then I wondered how it hid these before and looked up "vendorizing" and found the _vendor folder in site-packages. (I thought it was in the home directory). Nice!

If PRs are welcome here, I can add a few lines here and there to README.md.

**Comment by Victor-Savu** [comment]
You're welcome, @jeremy886!
My guess would be that you could open a PR for the README and/or for the docs, but @sdispater is the one putting in most of the hard work, so he is the best person to ask about contributing to poetry :)

**Comment by sdispater** [comment]
The fact that Poetry supports Windows is not specified in the README but is in the documentation: https://poetry.eustace.io/docs/#system-requirements

**Comment by jeremy886** [comment]
merici. :)

**Comment by sdispater** [comment]
Closing this since the installer can now also uninstall Poetry.
