### ISSUE TITLE
Custom build scipt

### ISSUE THREAD

**Issue by stinovlas** [sdispater/poetry#1453]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## General introduction
During the investigation whether poetry is the right tool for our company, I have bumped into undocumented `build` option. It seems that I can do something like this:

```
[tool.poetry]
build = "my_custom_build.py"
```

When I do, poetry adds following two lines to generated `setup.py` in `sdist`:

```
from my_custom_build import *
build(setup_kwargs)
```

When creating wheel, poetry executes the `build` function in `my_custom_build.py`.

## Issue

I really like this behaviour, because it allows me to execute custom build steps like compilation of translations, generating python modules from grpc protobuf files and so on.

However, the `build` option is undocumented. I propose that we document this behaviour, because it can be really useful.

Also, parsing of this option baffles me, because it's splitted by the dots and only the first part is used as the module name. Which means that I can only use python modules in the root directory. This is confusing and it could be improved (accepting a dotted path to python module seems like a logical choice).

**Comment by sdispater** [comment]
This is not a documented feature because it is likely to change since it's too tied to the generated `setup.py` file which will eventually be removed. So people should not rely on it at the moment and should wait until the feature and its implementation is stable.

**Comment by stinovlas** [comment]
@sdispater: Thank you for elaborating! I'm looking forward to the new solution. I'd just like it to support generating python modules during the build and including those generated modules to the (wheel) distribution. This is something I currently do with custom `setup.py` build step and this functionality is really important for me. If needed, I can lend a hand in implementation.

**Comment by etijskens** [comment]
.. wait until the feature and its implementation is stable.

When would that be?

Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 9 Oct 2019, at 21:51, Sébastien Eustace <notifications@github.com<mailto:notifications@github.com>> wrote:


This is not a documented feature because it is likely to change since it's too tied to the generated setup.py file which will eventually be removed. So people should not rely on it at the moment and should wait until the feature and its implementation is stable.

**Comment by paperwhite** [comment]
I see this hasn't been updated for a while. I'm trying to add the object detection API which requires [specific build steps](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md#python-package-installation) for installation and I'm having a hard time trying to figure out how to do that with poetry. Any suggestions would be helpful. Thanks!

**Comment by maelp** [comment]
Is there a way to run a pre-build script?
