### ISSUE TITLE
Add a way to perform non-eager `poetry update $package`

### ISSUE THREAD

**Issue by charettes** [sdispater/poetry#1456]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

When performing a `poetry update $package` all of the dependencies, even the one not related to `$package`, get updated and locked. That's a behaviour I would expect `poetry update` to do but I was surprised that it's also the case for `poetry update $package`.

This prevents updating a single package and its dependency without necessarily updating unrelated ones that might not be adhering and cause unrelated breakages.

This eager update strategy use to be the default of behaviour of `pip install` as well but it was changed to _only-if-needed_ a few years ago https://github.com/pypa/pip/pull/3972.

I personally think that `poetry update $package` should behave this way by default but I understand this might not be possible for backward compatible reason.

What I am asking for here is simple of way to perform a `poetry update $package` that only updates `$package` and packages that `$package` depends on to a compatible version.

**Comment by sdispater** [comment]
`poetry update $package` only updates the package and its dependencies. I use it regularly so I am pretty sure it works as intended so if you could provide a reproducible example that would be great.

**Comment by charettes** [comment]
@sdispater sure, working on that.

**Comment by charettes** [comment]
I'm still trying to figure out a minimal reproducible test case but it seems heavily related to our project and I can't reproduce with our anonymized `pyproject.toml` so far. I'll report back this week.

**Comment by charettes** [comment]
I still can't reproduce so I'll close for now.
