### ISSUE TITLE
Confusing output for install sub-command

### ISSUE THREAD

**Issue by pikeas** [sdispater/poetry#1471]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15
- **Poetry version**: 1.0.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pikeas/5c45fc9fd32353b5aee37163f95ef14d (reusing from unrelated issue https://github.com/sdispater/poetry/issues/1470)

## Issue

```
$ poetry install
Installing dependencies from lock file

Nothing to install or update

  - Installing foo (0.1.0)
$ poetry install -vvv
Using virtualenv: /Users/pikeas/Library/Caches/pypoetry/virtualenvs/foo-0mmka8-W-py3.7
Installing dependencies from lock file

Nothing to install or update

  - Skipping more-itertools (7.2.0) Already installed
  - Skipping zipp (0.6.0) Already installed
  - Skipping importlib-metadata (0.23) Already installed
  - Skipping atomicwrites (1.3.0) Already installed
  - Skipping attrs (19.3.0) Already installed
  - Skipping colorama (0.4.1) Not needed for the current environment
  - Skipping pluggy (0.13.0) Already installed
  - Skipping py (1.8.0) Already installed
  - Skipping six (1.12.0) Already installed
  - Skipping pytest (3.10.1) Already installed
  - Installing foo (0.1.0)
```

It is quite confusing to see a message saying "nothing to install" immediately followed by a message saying something is being installed!

**Comment by finswimmer** [comment]
I can think of why this is confusing. But the "Nothing to install" is the answer to "Installing dependencies". `foo` is not a dependency but he project package. So the wording is not wrong in my opinion.

One could make it more clearer by printing "No dependencies to install or update".
