### ISSUE TITLE
Pipsi like deployment option

### ISSUE THREAD

**Issue by brycearden** [sdispater/poetry#149]
Hey there!

First off, I am a huge fan of `poetry` and can't wait to see how this project changes Python packaging. I would like to start taking advantage of the `pyproject.tml` style of packaging, but I need to be able to deploy my packages on a remote mount, for which I have been using [pipsi](https://github.com/mitsuhiko/pipsi) for that.

It would be awesome for `poetry install` to support installing a package in a local virtual environment and providing a `bin` that has symlinks to the installed entry point script.

**Comment by cs01** [comment]
Maybe `poetry install <pkg> --global`?

**Comment by cauebs** [comment]
Maybe the functionality exposed by the current `install` command could be left to `develop` and `install` could work like Cargo's `install` and `pipsi`
