### ISSUE TITLE
incorrect docs for add command on poetry.eustace.io

### ISSUE THREAD

**Issue by vvoody** [sdispater/poetry#1495]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The [docs](https://poetry.eustace.io/docs/cli/#add) mention `add` command having options `--git` and `--path`. But Poetry doesn't provide them.

That'd be great if keep docs on website same as [cli.md](https://github.com/sdispater/poetry/blob/master/docs/docs/cli.md).

Thanks.

**Comment by finswimmer** [comment]
These parameter are valid for the current stable release and will be removed in 1.0. So it's valid that they are mentioned on the official website.

**Comment by vvoody** [comment]
My bad, didn't notice I was running 1.0.0b2.
