### ISSUE TITLE
Support Markdown README without pandoc

### ISSUE THREAD

**Issue by thebigmunch** [sdispater/poetry#15]
PyPI now supports Markdown README files directly using ``description_content_type`` set to ``"text/markdown"``. [Here](https://github.com/pypa/warehouse/pull/3296) is the PR that added it to the warehouse project.

**Comment by sdispater** [comment]
It has just been added in commit b0e9e0c.

I just tested it and it somewhat works, even though the rendered code blocks are odd (see https://test.pypi.org/project/poetry/0.6.0b1/)

**Comment by thebigmunch** [comment]
Thanks. Yeah, it looks like their CSS needs a little work there.

**Comment by thebigmunch** [comment]
I've posted on the warehouse issue tracker about the ``<pre><code>`` styling.
