### ISSUE TITLE
pytest shouldn't be automatically added to dev deps on poetry init

### ISSUE THREAD

**Issue by charettes** [sdispater/poetry#150]
I don't see a reason for automatically including it if `no` is specified.

**Comment by cauebs** [comment]
I created a new project and was very surprised when I tried to install pytest and it said it was already installed.

**Comment by sbstp** [comment]
I just used `init` on a new project using `0.11.2` and pytest is gone.

**Comment by charettes** [comment]
I confirm that this was fixed by 8c3d49f5e0f88f16696bce04b7fb9d4e72969385 which is part of 0.11.0.
