### ISSUE TITLE
Various keys are set to "None" in built "setup.py" file.

### ISSUE THREAD

**Issue by KelSolaar** [sdispater/poetry#1512]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6 
- **Poetry version**: 1.0.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/colour-science/colour/blob/9f8c91d45e8d18fee3a2437210b0990885ddb60c/pyproject.toml 

## Issue

I have just noticed that various keys in the generated `setup.py` upon invoking `poetry build` are set to `None`:

- **author_email**
- **maintainer**
- **maintainer_email**

```python
setup_kwargs = {
    'name': 'colour-science',
    'version': '0.3.14',
    'description': 'Colour Science for Python',
    'long_description': '...',
    'author': 'Colour Developers',
    'author_email': None,
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://www.colour-science.org/',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'python_requires': '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
}


setup(**setup_kwargs)
```

There is a `maintainers` property in the [schema](https://github.com/sdispater/poetry/blob/6a99ef21ddb89afef91b716e5f973210816fdbd6/poetry/json/schemas/poetry-schema.json) but I could not see anything related to email.

Cheers,

Thomas

**Comment by finswimmer** [comment]
Hello @KelSolaar ,

email addresses for authors and maintainer must be set like this in `pyproject.toml`:

```
[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors=["Jill <jill@example.org>"]
maintainers=["Bob <bob@example.org>"]
```

This will result in:
```
setup_kwargs = {
    'name': 'poetry-test',
    'version': '0.1.0',
    'description': '',
    'long_description': None,
    'author': 'Jill',
    'author_email': 'jill@example.org',
    'maintainer': 'Bob',
    'maintainer_email': 'bob@example.org',
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.7,<4.0',
}
```

**Comment by KelSolaar** [comment]
Ah sweet, this is great! I can see the [authors](https://poetry.eustace.io/docs/pyproject/#authors) in the documentation but not **maintainers**.

**Comment by KelSolaar** [comment]
Maybe this [PR](https://github.com/sdispater/poetry/pull/1175) should have updated the documentation accordingly.
