### ISSUE TITLE
Can't use poetry in several pre-release versions

### ISSUE THREAD

**Issue by Cgironalas** [sdispater/poetry#1517]
- [ ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19.1 Cinnamon
- **Poetry version**: 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0b1, 1.0.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: I have no specific gist to show but even in a sandbox, in a new virtual environment with only poetry having been pip installed the error happens.

## Issue

I have been having issues when trying to use poetry in general when using python 3.7.4 and any of the poetry versions mentioned. Whenever I try to run `poetry` I get the following error:
`ImportError: cannot import name 'ConsoleEvents' from 'clikit.api.event' (/home/carlos/sandbox/python_stuff/poetry_error/.env/lib/python3.7/site-packages/clikit/api/event/__init__.py)`.

But the error is not present in versions `1.0.0a0` nor in version `1.0.0b3`.

### Steps to get the error in a sandbox:
* `python -m venv venv`
* `source venv/bin/activate`
* `pip install poetry==1.0.0b2`
* `poetry`

**Comment by bersace** [comment]
Same here. I had to pin cleo to 0.7.5 as a workaround.

https://gitlab.com/dalibo/dramatiq-pg/commit/51682b5097a8ddd3445eb9c8d15e73c08601c367

**Comment by sdispater** [comment]
You should use the `1.0.0b3` version which properly sets the `clikit` dependency and fixes the issue.

If you absolutely need to use a previous prerelease then downgrading `cleo` like @bersace mentioned should work as a temporary fix.
