### ISSUE TITLE
Poetry intsall using custom installer is taking forever

### ISSUE THREAD

**Issue by mutant0609** [sdispater/poetry#1526]
## Issue
The poetry installating using command "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python" is taking forever to install. In the end it displays "Installing version: 0.12.17" and gets stuck there for a lot of time.

**Comment by stephsamson** [comment]
Hi @mutant0609 ! Thank you for this report but unfortunately your issue report is very sparse. I just tried installing `poetry` once again and did not have this issue. If you could provide us with reproducible steps and more context, maybe we could help you but until then for such issues, please post on [python-poetry tag on StackOverflow](https://stackoverflow.com/questions/tagged/python-poetry).

**Comment by Prakashvanapalli** [comment]
@stephsamson I am facing similar problem and raised a question on [stackoverflow](https://stackoverflow.com/questions/58708936/pythonpoetry-installation-is-getting-stuck)

**Comment by riquito** [comment]
I had this issue and found out that the underlying pip was stuck waiting to unlock the keyring (opened a bug report at https://github.com/pypa/pip/issues/7883).

Workaround:
```
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```
Same thing would happen with poetry install, so...

```
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
poetry install
```
