### ISSUE TITLE
poetry remove pytest then poetry stop working

### ISSUE THREAD

**Issue by linchiwei123** [sdispater/poetry#1529]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows10
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/linchiwei123/4eec30fd37722cec4c46ff3a9d266cef

## Issue

first:
(venv) C:\python\learn>poetry remove pytest
Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 0 installs, 0 updates, 14 removals

  - Removing atomicwrites (1.3.0)
  - Removing attrs (19.3.0)
  - Removing colorama (0.4.1)
  - Removing importlib-metadata (0.23)
  - Removing more-itertools (7.2.0)
  - Removing packaging (19.2)
  - Removing pathlib2 (2.3.5)
  - Removing pluggy (0.13.0)
  - Removing py (1.8.0)
  - Removing pyparsing (2.4.2)
  - Removing pytest (5.2.2)
  - Removing six (1.12.0)
  - Removing wcwidth (0.1.7)
  - Removing zipp (0.6.0)

second:
(venv) C:\python\learn>poetry -vvv add pytest

[ImportError]
No module named 'pyparsing'

Exception trace:
 c:\python\learn\venv\lib\site-packages\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 c:\python\learn\venv\lib\site-packages\poetry\console\application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 c:\python\learn\venv\lib\site-packages\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 c:\python\learn\venv\lib\site-packages\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 c:\python\learn\venv\lib\site-packages\cleo\commands\base_command.py in run() at line 136
   self.initialize(input_, output_)
 c:\python\learn\venv\lib\site-packages\poetry\console\commands\env_command.py in initialize() at line 12
   from poetry.utils.env import Env
 c:\python\learn\venv\lib\site-packages\poetry\utils\env.py in <module>() at line 25
   from poetry.version.markers import BaseMarker
 c:\python\learn\venv\lib\site-packages\poetry\version\markers.py in <module>() at line 3
   from pyparsing import ParseException, ParseResults, stringStart, stringEnd

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

**Comment by finswimmer** [comment]
Hello @linchiwei123 ,

how have you installed poetry? Is it installed in the same virtuell environment like the project?

fin swimmer

**Comment by linchiwei123** [comment]
> Hello @linchiwei123 ,
> 
> how have you installed poetry? Is it installed in the same virtuell environment like the project?
> 
> fin swimmer

i think so.

**Comment by linchiwei123** [comment]
(venv) C:\python\learn\poetry_test>poetry init

This command will guide you through creating your pyproject.toml config.

Package name [poetry_test]:
Version [0.1.0]:
Description []:
Author [linchiwei123 <306741005@qq.com>, n to skip]:
License []:
Compatible Python versions [^3.5]:

Would you like to define your dependencies (require) interactively? (yes/no) [yes] no



Would you like to define your dev dependencies (require-dev) interactively (yes/no) [yes] no

Generated file

[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors = ["linchiwei123 <306741005@qq.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


Do you confirm generation? (yes/no) [yes]


(venv) C:\python\learn\poetry_test>poetry install
Updating dependencies
Resolving dependencies...

Writing lock file

Nothing to install or update


(venv) C:\python\learn\poetry_test>poetry add pytest
Using version ^5.2 for pytest

Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 8 installs, 0 updates, 0 removals

  - Installing atomicwrites (1.3.0)
  - Installing colorama (0.4.1)
  - Installing packaging (19.2)
  - Installing pathlib2 (2.3.5)
  - Installing pluggy (0.13.0)
  - Installing py (1.8.0)
  - Installing wcwidth (0.1.7)
  - Installing pytest (5.2.2)

(venv) C:\python\learn\poetry_test>poetry remove pytest
Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 0 installs, 0 updates, 14 removals

  - Removing atomicwrites (1.3.0)
  - Removing attrs (19.3.0)
  - Removing colorama (0.4.1)
  - Removing importlib-metadata (0.23)
  - Removing more-itertools (7.2.0)
  - Removing packaging (19.2)
  - Removing pathlib2 (2.3.5)
  - Removing pluggy (0.13.0)
  - Removing py (1.8.0)
  - Removing pyparsing (2.4.2)
  - Removing pytest (5.2.2)
  - Removing six (1.12.0)
  - Removing wcwidth (0.1.7)
  - Removing zipp (0.6.0)

(venv) C:\python\learn\poetry_test>poetry add pytest -vvv

[ImportError]
No module named 'pyparsing'

Exception trace:
 c:\python\learn\poetry_test\venv\lib\site-packages\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\console\application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 c:\python\learn\poetry_test\venv\lib\site-packages\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 c:\python\learn\poetry_test\venv\lib\site-packages\cleo\commands\base_command.py in run() at line 136
   self.initialize(input_, output_)
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\console\commands\env_command.py in initialize() at line 12
   from poetry.utils.env import Env
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\utils\env.py in <module>() at line 25
   from poetry.version.markers import BaseMarker
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\version\markers.py in <module>() at line 3
   from pyparsing import ParseException, ParseResults, stringStart, stringEnd

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

**Comment by linchiwei123** [comment]
(venv) C:\python\learn\poetry_test>poetry add pytest
Using version ^5.2 for pytest

Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 8 installs, 0 updates, 0 removals

  - Installing atomicwrites (1.3.0)
  - Installing colorama (0.4.1)
  - Installing packaging (19.2)
  - Installing pathlib2 (2.3.5)
  - Installing pluggy (0.13.0)
  - Installing py (1.8.0)
  - Installing wcwidth (0.1.7)
  - Installing pytest (5.2.2)

**Comment by linchiwei123** [comment]
(venv) C:\python\learn\poetry_test>poetry remove pytest
Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 0 installs, 0 updates, 14 removals

  - Removing atomicwrites (1.3.0)
  - Removing attrs (19.3.0)
  - Removing colorama (0.4.1)
  - Removing importlib-metadata (0.23)
  - Removing more-itertools (7.2.0)
  - Removing packaging (19.2)
  - Removing pathlib2 (2.3.5)
  - Removing pluggy (0.13.0)
  - Removing py (1.8.0)
  - Removing pyparsing (2.4.2)
  - Removing pytest (5.2.2)
  - Removing six (1.12.0)
  - Removing wcwidth (0.1.7)
  - Removing zipp (0.6.0)

**Comment by linchiwei123** [comment]
(venv) C:\python\learn\poetry_test>poetry add pytest -vvv

[ImportError]
No module named 'pyparsing'

Exception trace:
 c:\python\learn\poetry_test\venv\lib\site-packages\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\console\application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 c:\python\learn\poetry_test\venv\lib\site-packages\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 c:\python\learn\poetry_test\venv\lib\site-packages\cleo\commands\base_command.py in run() at line 136
   self.initialize(input_, output_)
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\console\commands\env_command.py in initialize() at line 12
   from poetry.utils.env import Env
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\utils\env.py in <module>() at line 25
   from poetry.version.markers import BaseMarker
 c:\python\learn\poetry_test\venv\lib\site-packages\poetry\version\markers.py in <module>() at line 3
   from pyparsing import ParseException, ParseResults, stringStart, stringEnd

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

**Comment by finswimmer** [comment]
> > Hello @linchiwei123 ,
> > how have you installed poetry? Is it installed in the same virtuell environment like the project?
> > fin swimmer
> 
> i think so.

Don't do this. When using the poetry commands, poetry only knows about packages and dependencies it has installed for the project. So when you remove `pytest` from your project `pyarsing` get also removed, as it was installed as an dependency for it. But this packaging is necessary for poetry itself.

**Comment by linchiwei123** [comment]
> > > Hello @linchiwei123 ,
> > > how have you installed poetry? Is it installed in the same virtuell environment like the project?
> > > fin swimmer
> > 
> > 
> > i think so.
> 
> Don't do this. When using the poetry commands, poetry only knows about packages and dependencies it has installed for the project. So when you remove `pytest` from your project `pyarsing` get also removed, as it was installed as an dependency for it. But this packaging is necessary for poetry itself.

thanks!
