### ISSUE TITLE
Installation failed (poetry 0.12.17, Linux Mint 19.2)

### ISSUE THREAD

**Issue by vpoulailleau** [sdispater/poetry#1540]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19.2
- **Poetry version**: 0.12.17

## Issue

I failed to install poetry with Python 3.8 and found a relevant issue. I uninstalled it. I then tried to install poetry with Python 3.6, but I get the same kind of error: `ModuleNotFoundError: No module named 'cleo'`

I was conviced during last PyConFr to use poetry which seems great. So I want to install it.

Here is what happened:
```bash
 vincent  vincent-port  ~  $  python3.8 get-poetry.py --uninstall
# We are sorry to see you go!

This will uninstall Poetry.

It will remove the `poetry` command from Poetry's bin directory, located at:

$HOME/.poetry/bin

This will also remove Poetry from your system's PATH.


Are you sure you want to uninstall Poetry? (y/[n]) y

 vincent  vincent-port  ~  $  curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3.6
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time with `poetry self:uninstall`,
or by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 0.12.17
  - Downloading poetry-0.12.17-linux.tar.gz (8.37MB)

Poetry (0.12.17) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`

 vincent  vincent-port  ~  $  source $HOME/.poetry/env
 vincent  vincent-port  ~  $  poetry completions bash -vvv
Traceback (most recent call last):
  File "/home/vincent/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/vincent/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/vincent/.poetry/lib/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```
Thanks for your attention and for this project.

**Comment by sdispater** [comment]
The `0.12.17` release does not support Python 3.8 and you should, if possible, use the latest `1.0.0` beta release.

**Comment by vpoulailleau** [comment]
I'll try to use the beta release. 

But in the example I provided:

- Installed poetry with Python 3.8 (not shown in the issue)
- Uninstalled poetry with Python 3.8
- **Installed poetry with Python 3.6**
- Failed to use poetry

So there is a problem with either the uninstallation (with Python 3.8), or the reinstallation with Python 3.6, or with my computer. Any advice?

**Comment by xyzst** [comment]
I ran into a similar issue with poetry `0.12.17` installation on macOS Mojave with Python 3.8.0. I resolved it by following these instructions:

1. Remove the $HOME/.poetry directory
2. Re-install poetry with POETRY_PREVIEW enabled `$ curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_PREVIEW=1 python`

Thanks @sdispater as well as this comment on another issue https://github.com/sdispater/poetry/issues/553#issuecomment-548446831

**Comment by vpoulailleau** [comment]
@xyzst @sdispater Thanks, it works with the beta version.

**Comment by ksze** [comment]
> The `0.12.17` release does not support Python 3.8 and you should, if possible, use the latest `1.0.0` beta release.

Then that needs to be mentioned in the online documentation: https://poetry.eustace.io/docs/#system-requirements
