### ISSUE TITLE
`[Errno 2] No such file or directory` When trying to run poetry

### ISSUE THREAD

**Issue by AntoineSebert** [sdispater/poetry#1545]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Microsoft WIndows 10
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/AntoineSebert/359571369d2a5fef23523b9ede3699a5

### Short desc

When I try to run **poetry**, I get: `D:\Users\{username}\AppData\Local\Programs\Python\Python37\python.exe: can't open file '/cygdrive/c/Users/{username}/.poetry/bin/poetry': [Errno 2] No such file or directory`

### Replication

I followed the installation steps detailed at https://poetry.eustace.io/docs/:

```bash
{username}@{computer_name} /cygdrive/d 
$ curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
Retrieving Poetry metadata 

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at: 

%USERPROFILE%\.poetry\bin

This path will then be added to your `PATH` environment variable by     
modifying the `HKEY_CURRENT_USER/Environment/PATH` registry key.        

You can uninstall at any time with `poetry self:uninstall`,
or by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 0.12.17
  - Downloading poetry-0.12.17-win32.tar.gz (7.21MB) 

Poetry (0.12.17) is installed now. Great!

To get started you need Poetry's bin directory (%USERPROFILE%\.poetry\bin) in your `PATH` 
environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.
```

Then I show that the file is present:

```bash
{username}@{computer_name} /cygdrive/d
$ cd /cygdrive/c/Users/{username}/.poetry/bin        

{username}@{computer_name} ~/.poetry/bin 
$ ls 
poetry  poetry.bat
```

Finally I try to run poetry:
```bash
{username}@{computer_name} /cygdrive/d
$ poetry --version 
D:\Users\{username}\AppData\Local\Programs\Python\Python37\python.exe: can't open file '/cygdrive/c/Users/{username}/.poetry/bin/poetry': [Errno 2] No such file or directory
```

**Comment by AntoineSebert** [comment]
Fixed.
Probably a working environment error (Windows 10 + Terminus + Ubuntu WSL).

**Comment by mlgarchery** [comment]
After playing with poetry (multiple removal of the env/.lock file, and poetry install), `poetry install` would give me the same error.
Closing my terminal and relaunching it would solve the issue

**Comment by johnthagen** [comment]
The only fix for me was to manually wipe out Poetry's entire virtualenv cache:

- https://github.com/python-poetry/poetry/issues/6841#issuecomment-1284590137
