### ISSUE TITLE
Maximum recursion depth exceeded for `requests[security]` introduced in 1.0.0b4

### ISSUE THREAD

**Issue by tonysyu** [sdispater/poetry#1558]
- [x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.14.5
- **Poetry version**: 1.0.0b4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/tonysyu/82b3fc28b01e0fec6e53cece29adc7db

## Issue

While testing out the extras export fix for https://github.com/sdispater/poetry/issues/1313, I tried setting up a new project (with the `pyproject.toml` linked above) and ran into the following issue:
```
$ poetry --version
Poetry version 1.0.0b4

$ poetry add -v3 requests[security]
The currently activated Python version 2.7.13 is not supported by the project (^3.6).
Trying to find and use a compatible version.
Using python3 (3.6.5)
Using version ^2.22.0 for requests

Updating dependencies
Resolving dependencies... (13.7s)
Resolving dependencies... (13.8s)
[RuntimeError]
maximum recursion depth exceeded while calling a Python object
```
- Running the same command on 1.0.0b3 works as expected
- Running `poetry add requests` (without the extras) works as expected

**Comment by sdispater** [comment]
I know where the issue is coming from and it has been introduced in https://github.com/sdispater/poetry/pull/1555.

I'll try to make a fix as soon as possible.

Sorry for the regression!

**Comment by M5oul** [comment]
I don’t know if this is related, but it is happening on two projects of mine:

```bash
poetry update
Updating dependencies
Resolving dependencies... (4.2s)

[TooManyRedirects]
Exceeded 30 redirects.
```

**Comment by tonysyu** [comment]
Updated to 1.0.0b5 and confirmed the fix. Thanks!
