### ISSUE TITLE
Issues with parsing python-versions.

### ISSUE THREAD

**Issue by Tonkonozhenko** [sdispater/poetry#156]
Hi,

There are issues with parsing dependencies for [responses](https://github.com/getsentry/responses/blob/master/setup.py#L39)

**Comment by sdispater** [comment]
@Tonkonozhenko What is the issue exactly?

**Comment by Tonkonozhenko** [comment]
@sdispater cannot reproduce now. I had issues with this [line](https://github.com/sdispater/poetry/blob/master/poetry/packages/__init__.py#L114). Temporarily I fixed it with `version.split(' ')` => `re.split(r'[ ,]+', version)`, but I'm not sure if it's correct approach.

**Comment by sdispater** [comment]
This should be fixed in the latest release (`0.10.2`)
