### ISSUE TITLE
Windows default terminal can't handle color codes: --no-ansi by default?

### ISSUE THREAD

**Issue by madig** [sdispater/poetry#159]
The default Windows terminal (below) and even Hyper (above) can't handle color codes:
![image](https://user-images.githubusercontent.com/380829/40709890-2b7c359a-63ef-11e8-8e0f-7070f2955061.png)

Maybe make `--no-ansi` the default on Windows? Or allow me to set the setting system-wide?

**Comment by grilo** [comment]
I confirm this also happens on the default terminal of W10 build 17677.

Poetry is using the "cleo" library to manage the output, this probably should be fixed there instead.

**Comment by sdispater** [comment]
Actually, `cleo` behaves properly but a modification I made in `poetry` always activates the "decorated" mode by default.

This should be an easy fix. I will keep you posted.

**Comment by madig** [comment]
They seem to have Windows issues as well? https://github.com/tartley/colorama/issues/104

**Comment by moigagoo** [comment]
@madig Hmmm, I've been using it in a few crossplatform projects, no issues so far.

**Comment by moigagoo** [comment]
FYI colors are shown just fine in ConEmu.

**Comment by sdispater** [comment]
This should be fixed in the latest release (`0.10.2`)

**Comment by madig** [comment]
Works for me in 0.10.2. Thanks!

**Comment by vberlier** [comment]
Hmm... I'm using ConEmu as the integrated VS Code terminal and I have kind of the same problem.

![image](https://user-images.githubusercontent.com/24430071/41508181-bc7c956c-7240-11e8-9070-3d1cf17d6537.png)

The colors work fine in ConEmu but don't show up through VS Code. However they work when piping the output to `cat`.
