### ISSUE TITLE
Parseable format for `poetry version`

### ISSUE THREAD

**Issue by pgilad** [sdispater/poetry#1590]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I want to suggest adding an option to choose the output format for `poetry version`.
2 formats come to mind:
1. `json` - no words needed
2. `parseable text` - like `project:version`

This will help in bash scripts orchestration of poetry version to detect the current project version easily without needed regex to parse the current version (or use toml to read file)

Perhaps this could be done with:
`poetry version --format <json|parseable|text>` or something like that

**Comment by finswimmer** [comment]
I think different formats would introduce to much complexity.

My preferable solution of the output by `poetry version` would just: `<project_name> <version>`

This would be inline with how most command line tools output there version and is easily to parse.

If @sdispater agree I would contribute a PR. This would be just a small change in the output.

**Comment by pgilad** [comment]
I'm cool with anything that could be easily machine parseable for orchestrating scripts

**Comment by finswimmer** [comment]
PR is accepted. So from the next version on the output of `poetry version` is `<project_name> <version>` which is easy to parse.

**Comment by pgilad** [comment]
Amazing 🏛
