### ISSUE TITLE
1.0.0b5 removes my private source from the lockfile

### ISSUE THREAD

**Issue by JBKahn** [sdispater/poetry#1602]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6 (18G103)
- **Poetry version**:  https://gist.github.com/JBKahn/4bbb040c0181d974e0b71407ad764b6c

## Issue
When moving from `1.0.0b4` to `1.0.0b5` `poetry lock` is removing the 
```
[package.source]
reference = "private"
type = "legacy"
url = "https://private.url"
```

**Comment by JBKahn** [comment]
An example of such a package:
```python
```

**Comment by JBKahn** [comment]
[This](https://github.com/sdispater/poetry/compare/1.0.0b4...1.0.0b5#diff-82b23d5737d621bcdd9009dfa78a88f2L317) line seems to the one that "broke" that for us.

**Comment by JBKahn** [comment]
Some downstream checks seem to require that `source_type` is set, unsure how to set it manually anywhere. @sdispater didn't fully understand the change in your previous PR.

**Comment by stevegore** [comment]
I've just had a developer waste a day trying to work out why their Docker build wasn't working. Turns out it was this bug.

**Comment by jstriebel** [comment]
We are experiencing a similar problem. We have a package with a custom pypi source (`custom_pkg = {version = "5.0.0", source = "custom_pypi"`).
When using `poetry lock` everything is updated as expected, but when updating a single package (e.g. ` poetry update --lock another_pkg`) the custom_pypi entry is removed from the lockfile and `custom_pkg` becomes `{file = "…..tar.gz", hash = "sha256:…"}` in the lockfile.

Tested this with poetry versions `1.0.0b4` and `1.0.0b7`.

**Comment by petergaultney** [comment]
I'm also experiencing this. 

My `pyproject.toml` defines a `[[tool.poetry.source]]` entry for our private repo, but that URL does not appear in the `poetry.lock` file. I am on `1.0.0b7`.

**Comment by petergaultney** [comment]
readding the line `            package.source_type = "legacy"` in `legacy_repository.py` does fix this for us.
