### ISSUE TITLE
`poetry develop` doesn't make the package importable on Windows

### ISSUE THREAD

**Issue by moigagoo** [sdispater/poetry#162]
Steps to reproduce:

0. From the package root, run `poetry develop`.
1. Create a subfolder in the project root, e.g. foo.
2. In it, create a .py file with the content `import mypackage` where "mypackage" is the name of the package being developed, e.g. bar.py.
3. In the project root, run `poetry run python foo/bar.py`.

Expected result: the file runs, because mypackage should be installed the virtualenv used by this project and thus should be importable from any file executed in this virtualenv.

Actual result: file execution fails with `cannot import "mypackage"`.

UPD: It works in Ubuntu (WSL) but fails in Windows (pwsh). If the feature is implemented with `pip install -e`, apparently, it is to blame. However, a closer investigation is required.

**Comment by bertjwregeer** [comment]
I am not seeing the same issue:

```
Riley:developtest xistence$ poetry init

This command will guide you through creating your poetry.toml config.

Package name [developtest]: 
Version [0.1.0]: 
Description []: 
Author [Bert JW Regeer, n to skip]: n
License []: 
Compatible Python versions [*]: 

Would you like to define your dependencies (require) interactively? (yes/no) [yes] no



Would you like to define your dev dependencies (require-dev) interactively (yes/no) [yes] no

Generated file

[tool.poetry]
name = "developtest"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.5"


Do you confirm generation? (yes/no) [yes] yes

Riley:developtest xistence$ ls -lah
total 8
drwxr-xr-x   3 xistence  staff    96B May 30 14:49 .
drwxr-xr-x  29 xistence  staff   928B May 30 14:49 ..
-rw-r--r--   1 xistence  staff   201B May 30 14:49 pyproject.toml
Riley:developtest xistence$ mkdir developtest
Riley:developtest xistence$ touch developtest/__init__.py
Riley:developtest xistence$ mkdir foo
Riley:developtest xistence$ echo "import developtest" > foo/bar.py
Riley:developtest xistence$ poetry develop
Creating virtualenv developtest-py3.6 in /Users/xistence/Library/Caches/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.6s)


Package operations: 7 installs, 0 updates, 0 removals

Writing lock file

  - Installing atomicwrites (1.1.5)
  - Installing attrs (18.1.0)
  - Installing more-itertools (4.2.0)
  - Installing pluggy (0.6.0)
  - Installing py (1.5.3)
  - Installing six (1.11.0)
  - Installing pytest (3.6.0)
Installing developtest (0.1.0)
Riley:developtest xistence$ poetry run python foo/bar.py
```

Adding a shebang and marking the file as executable:

```
Riley:developtest xistence$ cat foo/bar.py 
#!/usr/bin/env python

import developtest

print("Imported just fine")
Riley:developtest xistence$ poetry run foo/bar.py
Imported just fine
```

What is your shebang line? Are you using the wrong Python interpreter (rather than the one defined by the venv poetry is using, you are using a different one?

**Comment by moigagoo** [comment]
Adding a shebang and making the file executable simply lets you run the script without typing "python" in front of it. It has nothing to do with the issue.

However, the fact that you're running Unix does matter. I've just tried running the script in Ubuntu, and it worked. On Windows, not so much.

Maybe this has something to do with how `pip install -e` works in different OSes. I remember having issues with it on Windows and switching to `python setup.py develop` instead.

**Comment by bertjwregeer** [comment]
@moigagoo your initial report stated:

```
poetry run foo/bar.py
```

This won't work unless the script is marked executable (and has a shebang on unix), I'm assuming that windows has associated it with a default version of python, which is entirely possible. Could you try running it with:

```
poetry run python foo/bar.py
```

And see if the error persists? That should run the python that is installed in the virtualenv to execute `foo/bar.py`, which should work.

**Comment by moigagoo** [comment]
@bertjwregeer

> your initial report stated:

Thanks for pointing it out! It was a typo, I'm afraid. Sorry for the confusion, fixed.

I have been running `poetry run python foo/bar.py`. The same project, the same files. Works in Ubuntu, fails in Windows. Updated the initial comment and the issue title accordingly.

**Comment by sdispater** [comment]
I can confirm the problem on Windows.

The problem comes from the fact that when `run` is executed `poetry` changes the `PATH` to make the Python virtualenv accessible but it does not seem to work on Windows.

**Comment by moigagoo** [comment]
@sdispater I can see `src` being added to `sys,path`, but not `.` (https://github.com/sdispater/poetry/blob/master/poetry/console/commands/run.py#L27). Could this be the reason? Also, wouldn't we add the abspath to the package dir or the `src` dir?

**Comment by sdispater** [comment]
@moigagoo I made a modification that might fix the issue. Could test with the latest release (`0.10.2`)?

**Comment by moigagoo** [comment]
@sdispater Just tried it, the result is the same. I've created a test repo to check the feature: https://github.com/moigagoo/foo

**Comment by sdispater** [comment]
@moigagoo I cannot reproduce on `0.10.2` on Windows:

```
>>> poetry develop
>>> poetry run python bar/baz.py
0.1.0
>>> poetry run python baz.py
0.1.0
```
