### ISSUE TITLE
Exit code 0 on "max retries exceeded" during publish

### ISSUE THREAD

**Issue by a-recknagel** [sdispater/poetry#1622]
poetry version: 0.12.17

When using poetry in CI/CD settings, errors during command execution should lead to an exit code other than 0 so that the job knows that it has failed. But when I run a publish and the connection times out, I got the following:

```
$ poetry publish -r localpipy -u test -p test

Publishing mypack (0.1.0) to localpipy
 - Uploading mypack-0.1.0-py3-none-any.whl 0% 
[ConnectionError]                                                
HTTPConnectionPool(host='1.3.3.7', port=8080): Max retries exceeded with  
 url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection ob  
ject at 0x7f1557201280>: Failed to establish a new connection: [Errno 110] O  
peration timed out'))                                                         
                                                                                
publish [-r|--repository REPOSITORY] [-u|--username USERNAME] [-p|--password PASSWORD] [--build]

Job succeeded
```

And the CI chugs happily on, thinking that everything is fine.

----
related:
 - https://github.com/sdispater/poetry/issues/239 (same issue on `poetry add`)
 - https://github.com/sdispater/poetry/issues/659 (same issue as this, closed due to staleness)

**Comment by finswimmer** [comment]
Hello @a-recknagel ,

does this also happens with the latest preview version?

This is what I get with 1.0.0b7:

```
$ poetry publish -u test -p test

Publishing example (0.1.0) to PyPI
 - Uploading example-0.1.0-py2.py3-none-any.whl 100%

[UploadError]
HTTP Error 403: Invalid or non-existent authentication information.

$ echo $?
1
```

fin swimmer

**Comment by a-recknagel** [comment]
hi @finswimmer,

thanks for pointing that out, I tested with the newest version and it's fixed there, `ConnectionError` reutrns an exit code of 1 as well. I'll assume that the 0.x.y branch will not receive this change as a backport since it's probably just going to be discontinued after 1.0, so I'll close this issue.
