### ISSUE TITLE
Unable to run poetry under Python 2.7 (missing importlib_metadata)

### ISSUE THREAD

**Issue by schinckel** [sdispater/poetry#1666]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS Catalina
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

I am in the process of transitioning to Python 3. As such, I am moving from Pipenv to Poetry.

I have poetry installed using `pipx`, which is being used to run things like `poetry lock`, and that all works great.

However, in my tox environment, I use `poetry` as a "dep", and the `poetry install` before running my tests.

In Python 2.7, this throws an exception:

    [ImportError]
    No module named importlib_metadata  

When I run it using `-vv`, I can see that the problem is not to do with installing the dependencies as such, but actually when poetry tries to parse the lock file:

    Exception trace:
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/cleo/application.py in run() at line 94
       status_code = self.do_run(input_, output_)
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/console/application.py in do_run() at line 88
       return super(Application, self).do_run(i, o)
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/cleo/application.py in do_run() at line 197
       status_code = command.run(input_, output_)
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/console/commands/command.py in run() at line 77
       return super(BaseCommand, self).run(i, o)
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/cleo/commands/base_command.py in run() at line 136
       self.initialize(input_, output_)
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/console/commands/env_command.py in initialize() at line 18
       current_env = Env.get(self.poetry.file.parent)
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/console/commands/command.py in poetry() at line 62
       return self.get_application().poetry
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/console/application.py in poetry() at line 55
       from poetry.poetry import Poetry
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/poetry.py in <module>() at line 11
       from .json import validate_object
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/poetry/json/__init__.py in <module>() at line 4
       import jsonschema
     /Users/matt/Development/ROSS/datamine/.tox/py27/lib/python2.7/site-packages/jsonschema/__init__.py in <module>() at line 33
       import importlib_metadata as metadata

It seems that poetry does not install `importlib_metadata` when being installed under Python 2.7: adding it as a secondary dependency to my tox environment fixes this.

**Comment by schinckel** [comment]
To be clear: I have a resolution - after some time I was able to see that I needed to have tox also install `importlib_metadata`, but this was non-obvious until running with `poetry -vv`, and I wonder if there is a way to have this install automatically as a dependency under Python 2.7?

**Comment by finswimmer** [comment]
Hello @schinckel,

this (or something similar?) was reported before in #1487 and should be fixed by #1586 

So please try it out with the latest preview release.

I will close this issue for now. But please leave a comment, if you still have any problems. I can reopen it any time.

fin swimmer

**Comment by schinckel** [comment]
I’ll check it at work in a couple of hours, but I thought it was different because that was to do with 3.8: the change in that PR shouldn’t have any different behaviour on 2.7

**Comment by schinckel** [comment]
I think maybe something else (prior to this change) fixed the issue: it appears to be working (but I've come across other issues related to running poetry from within tox that I am partway through documenting).

I've started a clean run without the extra requirement in my tox.ini on my CI server: I should know shortly if it has worked.
