### ISSUE TITLE
Unable to "poetry env use python2.7"

### ISSUE THREAD

**Issue by schinckel** [sdispater/poetry#1667]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina
- **Poetry version**: 1.0.0b8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/schinckel/11584f891a467aeda3623e87bec162be

## Issue

Unable to force poetry to use a Python 2 virtualenv:

    $ poetry env use python2.7 -vvv
    Creating virtualenv poetry-2.7-z4CKCkQ1-py2.7 in /Users/matt/Library/Caches/pypoetry/virtualenvs
    Traceback (most recent call last):
      File "<stdin>", line 10, in <module>
    ImportError: No module named virtualenv
    Using virtualenv: /Users/matt/.local/pipx/venvs/poetry

**Comment by schinckel** [comment]
You can manually create the virtualenv at the location, and then repeat the `poetry env use` command.

**Comment by schinckel** [comment]
Also, you can extract the target location from the error:

    virtualenv $(poetry env use python2.7 2> /dev/null | awk '{print $NF "/" $3}' | head -n 1) --python=python2.7

**Comment by finswimmer** [comment]
Hello @schinckel ,

you have to install the `virtualenv` for the choosen python interpreter once by yourself, e.g. `pip2 install virtualenv`. Afterwards the `poetry env` command should work normally.

fin swimmer

**Comment by schinckel** [comment]
Ah, that makes sense. I guess since I installed python 2.7.16 using `pyenv` it no longer had virtualenv.
