### ISSUE TITLE
poetry 0.10.1 on python 3.6 fails to install pytest-{code,doc}style due to python ~= 3.5 

### ISSUE THREAD

**Issue by pauricthelodger** [sdispater/poetry#168]
Hey there,

Maybe I'm misunderstanding pep-440, [pytest-codestyle](https://pypi.org/project/pytest-codestyle/) and [pytest-docstyle](https://pypi.org/project/pytest-docstyle/) both have the compatible release identifier of ~=3.5 for python, which I've been assuming means 3.5 up to 4.0? If so, poetry 0.10.1 is failing to install either of them into the current project python 3.6 venv with:
                                                                              
    [SolverProblemError]                             
    Because no versions of pytest-codestyle match >1.2,<1.2.1 || >1.2.1,<1.2.2 || >1.2.2,<2.0      
     and pytest-codestyle (1.2.0) requires Python ~=3.5, pytest-codestyle is forbidden.         
    And because pytest-codestyle (1.2.1) requires Python ~=3.5, pytest-codestyle is forbidden.  
    So, because pytest-codestyle (1.2.2) requires Python ~=3.5                                                                                                                  
    and pondus depends on pytest-codestyle (^1.2), version solving failed.

Thanks!

**Comment by sdispater** [comment]
Yes, there is a confusion on the part of poetry here.

Basically, `poetry` treats `~=3.5` as `~3.5` which in semver means `>=3.5, <3.6` (see https://poetry.eustace.io/docs/versions/#tilde-requirements). But PEP 440 says that it should mean `>=3.5, <4.0`.

I will see how I can fix this.

**Comment by pauricthelodger** [comment]
Ahh, ouch! Thanks for the info and good luck with it =)

**Comment by sdispater** [comment]
This should be fixed in the latest release (`0.10.2`)

**Comment by pauricthelodger** [comment]
Can confirm, works in 0.10.2 - cheers for that! =)
