### ISSUE TITLE
Clear PyPI Caches

### ISSUE THREAD

**Issue by mackeyja92** [sdispater/poetry#175]
Trying to install something that went live on PyPI in the last 15 minutes causes it to fail and not find the package. Is there a way to clear out the caches without manually deleting the folders?

**Comment by sdispater** [comment]
@mackeyja92 You can try:

```bash
poetry cache:clear pypi --all
```

**Comment by mackeyja92** [comment]
@sdispater derp, didn't see that. I looked all over it too.

**Comment by benoit-cty** [comment]
For those coming here from a search engine, the command is now:
`poetry cache clear pypi --all`
