### ISSUE TITLE
Allow to define package source dir in pyproject.toml

### ISSUE THREAD

**Issue by moigagoo** [sdispater/poetry#182]
Poetry has the convention of the package title being the same as the package dir name. However, this is not always the desired behavior.

Here's an example of a package called `foliantcontrib.includes` which is in fact exports `foliant.preprocessors.includes` module. In `setup.py`, package name and the names of the exported packages are independent: https://github.com/foliant-docs/foliantcontrib.includes/blob/develop/setup.py#L23.

Poetry could have an option `src` that would point to the source code path within the project path. By the way, this could be an alternative way to support src layout: you'd just set `src: src/mypackage`.

**Comment by moigagoo** [comment]
I'll note that the packages I want to switch to Poetry use namespace packing, so this issue is also relevant https://github.com/sdispater/poetry/issues/167

**Comment by jacebrowning** [comment]
I also need this.

I have a project named `coverage-space`, but the package is `coveragespace`.

**Comment by uSpike** [comment]
In my organization, we put all of our code under one namespace `abc`.  We have multiple packages, so the layout is like:
```
abc-projectA/
   pyproject.toml
   abc/
      projectA/
         __init__.py
abc-projectB/
   pyproject.toml
   abc/
      projectB/
         __init__.py
```

It would be great if poetry could support namespace packages for this reason.  Would it be better to be able to configure the "source" directory in `pyproject.toml`?

**Comment by jacebrowning** [comment]
I think it's fairly common for the PyPI name and package name to be different.

https://pypi.org/project/minilog/ is used as `import log`.

Can this library be developed using Poetry?

**Comment by sdispater** [comment]
The `packages` section of the `tool.poetry` section should address this: https://poetry.eustace.io/docs/pyproject/#packages
