### ISSUE TITLE
Testing against built project

### ISSUE THREAD

**Issue by bertjwregeer** [sdispater/poetry#183]
I have a project in poetry that I'd like to test the resulting sdist/wheel, right now I am running:

```
poetry develop
poetry run pytest
```

However I'd like to have some way of doing:

```
poetry build
poetry install --built --extra testing
poetry run pytest
```

So that `pytest` is run against the built `wheel` or `sdist` (as the case may be) so that I can be sure that the built package works.

I am considering doing the following:

```
poetry build
rm -rf .venv-testing
virtualenv .venv-testing
./venv-testing/bin/pip install -U dist/myproject-*.whl[testing]
./venv-testing/bin/pytest tests
```

So that I can be fairly sure that what I am shipping to users is working correctly and contains all of the necessary assets/bits.

(Yes, I currently specify my testing dependencies as an extra, and include them in my dev-dependencies too, I'd still like some way to not have that overlap if possible, or have some way of installing just certain deps with `poetry install` but force all other deps to come from the distributable package)

**Comment by sdispater** [comment]
You can have this behavior by using `tox` with [isolated builds](https://tox.readthedocs.io/en/latest/config.html#conf-isolated_build) and by using the PEP-517 compliant build system: https://poetry.eustace.io/docs/pyproject/#poetry-and-pep-517

**Comment by Victor-Savu** [comment]
@sdispater Is there a way to use a PEP-517 compliant build system to install the dev dependencies as well? For example, pytest is not installed by default if I just do `pip install .` with a PEP-517 build system.
