### ISSUE TITLE
Install git dependency using poetry

### ISSUE THREAD

**Issue by shawegit** [sdispater/poetry#184]
When a project that uses poetry depends on a package that is only available through git and that also uses poetry, it would be a great feature to use poetry to install the dependent package. Currently, it seems like installing packages from git is only possible using pip + setup.py, so we cannot install a poetry based package that is only available through git. Doing that is rather easy, once you know that a project.toml file exists, see a not polished and half pseudo example code below.
```python
from subprocess import call
import os
import glob
tmp_dir = Path(mkdtemp(prefix="pypoetry-git-{}".format("package_name")))
git = Git()
git.clone(source_url, tmp_dir)
git.checkout(branch/tag/.., tmp_dir)
crnt = os.getcwd()
os.chdir(tmp_dir)
call(['poetry','build','-f','wheel'])
wheel_file = glob.glob(f'{tmp_dir}/dist/*.whl')[0]
venv.run("pip", "install", wheel_file)
os.chdir(crnt)
...
```

**Comment by sdispater** [comment]
This is now supported.
