### ISSUE TITLE
Integrate setuptools-scm

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [sdispater/poetry#185]
Basic idea is instead of replicating scm metadata, just take them from the scm

I'm happy to ensure setuptools is no longer a hard dependency

**Comment by madig** [comment]
https://github.com/sdispater/poetry/issues/140 :)

**Comment by RonnyPfannschmidt** [comment]
@madig for extra context - im the maintainer of setuptools_scm and im willing to change it so setuptools wont be required for use from poetry

**Comment by webknjaz** [comment]
btw I'd bundle it with https://github.com/Changaco/setuptools_scm_git_archive

**Comment by webknjaz** [comment]
Let's close this in favor of #140 + #672 (demo discussion) so that it would be 1 single place with info, not 3 issues asking the same :)

**Comment by stephsamson** [comment]
Closing this in favor of #693.
