### ISSUE TITLE
clean/sync commands not present

### ISSUE THREAD

**Issue by polski-g** [sdispater/poetry#187]
> **Remove command**
> The remove command will only remove the package specified but not its dependencies if they are no longer needed.
> You either have to use `sync` or `clean` to fix that.

There does not seem to be either of these commands. I presume it is NYI.

pip-autoremove can be used in its stead.

**Comment by ambv** [comment]
Looks like you confused Poetry with Pipenv?

**Comment by polski-g** [comment]
No, I literally quoted from https://github.com/sdispater/poetry/blob/master/README.md

Either documentation is incorrect or this feature is NYI.

**Comment by jacebrowning** [comment]
@polski-g You're quoting from a section describing `pipenv`.

**Comment by polski-g** [comment]
It seems you are correct.
