### ISSUE TITLE
include= and exclude= missing from poetry-schema.json

### ISSUE THREAD

**Issue by ambv** [sdispater/poetry#188]
Hi, great work on Poetry! I might be missing something since that's my first try adopting Poetry.

I see code in `poetry.py` and `packages/package.py` around includes and excludes. I see it documented in https://poetry.eustace.io/docs/pyproject/#include-and-exclude. But since they are missing in the JSON schema, attempts to use either end with:
```
[InvalidProjectFile]
Additional properties are not allowed ('include' was unexpected)
```

**Comment by sdispater** [comment]
Thanks for your interest in Poetry!

Sorry about the confusion, the `inclue/exclude` sections are definitely planned but are not yet completely implemented.

It should land in release `0.11.0`. I will keep you posted.

**Comment by sdispater** [comment]
This is now supported in release `0.11.0a3`. Note that this has changed a bit and `include` is only to specify non package/module files (like change logs or any other file you want to include in the final distribution).

If you want to specify packages or modules that do not follow the poetry's recommended structure you can do so via the `packages` property.

See https://poetry.eustace.io/docs/pyproject/#packages and https://poetry.eustace.io/docs/pyproject/#include-and-exclude

**Comment by sdispater** [comment]
This now supported, see the links above.
