### ISSUE TITLE
Implement the Build Backend Interface described in PEP 517

### ISSUE THREAD

**Issue by cauebs** [sdispater/poetry#191]
I think it would help adoption if we could use poetry without requiring our users to also use it. I see that `poetry publish` already generates it. Is there any reason not to include a flag in, for example, `poetry build` to write it in the project root?

**Comment by ambv** [comment]
The point is not to have setup.py anymore. Instead, the next version of pip will be able to install packages that have `pyproject.toml` (see PEP 518 for details) and don't have `setup.py`. That will require support for `[build-system]` in Poetry. IIUC, this is a planned feature here.

**Comment by cauebs** [comment]
Oh, I see. Isn't there an issue regarding this? Should I close this and open one?

**Comment by Victor-Savu** [comment]
@ambv The current version of `pip` (10.x) already installs packages using `pyproject.toml`as per PEP 518. And `poetry` already acts as a build system.

**Comment by ambv** [comment]
@Victor-Savu, oh, if pip 10 already does that then great.

What do you put in your `[build-system]` section of your `pyproject.toml` to make pip install your poetry-powered package?

**Comment by Victor-Savu** [comment]
@ambv whoops, I have indeed been dreaming. `pip` only added support for PEP 518 and not for PEP 517 (here is the tracking issue for PEP 517 support: https://github.com/pypa/pip/issues/5407)

Sorry for the confusion! Indeed, poetry would need to be prepared to implement the [Build Backend Interface](https://www.python.org/dev/peps/pep-0517/#build-backend-interface) described in PEP 517 in order to be used by pip.

**Comment by orsinium** [comment]
I need this feature and create simple tool for this: [poetry-setup](https://github.com/orsinium/poetry-setup). Try it, if someone want it too :)

**Comment by bertjwregeer** [comment]
With `tox` supporting [`isolated_build`](https://tox.readthedocs.io/en/latest/config.html#conf-isolated_build) is there a way to set `poetry` as the build backend?

This would allow us to use `tox` for testing across multiple versions more easily.

**Comment by sdispater** [comment]
@bertjwregeer This has been added in commit 8055bcf. It will be officially available in the next `0.12` release.

I will try to make another alpha build this week so that it can be tested.

**Comment by bertjwregeer** [comment]
@sdispater Awesome. I am sorry I missed the commit!

**Comment by sdispater** [comment]
A PEP-517 compliant build system is now available: https://poetry.eustace.io/docs/pyproject/#poetry-and-pep-517
