### ISSUE TITLE
Consumable Public 'Debug Resolve' API

### ISSUE THREAD

**Issue by cooperlees** [sdispater/poetry#194]
Thanks for making this project, it's a shame it needs to exist, but Python really needs a nice solid resolver. I, along with a coworker tried to get JSON output added to `pip download`, but that was not received well (https://github.com/pypa/pip/pull/5400).

How do you feel about making the `debug:resolve` friendlier for other packages to import and use? I have a system where I wrap `pip` and build wheels for my build build system to consume (the are then also built with my version of gcc, openssl etc.). Today I use pip without the `--no-deps` option, but this means every time someone asks for a new module we build every single dep again, wasting time and resources (as I just skip uploading them to my internal PEP381 mirror if they already exist). Combining this system with poetry I could add the `--no-deps` to pip and pre calculate what I need to build.

For example, we request x:
- x depends on y
- y is already built
So I'd like to skip building y again and all its potential dependencies, building only what's required.

I hacked up an example file that poetry.console.commands.debug.resolve could then use: https://pastebin.com/AfHz4a2m (Naturally without the Py3 only stuff)

If this is to invasive, would you accept a PR that makes `--format=json` work or some parsable friendly output be generated from:
- `poetry debug:resolve $PACKAGE`
(We could generate a fake package .toml)

With debug:resolve I seem to get:
```
[NoSuchOption]
The "--format" option does not exist.
```

Thanks,
Cooper

**Comment by ambv** [comment]
@sdispater, if you'd be fine with making `--format=json` wok with `debug:resolve`, we're happy to make that PR for you.

**Comment by sdispater** [comment]
I think adding a `--format` option can be a good feature for the `debug:resolve` command if it can help get a dependency set consumable by other tools.

PR welcome :-)
