### ISSUE TITLE
Poetry add fails if path to venv contains space

### ISSUE THREAD

**Issue by Oisins** [sdispater/poetry#199]
If I run the CLI command `poetry add <package-name>` whilst in a virtual environment to which the path contains a space I get the following error:
```
[VenvCommandError]  
Command C:\Users\Oisin Smith\PycharmProjects\WxEpos\venv\Scripts\python.exe -c "import sys; print('.'.join([str(s) for s in sys.version_info[:3]]))" errored with the following output:
'C:\Users\Firstname' is not recognized as an internal or external command operable program or batch file
```

The problem seems to be that the venv is somewhere inside the `C:\Users\Firstname Lastname` directory that contains a space. This seems to be the Line causing the error https://github.com/sdispater/poetry/blob/master/poetry/utils/venv.py#L175

One possible fix would be to change [this](https://github.com/sdispater/poetry/blob/master/poetry/utils/venv.py#L241) line to add quotes around the `bin` (ie. `bin = f"'{bin}'"`) string.` I'm not sure where it would be most appropriate to change, so if you let me know, I could create a PR.

Thank you for your great work on this package!

**Comment by rcisterna** [comment]
Shows the same error when you have poetry configured to create the virtualenv in the project directory and try a `poetry install`.

**Comment by rschuetzler** [comment]
I have the same error when I try to use `poetry new` in a path that contains a space. 

```powershell
C:\Users\Firstname Lastname\code> poetry new learn-poetry
(null): can't open file 'C:\Users\Firstname': [Errno 2] No such file or directory
```

**Comment by sdispater** [comment]
Commit 58dbca4 fixes the issue.

It will land in the next bugfix release which should be out on Monday.

**Comment by sdispater** [comment]
Release `0.12.9` is out.
