### ISSUE TITLE
Poetry develop doesn't install dependencies defined by path as editable

### ISSUE THREAD

**Issue by cauebs** [sdispater/poetry#207]
Steps to reproduce:
```shell
~ $ git clone https://github.com/sdispater/poetry
~ $ git clone https://github.com/sdispater/cleo
~ $ cd poetry
# edit ~/poetry/pyproject.toml to change cleo's line to
# cleo = { path = "/home/<user>/test/cleo" }
~/poetry $ poetry develop
...
~/poetry $ source .venv/bin/activate.fish
(.venv) ~/poetry $ python -q
>>> import cleo
>>> cleo.__file__
'/home/<user>/test/poetry/.venv/lib/python3.6/site-packages/cleo/__init__.py'
```

What is expected: cleo is installed as editable and `cleo.__file__` is `/home/<user>/cleo/cleo/__init__.py`

Using `poetry install --develop=cleo` instead of `poetry develop` works as expected.

**Comment by cauebs** [comment]
Ok, I'm looking into `develop` and it seems it just calls `install` with no parameters.
https://github.com/sdispater/poetry/blob/master/poetry/console/commands/develop.py#L41

Additionally, it installs the current project in the venv with `-e` and `--no-deps`.

So, I must ask, is this actually the intended behaviour and I was wrong in expecting something different?
If that's not the case, how should dependencies specified by a path be handled?

**Comment by jacebrowning** [comment]
`develop` has been deprecated, but this still appears to be an issue with `install`

And `$ poetry install --develop=<dependency_name>` is still a valid workaround.

**Comment by sdispater** [comment]
@jacebrowning From release `0.12.0` and onward all path dependencies should be installed in editable mode by default. Is this not the case?
