### ISSUE TITLE
Please support .venv

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#213]
Please support a local .venv directory or link containing the virtualenv.
This way some tools like PyCharm just recognise the .venv and use it.

And for a manual link creation it would help to print out the full path rather than
"Creating virtualenv django-secrets-py3.6 in /Users/andy/Library/Caches/pypoetry/virtualenvs"
This sadly cant be used for copy and paste.

**Comment by kakulukia** [comment]
could you please document that and all other missing settings?

**Comment by kakulukia** [comment]
ill leave that ticket open as a reminder

**Comment by kakulukia** [comment]
yes, good point - maybe the changed valued on top or if there are many options, maybe another --list-all switch

**Comment by cauebs** [comment]
@kakulukia I've documented the available settings on #232. I'd appreciate if you could take a look at it :)

**Comment by Imaclean74** [comment]
looks great ! still - its always nice when tools can be self-documenting. And 'poetry config' should output something - a link to those docs, or a usage message - or something.

**Comment by cauebs** [comment]
@lmaclean74 I agree 100%. I'm going to leave that decision to @sdispater, though.

**Comment by cauebs** [comment]
@Imaclean74 In version 0.11, `poetry config --list` outputs all values, even if unset.

**Comment by kakulukia** [comment]
nice!

**Comment by mcarifio** [comment]
I didn't see a summary in the documentation, so this is my understanding of what I've gleaned above. If I've set 'poetry config settings.virtualenvs.in-project true`, then `poetry install` will create a project `.venv` directory and populate it with the correct python version based on `pyproject.toml` (?). If the project has a `.venv` directory in the project, then it will be respected regardless of `settings.virtualenvs.in-project`. `poetry shell` will use `.venv` and $VIRTUAL_ENV will be the path to that directory. There doesn't seem to be a convention about what the directory should be named, so I'll follow whatever default you have coded up. Please advise. Thanks.

**Comment by chingc** [comment]
@mcarifio There is no convention to what the virtual env directory is named, but the most common are `env`, `.env`, `venv`, and `.venv`.  The last one is probably the most popular and is the one poetry checks.  I'm not sure if it looks for the other names, but it's simple enough to check by creating a new empty project with a virtual env in it.

**Comment by mcarifio** [comment]
@chingc ty
