### ISSUE TITLE
Please use the default virtualenv directory 

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#214]
rather than that custom /Users/andy/Library/Caches/pypoetry/virtualenvs directory.

Currently all virtualenv(wrapper) command dont work due to the bad virtualenv home. :(

Other than that and the other ticket (https://github.com/sdispater/poetry/issues/213) i like poetry - just switched from pipenv.

**Comment by valignatev** [comment]
Yeah, respecting `WORKON_HOME` would be great.

**Comment by bertjwregeer** [comment]
If you activate the virtualenv before you use poetry, poetry will use your existing virtual environment.

Also, `~/Library/Caches/<app name>/` is the appropriate location for storing items that may be removed without damage on macOS, it's a system defined location, it's not a "custom" location.

**Comment by kakulukia** [comment]
Like @valignatev said, it would be cooler if poetry played nice with virtualenv(wrapper) and respects the already existing environment.

If there is no WORKON_HOME set, keep using that cache folder. Sounds like a good idea! 
But if somebody is already using virtualenvs and has some more tools expecting new virtualenvs to be right where the existing ones are, please put em there.
This IMHO will boost the acceptance of poetry!

**Comment by bertjwregeer** [comment]
> If you activate the virtualenv before you use poetry, poetry will use your existing virtual environment.

**Comment by bertjwregeer** [comment]
You said:

> respects the already existing environment.

It already does... it just doesn't support using `WORKON_HOME` as the directory to place virtualenvs. You could make `~/Library/Caches/pypoetry/virtualenvs/` a symlink to your preferred location.

**Comment by valignatev** [comment]
@cauebs I know that at least virtualenvwrapper and pipenv understand  `$WORKON_HOME`. PyCharm might as well (not sure).
I think that I didn't know about `poetry config settings.virtualenvs.path` because `poetry config --list` doesn't work for me, but it solves the issue for me entirely. Will try to look into it more closely.
Thanks!

**Comment by cauebs** [comment]
@valignatev `poetry config --list` only shows the ones you have set. Did you expect it to list the available ones? Because we were discussing that option recently and maybe you were right to expect that.

**Comment by cauebs** [comment]
Hmm... Maybe there are benefits to keeping Poetry's virtual environments separated from the rest. Python tooling and its userbase are more complex than they might seem initially. Remember:
>In the face of ambiguity, refuse the temptation to guess.

I think this is a discussion worth having, but I definitely wouldn't be ready to rule out the current approach.

**Comment by valignatev** [comment]
@cauebs Yeah, I'd expect to see the available list for `config --list` :) I've created separate #261 for this discussion, but you already saw it.

**Comment by garyo** [comment]
In case anyone's counting, I'm in the "respect `WORKON_HOME`" camp.

**Comment by kakulukia** [comment]
Well i now have auto activation of the projects .venv folder active and dont need the above, so this might be closed.

**Comment by nonZero** [comment]
With Poetry version 1.0.10 this works:

    config settings.virtualenvs.path $WORKN_HOME

> @cauebs I know that at least virtualenvwrapper and pipenv understand `$WORKON_HOME`. PyCharm might as well (not sure).
> I think that I didn't know about `poetry config settings.virtualenvs.path` because `poetry config --list` doesn't work for me, but it solves the issue for me entirely. Will try to look into it more closely.
> Thanks!
