### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#216]
I get this error while uploading my package to pypi

[HTTPError]
400 Client Error: '*' is an invalid value for Requires-Python. Error: Invalid specifier in requirement. See https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/

I tried to search for an answer, but i dont know what metadata is meant here. I added python_requires='>=2.6' to my setup.py, but that didnt change anything and also does not match the mentioned syntax. Im not sure what that means.

I get a totally different error while trying to upload via twine, so it might be a missing settings on my end - it seams that something has changed since i uploaded that last version of my package. :(

**Comment by sdispater** [comment]
How do you upload your package?

Also you do not need a `setup.py` file with `poetry` if you use both `build` and `publish` commands.

**Comment by kakulukia** [comment]
i tried to use publish and was using twine before

**Comment by kakulukia** [comment]
> Also you do not need a setup.py file with poetry if you use both build and publish commands.

So that means im missing something in my pyproject.toml?

**Comment by kakulukia** [comment]
Okay, it has something todo with the `poetry build` step. I just built it with `python setup.py bdist_wheel` and was able to upload the new version without any trouble.

Im going to investigate the results of both build tools now.

**Comment by kakulukia** [comment]
The PKG-INFO file is the one that lists the "broken" `Requires-Python: *` line.
So whats the right way to put that info into the pyproject.toml file?

**Comment by sdispater** [comment]
Poetry should not create a PKG-INFO with `Requires-Python: *`.

Let me check if I can reproduce this.

**Comment by kakulukia** [comment]
You can test that with a fresh copy of https://github.com/kakulukia/django-secrets

Well poetry should support that entry, since it’s needed for packages to no be available under older Python versions.

**Comment by kakulukia** [comment]
I just tried to read through the PEP, but i could not figure out, how the Python requirement shall be put into the toml file.

In case you @sdispater can figure that out and i have some time next week, i might help out in fixing that bug.

**Comment by sdispater** [comment]
Closing as this has been fixed for quite a while.
