### ISSUE TITLE
Does this replace poet?

### ISSUE THREAD

**Issue by ulope** [sdispater/poetry#22]
While trying to remember the exact name of this project and googling I first found your poet package which was a bit confusing.
Could you clarify what the (if any) relationship between the two is?

Also: Thanks a ton for bringing some fresh air into the python packaging world!

**Comment by sdispater** [comment]
Thanks for your interest in Poetry and your kind words!

Yes, Poetry replaces poet. This is due to the fact that I wanted to start over with a cleaner codebase.

I will add a message and the poet's README to acknowledge that it is now obsolete.

**Comment by thebigmunch** [comment]
You could also use GitHub's repository deprecation feature on the poet repository and change its description to point to poetry.

**Comment by sdispater** [comment]
The poet project has been archived and I added a line saying that it's been deprecated in favor of poetry.
