### ISSUE TITLE
Question about version string

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#220]
In my projects i have the habit of putting the version string under `<myproject>/__init__.py` as
  
    __version__ = '1.0.2'

So that its not just deco but usable from within python. Since setup.py was a Python file, i was able to just reuse that version string for the package info. With pyproject.toml not being able to execute Python, whats the best way to get my old functionality back? 
Otherwise id have to change the version by hand.

BTW: Up until now i was/am using bumpversion to update the version number, which take a list of files to update - maybe poetry could use the same technique?

**Comment by jgirardet** [comment]
you should search a little before asking many questions. there is an issue opened on this. https://github.com/sdispater/poetry/issues/144

**Comment by kakulukia** [comment]
well, i did search for version but didnt spot that issue
