### ISSUE TITLE
tox support

### ISSUE THREAD

**Issue by sobolevn** [sdispater/poetry#222]
Hi, thanks for this awesome package. It look really promising.

Here's my problem: I am using `tox` and `pyproject.toml` for my library.
When trying to use them together that's what happens:

```
» tox
ERROR: No setup.py file found. The expected location is:
  /Users/sobolev/Documents/github/mimesis-factory/setup.py
You can
  1. Create one:
     https://packaging.python.org/tutorials/distributing-packages/#setup-py
  2. Configure tox to avoid running sdist:
     http://tox.readthedocs.io/en/latest/example/general.html#avoiding-expensive-sdist
```

What is the recommended solution for this workflow? 
The only thing that I do not want to do is returning to the old `setup.py`.

**Comment by rcisterna** [comment]
Hi, I'm in the same situation here. It seems like this is a [tox issue](https://github.com/tox-dev/tox/issues/573), which depends on a [pip issue](https://github.com/pypa/pip/issues/5407).

I really hope that all this awesome tools implements **PEP-517** and **PEP-518** soon.

**Comment by sdispater** [comment]
For now, you can use `poetry` with `tox` by using something similar to what I did in `pendulum`: https://github.com/sdispater/pendulum/blob/master/tox.ini

**Comment by vberlier** [comment]
Thanks a heap I was just wondering how `tox` would work without any `setup.py`. Perfect timing!

**Comment by valignatev** [comment]
If we'd think about `setup.py` as some kind of a lock file which you never generate by hand, maybe an option for `poetry lock` which generates `setup.py` might be helpful. Of course, it doesn't work for those who want to avoid storing `setup.py` in their repo. Just brainstorming here.

**Comment by cs01** [comment]
@valignatev this was suggested in https://github.com/sdispater/poetry/issues/191

**Comment by tadeoos** [comment]
I think it would be a good idea to add the pendulum example to FAQ (or start a wiki?)

**Comment by tadeoos** [comment]
I think we can close this issue for now

**Comment by sobolevn** [comment]
Yeap, #227 solves the problem. Thanks everyone!

**Comment by mlissner** [comment]
For those arriving here, the solution mentioned in #227 is this link: https://python-poetry.org/docs/faq/#is-tox-supported
