### ISSUE TITLE
Pyproject.lock attributes needs to be sorted (in case of putting this file to a .git repo or diffing ).

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#228]
Pyproject.lock attributes needs to be sorted (in case of putting this file to a repo or making a diff ).

For example:
diff --git a/pyproject.lock b/pyproject.lock
index 58b71c9..a7f29c3 100644
--- a/pyproject.lock
+++ b/pyproject.lock
@@ -1,393 +1,393 @@
 [[package]]
-name = "atomicwrites"
-version = "1.1.5"
-description = "Atomic file writes."
 category = "dev"
-optional = false
-python-versions = "*"
 platform = "UNKNOWN"
+version = "1.1.5"
+name = "atomicwrites"
+python-versions = "*"
+optional = false
+description = "Atomic file writes."

**Comment by sdispater** [comment]
This has been fixed in version `0.11.0`
