### ISSUE TITLE
How do you setup a forked repo for developement with poetry?

### ISSUE THREAD

**Issue by tadeoos** [sdispater/poetry#229]
Hey,
@cauebs already mentioned in #203 that a contributing guide would come handy, for now I am struggling with setting up a proper developement environment. Since there is a `pyproject.toml` it makes sense to develop poetry using poetry, but when I run `poetry install` from forked repo dir I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/<truncated>/open-source/poetry/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/<truncated>/open-source/poetry/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

As you can see it gets confused with imports: the actual poetry installed on my machine (`/usr/local/bin/poetry`) starts using paths from the forked repo and hence can't find the modules which of course aren't there since we want to install them with this command...

Any ideas? Contributors - how does your setup looks like?

**Comment by cauebs** [comment]
I don't know how the existing contributors handle this, but my workflow has become:
- Clone my fork
- `poetry develop`
- `alias pt .venv/bin/poetry` and use `pt` to test

See if that works for you :)

**Comment by tadeoos** [comment]
Unfortunately `poetry develop` returns the same error. Did you have virtual environemnt already created before using any poetry commands?

**Comment by tadeoos** [comment]
I managed to hack my way out of this impass by running `poetry install` commands not from the forked repository root but from the `docs` directory... This isn't very nice solution though

**Comment by cauebs** [comment]
>Did you have virtual environemnt already created before using any poetry commands?

I believe I didn't. What error are you getting?

**Comment by tadeoos** [comment]
As I mentioned the error is _the same_ - `ModuleNotFoundError`.  It's all about pyton module import resolution...
@sdispater have you come across this problem?

**Comment by cauebs** [comment]
Ok, let me get this right: you cloned it, ran `poetry develop` and then how did you run it? Or did it fail in  the `poetry develop` stage already?
Could you show us the exact sequence of commands you're running and the output you're getting?
I don't mean to annoy you, it's just that what I suggested has really worked well for me.

**Comment by tadeoos** [comment]
It goes like this:

```bash
$ git clone ... 
$ cd poetry

$ poetry install  # not working
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/<truncated>/open-source/poetry/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/<truncated>/open-source/poetry/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'

$ poetry develop  # also not working
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/<truncated>/open-source/poetry/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/<truncated>/open-source/poetry/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'

$ cd docs  # this would work with any other directory as well

$ poetry install  # now it's working cause local `poetry` is no longer in the `$PATH`
Updating dependencies
Resolving dependencies... (34.6s)


Package operations: 49 installs, 0 updates, 0 removals
....
```

**Comment by tadeoos** [comment]
Without running any `pyenv` commands (i.e. running poetry commands without active venv) the error is the same, so I don't think it's connected.

btw I'm running on macOS High Sierra (10.13.5)

**Comment by cauebs** [comment]
How did you install poetry?

**Comment by tadeoos** [comment]
```
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
```

**Comment by sdispater** [comment]
If you install Poetry globally via the recommended installer, there should not be any issues.

If you want to test the behavior of your modification to the poetry codebase by executing the `poetry` executable you can just do `poetry run poetry`
