### ISSUE TITLE
Support --trusted-host for non HTTPS repos

### ISSUE THREAD

**Issue by BorePlusPlus** [sdispater/poetry#230]
Private repository that I'm installing from is exposed via HTTP and not HTTPS, and I can't see a way to use it with poetry.

Example:
```toml
[[tool.poetry.source]]
name = "private"
url = "http://pypi.example.com:8080/simple/"
```

```bash
$ poetry add psycopg2-binary
Using version ^2.7 for psycopg2-binary

Updating dependencies
Resolving dependencies... (0.2s)


Package operations: 2 installs, 0 updates, 0 removals

Writing lock file

  - Installing setuptools (39.2.0)
  - Installing psycopg2-binary (2.7.4)

[VenvCommandError]
Command ['pip', 'install', '--no-deps', '--index-url', 'http://pypi.example.com:8080/simple', 'psycopg2-binary==2.7.4'] errored with the following output:                                                      
Collecting psycopg2-binary==2.7.4                                                                                                                                                                                
  The repository located at pypi.example.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence  
 this warning and allow it anyways with '--trusted-host pypi.example.com'.                                                                                                                                      
  Could not find a version that satisfies the requirement psycopg2-binary==2.7.4 (from versions: )                                                                                                               
No matching distribution found for psycopg2-binary==2.7.4         
```

I have some experience with pipenv and it [supports `verify_ssl` flag](https://github.com/pypa/pipenv/blob/master/docs/advanced.rst#-specifying-package-indexes) that will result in `--trusted-host` option being added.

Is there something similar in poetry?

P.S.: How come poetry seems to be adamant on installing setuptools every time I add a package?

**Comment by guillaumerenault** [comment]
I think this feature is not yet implemented but on the roadmap iirc.
In the meantime you can add the following line after : 
https://github.com/sdispater/poetry/blob/master/poetry/masonry/publishing/uploader.py#L79

```
session.verify = 'path_to_your_bundle.crt'
```

**Comment by sdispater** [comment]
A `verify_ssl` only makes sense for a `https` url.

For standard `http` urls, I think `poetry` should use the `--trusted-host` automatically.

> How come poetry seems to be adamant on installing setuptools every time I add a package?

What do you mean exactly?
