### ISSUE TITLE
`remove` not smart enough to detect depencency type

### ISSUE THREAD

**Issue by ranisalt** [sdispater/poetry#231]
On other dependency managers, namely `npm` and `yarn` which I use the most, `remove`ing a dependency removes it from whatever dependency list it's in, be it runtime, development, peer or another dependency type, while poetry requires `remove -D <package>` to remove from dev deps.

I suggest that `remove` is made smart enough to remove the package name from any dependency list instead.

**Comment by cauebs** [comment]
What do you think would be the appropriate behaviour? 

1. Remove the specified package from both the dependencies and dev-dependencies, even if it's not present in one of them?
2. Remove it from dev-dependencies first and, if it's not present, remove from normal dependencies?
3. Same as 2, but the other way around?
4. Remove from any of the two, but ask the user in case it is present in both?
5. Always ask (I imagine this is no better than the current method)
6. Some other approach you can think of

**Comment by ranisalt** [comment]
1, it does not make sense for a dependency to be both dev and runtime as all runtime deps are also installed on development phase. Thus, the flag should be removed, or kept and ask the user if he wants to remove from dev deps instead (but not ignore).

**Comment by sdispater** [comment]
@ranisalt Sometimes you might want to specify a dependency twice: in runtime and in dev. There are some valid reasons for that, like setting the dependency with extras in development:

```toml
[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.19"

[tool.poetry.dev-dependencies]
requests = { version = "^2.19", extras = ["security"] }
```

**Comment by ranisalt** [comment]
Sure, then 4 looks better, with the flag `-D` forcing to search only on dev dependencies.
