### ISSUE TITLE
Add option to install dependencies to the system site packages

### ISSUE THREAD

**Issue by ZhukovGreen** [sdispater/poetry#234]
It is not always easy to have some packages installed inside the virtualenv + having the virtualenv inside the docker container, which only runs your app, makes no sense.

It would be nice to have an option i.e. `--system` to deploy your package right inside the system without venv.

Now solving it in a stupid way:
```Dockerfile
RUN mkdir -p /root/.cache/pypoetry/virtualenvs/phex-recutech-mcs-py3.6/lib/python3.6 
RUN ln -sf /usr/local/lib/python3.6/site-packages /root/.cache/pypoetry/virtualenvs/phex-recutech-mcs-py3.6/lib/python3.6
```

**Comment by sdispater** [comment]
You can disable the automatic creation of virtualenvs by using:

```
poetry config settings.virtualenvs.create false
```

**Comment by piotr-dobrogost** [comment]
> having the virtualenv inside the docker container, which only runs your app, makes no sense

This is common misconception. See [Deploying Python Applications with Docker - A Suggestion](https://glyph.twistedmatrix.com/2015/03/docker-deploy-double-dutch.html) or [Why people create virtualenv in a docker container?](https://stackoverflow.com/q/29146792/95735).

**Comment by ZhukovGreen** [comment]
There are some situation when using a virtualenv creates complications. For example a docker container with some global python package. In my case it was compiled from the source freecad. Exposing it to the virtualenv is a headache.

**Comment by wyl8899** [comment]
For those who find here later, the config command worked for me was:

```
poetry config virtualenvs.create false
```

**Comment by dyno** [comment]
how about use the export option?

https://python-poetry.org/docs/cli/#export

```
poetry export -f requirements.txt --output requirements.txt
pip install -f requirements.txt
```

**Comment by couling** [comment]
> > having the virtualenv inside the docker container, which only runs your app, makes no sense
> 
> This is common misconception. See [Deploying Python Applications with Docker - A Suggestion](https://glyph.twistedmatrix.com/2015/03/docker-deploy-double-dutch.html) or [Why people create virtualenv in a docker container?](https://stackoverflow.com/q/29146792/95735).
> 
> This is duplicate of issue #218

I heard you liked virtual environments so I put a virtual environment in your virtual environment so you can isolate while you're isolated.

More seriously: calling this a "misconception" is overstated.  There can be contexts where a virtual-env in a docker container is useful but many (and arguably most) of them are the result of an anti-pattern.

The most common anti-pattern to make them useful is breaking the "one app per container" rule.  If your container is supposed to just run your python app then the "system" packages should be redundant and just useless files in the image. This redundancy _should_ mean there's no need for a virualenv; you should just be able to clobber the system packages.

**Comment by clafoutis42** [comment]
> how about use the export option?
>
> https://python-poetry.org/docs/cli/#export
>
> poetry export -f requirements.txt --output requirements.txt
> pip install -r requirements.txt

The problem with this is that the application is not properly installed as a package. You only install the requirements.
For most applications this is not a problem, but for applications with various entrypoints you might want to install it to the system.
