### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by tadeoos** [sdispater/poetry#240]
I think it would be nice to add some config options to `.coveragerc` so the coverage could be measured consistently across forks. Maybe also add Poetry to [coveralls](https://coveralls.io/) and add a coverage badge to README file? @sdispater it's your decision, IMHO it's a great practice.

I ran a test suite with the following config:
```ini
[run]
branch = True
source = poetry
```
And got **67%** (it raises up to 70% with `branch = False`) of the code covered by our tests.
It's not great. **We definietly need more tests.**

**Comment by abitrolly** [comment]
What was the consensus on this? I see empty https://github.com/python-poetry/poetry/blob/master/.coveragerc and nothing on SonarCloud, Codecov and Coveralls.

* https://coveralls.io/github/python-poetry/poetry
* https://codecov.io/gh/python-poetry/poetry
* https://sonarcloud.io/dashboard?id=python-poetry
