### ISSUE TITLE
Install specific groups of deps?

### ISSUE THREAD

**Issue by alok** [sdispater/poetry#244]
I'm working on a project where there are multiple `requirements.txt` files that are meant to be mutually exclusive and deployed in different environments (one file has only a single dependency in it since it's meant to run a scheduler package in a constrained environment). I was wondering if poetry supported that, where the TOML file would look something like

```
[tool.poetry.dependencies]
...
[tool.poetry.deps1-dependencies]
...
[tool.poetry.deps2-dependencies]
...
```
and you would do something like `poetry install -E deps1` and it would install only the set in `deps1` without touching the base set of dependencies used elsewhere.

**Comment by sdispater** [comment]
What you want to use in this case are [extras](https://poetry.eustace.io/docs/pyproject/#extras)

Dependencies sections other than `dependencies` and `dev-dependencies` will likely not be supported.
