### ISSUE TITLE
Support PyPI trove classifiers

### ISSUE THREAD

**Issue by monkeez** [sdispater/poetry#25]
Basically this https://github.com/sdispater/poet/issues/5

It'd be nice to detect as many things automatically, but somewhere in `pyproject.toml` to manually add them would also be useful.

**Comment by sdispater** [comment]
I agree. For now, only Python trove classifiers are set automatically.

And while I can set the license ones automatically as well, having a section where developers can set them is actually a good idea.

**Comment by sdispater** [comment]
This is supported in the latest release (`0.7.0`). See https://poetry.eustace.io/blog/poetry-0-7-0-is-out.html#support-for-trove-classifiers
