### ISSUE TITLE
'packages' are unexpected option

### ISSUE THREAD

**Issue by markovendelin** [sdispater/poetry#254]
I have a project with name `aaa.bbb` and the directory structure in agreement with it:

```
-- bbb
   |
   - pyproject.lock
   - aaa
      |
      - bbb
...
```

So, I thought to specify packages (https://poetry.eustace.io/docs/pyproject/#packages). Unfortunately, it seems to be unsupported:

```
> poetry build                                                                
                                                                     
[InvalidProjectFile]                                  
Additional properties are not allowed ('packages' was unexpected)  
                                                                     
build [-f|--format FORMAT]
```

with corresponding section in toml file:

```
packages = [
         { include="aaa.bbb", from="aaa/bbb" }
]
```

Would be of great help to learn how to specify such package and whether `packages` keyword is supported already.

**Comment by sdispater** [comment]
It's supported in the preview release `0.11.0a4`, and will be available officially when the stable release is out.

**Comment by markovendelin** [comment]
After passing some barriers induced by strong recommendation of use of `--user` with pip on Gentoo, I managed to get 0.11.0a4 installled (thanks to https://github.com/sdispater/poetry/pull/146). 

Now, packages is accepted, but poetry is still rather unhappy:

```
[NameError]    
name 'base' is not defined
```
BTW, I looked through earlier issues and couldn't find any that would cover my use-case - having `aaa.bbb` in the name and sources in `aaa/bbb` subfolder. I guess, it would be helpful to have it covered in the docs as well, when we get there.

Thank you very much for your work on it and I am looking forward to distribute our software with its help!

**Comment by markovendelin** [comment]
It fails at https://github.com/sdispater/poetry/blob/develop/poetry/masonry/utils/package_include.py#L39 and that should probably be

```
            raise ValueError("{} does not contain any element".format(self._base / self._include))
```

As soon as I replace the current line with it, I get something like 

```
[ValueError]                                                          
[...]/aaa/bbb/aaa.bbb does not contain any element
```

So, I think I am back again with missing example on packages with the names in form 'aaa.bbb'
