### ISSUE TITLE
GIT Dependency Infinite Loop

### ISSUE THREAD

**Issue by giovannibelzoni** [sdispater/poetry#259]
If I give a dependency a key that doesn't match the package name in `setup.py`, it will loop indefinitely at `poetry/mixology/version_solver.py:77`, outputting the `selecting` message like so:

`my-package/setup.py`
```
setup(
  package_name='package', # Note: differs from key 'my-package' in pyproject.toml
  version='0.1',
  ...
)
```

`my-main-project/pyproject.toml`
```
...
my-package = { git = "https://github.com/belzoni/my-package", branch = "master" }
...
```

`$ poetry lock -vvv` 
```
...
1: selecting my-package (0.1 6fb5254)
1: selecting my-package (0.1 6fb5254)
1: selecting my-package (0.1 6fb5254)
...
```

However, if I change `package_name='my-package'` in `setup.py`, all is good. Leaving this here as a bug report for anyone else with this problem.

**Comment by bertjwregeer** [comment]
How do you expect poetry to know that `my-package` is satisfied by `package`? It should likely not loop forever, but it feels like this is somewhat expected.

**Comment by sdispater** [comment]
The name of your dependency must match the name of the package you are trying to install. This is a requirement for git, file and directory dependencies.

But like @bertjwregeer said, this should not cause an infinite loop but rather raise an error to warn the user that there is something wrong.

**Comment by giovannibelzoni** [comment]
I agree. I was a bit dubious calling it a 'bug', and was going to suggest it be explicitly documented. But also, yes, it shouldn't fail in this way.

**Comment by sdispater** [comment]
The infinite loop should no longer be a thing in the latest release. Poetry will now warn you about the package name difference.
