### ISSUE TITLE
Show all possible configuration options with CLI

### ISSUE THREAD

**Issue by valignatev** [sdispater/poetry#261]
Hi!
When I do `poetry config --list`, poetry shows no output. 

I've tried to dig a little bit, and found out that I have an empty `~/.config/pypoetry/config.toml` which poetry probably created during the installation. I also found that `--list` reads this file and tries to get config variables from there.

So it seems like an expected behavior, but it's very unintuitive. How about showing the list of the possible configuration values without the need to go to the documentation site or compiling docs myself? What do you think?

**Comment by cauebs** [comment]
All available settings are now documented on [this page](https://poetry.eustace.io/docs/configuration/), but I think you shouldn't have to leave the terminal to see them, so I agree with you.
Now, we have to discuss precisely _how_ we're going to do this. Perhaps `--list` shows all available settings and `--show` shows the ones you've set? Or should we try to leave `--list` unchanged?

**Comment by valignatev** [comment]
Yeah, eventually I found the docs section inside the web site, but not leaving the terminal would be great.
I think that approach of showing available options with their values (defaults in case they weren't set yet) is the best one and multiple existing tools are doing that. Git is one of those

I'm talking about something so you can do `poetry config --list > conf.toml`. And maybe it worth writing them explicitly in the default config file as well.
What do you think?

**Comment by cauebs** [comment]
Version 0.11 was just released and this feature is in it ;)

**Comment by valignatev** [comment]
Great! Much more helpful :tada:
