### ISSUE TITLE
settings.virtualenvs.path can't be configured via CLI

### ISSUE THREAD

**Issue by riverfr0zen** [sdispater/poetry#267]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

At https://poetry.eustace.io/docs/configuration/ the documentation describes the 'settings.virtualenvs.path' as an available setting that can be configured with the `config` command.

However, running the following command results in failure:
```
poetry config settings.virtualenvs.path 'build/venvs'

[ValueError]                         
Setting settings.virtualenvs.path does not exist  
                                                    
config [--list] [--unset] [--] <key> [<value>]...
```
The following command works within the same installation:
`poetry config settings.virtualenvs.in-project true`

Is the above setting no longer supported or not configurable via the `config` command?

I've seen other issues discussing some issues with setting of virtualenvs, but none of them indicates clearly whether this particular setting is supported or not. The documentation implies that it is not  different from any other setting.

Encountering this with Poetry 0.10.3 on Ubuntu 18.04 LTS

**Comment by cauebs** [comment]
Could you update Poetry to 0.11 and try again? :)

**Comment by riverfr0zen** [comment]
Nice, works as expected now. Thanks.

**Comment by AIGeneratedUsername** [comment]
`poetry config settings.virtualenvs.in-project true` on Poetry version 1.1.12 gives the same error:

>  `Setting settings.virtualenvs.in-project does not exist` 

(Python 3.10)
