### ISSUE TITLE
interactive install breaks with GNU coreutils installed on macOS

### ISSUE THREAD

**Issue by alok** [sdispater/poetry#269]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.12
- **Poetry version**: latest pip release

## Issue

If I run `poetry init` and attempt to add packages via the search feature, I get `stty: 'standard input': unable to perform all requested operations`.

Googling gives [this](https://github.com/alexch/rerun/issues/62) as the reason. GNU coreutils `stty` clashes with `/bin/stty` on macOS and breaks interaction.

On macOS, perhaps `/bin/stty` should explicitly be used?

**Comment by estysdesu** [comment]
This is still an issue. Not seeing any resolution.
