### ISSUE TITLE
Build from locked dependencies

### ISSUE THREAD

**Issue by uSpike** [sdispater/poetry#271]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I have a need to deploy applications with a fixed set of dependencies, basically the contents of `pyproject.toml`.  The end goal is to be able to `pip install` these applications each into a separate environment via `pipsi` and be able to guarantee every install is the same.

I realize this is not a very common use case.  Would there be interest in having some way of using the contents of `pipfile.lock` to populate dependencies in the `wheel` and `sdist` outputs?  Possibly a flag like `poetry build --from-lock`?

**Comment by cauebs** [comment]
Now that I think of it, maybe we need a way to revert changes to `pyproject.toml` by reading the lock file. Would that solve your problem?

**Comment by sdispater** [comment]
This is not the intended use case for Poetry. If you need to build from pinned dependencies you should pin them in the `pyproject.toml` file.
