### ISSUE TITLE
Is working on branches with differing requirements possible?

### ISSUE THREAD

**Issue by hwine** [sdispater/poetry#272]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I'm in the process of testing poetry for my python work. The one stumbling block I've hit is how to approach working on a different branch that has different requirements. (For example, working on a bug fix for the current version while still developing a new feature using different version of some dependencies.)

My workflow for this, is to clone a separate copy of the repo in a different directory for the bug fix. (Tests can take hours to run.) However, poetry appears to only allocate one virtualenv for the project, based on the ``name`` field of ``pyproject.toml``.

How can I get poetry to maintain different virtualenvs for the same project?

**Comment by cauebs** [comment]
Ok, to tackle this _today_, you could remove the virtual environment and let poetry recreate it after you checkout to another branch. The problem, of course, is that you'd have to reinstall everything, which may take some time even if everything's cached.

In the future we can add a setting like `settings.virtualenvs.per-branch`, which would default to false. That would require some work, but it might be justifiable if it's a commonly wanted feature and if the alternatives are not very good. I'll leave this decision to @sdispater.

If we get a greenlight, I can give this a go in a few days, after my finals.

**Comment by roywes** [comment]
In the given scenario, where a separate clone is made for the different tasks, poetry can be directed to create the virtualenv in the project using the [settings.virtualenvs.in-project](https://poetry.eustace.io/docs/configuration/#settingsvirtualenvsin-project-boolean) configuration option. Each clone will have it's own virtualenv when this is set to true.

The configuration option is global though, so it may impact all your other projects.

**Comment by hwine** [comment]
@roywes  - thanks -- I'd missed that one. Disk space is cheap. I'll try using that. Fewer "foot guns" in that scenario, I think.

@sdispater - sorry, that doesn't help my OP. I need to have two branches active on the same machine at the same time (from different checkouts, of course).

**Comment by glehmann** [comment]
I there a strong reason to put the virtualenvs in a global space? It would seem more logical to put it in the current project's directory — something like a `.venv` directory. That would make possible to work on several versions of the same project. Not sure how poetry handle the deletion of the virtualenvs when the a project is destroyed — it may help with that too.

An alternative is to include a hash of the project path in the virtualenv dir name: `~/.cache/pypoetry/virtualenvs/{name}-py{pyversion}-{path_hash}`

**Comment by cauebs** [comment]
@glehmann You can set `settings.virtualenvs.in-project` to `true` in order to have them be created in the root of the project, just like you suggested :)

**Comment by glehmann** [comment]
It works for me! I guess it should work too for the op :)

For the record this is a setting global to all the projects that is activated with `poetry config settings.virtualenvs.in-project true`.

Is there a reason why this is not the default? I see a comment in #108 that list several reasons to make it the default. This use case makes one more reason.

**Comment by hwine** [comment]
Oops -- it **DOES** work for the OP! Closing

**Comment by famura** [comment]
Even though this issue has been solved more than two years ago, I would like to point to poetry's `--remove-untracked` option.
A possible workflow is:

`git checkout branch_you_want_to_work_on`
`poetry shell`
`poetry update`
`poetry install --remove-untracked`

This way your venv only contains the packages specified in the poetry.lock file of the branch you witched to.
