### ISSUE TITLE
poetry install --develop does not install scripts in venv/bin

### ISSUE THREAD

**Issue by jbarlow83** [sdispater/poetry#283]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS High Sierra
- **Poetry version**: 0.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jbarlow83/8e3cd45139e5ba60ebcb0d218371fa17

## Issue

When a package specifies a script and the package is installed in develop mode, the script should be placed in the virtualenv's bin directory, as `pip install -e .` would do. `poetry install --develop <package>` does not install scripts.

**Comment by nchammas** [comment]
Does `poetry develop` do what you want? I had a similar issue in #311 and it turned out I just needed to use that command instead of `poetry install --develop`.

**Comment by jonchu** [comment]
I'm not sure why this was closed? I'm running into the same issue and don't see an answer to how to get poetry to install scripts.

**Comment by ameier38** [comment]
If you have a package with the same name as your poetry project then poetry will install the scripts with `poetry install`

```
[tool.poetry]
name = "my-package"
version = "0.1.0"
description = "My package"
```
```
my-package
├── my_package
│   ├── __init__.py
```

**Comment by braincore** [comment]
Just confirming that this behavior persists.
