### ISSUE TITLE
automatic version à la python-versioneer

### ISSUE THREAD

**Issue by glehmann** [sdispater/poetry#284]
We are using https://github.com/warner/python-versioneer to version our tools, and it's been working very well so far. Now we are looking into using poetry, but would like to keep a versioneer like behavior that doesn't seem to be possible at this time.

Basically, versioneer automatically generates the package version number based on the current git commits and tags of the package repository. It uses the information from `git describe` to generate the version, and apply a few changes to it to be compatible with python versioning scheme and include some useful info.

For example, in our repository, we have:

~~~
> git describe
v0.11.0-136-g2f043654
> mytool --version
0.11.0+136.g2f043654.dirty
~~~

and `python setup.py sdist` generates a package called `mytool-0.11.0+136.g2f043654.dirty.tar.gz`.

Any chance we can make that happen in poetry?

**Comment by seglberg** [comment]
This is whats holding us back from switching to Poetry as well. We love versioneer!

**Comment by whoiswes** [comment]
I do something similar with setuptools and some homegrown code to programatically determine the version (similar to versioneer).  Having the ability to keep such functionality would be ideal.

**Comment by psafont** [comment]
Related requests: https://github.com/sdispater/poetry/issues/185 https://github.com/sdispater/poetry/issues/140

**Comment by webknjaz** [comment]
Let's close this in favor of #140 + #672 (demo discussion) so that it would be 1 single place with info, not 3 issues asking the same :)
