### ISSUE TITLE
Configurable `poetry new` directory tree

### ISSUE THREAD

**Issue by apnewberry** [sdispater/poetry#287]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I'm looking at poetry, but haven't used it yet. One thing that I noted in the docs is the `poetry new` package structure.

https://poetry.eustace.io/docs/cli/#new produces one of these:

```
my-package
├── pyproject.toml
├── README.rst
├── my_package
│   └── __init__.py
└── tests
    ├── __init__.py
    └── test_my_package

my-package
├── pyproject.toml
├── README.rst
├── src
│   └── my_package
│       └── __init__.py
└── tests
    ├── __init__.py
    └── test_my_package
```

I like my `tests/` to be _inside_ the package directory so all the code is installed and testable by the user. 

```
project/
├── project
│   ├── __init__.py
│   └── tests
│       ├── __init__.py
│       └── test_project.py
├── pyproject.toml
└── README.rst
```

Could this option be supported,  or perhaps a more general configurable layout from `poetry new`?

In case it's helpful, here are some discussions of the style I prefer:
- http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html
- http://blog.habnab.it/blog/2013/07/21/python-packages-and-you/

**Comment by apnewberry** [comment]
Looks like lots of the people in https://github.com/sdispater/poetry/issues/34 are also referring to this workflow, where you'd have the package installed while developing it.

**Comment by sdispater** [comment]
I don't think Poetry will ever support this project structure in the `new`. Poetry tries to standardize a lot of things about packaging and the structure is one of those things. I personally don't think you should bundle your tests with your package.

Now, don't get me wrong, you can still structure your code like this but you will have to do it manually.

Another point in favor of having the `tests` outside the package directory is that the most popular Python projects and libraries do it (django, flask, requests) and following them, at least in part, should help standardize good practices.
