### ISSUE TITLE
curl on system-wide python on Mac never install completely to Python3

### ISSUE THREAD

**Issue by patarapolw** [sdispater/poetry#290]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: MacOSX 10.13.4, MacBook Air 11" (Early 2015)
- **Poetry version**: 0.11.2

## Issue
Running `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python` and `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3` outside or inside virtual environment gives a `poetry` that doesn't work. When `pip3 freeze`, too few packages are shown...

However, using `pip3 install poetry` in system-wide, or `pip install poetry` inside the virtual environment in PyCharm works perfectly.

I also noticed that PyCharm detected the wrong pip version.

**Comment by zmitchell** [comment]
When you say that poetry doesn’t work, what do you mean? Does poetry show an error when you run a particular poetry command?

**Comment by patarapolw** [comment]
BTW, how do uninstall poetry (completely)? I want to replicate the error message (and clean my system Python2 and Python3).

**Comment by cauebs** [comment]
@patarapolw `pip uninstall poetry`, if you installed through `pip` or the official `get-poetry.py` script.

**Comment by patarapolw** [comment]
Cannot replicate the error for now, but I believe:-

> pip uninstall poetry, if you installed through pip or the official get-poetry.py script.

I might have to `pip freeze | xargs pip uninstall -y`, but I don't know of the side-effects, if I do it on system-wide Python.

**Comment by sdispater** [comment]
The new installer is out which fixes a lot of installation issues.
