### ISSUE TITLE
poetry new project with unittest instead of pytest?

### ISSUE THREAD

**Issue by Terrabits** [sdispater/poetry#299]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
My question is related to #150 

Does `poetry new` support other testing frameworks? I prefer unittest.

Or, if not, is there a way to exclude the `test/` directory and the `pytest` dev dependency when creating a new project?

It doesn't look like it from the docs, but I figured I'd ask. Thanks!

**Comment by tadeoos** [comment]
I believe that since the 0.11 version pytest is no longer added by default, cf. #150

**Comment by cauebs** [comment]
@tadeoos `pytest` is no longer added by default on `poetry init`, but it still is on `poetry new`.
