### ISSUE TITLE
`poetry shell` should modify PS1 to show that we're now inside Poetry's managed venv

### ISSUE THREAD

**Issue by nchammas** [sdispater/poetry#308]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

It's a minor user experience thing, but basically after running `poetry shell` you get no persistent indication that you're inside Poetry's managed virtual environment:

```sh
$ poetry shell
Spawning shell within /Users/user/Library/Caches/pypoetry/virtualenvs/flintrock-py3.6
<some commands later>
$ echo "Am I still inside Poetry's venv? Not sure..."
```

Compare this to what happens when you `source venv/bin/activate` with your vanilla Python virtual environment. `PS1` is modified so that you always know where you are when running commands.

```sh
$ source venv/bin/activate
<some commands later>
(venv) $ echo "I'm still inside a venv."
```

It would be nice if Poetry did something similar to signal to the user that they are inside a virtual environment managed by Poetry. Maybe something like `(poetry-py3.6) $ `. And after exiting the shell with `Ctrl + D` everything goes back to the way it was.

**Comment by cauebs** [comment]
The problem with changing the prompt is that it works differently in each shell. We would need a dozen separate implementations... Has anyone got any better ideas?

**Comment by nchammas** [comment]
Indeed, looking at [virtualenv's implementation](https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/), it seems there is a bit of boilerplate to maintain for the various shells. I can't judge if it would be worth the maintenance burden in the long run, but at least we have a readily available reference implementation if we want to add something like this to Poetry.

I suppose an alternative we could go with is to simply advocate that people rerun `poetry shell` if they are ever unsure whether or not they are in a venv. Poetry will tell you if one is already active.

**Comment by nchammas** [comment]
Rerunning `poetry shell` is a good enough solution for me, so I'm going to close this issue.
