### ISSUE TITLE
`poetry init` should accept the long license name in addition to the abbreviation

### ISSUE THREAD

**Issue by nchammas** [sdispater/poetry#310]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

A minor quality-of-life improvement to `poetry init` would be to accept the long name for a license, e.g. "Apache License 2.0", in addition to the abbreviation, "Apache-2.0". It looks like Poetry [already tracks both variations](https://github.com/sdispater/poetry/blob/af8f86cda703144e9261b700d3165433aa2d3603/poetry/spdx/data/licenses.json#L147-L148).

```
$ poetry init

This command will guide you through creating your poetry.toml config.

Package name [flintrock]:
<snipped>
License []: Apache License 2.0
 Invalid license id: Apache License 2.0
License []: Apache-2.0
<success>
```

The reason I tried the longer version of the license name first, and the reason I think it would make sense for Poetry to accept that variation, is because that's what I had in my call to `setuptools.setup(license=...)` in my `setup.py`. I imagine other users might try the same and try to work through `poetry init` by copying things out of their `setup.py`.

**Comment by brycedrennan** [comment]
Thanks for bringing this up. It's been [addressed](https://github.com/sdispater/poetry/commit/53c22155e59d9efa4979311aa66f40cf39270ced) now in the upcoming version.
