### ISSUE TITLE
Add a note discussing installing poetry with pipsi

### ISSUE THREAD

**Issue by simonpercivall** [sdispater/poetry#318]
As a Python dev, installing tools like `poetry` with `pipsi` makes for a very convenient experience. However, the interaction between the currently available `pipsi` on PyPI and how `poetry` makes broken virtualenvs. This has been noted in a couple of `poetry` GitHub issues already.

A note in the `poetry` documentation, that describes installing via `pipsi`, and how to handle the resulting broken envs, would be helpful for users wanting to install that way. While partially off topic (since the problem really isn't with `poetry`) it adds real value to the documentation.

See also:

* https://github.com/sdispater/poetry/issues/59
* https://github.com/sdispater/poetry/issues/169

**Comment by NotAFile** [comment]
Just got bit by this too. A note would be great. Or even better, fixing the relevant issues.

**Comment by jgirardet** [comment]
See #378

**Comment by sdispater** [comment]
The documentation has been updated. But note that installing Poetry with pipsi is not the recommended method.
