### ISSUE TITLE
How do you pip install package maintained with poetry from github?

### ISSUE THREAD

**Issue by tkossak** [sdispater/poetry#321]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
How do you pip instal package (maintained with poetry) from github? When I want people to try latest development version from github, they can't install it in their venv using `pip install git+URL` because repo doesn't have `setup.py` file. What's the best solution here - should I add `./dist/*` to github, manually create `setupy.py` or something else?

**Comment by gmacon** [comment]
Once [pip's PEP-517 support](https://github.com/pypa/pip/issues/5407) is available, this ought to work provided that the project has the correct information in its pyproject.toml. This should work (but I haven't tried it):

```toml
[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
```

Until then, I might consider publishing prerelease wheels to PyPI from an automated build system.

**Comment by azag0** [comment]
PEP-517 support was just [merged](https://github.com/pypa/pip/pull/5743) into PIP. Can be probably expected in the 19.0 release in January.

**Comment by jhrmnn** [comment]
Pip 19.0 was [released](https://pip.pypa.io/en/stable/news/#id4) on 22 January 2019, and I have just successfully Pip-installed a Poetry-managed Python package from a git repository without `setup.py`. So I guess this issue can be closed.

**Comment by yisraeldov** [comment]
@jhrmnn Can you tell he how you got this to work ? 

I'm using pip 19.2.2 and I can't seem to install my poetry project using pip

```
pip install -e git+git@gitlab.com:yisraeldov/gpiozero-shiftregister.git#egg=gpiozero_shiftregister
```

It is still trying to run `setup.py`

```

...
 FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/hardware/driver/.venv/src/gpiozero-shiftregister/setup.py'
```

Thanks for any help

**Comment by jhrmnn** [comment]
That's because you're trying to do an editable install (`-e`). As far as I know, that doesn't really make sense for a package installed from a remote repository. Without `-e`, the installation works.

**Comment by yisraeldov** [comment]
@jhrmnn 

> That's because you're trying to do an editable install (`-e`). As far as I know, that doesn't really make sense for a package installed from a remote repository. Without `-e`, the installation works.

Thanks but why doesn't it make sense to do an editable install? That is exactly what I want to do. Clone the required library from git  and link it to my current project? I want to be able to push back any changes I have made to the required library.

From the [pip documentation](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)

> VCS projects can be installed in editable mode (using the --editable option) or not.

Also 
> -e, --editable <path/url>
> Install a project in editable mode (i.e. setuptools “develop mode”) from a local project path or a **VCS url**

Thanks for any help.

**Comment by jhrmnn** [comment]
Ah sure. I do that often too, but I usually clone the repository manually in my project, because I want to track it, and Pip-install it from the path (`pip install -e <local path>`). Anyway, what you describe cannot be done at the moment, as far as I know. PEP517 has no support for editable installs. If you manually clone your repo, and try to to Pip-install it locally, you will get the following error message from Pip:

> File "setup.py" not found. Directory cannot be installed in editable mode: \<path>/gpiozero-shiftregister
> (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by yisraeldov** [comment]
@jhrmnn Ok thanks! So how would one go about working on a project and a required library simultaneously ad I described above? Is there a way to do this using `poetry` and not `pip` ? 

This seems like such an obvious use case.

**Comment by jhrmnn** [comment]
Yes, there is. Essentially, it needs to be Poetry all the way up. In the parent project's `pyproject.toml` under `tool.poetry.dependencies`, you then have something like

```
<package> = { path = "<path>", develop = true }
```

The `develop` option tells Poetry to install it in editable mode. I've never tried with packages installed from a repository (`git` instead of `path`), but that should presumably work too.

**Comment by yisraeldov** [comment]
@jhrmnn Thanks, I should be migrating my project to poetry any way!

**Comment by alexmojaki** [comment]
@jhrmnn this seems to work for temporarily setting up the editable link, but I can't have a line like that permanently in pyproject.toml for a deployed package. How do I implement this in practice? Do I just have to remember to edit the toml file every time I rerun poetry lock and install so that I don't break the link?

**Comment by jhrmnn** [comment]
What do you actually want to achieve? For a deployed package, I guess you don't used editable installs, and then you can install a Poetry-managed package from a Git repository with the usual

```
pip install git+https://...
```

**Comment by alexmojaki** [comment]
My case doesn't actually involve git or github, so I guess maybe this is the wrong place to ask. I'm just trying to understand how to work with editable installs.

I am developing two projects, call them A and B, both using poetry. A depends on B.

In `A/pyproject.toml`, I will typically have a line like:

    B = "*"

under dependencies for a sensible deploy.

Now I want to locally make a change to B and see what effet this has on A without deploying. Basically the usual use case for `pip install -e`, but that command doesn't work.

I can follow these steps:

1. Change the line above to:

    B = { path = "../A", develop = true }

2. Run poetry lock and install to establish the link in the virtualenv.
3. Change pyproject.toml back to the 'correct' state.
4. Run poetry lock again to similarly fix the lock file.

But this is far from ideal. It becomes a mess if dependencies change and I have to remember to follow all these steps to preserve the link.

Is there a better option for a workflow in practice?

**Comment by EliaSchiavon** [comment]
Hi guys, suppose to build the package and publish it in GitHub release, is it possible to pip install a specific package from GitHub releases? I use Windows PowerShell. Thank you.

**Comment by neersighted** [comment]
You can add a VCS dependency. Please see the docs at [python-poetry.org](https://python-poetry.org), and open a Discussion or join Discord for help if you need it -- this closed issue is not a good venue for it as we are generating notifications for many users.
