### ISSUE TITLE
Run a module without any functions

### ISSUE THREAD

**Issue by jeremejevs** [sdispater/poetry#322]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I'm writing a simple one-off script, without any functions, and I'd like to run it through Poetry, in its virtual environment. However, it appears this currently isn't possible, as Poetry expects a callable:

https://github.com/sdispater/poetry/blob/af8f86cda703144e9261b700d3165433aa2d3603/poetry/console/commands/run.py#L35-L37

My Python is rusty, so maybe there's a way around this (which makes it a documentation concern), but if there isn't, I suggest adding a quick heuristic, checking for the presence of a colon, and just executing `import_module('{}')` instead of `import_module('{}').{}()` otherwise.

**Comment by cauebs** [comment]
This was proposed in #241 and implemented in #304. While it's waiting to be merged (or even rejected), you can just wrap your code in a function and call it immediately after that.

If that other proposal fits your needs as well, consider closing this one, just to keep all the discussion in one place ;)

**Comment by jeremejevs** [comment]
Thanks for the links! Haven't seen those.

I haven't tried the PR, but it seems it's about distribution, not running? I don't think it'll make `poetry run main` work with this `pyproject.toml`:

```toml
[tool.poetry.scripts]
main = { path = "main" }
```

And this `main.py`:

```python
print("Hello world!")
```

Or am I missing something?

**Comment by cauebs** [comment]
It allows you to specify not just entry points (python functions), but any script, by setting its path.
```toml
[tool.poetry.scripts]
main = { path = "main.py" }
```
```shell
~/project $ poetry run main
```

**Comment by jeremejevs** [comment]
Okay, sorry, wasn't evident from the PR's diff. Last question, is it run inside Poetry's virtual environment?

**Comment by cauebs** [comment]
I'm not sure, really. I haven't played much with that fork. But I still think you should just wrap it in a function, hahah

**Comment by jeremejevs** [comment]
Have already done that, of course :smile: Not a fan of wasting horizontal space for nothing though. Just checking whether that PR covers my usecase before closing.

**Comment by RaptDept** [comment]
Thanks for the clarification! I wanted to run a script directly, too, but I wasn't aware of the `path` parameter for `tool.poetry.scripts`. I don't think it's documented yet.

**Comment by cauebs** [comment]
@RaptDept Maybe it's not as visible as it should, but it's there: https://poetry.eustace.io/docs/pyproject/#scripts

**Comment by RaptDept** [comment]
Oh, I misunderstood. I didn't realize the `path` feature was still in a pending PR.

**Comment by dimaqq** [comment]
I'm still confused how to achieve what OP wanted or if it's even possible.
The docs are so skimpy, they are hardly helpful 😭 
If someone knows, please shed some light 💡

**Comment by wohali** [comment]
It's not ready yet, but there's 2 things coming (maybe?) that may help:

* https://github.com/python-poetry/poetry/issues/1132
* https://github.com/python-poetry/poetry/issues/2310#issuecomment-1803757408
