### ISSUE TITLE
Cannot add grpcio

### ISSUE THREAD

**Issue by a-musing-moose** [sdispater/poetry#328]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 0.11.2
- **Python version**: 3.6.5

## Issue

When trying to add `grpcio` using `poetry add grpcio` I expect it it install `grpcio`. Instead I get a resolver error:

```
Using version ^1.13 for grpcio

Updating dependencies
Resolving dependencies... (0.2s)
                                                                                                       
[SolverProblemError]                                                                    
The current supported Python versions are 3.6.5                                                      
Because no versions of grpcio match >1.13,<2.0                                                       
 and grpcio (1.13.0) depends on futures (>=2.2.0), grpcio (>=1.13,<2.0) requires futures (>=2.2.0).  
Because futures (3.2.0) requires Python >=2.6, <3                                                    
 and no versions of futures match >=2.2.0,<3.2.0 || >3.2.0, futures is forbidden.                    
Thus, grpcio is forbidden.                                                                           
So, because whodat depends on grpcio (^1.13), version solving failed.                                
                                                                                                       
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

Looking at the `setup.py` for `grpcio` the only reference to the failed dependency `futures` is inside a `if not PY3` block (https://github.com/grpc/grpc/blob/v1.13.0/setup.py#L281), so should not actually form part of the requirements as far as I can see.

I'm not sure why the resolving is still seeing the `futures` dependency.

**Comment by sdispater** [comment]
Declaring Python version specific packages is no longer the recommended way and it should use the [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) for this purpose.

Poetry never executes the `setup.py` file for security reasons and as such relies on the package metadata available in the JSON API: https://pypi.org/pypi/grpcio/json

There, `futures` is declared as a non-conditional dependency and as such is picked up by Poetry.

The issue should be reported upstream.

**Comment by a-musing-moose** [comment]
Thanks for the explanation Sébastien. I'll do some research and report upstream.
