### ISSUE TITLE
Pinned python version will generate invalid python_requires in setup.py

### ISSUE THREAD

**Issue by ciarancourtney** [sdispater/poetry#329]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 0.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ciarancourtney/1601a961ee6bf02069f783f0513d38c8

## Issue

Probably more specific to private applications, but if you pin python version to say "3.6", you will get the following error on pip installing a sdist

    ubuntu@ciaran:~/test_poetry$ venv/bin/pip install dist/mycode-2018.9.tar.gz 
    Processing dist/mycode-2018.9.tar.gz 
      Installing build dependencies ... done
        Complete output from command python setup.py egg_info:
        error in mycode setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '3.6'

"=3.6" produces same result

PKG-INFO seems fine

P.S. are equal symbols redundant in pinned dependency listings? And is there any way to make strictly pinned the default semantics through cli/config?

**Comment by sdispater** [comment]
This should now be fixed.
