### ISSUE TITLE
Code copy-pasted from Twine without Apache License source attribution

### ISSUE THREAD

**Issue by pirate** [sdispater/poetry#33]
Might want to provide proper Apache License source attribution in your README for the code copied from Twine (and any other copy-pasted code in the codebase):

https://github.com/sdispater/poetry/blob/master/poetry/masonry/publishing/publisher.py#L257
https://github.com/pypa/twine/blob/master/twine/commands/upload.py#L149

Hat-tip to @brainwane for pointing this out!

**Comment by sdispater** [comment]
Sorry about that. It's actually a leftover of an early implementation that was using twine.

I remove it since I no longer needed it anyway.

Thanks for pointing this out.

And, again, sorry about that but know there were no bad intentions here.
