### ISSUE TITLE
Issue during the installation of Instagram-py

### ISSUE THREAD

**Issue by dttfrancesco** [sdispater/poetry#330]
Hello guys I have 1 issue during the installation of instagram-py
this is the full line:
`sudo pip install instagram-py
Collecting instagram-py
  Using cached https://files.pythonhosted.org/packages/c8/96/9a42a1f49c6710c52bffb474e6c966247cfabb3b0ec7f3a1f770d412444e/instagram-py-2.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ZdrsrO/instagram-py/setup.py", line 13, in <module>
        from InstagramPy import __version__
      File "InstagramPy/__init__.py", line 10, in <module>
        from .InstagramPyCLI import InstagramPyCLI
      File "InstagramPy/InstagramPyCLI.py", line 138
        end='')
           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in `/tmp/pip-install-ZdrsrO/instagram-py/`

I don't know what to do. this is the video from where I'm taking instructions  [https://youtu.be/KZEcFn3Z5L0](url)  (I don't want to hack anyone, I want to install it because I like penetrations systems)

**Comment by sdispater** [comment]
This issue has nothing to do with Poetry.

You are likely trying to use a version of instagram-py that is not compatible with your current Python version.

**Comment by dttfrancesco** [comment]
oh yeah... i didn't saw it sorry

**Comment by dttfrancesco** [comment]
Thank you very much. My python version is the latest, that program needs 3.5 or 3.4 if I good remember
