### ISSUE TITLE
Venv python on 3.6.5 and not 3.7

### ISSUE THREAD

**Issue by oddProton** [sdispater/poetry#333]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 18.04 
- **Poetry 0.11.2**: 
- **https://gist.github.com/oddProton/0b7dd06b4dfebc679afe53f5ca261bd8**: 

## Issue
.venv is on python 3.6.5 and not on 3.7, the project file has 3.7 as dependency.

**Comment by sdispater** [comment]
What is the output of `poetry debug:info`?

**Comment by oddProton** [comment]
```
Poetry
======

 * Version: 0.11.2
 * Python:  3.6.5


Virtualenv
==========

 * Python:         3.6.5
 * Implementation: CPython
 * Path:           /home/dimitris/projects/pywplib/.venv


System
======

 * Platform: linux
 * OS:       posix

```

**Comment by sdispater** [comment]
I see what is going on.

You will need to rebuild you `.venv` virtualenv with Python 3.7. Poetry does not manage Python versions and it is not in the scope of the project at the moment.
