### ISSUE TITLE
Add a bump command to increment package version.

### ISSUE THREAD

**Issue by golyalpha** [sdispater/poetry#334]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

When using the `poetry new` command, a lot of files get generated.  
First there's the, probably, most important file, `pyproject.toml`.  
Then, there's the package itself `[name]\__init__.py`.  
And last but not least, the tests folder.

Each of these, contain a reference to the package's version (default being `0.1.0`). Because of them being automatically generated, I think it would be nice, if there was a `poetry bump` command, that could automatically bump version in all three of the files.

**Comment by cauebs** [comment]
A `poetry version` command already exists to handle this, but it will only edit your `pyproject.toml`.

**Comment by golyalpha** [comment]
Then maybe extend that with bumping the packages \_\_init\_\_.py? Probably not in tests though, just to remind the devs of a package, that they might need to update the tests as well.

**Comment by cauebs** [comment]
Editing .py files is complicated and dangerous

**Comment by matthewdeanmartin** [comment]
I wrote a version bumper that targets source code- there are a lot of challenges in doing this in a way that works universally.

If anyone is curious, here is:
https://github.com/matthewdeanmartin/jiggle_version
