### ISSUE TITLE
Templates for "new" command

### ISSUE THREAD

**Issue by rmerkushin** [sdispater/poetry#335]
Hello! Thanks for your project, it's very useful!

How about customizable templates for "new" command? I'm developer in test and i often coding only tests and of course i don't need to write tests for test :) It's will be great if i can create my new project by custom template.

Sorry if i duplicate some proposal and sorry for my bad English )

**Comment by sdispater** [comment]
This is not something I plan on adding at the moment.

**Comment by pmav99** [comment]
@rmerkushin Creating a cookiecutter template using `pyproject.toml` + `poetry` is probably a better option.

**Comment by moattarwork** [comment]
+1
