### ISSUE TITLE
How to verify private HTTPS repositories

### ISSUE THREAD

**Issue by guillaumerenault** [sdispater/poetry#340]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

How can I validate ((verify=path_to_ca_bundle), requests style) a private repository index, I couldn't find it in the documentation.

Thank you.

(Thank you for this amazing tool, I use it everyday, it's truely remarkable how well made it is)

**Comment by sdispater** [comment]
This is not supported at the moment.
