### ISSUE TITLE
Poetry assumes it is the only one editing pyproject.lock

### ISSUE THREAD

**Issue by apollo13** [sdispater/poetry#347]
Poetry assumes it is in full control of `pyproject.lock`. Imo it should at least consider the possibility that another tool writes into it too and handle it like `pyproject.toml` -- ie only add/edit sections that are namespaced to poetry.

**Comment by cauebs** [comment]
Why would another tool edit `pyproject.lock`? Does it happen with NPM's, Cargo's or Pipenv's lockfile?

**Comment by sdispater** [comment]
@apollo13 I actually thought about this and I agree that we should have in the lock file a section similar to the one we have in `pyproject.toml`: `tool.poetry`

@cauebs `pyproject` is a generic name that covers basically any tool that want to use `pyproject.toml` so there are no reasons why Poetry should be the only one to write to `pyproject.lock`.

**Comment by apollo13** [comment]
I does not happen for pipenv, because pipenv basically is the tool that "owns" pipfile. But pyproject.toml by design was a file ment to be used by multiple systems.

**Comment by sdispater** [comment]
Poetry has now switched to is own lock file: `poetry.lock`
