### ISSUE TITLE
--trusted-host parameter includes port

### ISSUE THREAD

**Issue by asumal** [sdispater/poetry#348]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows 10
- **Poetry version**:  0.11.3

## Issue

When attempting add a dependency with a private repository in http, i see the command adding the host and the port to the `--trusted-host` flag. For example, if I am attempting:

`poetry add pendulum`

Then the error I'll see:

`Command ['pip.exe', 'install', '--no-deps', '--trusted-host', 'foo:8081', '--index-url', 'http://foo:8081/simple', 'six==1.11.0'] errored with the following output:
Collecting six==1.11.0
  The repository located at foo is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host foo'.`

I have the following in my `pyproject.toml`

[[tool.poetry.source]]
name = "foo"
url = "http://foo:8081/simple"

When doing pip myself (without the port `:8081` attached) I can download the dependency.

Please advise.

**Comment by MadHatt3rs** [comment]
Hello I have the same issue and i fixed it. 

On poetry in installation/pip_installer.py  I changed parsed.netloc for parsed.hostname.
