### ISSUE TITLE
wheel is installed at every update, if there is `--path` in `pyproject.toml` (i.e. local package)

### ISSUE THREAD

**Issue by patarapolw** [sdispater/poetry#353]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS High Sierra 10.13.6
- **Poetry version**: 0.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/patarapolw/HanziLevelUp/blob/master/pyproject.toml

## Issue

I don't know if this is a known bug and is supposed to be fixed some day, like autogenerated `setup.py`.

It is weird that `wheel` is re-installed, rather than update or ignored. And this occurs whether or not I update my local package.

Even if I remove `{path = `, wheel is still installed every time I update!

**Comment by kadrach** [comment]
This still occurs with `master` as of now. A simple default `poetry init` `pyproject.toml` with `wheel` as added dependency will always install `wheel`, e.g. two consecutive calls to `poetry install` both install the package.

**Comment by kadrach** [comment]
I *suspect* this is because pip purposefully excludes `wheel` (https://github.com/pypa/pip/pull/3453) from the output of `pip freeze` which poetry uses to determine installed packages [here](https://github.com/sdispater/poetry/blob/master/poetry/repositories/installed_repository.py#L17).

**Comment by kadrach** [comment]
> --all                       Do not skip these packages in the output: wheel, setuptools, distribute, pip

Using `pip freeze --all` fixes this particular issue, but I'm unsure what impact this may have on poetry as a whole (python packaging still confounds me).
```diff
diff --git a/poetry/repositories/installed_repository.py b/poetry/repositories/installed_repository.py
index 9ac50fd..0aae308 100644
--- a/poetry/repositories/installed_repository.py
+++ b/poetry/repositories/installed_repository.py
@@ -14,7 +14,7 @@ class InstalledRepository(Repository):
         """
         repo = cls()

-        freeze_output = env.run("pip", "freeze")
+        freeze_output = env.run("pip", "freeze", "--all")
         for line in freeze_output.split("\n"):
             if "==" in line:
                 name, version = line.split("==")
```

**Comment by sdispater** [comment]
This is a limitation of the internal tooling. `pip` protects its dependencies by not displaying them in `pip freeze` and adding `--all` is not desirable at the moment.
