### ISSUE TITLE
Poetry fails when Poetry's Python version differs from the active environment's Python version

### ISSUE THREAD

**Issue by nchammas** [sdispater/poetry#354]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13.6
- **Poetry version**: 0.11.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not relevant

## Issue

This is a minor issue. Poetry names the virtual environments it creates using the Python version it is running under, which I think is incorrect. Instead, it should use the Python version currently active.

For example, say I install Poetry with my Homebrewed Python, which is at Python 3.7.0. But inside a specific project, I have Python 3.6.6 activated via pyenv. This is what happens:

```sh
myproject$ python --version
Python 3.6.6
myproject$ which python
.../.pyenv/shims/python
myproject$ poetry shell
Creating virtualenv myproject-py3.7 in .../Library/Caches/pypoetry/virtualenvs
Spawning shell within .../Library/Caches/pypoetry/virtualenvs/myproject-py3.7
myproject$ python --version
Python 3.6.6
```

I believe the cause of this confusing discrepancy between the venv name and the active Python version is [here](https://github.com/sdispater/poetry/blob/991842bd8aeccd144b49afff8a415f19f03be48f/poetry/utils/venv.py#L80). Instead of querying its own Python version, Poetry should query the version of the Python that would be invoked when it creates the virtual environment.

**Comment by nchammas** [comment]
Hmm, this issue may be deeper than I thought. If I call `poetry develop` on a project setup in the above way, I get this error:

```
myproject$ poetry develop
Installing dependencies from lock file
<snipped>
[VenvCommandError]
Command ['pip', 'install', '-e', '.../myproject', '--no-deps'] errored with the following output:
Obtaining file:///.../myproject
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
myproject requires Python '>=3.4,<3.7' but the running Python is 3.7.0  # error here!
<pip version warning snipped>
myproject$ pip --version
pip 10.0.1 from .../.pyenv/versions/3.6.6/lib/python3.6/site-packages/pip (python 3.6)
myproject$ python --version
Python 3.6.6
```

I do have the following snippet in my pyproject.toml

```toml
[tool.poetry.dependencies]
python = ">=3.4, <3.7"
```

but I would expect Poetry to work since the active Python is Python 3.6.6. However, it seems that the faulty Python version detection I pointed to for `poetry shell` also affects `poetry develop`.

**Comment by nchammas** [comment]
Looking again through past issues, what I'm describing here may be related to #172.

**Comment by nchammas** [comment]
Hi @sdispater - Has this issue been resolved with a recent change? I don't see a recently linked PR that would explain the close.

**Comment by nchammas** [comment]
Hey @sdispater, just checking in again to understand why this issue was closed, since it's not clear to me.

**Comment by nchammas** [comment]
Hey @brycedrennan, I noticed you reopened #172. You may be interested in taking a quick look at this issue, which I believe is related.

**Comment by brycedrennan** [comment]
Thanks for the example!
