### ISSUE TITLE
How to generate this setup.py for a namespace subpackage?

### ISSUE THREAD

**Issue by moigagoo** [sdispater/poetry#356]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hi!

I'm moving all my projects to Poetry and have issues with some of them. Namely, it's packages that are subpackages to a bigger project.

Here is one example: https://github.com/foliant-docs/foliantcontrib.bump. It's an extension for https://github.com/foliant-docs/foliant.

It means that during installation, the file `foliant/cli/bump.py` should be placed in `foliant/cli` folder in Foliant installation. To accomplish this, I'm using namespace package in [setup.py](https://github.com/foliant-docs/foliantcontrib.bump/blob/master/setup.py#L23).

I haven't found a way to achieve the same thing with Poetry. Tried using `packages` in [pyproject.toml](https://github.com/foliant-docs/foliantcontrib.bump/commit/6dcb421678cd72773253e36d6d18c39b45e32af9#diff-522adf759addbd3b193c74ca85243f7dL7), but that gives me a package name `cli`, not `foliant.cli`.

**Comment by nicktimko** [comment]
I think this sounds related: https://github.com/sdispater/poetry/issues/167

**Comment by RaptDept** [comment]
Your `pyproject.toml` link leads to a 404. How did you use `packages`?

I've been able to use namespace packages in Poetry just fine, but my use case is slightly different. I don't have projects that share innermost (leaf) packages, so I'm not sure if this will work for you.

I have two projects, `foo-project` and `bar-project`:
```
foo-project
├── pyproject.toml
└── root_namespace
    └── nested_namespace
        └── subpackage_a
        │   └── __init__.py
        └── subpackage_b
            └── __init__.py
```

```
bar-project
├── pyproject.toml
└── root_namespace
    └── nested_namespace
        └── subpackage_c
            └── __init__.py
```


This is how I use `packages` in each `pyproject.toml`:
```
[tool.poetry]
...
packages = [{ include = "root_namespace" }]
...
```

This picks up `root_namespace` and the subpackages in the generated `setup.py`.

`foo-project/setup.py`:
```
packages = \
['root_namespace',
 'root_namespace.nested_namespace.subpackage_a',
 'root_namespace.nested_namespace.subpackage_b']
```

`bar-project/setup.py`:
```
packages = \
['root_namespace',
 'root_namespace.nested_namespace.subpackage_c']
```

Installing both places the files in the correct directories.

**Comment by moigagoo** [comment]
Sorry, I've updated the link.

Thanks for the code sample, I'll try to do something similar and report the result.

**Comment by RaptDept** [comment]
`[{ include="foliant.cli" }]`might be what you want. I think the `from` field is for specifying the parent directory of your package tree (e.g. `src` if the `foliant` directory is in `src`)

**Comment by moigagoo** [comment]
@RaptDept `[{ include="foliant.cli" }]` doesn't work because Poetry tries to look for `foliant.cli` folder, which is not there:

```shell
[ValueError]
C:\Users\moigagoo\Projects\foliantcontrib.bump\foliant.cli does not contain any element
```

`[{ include="foliant" }]` only adds `foliant` as a package. But if I put an empty `__init__.py` file in `foliant/cli`, both `foliant` and `foliant.cli` are detected. Even though I'd rather have only `foliant.cli` added to `packages` in `setup.py` and not add and empty `__init__.py`, it seems to work. Thanks!

**Comment by moigagoo** [comment]
It turns out, putting __init__.py is not a solution. It overwrites the __init__.py that's already there in the parent package during installation, which breaks stuff.

**Comment by dfee** [comment]
See my solution here: https://github.com/sdispater/poetry/issue_comments#issuecomment-411573655

**Comment by moigagoo** [comment]
@dfee it's 404 unfortunately.

**Comment by dfee** [comment]
@moigagoo Updated the link, glad you'd already found it.

**Comment by dfee** [comment]
@moigagoo I'm not understanding how your project doesn't follow the PEP420 guidelines. Is it because you don't have and `__init__.py` https://github.com/foliant-docs/foliantcontrib.bump/tree/develop/foliant/cli
