### ISSUE TITLE
Discussion forum?

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#358]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

What's the best discussion forum in which to discuss Poetry and related issues? Is there an IRC channel somewhere? Mailing list? Slack or Gitter?

Apologies if I've missed this, wasn't anything obvious in the docs or in a few searches of this issues tracker...

**Comment by jacebrowning** [comment]
I'd vote for Gitter.

**Comment by cjw296** [comment]
If there's a choice, Gitter would be my least favourite... Slack or IRC work best for me, but I am only one person, so happy if many other people feel strongly...

**Comment by rainyday** [comment]
Personally not a huge fan of using closed source communication tools for open source projects so my vote would be something like IRC or matrix but I understand that they're not as user friendly or polished.

**Comment by moigagoo** [comment]
GitHub is closed source software, as is macOS and Windows, which are all used by Poetry maintainers and users. This doesn't make Poetry itself any less open source.

As to IRC, I believe it's the worst option in terms of usability. No history, no search, no formatting, no mentions. Yes it is cool and hacky in a way, but I'd rather have a communication channel available right of the bat in the browser.

I'm voting for Gitter.

**Comment by sdispater** [comment]
Ok. I created a Python Poetry server on Discord. So if anyone wants to join, here is the invitation link:

https://discordapp.com/invite/KBp3a4X

I will update the documentation and the contributing guide to mention it.

**Comment by moigagoo** [comment]
Unfortunately, the link seems to be invalid. But the idea is great!

**Comment by sdispater** [comment]
Sorry about that. Does this one work?

https://discordapp.com/invite/awxPgve

**Comment by moigagoo** [comment]
Yep, thanks!

**Comment by cjw296** [comment]
I think this is fixed :-)
