### ISSUE TITLE
git dependencies are not reflected in setup.py file

### ISSUE THREAD

**Issue by jykntr** [sdispater/poetry#363]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS High Sierra 10.13.6
- **Poetry version**: 0.11.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Example Gist](https://gist.github.com/jykntr/35cd062fe6df9d3ff1f4c32ba7347f9a)

## Issue
When I create a package that has a git dependency as described in the docs [here](https://poetry.eustace.io/docs/versions/#git-dependencies), when I `pip install` the distribution file poetry builds the git dependency is not installed.  Instead, an older version available on PyPi is installed.

The gist linked above has snippets from what I think is relevant in the project.  I don't really know, but I assume something like what is described in [this post](https://mike.zwobble.org/2013/05/adding-git-or-hg-or-svn-dependencies-in-setup-py/) needs to happen.

**Comment by sdispater** [comment]
This should now be fixed in the latest version.
