### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ritalinn** [sdispater/poetry#364]
I like open sources. I want to design a logo for the development of the project. I can design. What dou you think?

**Comment by jgirardet** [comment]
Do it !!

**Comment by pawamoy** [comment]
Any progress :slightly_smiling_face:? I'm interested in putting it on [VectorLogoZone](https://www.vectorlogo.zone/) ([GitHub repo](https://github.com/VectorLogoZone/vectorlogozone)) to give credits to Poetry in my projects!

**Comment by stephsamson** [comment]
Hi @ritalinn thanks so much for reaching out and volunteering! Poetry already [has a logo](https://github.com/python-poetry) but if you would like to help in any other way regarding design, please reach out to us via [Discord](https://discord.gg/ess4AMy). You can find Sébastien there as `sdispater` or me as `panyang`.  I will close this issue for now.
