### ISSUE TITLE
AttributeError caused by author field, breaking `poetry build`

### ISSUE THREAD

**Issue by nackjicholson** [sdispater/poetry#370]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

```
poetry build -f sdist
```

With author field in pyproject.toml

```toml
authors = ["R&D <researchanddevelopment@example.com>"]
```

Output:

```
[AttributeError]               
'NoneType' object has no attribute 'group'  
```

Perhaps this is for a good reason, but it confused me for a long while because I didn't know this meant something was wrong in my pyproject.toml file. It would be useful to have indications of toml validation problems by field.

Changed to:

```
authors = ["Research Development <researchanddevelopment@example.com>"]
```

Works, and that is fine. Just didn't know there were validation rules for these strings.

**Comment by kam1sh** [comment]
Faced this problem today, on version 0.12.11 (Python 3.7.2). Had this field in pyproject.toml:  
`authors = ["support@example.com]`

Changed to `authors = ["Example support <support@example.com>"]`, works fine.

I'll try to fix this in this or next weekend, because it looks like obvious regex mismatch.

**Comment by kam1sh** [comment]
@nackjicholson What do you think, maybe replacing `'NoneType' object has no attribute 'group'  ` to `Invalid project's author` would be enough?

**Comment by kam1sh** [comment]
Well... my PR got softly rejected, but you or someone else could find some useful solutions among my commits =/

**Comment by drunkwcodes** [comment]
Thanks,  @kam1sh.

The problem is '&' mismatched in `AUTHOR_REGEX`.

Here are some common punctuation marks in names.
I would like to make a PR to add them into regex with test cases if the list has no issue.

```
,
.
’
()
-

&
@ 
# 

™
®
㊣
↗
↙

```

**Comment by drunkwcodes** [comment]
And I thought this is a good place to discuss introducing `email` lib.
It handles arbitrary marks so well in the case of formal email form.

Here are example results with inputs listed above:


```
In [1]: from email.utils import parseaddr

In [2]: parseaddr('R&D <r&d@example.com>')
Out[2]: ('R&D', 'r&d@example.com')

In [3]: parseaddr('R#D <r#d@example.com>')
Out[3]: ('R#D', 'r#d@example.com')

In [4]: parseaddr('R()D <r()d@example.com>')
Out[4]: ('R D ( )', 'rd@example.com')

In [5]: parseaddr('R@D <r@d@example.com>')
Out[5]: ('', 'R@D')

In [6]: parseaddr('R®D <r®d@example.com>')
Out[6]: ('R®D', 'r®d@example.com')

In [7]: parseaddr('RD™ <rd@example.com>')
Out[7]: ('RD™', 'rd@example.com')

In [8]: parseaddr('RD㊣ <rd㊣@example.com>')
Out[8]: ('RD㊣', 'rd㊣@example.com')

In [9]: parseaddr('↙R&D↗ <↙rd↗@example.com>')
Out[9]: ('↙R&D↗', '↙rd↗@example.com')
```

Not supporting partentheses is the only concern to change to use `parseaddr`.

**Comment by brettatoms** [comment]
There's another error as well if the author string isn't formatted correctly, e.g. if the closing bracket is missing like "Me <me@example.com"
