### ISSUE TITLE
Could not parse version constraint for `poetry add ipython`

### ISSUE THREAD

**Issue by agoose77** [sdispater/poetry#38]
Poetry 0.7.0
`sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)`

Bash executed:
```bash
poetry add ipython
```

Error message:
```traceback                                                
  [ValueError]                                         
  Could not parse version constraint: >=18.5decorator  
                                                       

add [-D|--dev] [--optional] [--dry-run] [--] <name> (<name>)...
```

The `setup.py` contents include
```python


install_requires = [
    'setuptools>=18.5',
    'jedi>=0.10',
    'decorator',
    'pickleshare',
    'simplegeneric>0.8',
    'traitlets>=4.2',
    'prompt_toolkit>=1.0.15,<2.0.0',
    'pygments',
    'backcall',
]
```

So it would seem that install requires is being parsed incorrectly, or something!

Hope this helps

**Comment by sdispater** [comment]
@agoose77 Yes, it seems that `ipython 4.1.0rc1` has badly defined dependencies which leads to poetry failing to resolve.

I will fix this by dropping malformed dependencies. For the time being, you can specify the constraint yourself:

```bash
poetry add "ipython=^6.3"
```

**Comment by agoose77** [comment]
Thanks for the swift reply, that's great

**Comment by agoose77** [comment]
Is there any way to do this for a nested dependency, e.g `jupyterlab` which depends upon ipython?

**Comment by agoose77** [comment]
Ah, my mistake. I had thought that it was quick for a new release! Thanks
