### ISSUE TITLE
 Clarity regarding versioning (tilde / ~)

### ISSUE THREAD

**Issue by dfee** [sdispater/poetry#380]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
It seems that `poetry` interprets the tilde operator (`~`) differently than `pip` (and `setuptools`?) https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file

I'm looking at a particular setup.py file and trying to convert it to a pyproject.toml file with poetry support. It appears something like `"six~=1.0" in setup.py is equivalent to `six = "^1.0"` and not `six = "~1.0".

If my understanding is correct, then additional documentation around mapping of values might be helpful.

**Comment by dfee** [comment]
I found that the tilde (`~`) is standardized in [PEP-440](https://www.python.org/dev/peps/pep-0440/#compatible-release) to mean:
```
For a given release identifier V.N, the compatible release clause is 
approximately equivalent to the pair of comparison clauses:

>= V.N, == V.*
```

Therefore, I think that poetry makes *wrong* use of the tilde.

**Comment by sdispater** [comment]
The use of `~` in Poetry matches what you can find in other tools in other languages, like `composer` for PHP or `npm` in Javascript.

However, you can still use `~=` to match the behavior defined in PEP 440.

**Comment by niteshthakur** [comment]
@sdispater  I added `Flask = "~=0.1"` to toml and got version `0.12.5` in lock file. Is this a bug ?
