### ISSUE TITLE
Watch scripts that Poetry executes on change of the repo's files

### ISSUE THREAD

**Issue by golyalpha** [sdispater/poetry#385]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

Add support for "watch scripts" that Poetry could execute when there's a change in the repo.
For example, I have docker set up, so I can check out my web app locally just by running  
`docker-compose up --build`

The issue I'm having right now, is that every time I change the code, I have to Ctrl+C in the console window for docker to gracefully stop all services (DB, Adminer and my app in my case, can force it by doing Ctrl+C again), and then re-run the command mentioned previously to build and launch the app again.

It would be nice, if I could have a definition in the pyproject.toml file, with scripts to launch on change in the repo (supporting continously running scripts, like `docker-compose up`, terminating them with Ctrl+C, and waiting for them to exit before re-running).
```toml
[tools.poetry.watch]
docker-compose = "docker-compose up --build"
```
And then, I could use the `poetry watch` and `poetry watch [script-name]` to run all, and selected scripts respectively.

**Comment by sdispater** [comment]
This is not a feature that is suitable for the core project. There are other tools that exist that might be more appropriate for this.
