### ISSUE TITLE
poetry add --path fails on Windows (10)

### ISSUE THREAD

**Issue by rcisterna** [sdispater/poetry#386]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 Pro 1803
- **Poetry version**: 0.11.4

## Issue
First of all, thanks for this awesome tool.

Now, to the issue. I just try to add a dependency as follows
`poetry add my-lib --path ..\my-lib\`

but poetry shows the error
> [InvalidCharInStringError]
> Invalid character 'm' in string at line 9 col 21

Looking at my pyproject.toml file, I notice that the line added by poetry is
> my-lib = {path = "..\my-lib\"}

Changing the `\` for `\\` fix the problems.

**Comment by sdispater** [comment]
This is now fixed!

See my comment https://github.com/sdispater/poetry/issues/396#issuecomment-418764600 for more details.
