### ISSUE TITLE
`poetry run` exits on KeyboardInterrupt

### ISSUE THREAD

**Issue by Curly-Mo** [sdispater/poetry#393]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 0.11.4

## Issue

KeyboardInterrupt is not properly handled when executing with `poetry run`.
If a python script attempts to catch a KeyboardInterrupt exception, instead of it being handled, the entire `poetry run ...` command exists completely.

Here is an example of running the python interpreter.
```
$ python
>>> try:
...     while True:
...         pass
... except KeyboardInterrupt:
...     print('hello')
...
^Chello
>>> print('I am still in the interpreter')
```
```
poetry run python
>>> try:
...     while True:
...         pass
... except KeyboardInterrupt:
...     print('hello')
...
^Chello
$ echo 'I am back to the shell'
```

Even worse is the way this affects poetry scripts. Completely exiting the script instead of handling the KeyboardInterrupt exception.
pyproject.toml
``` 
[tool.poetry.scripts]
script = 'script:main'
```
script.py
``` 
def main():
    try:
        while True:
            pass
    except KeyboardInterrupt:
        print('Never reached when executed using `poetry run script`')
```
```
$ poetry run script
^C
```
This does not happen when the package is installed with pip and the script is executed.
```
$ poetry build
$ pip install dist/project.whl
$ script
^CNever reached when executed using `poetry run script`
```

**Comment by altendky** [comment]
Not fixing a bug for awhile doesn't make its ticket invalid.  Perhaps I should write a toaster app to respond to everything stale [bot] wants to close.

**Comment by bertjwregeer** [comment]
This is fixed in the newer versions of poetry that are in beta release because `poetry run` no longer runs it through a `popen` wrapper and instead exec's the new process directly.

**Comment by finswimmer** [comment]
Hell @altendky ,

running the stale bot was necessary to get a better overview about what issues are still relevant, before poetry 1.0 is released. @sdispater explained in another issue, that the bot may be disabled again later.

If you find that an issue isn't fixed, please just leave a comment in the issue. We can reopen it anytime.

Thanks a lot for your contribution!

fin swimmer

**Comment by altendky** [comment]
In my experience closing tickets due to being untouched usually just means a valid ticket wasn't addressed for a long time.  I'm glad to hear that this case is an exception and that stale [bot] might go away.
