### ISSUE TITLE
Add correct PyPI classifier for supported license

### ISSUE THREAD

**Issue by Aloha68** [sdispater/poetry#398]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hi, and first, thank's for poetry :-)

I looked at your code and noticed that the list of licenses managed by poetry is retrieved from the spdx [license-list-data](https://github.com/spdx/license-list-data) repository.

Apparently, PyPI classifiers are generated from the **poetry/spdx/license.py** file with the variables *CLASSIFIERS_SUPPORTED* and *CLASSIFIERS_NAMES*? Is that correct?

If so, is there a way to update this list automatically or should it be done manually? Can you explain me how to add some licenses by hand so that the classifier is correct at the end? Do the values in the *CLASSIFIERS_SUPPORTED* list match the data keys recovered in the **poetry/spdx/data/licenses.json** file? And for values in the *CLASSIFIERS_NAMES* list, should I enter the license name in [PyPI classifiers](https://pypi.org/pypi?%3Aaction=list_classifiers) with the previous key?

I can probably create a PR to complete the license list to get the correct PyPI classifier.

**Comment by sdispater** [comment]
The naming of PyPI classifiers differs from the official ones that's what the `CLASSIFIER_NAMES` attribute is for.

So, yeah, we will need to update it, along with CLASSIFIERS_SUPPORTED, to support more classifiers.

Feel free to submit a PR and I'll gladly review it.
