### ISSUE TITLE
Support a --venv flag similar to pipenv

### ISSUE THREAD

**Issue by klardotsh** [sdispater/poetry#401]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

pipenv supports a flag `--venv` flag that simply prints the path to the existing venv, or returns a non-0 status code if it doesn't exist. This allows solutions like https://github.com/w0rp/ale/issues/1656 to auto-detect (without unwanted side effects) whether pipenv should be used to run, for example, a linter.

The closest thing I've found in poetry so far to this effect is `debug:info`, which will unfortunately auto-create the virtualenv if it doesn't exist, which would lead to false positives in scenarios like the ALE one.

I may be able to take a crack at this one personally, I don't imagine it'll be the hardest task in the world.

**Comment by jacebrowning** [comment]
`poetry show` will fail if the virtual environment needs to be created and `poetry show -v` includes the path to the virtual environment if it exists.

**Comment by klardotsh** [comment]
Unfortunately `poetry show` does not appear to fail correctly if the venv needs created, instead it creates it anyway:

```sh
(spoonman) rendering » poetry show -v
Creating virtualenv rendering-py3.7 in /home/j/.cache/pypoetry/virtualenvs
Using virtualenv: /home/j/.cache/pypoetry/virtualenvs/rendering-py3.7
```

**Comment by yunti** [comment]
Agreed it would be better if `poetry show -v` didn't create a venv if it didn't find one as the command name leads the user to expect this is how it works.

**Comment by zymergen-luke** [comment]
I have a similar use case where I'd like to activate the virtualenv programmatically (without resorting to nesting shells).
```
source ${pipenv --venv}/bin/activate
```
works well for me, but unfortunately there is no easy alternative for poetry.

**Comment by K900** [comment]
I'm up to write a patch to add this if there's a chance for it to be accepted. @sdispater?

**Comment by zymergen-luke** [comment]
@K900 I had some spare time this morning so I threw together a quick patch myself. Want to take a look and see if that's roughly what you have in mind?

**Comment by zymergen-luke** [comment]
This can be closed now since @sdispater added a new feature in #731 

```
poetry env info --path
```
will return the path to the environment.

You can call the following to activate your environment consistently:
```
source ${poetry env info --path}/bin/activate
```

**Comment by garyo** [comment]
Agreed, this is the way to go -- thanks, @sdispater !. And to follow up on @zymergen-luke , for you Windows folks out there writing shell functions, it's `.../Scripts/activate` rather than `.../bin/activate`.
