### ISSUE TITLE
Deploy app on Heroku using Poetry

### ISSUE THREAD

**Issue by karantan** [sdispater/poetry#403]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Let say you have a simple Flask web app but instead of using pipenv (or regular pip + requirements.txt) I want to use poetry. How do I deploy this app on heroku?

With pipenv it is easy because there already exists a buildpack for pipenv but it does not for poetry.

**Comment by jacebrowning** [comment]
IMO, the best solution would be to update the Python buildpack to key off `pyproject.toml` then run `poetry` commands. I'll see if I can put something together.

**Comment by yunti** [comment]
This would work too #100

**Comment by nmunro** [comment]
I have a more general solution to this, if I may, I had begun working on a patch, but I'm still familiarising myself with the poetry package.

We need to use pip directly on EC2 instances and I threw together a solution to generate a traditional requirements.txt file, but using a make rule, ideally a command to regenerate a standard requirements.txt file for use with heroku/aws etc would be a good way to integrate quickly and easily with existing services etc

Something like:

```poetry export-requirements --no-deps```

**Comment by zyv** [comment]
Yet another pipenv refugee here... Would be great to have an analog to `pipenv lock -r` in poetry. This is what we are currently using for our Heroku deployments.

In the meantime, we are thinking of running `pip freeze` in `poetry shell` and filtering out the current project with `grep`, but native support for `pipenv lock -r` would be much appreciated. Thanks!

**Comment by sdispater** [comment]
An `export` command is currently being worked on which will make exporting the lock file to other formats (`requirements.txt` being the only one for now) possible.

**Comment by zyv** [comment]
@sdispater sounds awesome! Would be great if that `export` command supported filtering dependencies by type (i.e. to be able to automatically filter out dev dependencies), and custom index sources. These are both pipenv features that we are currently using to generate our requirements.txt for Heroku.

**Comment by zyv** [comment]
Merged in develop in #675, yay! 👍 Will be testing when it hits the next release.

**Comment by zyv** [comment]
@Woile the feature has been merged in `develop`, but, unfortunately, still not released :(

In the meantime, we use an internal tool that we have written to the same effect, which parses the lock-file and outputs `requirements.txt` for Heroku...

**Comment by jacebrowning** [comment]
@Woile If you don't care about leveraging Heroku's dependency cache, the following works for a Django project using the default Python buildpack:

`requirements.txt`
```bash
poetry==0.12.10
```

`bin/post_compile`
```bash
#!/usr/bin/env bash

set -eo pipefail

indent() {
  sed "s/^/       /"
}

puts-step() {
  echo "-----> $@"
}

puts-step "Installing dependencies with poetry..."
poetry config settings.virtualenvs.create false 2>&1 | indent
poetry install --no-dev 2>&1 | indent

puts-step "Collecting static files..."
python manage.py collectstatic --no-input 2>&1 | indent
```

**Comment by sdispater** [comment]
The `export` command is available in the `1.0.0` latest pre release

**Comment by joshfriend** [comment]
@jacebrowning i disagree with how heroku's dependency cache works anyways, so this is actually OK with me 😆

**Comment by CptSpaceToaster** [comment]
Due to a conflict with

I modified my install for a flask-app to allow poetry to keep it's virtual env, but just in the repo

`requirements.txt`

```
poetry==0.12.17
```

`bin/post_compile`

```bash
#!/usr/bin/env bash

set -eo pipefail

indent() {
  sed "s/^/       /"
}

puts-step() {
  echo "-----> $@"
}

puts-step "Installing dependencies with poetry..."
# Use a venv, but install locally
poetry config settings.virtualenvs.in-project true 2>&1 | indent
poetry install --no-dev 2>&1 | indent

# Not using Django
# puts-step "Collecting static files..."
# python manage.py collectstatic --no-input 2>&1 | indent
```

This requires the Procfile to be mangled, as the installed version of gunicorn I needed wasn't receiving a functional hashbang

`Procfile`

```
web: .venv/bin/python3 .venv/bin/gunicorn package:flask_app
```

**Comment by fidelitas** [comment]
I got it working by doing
```sh
# Get poetry from source
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
# Make poetry available to $PATH
source $HOME/.poetry/env
# Export poetry packages to requirements.txt to be used for installing the pipy packages
poetry export -f requirements.txt -o requirements.txt
```

**Comment by CptSpaceToaster** [comment]
Now that poetry 1.0.0 is out, you can run `poetry export`. If you do not have the 1.0.0 release, you'll still need a work around.

**Comment by laike9m** [comment]
> ```shell
> poetry config settings.virtualenvs.create false 2>&1 | indent
> ```

As of Poetry 1.0, 
```
poetry config settings.virtualenvs.create false
```
has changed to
```
poetry config virtualenvs.create false
```

Could you help update it to help future readers? Also, it's better to use `--local` because you don't want to affect other projects.

**Comment by zyv** [comment]
FYI, we've eventually created a buildpack and moved to Poetry also on Heroku:

https://github.com/moneymeets/python-poetry-buildpack

/cc @marns93
