### ISSUE TITLE
Installing package with setup.py-based local dependencies creates wrong venv

### ISSUE THREAD

**Issue by jhrmnn** [sdispater/poetry#409]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.13.5
- **Poetry version**: 0.11.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/7755ad36b3e1fb47db67e9fbe5fd4807

## Issue

When installing a package with local directories as dependencies, and one of them is `setup.py`-based rather then Poetry-based, the wrong virtualenv is created.

This caused by `DirectoryDependency()` [calling](https://github.com/sdispater/poetry/blob/f4ad371e416c98566680c542a29a73d5cdaebcaf/poetry/packages/directory_dependency.py#L90) `Venv.create()` for a `setup.py`-based package, which [exports](https://github.com/sdispater/poetry/blob/f4ad371e416c98566680c542a29a73d5cdaebcaf/poetry/utils/venv.py#L112) `VIRTUAL_ENV` into the environment, so that the [subsequent call](https://github.com/sdispater/poetry/blob/f4ad371e416c98566680c542a29a73d5cdaebcaf/poetry/console/commands/venv_command.py#L15) to `Venv.create()` from `VenvCommand()` for the actual package being installed returns a wrong virtualenv.

Simply removing `VIRTUAL_ENV` from the environment at the end of `Venv.create()` when no `name` argument is passed seems to solve the problem (or adding `export=False` with `VenvCommand()` calling `Venv.create(export=True)`), but I'm not sure what's the logic behind Poetry's use of the `VIRTUAL_ENV` variable, so I won't make a pull request.

**Comment by azag0** [comment]
And while I'm at it, I'm not sure if leaving the dependency's virtualenv that was created just for the purpose of parsing `setup.py` in the cache dir is the right approach.

**Comment by sdispater** [comment]
A lot has been changes internally (especially on the `develop` branch) so closing this as it might have been fixed. Feel free to reopen if this is not the case.
