### ISSUE TITLE
poetry is unable to handle empty passwords for publishing

### ISSUE THREAD

**Issue by diefans** [sdispater/poetry#410]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS**: ubunto 16.04
- **poetry version**: 0.11.4 f4ad371
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

poetry is unable to handle empty password for publishing e.g. to gemfury.io. gemfury.io uses just a token for the username and an empty password, so you are unable to automatically upload/publish...

**Comment by sdispater** [comment]
This should now be fixed
