### ISSUE TITLE
Install dependencies into folder

### ISSUE THREAD

**Issue by Tonkonozhenko** [sdispater/poetry#416]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
Is it possible to install dependencies into directory like using next pip command?
```
pip install -r requirements.txt -t ./vendor
```

**Comment by azag0** [comment]
Poetry works within a virtual environment, which is IMO a more robust and encompassing approach.

**Comment by Tonkonozhenko** [comment]
I need to bundle them into directory for AWS lambda so that's why I need it.

**Comment by azag0** [comment]
Then how about

    <path to poetry venv>/bin/pip freeze >requirements.txt && pip install -r requirements.txt -t ./vendor

**Comment by Tonkonozhenko** [comment]
It worked for me for a while. But recently I added a package from git repository.

**Comment by mvoitko** [comment]
@azag0 Working with AWS is a quite common use case. How about adding a new command to poetry where it's possible to specify <path to dependency folder>?

**Comment by sdispater** [comment]
This is not supported and likely won't be .
