### ISSUE TITLE
Poetry should support installing extras even if the base package is already installed

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#417]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

So far this is only possible through removing the package and installing it again with extras. It would be nice to just be able to add extras as needed.

**Comment by sdispater** [comment]
I am not sure I understand.

I you add the extras to your dependency in your `pyproject.toml` and then do `poetry update my-dependency` it should work.

**Comment by kakulukia** [comment]
That probably also works, but if I’m not familiar with the syntax, I‘d rather like to use poetry add instead.

**Comment by sdispater** [comment]
Closing this since a solution has already been provided.
