### ISSUE TITLE
Broaden virtualenv in project option to support custom location

### ISSUE THREAD

**Issue by yunti** [sdispater/poetry#423]
- [ X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
As mentioned in #278 and other issues (hmm... can't find  now). Widen the ability to support venv locations not just in the project folder but a user specified one.
This will have the benefit of increasing compatibility with more user workflows and tooling, eg IDEs that looks for venvs in the `~./virtualenvs` location.

**Comment by sdispater** [comment]
This already supported by setting the `settings.virtualenvs.path` setting. See https://poetry.eustace.io/docs/configuration/#settingsvirtualenvspath-string

**Comment by yunti** [comment]
Thanks, sorry I missed that.
