### ISSUE TITLE
Poetry does not install extras if they're not required in a root package, but in a dependency

### ISSUE THREAD

**Issue by narimansafiulin** [sdispater/poetry#425]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, Ubuntu Server 18.04
- **Poetry version**: 0.11.5

## Issue

There's two examples I tested on to reproduce this problem:
<details><summary>Demo packages hierarchy  (spoiler)</summary>

**project-a/pyproject.toml:**
```
[tool.poetry]
name = "project-a"
version = "1.0.0"
description = "This is a description"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
project-b = { path = "../project-b"}
project-c = { path = "../project-c"}
```

**project-b/pyproject.toml:**
```
[tool.poetry]
name = "project-b"
version = "1.0.0"
description = "This is a description"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
project-c = { path = "../project-c", extras = ["extra_d"] }
```

**project-c/pyproject.toml:**
```
[tool.poetry]
name = "project-c"
version = "1.0.0"
description = "This is a description"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
project-d = { path = "../project-d", optional = true }

[tool.poetry.extras]
extra_d = [ "project-d" ]
```

**project-d/pyproject.toml:**
```
[tool.poetry]
name = "project-d"
version = "1.0.0"
description = "This is a description"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
```
</details>
<details><summary>Test, if I wrote it correctly (spoiler)</summary>

It's a test for puzzle solver:
```python
def test_solver_returns_extras_if_requested_in_dependencies_and_not_in_root_package(solver, repo, package):
    package.add_dependency("A")
    package.add_dependency("B")
    package.add_dependency("C")

    package_a = get_package("A", "1.0")
    package_b = get_package("B", "1.0")
    package_c = get_package("C", "1.0")
    package_d = get_package("D", "1.0")

    package_b.add_dependency("C", {"version": "^1.0", "extras": ["foo"]})

    package_c.add_dependency("D", {"version": "^1.0", "optional": True})
    package_c.extras = {"foo": [get_dependency("D", "^1.0")]}

    repo.add_package(package_a)
    repo.add_package(package_b)
    repo.add_package(package_c)
    repo.add_package(package_d)

    ops = solver.solve()

    check_solver_result(
        ops,
        [
            {"job": "install", "package": package_d},
            {"job": "install", "package": package_c},
            {"job": "install", "package": package_a},
            {"job": "install", "package": package_b},
        ],
    )
```
</details>

Let's suppose we have some package (`first`) with extra dependency (`extra`), and another one (`second`) which requires the `first` package **with** extra dependency.
Root package (`project`) requires `second` package, and also the `first` package, but **without** extra dependency.
It's obvious that `extra` package should be installed, otherwise the `second` package can raise errors on runtime.
When we'll try to resolve or install dependencies for the project, `extra` package will not be installed or resolved. But resolving dependencies in the `second` package shows correct result (`extra` will be installed).

```
Resolving dependencies...
   1: fact: project-a is 1.0.0
   1: derived: project-a
   1: fact: project-a depends on project-b (1.0.0)
   1: fact: project-a depends on project-c (1.0.0)
   1: selecting project-a (1.0.0)
   1: derived: project-c (1.0.0)
   1: derived: project-b (1.0.0)
   1: selecting project-c (1.0.0)
   1: fact: project-b (1.0.0) depends on project-c (1.0.0)
   1: selecting project-b (1.0.0)
   1: Version solving took 0.006 seconds.
   1: Tried 1 solutions.

Resolution results:

  - project-c (1.0.0)
  - project-b (1.0.0)
```

**Comment by sdispater** [comment]
Thanks a lot for the detail report and the provided test case!

I can definitely reproduce this issue. After taking a quick look at it, this won't be a trivial fix. I will get back to you.

**Comment by sdispater** [comment]
This should be fixed in the latest release.
