### ISSUE TITLE
Support "standard" square bracket syntax for package extras

### ISSUE THREAD

**Issue by ulope** [sdispater/poetry#429]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

It would be great if poetry would support the "standard" square bracket syntax to specify package extras (i.e. `somepackage[someextra]`).

I'm aware of the `-E` option but it's a departure from what other tools are doing and also it's not immediately clear how to specify multiple different extras for multiple packages.

**Comment by vab2048** [comment]
What is the recommended way of installing extras?

In other words what would be the equivalent of the command `pip install dash[testing]`?

**Comment by fgimian** [comment]
I think I managed to get this to work finally.  So it goes like this:

```bash
poetry add -E <category> <package>
```

e.g.

```
[fots@mydevmachine ~]$ poetry add -E web fastapi

[RuntimeError]
Poetry could not find a pyproject.toml file in /home/fots or its parents

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

[fots@mydevmachine ~]$ ^C
[fots@mydevmachine ~]$ poetry new testing
Created package testing in testing
[fots@mydevmachine ~]$ cd testing/
[fots@mydevmachine testing]$ poetry add -E packaging virtualenv-tools3
Using version ^2.0 for virtualenv-tools3

Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file


Package operations: 7 installs, 0 updates, 0 removals

  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.2.0)
  - Installing pluggy (0.13.0)
  - Installing py (1.8.0)
  - Installing six (1.12.0)
  - Installing pytest (3.10.1)
  - Installing virtualenv-tools3 (2.0.2)
[fots@mydevmachine testing]$ cat pyproject.toml
[tool.poetry]
name = "testing"
version = "0.1.0"
description = ""
authors = ["My Name <me@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
virtualenv-tools3 = {version = "^2.0", extras = ["packaging"]}

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Hope this helps
Fotis

**Comment by sdispater** [comment]
This is supported in the latest prereleases of the `1.0.0` release and will be globally available when it's officially released.

**Comment by a-ilango** [comment]
I'm unable to make use of this feature. The following is my pyproject.toml contents excerpt:

```
[tool.poetry.dependencies]
python = "^3.7"
...
testcontainers[postgresql] = "2.6.0"
```

This one throws the following error when issuing `poetry install -v --dry-run`
```
[UnexpectedCharError]
Unexpected character: u'p' at line 24 col 15
```
which is the character `p` in `testcontainers[postgresql]`.
I would appreciate if someone can point to any workaround. Thanks!

```
poetry --version
Poetry version 1.0.5
```

**Comment by clintonroy** [comment]
If you try:
```
poetry add testcontainers[postgresql]
```

You'll get:
```
testcontainers = {extras = ["postgresql"], version = "^2.6.0"}

```

**Comment by a-ilango** [comment]
That helped. Appreciate the quick response @clintonroy !

**Comment by JulianFerry** [comment]
For anyone stumbling on this with the same issue as me:
- `poetry add apache-beam[gcp]` errors with `zsh: no matches found: apache-beam[gcp]`
- Writing `poetry add "apache-beam[gcp]"` fixed this

**Comment by tpvasconcelos** [comment]
@JulianFerry the issue you are experiencing is probably due to zsh's use of square brackets for [globbing](https://stackoverflow.com/a/30539963/6028742).

**Comment by virajkanwade** [comment]
This still seems to be an issue.

`poetry add 'piccolo[postgres]' 'piccolo[orjson]' 'piccolo[uvloop]'`

It only seems to add the last extra in the pyproject.toml.

If I run `poetry add 'piccolo[orjson]'` followed by `poetry add 'piccolo[postgres]'`

It removed orjson and only has `piccolo = {extras = ["postgres"], version = "^0.74.3"}` in toml.

**Comment by virajkanwade** [comment]
`piccolo = {extras = ["postgres", "orjson", "uvloop"], version = "^0.74.3"}`

**Comment by virajkanwade** [comment]
If you manually set pyproject.toml, it installs everything properly. So it seems to be an issue with `poetry add`

**Comment by sur0g** [comment]
`zsh` user here. I can confirm that it causes issues as @tpvasconcelos mentioned
