### ISSUE TITLE
poetry commands fail after upgrade to 0.12.0a1 - cleo is not installed

### ISSUE THREAD

**Issue by dmfigol** [sdispater/poetry#441]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 
- **Poetry version**: 0.12.0a1

## Issue
Upgraded poetry to 0.12.0a1 from 0.11.4 and now poetry commands fail because `cleo` package is not installed automatically:
```
-> % poetry self:update --preview
Updating to 0.12.0a1
  - Getting dependencies
  - Vendorizing dependencies
  - Updating poetry

poetry (0.12.0a1) successfully installed!
-> % poetry install
Traceback (most recent call last):
  File "/Users/dmfigol/.pyenv/versions/3.6.6/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/Users/dmfigol/.pyenv/versions/3.6.6/lib/python3.6/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/dmfigol/.pyenv/versions/3.6.6/lib/python3.6/site-packages/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```
Note: I am using pyenv

**Comment by sdispater** [comment]
Yes. That's something I am aware of and I will make a note on the release blog post for `0.12`.

Basically you can't use `self:update` to go from `0.11.x` to `0.12.x`, you will need to use the official installer for that.

```
POETRY_PREVIEW=1 curl -sSL https://raw.githubusercontent.com/sdispater/poetry/develop/get-poetry.py | python
```

**Comment by songww** [comment]
Why not drop this options?  `pip install -U` works good.
