### ISSUE TITLE
Git requirements are not present in setup.py

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#443]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed 
- **Poetry version**: Poetry 0.11.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rominf/39a9578ce644b77b47cab638b1020bee

## Issue
I have dependencies in git repositories in my `pyproject.toml` file. I run `poetry build`, unpack the archive, open `setup.py` and I see no git repositories in it. See attached gist.

Running `poetry install` works fine though.

**Comment by kipyin** [comment]
Having the same issue here too. 

I think what's needed is adding `dependency_links` argument to `setup()` in `setup.py`, where [`dependency_links` is the list of git deps](https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi).

To solve it, we have to differentiate the git deps from regular deps, and append a `dependency_links` argument with the git deps to the `extra` section in `poetry/masonry/buiders/sdist.py`:

https://github.com/sdispater/poetry/blob/3dd09c2c53e39856577ac8b336d08f65791b0421/poetry/masonry/builders/sdist.py#L162-L166

I've never worked with wheels before so I have no idea how to fix this for `.whl`.

**Comment by kipyin** [comment]
I think this is the same issue mentioned in https://github.com/pypa/pip/issues/6181 and #825.

**Comment by sdispater** [comment]
This is fixed as of version `0.12.12`
