### ISSUE TITLE
poetry update hangs forever on cloning protected git repository

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#446]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed 
- **Poetry version**: Poetry 0.11.5

## Issue

I successfully added private git repository using `poetry add --git  ssh://git@gitlab_url/username/repository_name.git package_name`. Then I ran `poetry update`, but it hanged forever on cloning repository (there: https://github.com/sdispater/poetry/blob/master/poetry/vcs/git.py#L99). The problem is that I have to authenticate using my ssh key for cloning repository, `git` asks for the passphrase, but I cannot enter it.

**Comment by androiddrew** [comment]
I too am trying to use Poetry for the first time, but having issues with my one package that is still on git and not pypi.  That counter just continues to run. Trying your export command didn't work either.

**Comment by timonbimon** [comment]
same issue here, have you guys found a solution?

**Comment by rominf** [comment]
@timonbimon, Yep. I just add the passphrase using `ssh-add` to `ssh-agent`.

**Comment by timonbimon** [comment]
ah cool, thank @rominf 

the second thing I needed to do to get it to work was adding Github's RSA key fingerprint (I assume it is basically anything that wants an interactive prompt)

**Comment by dsevero** [comment]
@timonbimon would you mind sharing exactly how that was done? I'm trying to add a dependency via ssh+git.

**Comment by timonbimon** [comment]
hmm I do not remember the exact steps, but my debugging strategy was basically to run a ssh+git command not involving poetry (like just doing a git clone for fun for example) and making sure that that worked without any input from me

**Comment by danihodovic** [comment]
This is still an issue in 1.1.0b2

**Comment by Mpreyzner** [comment]
I have the same issue with repos from git using https.
