### ISSUE TITLE
Packaging stub files

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#451]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Python packages can include stub files with type hints. They can be packaged this way: https://www.python.org/dev/peps/pep-0561/#packaging-type-information

Please make it possible to package them using `poetry`!

**Comment by sdispater** [comment]
This is automatically done by Poetry. Any non-Python file in your package will be packaged as `package_data`.

**Comment by rominf** [comment]
Thank you for your response.
