### ISSUE TITLE
Would be helpful for the docs to explain where the virtualenv will be created and how to control that 

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#452]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
It's unclear whether `poetry install` creates a virtualenv or whether I need to do this myself.
If it does create a virtualenv, it would be good to explain this.
If it does not, it would be good to point this out in the docs to save people accidentally polution their root python installation with their project.

**Comment by cjw296** [comment]
Hmm, maybe https://poetry.eustace.io/docs/basic-usage/#poetry-and-virtualenvs is the answer?
Would be helpful for the docs to explain where the virtualenv will be created and how to control that location (assuming that's possuble) :-)

**Comment by thernstig** [comment]
@cjw296 There is another discussion ongoing here as well https://github.com/sdispater/poetry/issues/214 that is slightly similar in nature. It is not about documentation, but moreso about to choose where to install the venv.

**Comment by thernstig** [comment]
Unstale

**Comment by sdispater** [comment]
The documentation already gives pointers to the location of the virtualenvs: https://poetry.eustace.io/docs/configuration/ and like mentioned above it's stated in https://poetry.eustace.io/docs/basic-usage/#poetry-and-virtualenvs that install will create a virtualenv if it's not running inside one already.

Closing this.
