### ISSUE TITLE
Poetry does not execute in the same directory when it finds pyproject.toml

### ISSUE THREAD

**Issue by slurps-mad-rips** [sdispater/poetry#458]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS High Sierra 10.13.6
- **Poetry version**: 0.11.5
- ~~Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file~~

## Issue

Hello! I've not attached a gist, as this is more a behavior problem. I *really* like that I can run poetry from any directory within my project and it will look up the path. However, when I'm running `poetry add`, or `poetry install`, it will execute from the directory I'm currently in, rather than where the `pyproject.toml` file is located. I ran into a bug that had me ripping my hair out. I realized that the package I was trying to install (`importlib_resources`) had a dependency that conflicted with the name of a module I had in the directory I was in. If it had executed from the location of the `pyproject.toml` this would not have happened. I did figure this out in the end, but it would be nice to not have to think or know about this when calling `poetry add` and friends.

**Comment by sdispater** [comment]
Could you test again with the latest stable release, and also with the latest `1.0.0` prerelease to see if the issue still occurs. Closing this for now but feel free to reopen if the issue still occurs.
