### ISSUE TITLE
Basic usage questions

### ISSUE THREAD

**Issue by apnewberry** [sdispater/poetry#460]
- How do I remove the virtualenv? I ended up doing it manually.
- How do I change the python version if I want to upgrade that? I tried editing pyproject.toml to `python = "3.7"` (from 3.6) and running `poetry install` but it didn't do the upgrade.
- ~~Is there a way to get the path of the virtualenv in one command?~~
- What is the cache?

**Comment by jgirardet** [comment]
please read the doc et issues. almost everything is there.
I can also find help in the discuss group

**Comment by apnewberry** [comment]
> - Is there a way to get the path of the virtualenv in one command?

Has an open issue here. https://github.com/sdispater/poetry/issues/401 Sorry I didn't look there before asking.

The other ones I was not able to figure out. What's the discuss group?

**Comment by jgirardet** [comment]
>     * How do I remove the virtualenv? I ended up doing it manually.
Yes for now you have to. You can create .venv dir in your folder if you want : https://poetry.eustace.io/docs/configuration/

> 
>     * How do I change the python version if I want to upgrade that? I tried editing pyproject.toml to `python = "3.7"` (from 3.6) and running `poetry install` but it didn't do the upgrade.
https://poetry.eustace.io/docs/basic-usage/#poetry-and-virtualenvs  and #82 

> 
>     * Is there a way to get the path of the virtualenv in one command?
#401 
> 
>     * What is the cache?
I'm not sure. I would the the already downloaded packages

**Comment by apnewberry** [comment]
@jgirardet Terrific, thank you for all the references! All extremely helpful.
