### ISSUE TITLE
Poetry remove causes package update

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#463]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed 
- **Poetry version**: Poetry 0.11.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rominf/e7e43bcec17b442127a449757bf41b1d

## Issue

I had `dacite` package as a dependency in `pyproject.toml`. I ran `poetry remove dactie` but instead of deleting I got package update:
```
poetry remove dacite
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies... (0.5s)


Package operations: 0 install, 1 update, 0 removals

Writing lock file

  - Updating dacite (0.0.16 -> 0.0.17)
```

**Comment by songww** [comment]
Are there other packages that depend on it?

**Comment by sdispater** [comment]
I am closing this issue.

If the problem still occurs feel free to reopen it.
