### ISSUE TITLE
auth file should only be readable by the user

### ISSUE THREAD

**Issue by wfscheper** [sdispater/poetry#464]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 28
- **Poetry version**: 0.11.5

## Issue
When I add credentials to a repository, I expect that the auth file is only accessible by my user. However, when I checked the file it is globally readable:
```shell
$ ls -l ~/.config/pypoetry/
total 8
-rw-r--r--. 1 wasche users 142 Oct  2 10:55 auth.toml
-rw-r--r--. 1 wasche users 117 Oct  2 10:54 config.toml
```

edit to fix version info block.

**Comment by songww** [comment]
You can fix this yourself. 
`chmod 0600 ~/.config/pypoetry/auth.toml`

**Comment by wfscheper** [comment]
@sdispater, would you be interested in a PR for this issue? I'm assuming it is a relatively simple change, but I'm new to poetry's code.

**Comment by sdispater** [comment]
This should now be fixed.
