### ISSUE TITLE
Poetry update doesn't update git repositories

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#467]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed 
- **Poetry version**: Poetry 0.11.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rominf/a3f70219b49becc287d167761ea887d0 

## Issue

I have `kg` library as git dependency. I push some comments to the `kg` repository, run `poetry update` in the project, that depends on this library but `poetry` doesn't update the library.

**Comment by rominf** [comment]
I have found that if I increase the version of libraries, they are updated. Nevertheless, it would be nice to have a flag to update dependencies unconditionally.

**Comment by phobologic** [comment]
I've ran into this too - was pretty sure it had to do with the fact that we didn't update the version of the package in the git repository, but hadn't gotten a chance to double check it.  Definitely agree it'd be nice if poetry could ignore the version on things like git repos.

**Comment by djrobstep** [comment]
Agree, this is really unexpected. 

Poetry update is meant to "Update dependencies as according to the pyproject.toml file."

That means git dependencies should get updated to the tip of the branch.

**Comment by sdispater** [comment]
This should be fixed in the latest `0.12.6` version.
