### ISSUE TITLE
Poetry remove doesn't remove package

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#468]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed 
- **Poetry version**: Poetry 0.11.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rominf/a3f70219b49becc287d167761ea887d0 

## Issue

I have `kg` library as git dependency. I remove it with `poetry remove kg` but nothing happens:
```
$ poetry remove kg
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies... (0.4s)


Package operations: 1 installs, 0 updates, 0 removals

Writing lock file

  - Installing peewee-async (0.6.0a0 8feebdf)
$ pip uninstall kg
Uninstalling kg-0.1.0:
  Would remove:
    /home/rominf/.pyenv/versions/3.6.6/envs/profile/lib/python3.6/site-packages/kg-0.1.0-py3.6.egg-info                                                              
    /home/rominf/.pyenv/versions/3.6.6/envs/profile/lib/python3.6/site-packages/kg/*                                                                                 
Proceed (y/n)? y
  Successfully uninstalled kg-0.1.0
```

**Comment by jobec** [comment]
I guess this is related to #648

**Comment by jacebrowning** [comment]
From your log, it definitely looks like `$ pip uninstall kg` is uninstalling a globally installed version of `kg`. Using `$ poetry run pip uninstall kg` would be more conclusive.

**Comment by sdispater** [comment]
I am closing this issue.

If the problem still occurs feel free to reopen it.

**Comment by PetterS** [comment]
@sdispater 

This is very important and I don't know of any way to do this.

Say several developers work on a project. One performs an update which removes a package from the pyproject and lock files. How will the other developers ever remove this package?

**Comment by grumbling-tom** [comment]
> Say several developers work on a project. One performs an update which removes a package from the pyproject and lock files. How will the other developers ever remove this package?

For anyone stumbling across this thread, it looks as though `poetry install --remove-untracked` would do the trick here.

**Comment by gaoming714** [comment]
poetry install --sync

--sync: Synchronize the environment with the locked packages and the specified groups.
--remove-untracked: Remove dependencies not presented in the lock file. (Deprecated, use --sync instead)
