### ISSUE TITLE
Support creating stub-only packages

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#475]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

[MyPy documentation](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages) explains how to create stub-only packages. It would be nice if Poetry supported stub-only packages. Current behaviour:
```
$ fd
ordered_set-stubs
pyproject.toml
LICENSE
README.md
ordered_set-stubs/__init__.pyi
$ poetry build
Skipping virtualenv creation, as specified in config file.
Building ordered_set-stubs (0.1.0)
                                                      
[ValueError]                           
No file/folder found for package ordered-set-stubs  
                                                      
build [-f|--format FORMAT]
```

**Comment by sdispater** [comment]
It's already supported. Just add the following to the `[tool.poetry]` section.

```toml
[tool.poetry]
# Basic package information

packages = [
    {include = "ordered_set-stubs"}
]
```

Then, if you run `poetry build` you should have stub-only distributions.

**Comment by sdispater** [comment]
You can have more information in the documentation: https://poetry.eustace.io/docs/pyproject/#packages

**Comment by rominf** [comment]
Thank you, @sdispater, it worked. Sorry didn't figured out myself.

**Comment by fsenart** [comment]
@sdispater right after version 1.0.0, in version 1.0.1, stub-only packages are no longer supported. One gets an `... is not a package."` error. This issue should be reopened.
