### ISSUE TITLE
Poetry resolving dependencies is amazingly slow

### ISSUE THREAD

**Issue by cprieto** [sdispater/poetry#476]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14
- **Poetry version**: 0.11.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/cprieto/b5996c4ffd2e77c7ab05253022c482bd

## Issue
I just created a new project with `poetry new` and just added one package, `petl`, I was surprised when I found out in a new project (which includes `pytest`) it took over _half an hour_ to install, yes, I know no cache was used, and yes, I know it has to download all the dependencies and handle their installation, but this time was insane.

I know this has been reported before in https://github.com/sdispater/poetry/issues/65 but maybe I am missing some discussion about how to improve this time, because honestly, waiting between 3min to 30min to install a package is too much, especially when the package size is small.

I included the output of my `time poetry add -vvv petl` command: https://gist.github.com/cprieto/ed5def2f51e8e16328770ebd76a6355e

**Comment by cprieto** [comment]
That is weird, a simple ping to files.pythonhosted.org or PyPI didn't help, but after doing a simple `traceroute` I found really weird jumps and delays so I think it is something really really wrong with my internet connection (or at least the way they route the packages).

Is there any way I can tell `poetry` to use a mirror in the same way `pip` does with `--use-mirrors`? maybe in that way I can diagnose what is happening and see if the situation improves.

**Comment by Zac-HD** [comment]
This is not an issue with Poetry, it's a problem with your internet connection and IMO that should be handled by other tools (e.g. a speed test, `traceroute`, etc), not Poetry.

**Comment by hangtwenty** [comment]
[for posterity]

Even aside from network or PyPI issues, sometimes clearing out the cache from `filelock`/`cachecontrol`, can help. (tangentially related to https://github.com/sdispater/poetry/issues/832 perhaps)

**Comment by cmoutafidis** [comment]
Not sure why this issue is closed, clearly there is something wrong with poetry
poetry install
Updating dependencies
Resolving dependencies... (64103.8s)

**Comment by mahendranbhathp** [comment]
I am also facing same issue with poetry 1.2.0

**Comment by clintonroy** [comment]
Please people, don't comment on closed bugs,. If you have a problem, please fill out the bug report, and give us all the details that we actually need to debug a problem. Saying your setup is slow does not help *at* all.
