### ISSUE TITLE
Make poetry-agent for storing repository passwords in memory

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#479]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

`ssh` has nice helper program called `ssh-agent` (https://www.ssh.com/ssh/agent). It asks passwords for ssh keys, stores them in memory and fills the passwords every time `ssh` asks for them. It also supports integration with other programs to get passwords from them. For example, KDE has integration with `ssh-agent` through `ksshaskpass`.

It would be nice to have similar program for `poetry`.

**Comment by hangtwenty** [comment]
Great thinking, it would be good to securely store credentials

My initial thoughts:

* maybe this could be done via plugin; not everyone will want same means of doing this, and dev vs production will likely do it differently
* maybe first option for dev:  https://pypi.org/project/keyring/
* personally in production I’d use AWS Secrets Manager (such that the authorization responsibility is basically shifted over to IAM)

**Comment by sdispater** [comment]
In the latest `1.0.0` beta release, credentials can be stored using the `keyring` package or you can use environment variables (see #1272)
