### ISSUE TITLE
Provide documentation for installing on macOS

### ISSUE THREAD

**Issue by rainyday** [sdispater/poetry#48]
I'm unclear how to actually install and use this on macOS.

According to https://github.com/sdispater/poetry/issues/36 there are no plans to support hombrew's python and the recommended method is to use pyenv. However, when using pyenv, the poetry command is only available in the env you've run the install script from which doesn't really work since we use virtualenvs for all our projects.

**Comment by sdispater** [comment]
It doesn't matter in which env poetry has been installed as long as it is available in your PATH.

So let's say you install Python 3.6.5 with `pyenv`:

```bash
pyenv install 3.6.5
```

and set it as your default Python

```bash
pyenv global 3.6.5
```

At this point you can install `poetry` the recommended way:

```
url -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```

Now, `poetry` is available globally and can manage any Python project.

If you already have virtualenvs and you activate them, `poetry` will use them without creating its own. If not, it will create one for you automatically.

**Comment by rainyday** [comment]
When I try running poetry when a virtualenv is activated I get the following message:

```
pyenv: poetry: command not found

The `poetry' command exists in these Python versions:
  3.6.5
```

**Comment by sdispater** [comment]
Well you should create your virtualenvs using `pyenv` so you can specifify which python versions it will use.

But, be aware that the recommended way to use `poetry` is to not create your virtualenvs yourself but rather let `poetry` do it automatically.

**Comment by rainyday** [comment]
This is using venvs created with pyenv. It looks to me that if you're using pyenv you have to install poetry separately in any venv you want to use it in. Is this correct?

**Comment by rainyday** [comment]
Gotcha, thanks for your help!

**Comment by nat-n** [comment]
What if one needs to switch back and forth between python versions? does this require installing poetry again for each python version?
