### ISSUE TITLE
Env.get_base_prefix() method is called as a class method

### ISSUE THREAD

**Issue by azag0** [sdispater/poetry#491]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry development  version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14 
- **Poetry version**: 0.12.0a3 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/262f30544b8df73997592576eab0f43a 

## Issue

```
10:33 ~/Code/Cellar/pyberny (master) [1] poetry install -vvv
                                                                    
[TypeError]                                          
get_base_prefix() missing 1 required positional argument: 'self'  
                                                                    
Exception trace:
 /opt/poetry/lib/python3.7/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /opt/poetry/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /opt/poetry/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /opt/poetry/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /opt/poetry/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /opt/poetry/lib/python3.7/site-packages/poetry/console/commands/env_command.py in initialize() at line 16
   o, self.poetry.package.name, cwd=self.poetry.file.parent
 /opt/poetry/lib/python3.7/site-packages/poetry/utils/env.py in create_venv() at line 127
   env = cls.get(cwd=cwd)
 /opt/poetry/lib/python3.7/site-packages/poetry/utils/env.py in get() at line 118
   base_prefix = cls.get_base_prefix()
```

a2e2c6525ab16a17 introduced method `Env.get_base_prefix()`
https://github.com/sdispater/poetry/blob/a2e2c6525ab16a17043ec09c7721b71bfeb581fc/poetry/utils/env.py#L202
but it is called as a class method in `Env.get()`
https://github.com/sdispater/poetry/blob/a2e2c6525ab16a17043ec09c7721b71bfeb581fc/poetry/utils/env.py#L109

**Comment by sdispater** [comment]
This is fixed in the latest release.
