### ISSUE TITLE
Support Semantic Versioning pre-release labels

### ISSUE THREAD

**Issue by Curly-Mo** [sdispater/poetry#492]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

[Semantic Versioning pre-releases](https://semver.org/#spec-item-9) are not supported by the `poetry version` nor the `poetry publish` commands. 

The `build` command names the sdist file differently from what the `publish` command looks for.
```pyproject.toml
[tool.poetry]
version = "0.1.1-alpha.0"
``` 
```sh
$ poetry publish --build
Building myproject (0.1.1-alpha.0)
 - Building sdist
 - Built myproject-0.1.1a0.tar.gz
Publishing myproject (0.1.1-alpha.0) to PyPI
[RuntimeError]
"myproject-0.1.1-alpha.0.tar.gz" does not exist.
```

Version bumping drops all pre-release labels 
```sh
$ poetry version
Bumping version from 0.1.1-alpha.0 to 0.1.1
```

**Comment by sdispater** [comment]
The bug in publishing has been fixed in commit ea420b8 on the `develop` branch. It will be available in the next `0.12` release.

Regarding bumping a prerelease version, just do:

```bash
poetry version prerelease
```

**Comment by Curly-Mo** [comment]
Fantastic! Thanks so much.
I couldn't find those `pre*` bump rules anywhere in the docs. But I see it now in the help text.

**Comment by sdispater** [comment]
This should be fixed in the latest release.
