### ISSUE TITLE
"quick" install command in README fails, expecting input

### ISSUE THREAD

**Issue by seansfkelley** [sdispater/poetry#499]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14
- **Poetry version**: 0.12.0

## Issue

Running `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python` per the README outputs:

```
Retrieving Poetry metadata

Before we start, please answer the following questions.
You may simple press the Enter key to keave unchanged.
Modify PATH variable? ([y]/n) Traceback (most recent call last):
  File "<stdin>", line 830, in <module>
  File "<stdin>", line 826, in main
  File "<stdin>", line 313, in run
  File "<stdin>", line 432, in customize_install
EOFError: EOF when reading a line
```

Looks like it's expecting input now, but of course curling the script onto disk and then executing it with `python` manually works fine.

**Comment by sdispater** [comment]
This should now be fixed!

**Comment by seansfkelley** [comment]
Looks fixed!
