### ISSUE TITLE
PosixPath TypeError with `poetry install` on 0.12.1

### ISSUE THREAD

**Issue by phobologic** [sdispater/poetry#504]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.13.6
- **Poetry version**: Poetry 0.12.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/phobologic/07c8a56f7f97b981ac046b9ee8d09a64

## Issue

We've been using poetry internally at my company for a project for a while now and it has worked well, but since updating to poetry .12.1, whenever we do a poetry install in a fresh (blank) environment, we end up getting this error:

```
[TypeError]
coercing to Unicode: need string or buffer, PosixPath found

Exception trace:
 /Users/mike/Library/Python/2.7/lib/python/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/mike/Library/Python/2.7/lib/python/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/mike/Library/Python/2.7/lib/python/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/mike/Library/Python/2.7/lib/python/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/mike/Library/Python/2.7/lib/python/site-packages/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /Users/mike/Library/Python/2.7/lib/python/site-packages/poetry/console/commands/env_command.py in initialize() at line 16
   o, self.poetry.package.name, cwd=self.poetry.file.parent
 /Users/mike/Library/Python/2.7/lib/python/site-packages/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /Users/mike/Library/Python/2.7/lib/python/site-packages/poetry/console/application.py in poetry() at line 60
   self._poetry = Poetry.create(os.getcwd())
 /Users/mike/Library/Python/2.7/lib/python/site-packages/poetry/poetry.py in create() at line 191
   shutil.move(old_lock, lock)
 /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py in move() at line 283
   if os.path.isdir(dst):
 /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py in isdir() at line 49
   st = os.stat(s)

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

Thanks for any help you can provide!

**Comment by rsiemens** [comment]
I also ran into this issue, renaming your `pyproject.lock` to `poetry.lock` was a work around that got me past it.

**Comment by sdispater** [comment]
I just published the `0.12.2` release which should fix the issue!

**Comment by phobologic** [comment]
Thanks @sdispater - I upgrade to 0.12.2, but one thing I noticed is that now it doesn't show the virtualenv path when I do a `poetry debug:info`:

```
# poetry debug:info

Poetry
======

 * Version: 0.12.2
 * Python:  2.7.10


Virtualenv
==========

 * Python:         2.7.10
 * Implementation: CPython
 * Path:           NA


System
======

 * Platform: darwin
 * OS:       posix
 * Python:   /System/Library/Frameworks/Python.framework/Versions/2.7
```

It does on 0.11.5

**Comment by phobologic** [comment]
(btw, 0.12.2 does fix the original issue - I can open another for the virtualenv path if you want!)

**Comment by sdispater** [comment]
@phobologic Yes please. It will be easier to track the issue that way.

**Comment by phobologic** [comment]
Done, thanks (#505)!  Closing this issue, since 0.12.2 fixed it.
