### ISSUE TITLE
Virtualenv Path no longer shown in debug:info with 0.12.2

### ISSUE THREAD

**Issue by phobologic** [sdispater/poetry#505]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.13.6
- **Poetry version**: 0.12.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/phobologic/07806ca3abbc52dbb73b3b4d0ace55e1

## Issue

poetry 0.12.2 no longer displays the virtualenv path when `poetry debug:info` is run, and instead displays NA.

**Comment by Sharparam** [comment]
As a potential workaround, it seems possible to run `debug:info` with the `run` command to get the virtualenv path:

```
poetry run poetry debug:info
```

Not ideal obviously, but at least works to extract the path in my very limited testing.

**Comment by sdispater** [comment]
The issue with the difference between the project name and the virtual environment name, leading to this issue, has been fixed in the latest beta release of the `1.0.0` version.
