### ISSUE TITLE
Poetry fails to run on Windows

### ISSUE THREAD

**Issue by epage** [sdispater/poetry#518]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 0.12.2

## Issue

Summary: poetry.bat doesn't point to the actual path poetry gets installed to, causing it to fail

I ran
```
wget --no-check-certificate https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
python3 get-poetry.py
```

The installation completed and told me:
```
To get started you need Poetry's bin directory (%USERPROFILE%\AppData\Roaming\.poetry\bin) in your `PATH`
environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.
```

I opened a new shell and ran `poetry`.
```
poetry
python: can't open file 'C:\Users\<edited>.poetry/bin/poetry': [Errno 2] No such file or directory
```

I opened `poetry.bat` and found
```
@echo off
python %USERPROFILE%/.poetry/bin/poetry %*
```

poetry.bat seems to point to an invalid path.

### Workaround

Manually edit the file and fix the path

**Comment by sdispater** [comment]
That's weird since your home directory seems to point to `%USERPROFILE%\AppData\Roaming\` while it should point to `%USERPROFILE%`.

Basically to detect the user's home directory, the `get-poetry.py` script uses `os.path.expanduser(path)` which in your case seems to give `%USERPROFILE%\AppData\Roaming\`.

I am not a Windows user so I am not sure if this is common.

Anyway, I think it's just a matter of generating the `poetry.bat` file dynamically by inserting the proper home value when writing it.

**Comment by sdispater** [comment]
I just pushed a new version of the installer which should fix the issue. Could you test reinstalling Poetry to see if the proper path is now used in `poetry.bat`?

**Comment by epage** [comment]
That worked!

**Comment by bfailing** [comment]
I am having the same issue.  Windows 10 and Poetry version 0.12.10.

My poetry.bat file was initially:
```
@echo off
python "%USERPROFILE%\.poetry\bin\poetry" %*
````
To get it to work properly, I changed it to the following (USERNAME represents the actual name of the user):
```
@echo off
python "C:\Users\USERNAME\.poetry\bin\poetry" %* 
```
