### ISSUE TITLE
Poetry install removes dependencies installed by other means

### ISSUE THREAD

**Issue by chrisrink10** [sdispater/poetry#533]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14 Mojave 
- **Poetry version**: 0.12.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/chrisrink10/2af2e425d68733d28be9f000865c3751

## Issue
Since Poetry `0.12.3`, Poetry removes dependencies installed in the virtual environment by other means. I think this is probably a good default behavior, since Poetry is intended to manage project dependencies _however_ it causes problems with Tox. 

We run a few tasks such as linting, code formatting verification, and package vulnerability checks using Tox to install dependencies in its virtual environment (rather than specifying these otherwise unused dependencies as dev dependencies with Poetry). 

When running `poetry install` in a Tox context, I found that Poetry now seems to uninstall unused dependencies, which causes Tox targets to fail. I would like if we could disable this behavior with a flag (like `--no-clean`), since it is disruptive in this context.

**Comment by sdispater** [comment]
There is no reason for Poetry to uninstall anything other than what's in the lock file, so I am not sure what's happening here.

Could you provide an easy to reproduce test case?

**Comment by sdispater** [comment]
Closing this issue.

If the problem still occurs, feel free to create a new issue.
