### ISSUE TITLE
poetry init does not work with Git Bash on Windows 10

### ISSUE THREAD

**Issue by davegallant** [sdispater/poetry#543]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 0.12.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

I can get `poetry init` working with cmd.exe on Windows 10, but on Git Bash (mintty), there are no prompts and execution ends with the creation of a rather bare pyproject.toml.

**Comment by AnTiZ** [comment]
Technically it's not Git Bash that's causing issues, it's Mintty.

Whether you're using CMD, PowerShell or Git Bash, as long as you are using the Windows Console/ConHost, this issue won't occur.

To quote the Git for Windows setup:

> Windows console programs (such as interactive Python) must be launched via `winpty` to work in MinTTY.

Or the Mintty website:

> […] mintty is not a full replacement for the Windows Console window […]. While native console programs with simple text output usually work fine, interactive programs often have problems [...].
