### ISSUE TITLE
Colors in Windows Console

### ISSUE THREAD

**Issue by AnTiZ** [sdispater/poetry#548]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Poetry currently suppresses ANSI color codes on Windows. (ref #159)
Modern versions of Windows do in fact support a large number of VT sequences, but applications have to opt-in to this behavior.

### Details
Starting with Windows 10 TH2, also known as version 1511, virtually all commonly used VT sequences are supported. However, due to backwards compatibility, applications need to set the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` console flag to activate this functionality.

The CPython interpreter does not set this flag automatically.
See [this comment](https://github.com/Microsoft/WSL/issues/1173#issuecomment-254250445) for more details on the version numbers and some confusion regarding the availability of this feature.

Side note: Build `10.0.14931` is when the console (additionally) gained support for 24-bit colors/truecolor.

## Expected behavior / Enhancement
Check the Windows version upon launch (e.g. with `platform.version()`).
If the version is too old (e.g. Windows 7, Windows 10 TH1, etc.) continue to suppress VT sequences by default, otherwise set the appropriate console flag and emit ANSI codes/VT sequences.

## Demonstration
```python3
import ctypes

print("\033[38;5;208mpeach\033[0;00m")

kernel32 = ctypes.windll.kernel32
kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)

print("\033[38;5;208mpeach\033[0;00m")
```
[This might serve as a more thorough example of an implementation.](https://github.com/rg3/youtube-dl/issues/15758#issuecomment-370630896).

The registry key `HKEY_CURRENT_USER\Console\VirtualTerminalLevel` controls the default behavior of this functionality (opt-in vs opt-out). Using that and `poetry --ansi` I can indeed get colored output.

---

Should this be handled in [sdispater/cleo](https://github.com/sdispater/cleo) instead?

**Comment by fralik** [comment]
For people using ConEmu and who still do not have colors. You have to enable settings `Inject ConEmuHk` and `ANSI and xterm sequences` in ConEmu settings. You will find it in `Settings -> Features`.

**Comment by sdispater** [comment]
I think this should be fixed in the latest beta release.
