### ISSUE TITLE
Error on $ poetry show

### ISSUE THREAD

**Issue by Ublimjo** [sdispater/poetry#55]
[ImportError]    
  cannot import name 'where'

**Comment by sdispater** [comment]
Could you provide more information?

You can also execute the command in verbose mode to have a complete stacktrace:

```bash
poetry show -v
```

**Comment by Ublimjo** [comment]
Ohh, I have another error

[RuntimeError]
  Poetry could not find a pyproject.toml file in /data/data/com.termux/files/home


Exception trace:  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/cleo/application.py in run() at line 94  
   status_code = self.do_run(input_, output_)  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/poetry/console/application.py in do_run() at line 74  
   return super(Application, self).do_run(i, o)  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/cleo/application.py in do_run() at line 197  
   status_code = command.run(input_, output_)  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/poetry/console/commands/command.py in run() at line 22  
   return super(BaseCommand, self).run(i, o)  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/cleo/commands/base_command.py in run() at line 136  
   self.initialize(input_, output_)  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/poetry/console/commands/venv_command.py in initialize() at line 16  
   self._venv = Venv.create(o, self.poetry.package.name)  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/poetry/console/commands/command.py in poetry() at line 10  
   return self.get_application().poetry  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/poetry/console/application.py in poetry() at line 49  
   self._poetry = Poetry.create(os.getcwd())  
 /data/data/com.termux/files/home/.local/lib/python3.6/site-packages/poetry/poetry.py in create() at line 75  
   'Poetry could not find a pyproject.toml file in {}'.format(cwd)  

show [-t|--tree] [-l|--latest] [-o|--outdated] [--] [<package>]

**Comment by Ublimjo** [comment]
My home path is '/data/data/com.termux/files/home/'

**Comment by sdispater** [comment]
You have to execute `poetry show` inside your project.
