### ISSUE TITLE
ModuleNotFoundError: No module named 'cleo' after poetry self:update

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#553]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed
- **Poetry version**: 0.12.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Irrelevant

## Issue

I have updated poetry using the command:
```shell
$ poetry self:update
Updating to 0.12.4                                                                                                                                                      
  - Getting dependencies
  - Vendorizing dependencies
  - Updating poetry

poetry (0.12.4) successfully installed!
```

Then if run any command I get this:
```shell
$ poetry -vvv --version
Traceback (most recent call last):
  File "/home/rominf/.local/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/home/rominf/.pyenv/versions/3.6.5/envs/pendulum/lib/python3.6/site-packages/poetry/console/__init__.py", line 1, in <module>                                  
    from .application import Application
  File "/home/rominf/.pyenv/versions/3.6.5/envs/pendulum/lib/python3.6/site-packages/poetry/console/application.py", line 6, in <module>                               
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

I have tried to install `cleo` with `pip`, but it didn't help. The only thing that helped me is the `poetry` installation using `pip`.

**Comment by sdispater** [comment]
Did you upgrade with `self:update` from version `0.11.5`? I think this must be it and it is not supported as explained in the [release notes](https://poetry.eustace.io/blog/poetry-0-12-0-is-out.html).

You might want to uninstall `poetry` completely and reinstall with the recommended installer.

```bash
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```

**Comment by rominf** [comment]
@sdispater, OK, thanks. Didn't read the release notes. Can you handle this in the future and give the user installation instructions if `poetry` can't be updated the normal way?

**Comment by crgarcia12** [comment]
I leave this comment in here because it was the first search result I got:
If you are running on Wndows 10 + Python 3.8, then you need to install the preview version that contains a fix for the issue:

`curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_PREVIEW=1 python
`

**Comment by AndreGuerra123** [comment]
I have an docketing image with:

```
FROM alpine:edge
RUN apk add --no-cache alpine-sdk poetry --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
```

Which worked perfectly but now it fails. A couple days ago was ok. Something went wrong because I'm getting Cleo dependency missing.

**Comment by Steffo99** [comment]
@crgarcia12 Had the same problem on Arch Linux, the fix worked there too :tada:

**Comment by lucastamoios** [comment]
Just documenting that I was having the same problem, even after upgrading `poetry`. As I just had installed python 3.8, I had to make

    sudo cp -r $HOME/.poetry/lib/poetry/_vendor/py3.7 $HOME/.poetry/lib/poetry/_vendor/py3.8

to be able to run poetry correctly. Now it is fine!

**Comment by sthysel** [comment]
@lucastamoios  works for me to, I'd get rid of the 'sudo' though.

**Comment by crgarcia12** [comment]
> Just documenting that I was having the same problem, even after upgrading `poetry`. As I just had installed python 3.8, I had to make
> 
> ```
> sudo cp -r $HOME/.poetry/lib/poetry/_vendor/py3.7 $HOME/.poetry/lib/poetry/_vendor/py3.8
> ```
> 
> to be able to run poetry correctly. Now it is fine!

That is for linux and mac, for windows you still need the preview :'(

**Comment by CarlosDomingues** [comment]
I just experienced this issue while setting up a new dev environment in a Windows 10 machine.

Since I rely on a feature that is currently broken in poetry v1.0-beta (poetry config settings.virtualenvs.in-project true) I ended up having to downgrade Python from 3.8 to 3.7.4.

**Comment by finswimmer** [comment]
> Since I rely on a feature that is currently broken in poetry v1.0-beta (poetry config settings.virtualenvs.in-project true) I ended up having to downgrade Python from 3.8 to 3.7.4.

The syntax has changed to `poetry config virtualenvs.in-project = true`

**Comment by CarlosDomingues** [comment]
@finswimmer I tried again and here is what worked for me (Powershell@Windows10 + `python 3.8.0` + `poetry 1.0.0b5`):

```Powershell
poetry config virtualenvs.in-project true
poetry update -vvv
```

Before (Powershell@Windows10 + `python 3.7.4` + `poetry 0.12.17`):

```Powershell
poetry config settings.virtualenvs.in-project true
poetry -vvv update
```

**Comment by finswimmer** [comment]
Oops, of course without `=`.

Fixed it :laughing:

**Comment by kigawas** [comment]
> I leave this comment in here because it was the first search result I got:
> If you are running on Wndows 10 + Python 3.8, then you need to install the preview version that contains a fix for the issue:
> 
> Delete the installation removing the `.poetry` folder from `C:\Users\<your user>`
> 
> Then run this command:
> `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_PREVIEW=1 python `
> 
> Or, in PowerShell, you can run this:
> 
> ```
> Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py -OutFile get-poetry.py
> python .\get-poetry.py --preview
> Remove-Item .\get-poetry.py
> $env:Path += ";$env:USERPROFILE\.poetry\bin"
> ```

this will break on Python 3.5

**Comment by dimaqq** [comment]
Just pasting a note here that trying to use Python-3.9 hits same error with `poetry==1.0.0 ~ poetry==1.0.3` 

Solved by `pushd ~/.poetry/lib/poetry/_vendor/; ln -s py3.8 py3.9`
Followed by `collections.abc` fix.

**Comment by CircleOnCircles** [comment]
install poetry with `pipx` fixed
`pipx install poetry`

**Comment by MichaelSainsburys** [comment]
> I experienced this issue today due to an old Poetry binary being in `~/.poetry` and that being included in my `$PATH` in `~/.bashrc` ahead of the new binary. Once I fixed that, it was resolved.

How did you do this?

**Comment by nyuszika7h** [comment]
I just did `rm -rf ~/.poetry` and that solved the issue.

**Comment by MostHated** [comment]
> install poetry with `pipx` fixed `pipx install poetry`

I tried that based on your recommendation. The result was as follows:

```sh
❯ poetry self update
  RuntimeError
  Poetry was not installed with the recommended installer. Cannot update automatically.

  at .local/pipx/venvs/poetry/lib/site-packages/poetry/console/commands/self/update.py:389 in _check_recommended_installation
      385│         current = Path(__file__)
      386│         try:
      387│             current.relative_to(self.home)
      388│         except ValueError:
    → 389│             raise RuntimeError(
      390│                 "Poetry was not installed with the recommended installer. "
      391│                 "Cannot update automatically."
      392│             )
      393│
```

**Comment by clintonroy** [comment]
> > install poetry with `pipx` fixed `pipx install poetry`
> 
> I tried that based on your recommendation. The result was as follows:

If you install something with pipx, upgrade it with pipx:

pipx upgrade poetry

Same general rule would apply for any packaging/distribution system.

**Comment by hoishing** [comment]
I think this problem is caused by compatibility of python3.10
In Windows, I work it around by installing python3.9 and then edit the `%USERPROFILE%\.poetry\bin\poetry.bat` file, specifying the use of python3.9 instead of my default python (3.10) like this
`%LOCALAPPDATA%\Programs\Python\Python39\python.exe "%USERPROFILE%\.poetry\bin\poetry" %*`

I guess linux / macOS can work around it by the similar approach, changing the first line of  `.poetry/bin/poetry`, that is `#!/usr/bin/env python` to python3.9

**Comment by Mapachana** [comment]
I had this problem a few days ago, and I've tried to solve it.
I have made a docker container that has poetry and python 3.10 installed.
I think I figured out all the missing modules that poetry needs, so I also made a list to install them using pip on your personal computer.
My repository is: https://github.com/Mapachana/Python-3.10-with-poetry
And the docker image can be found here: https://hub.docker.com/repository/docker/mapachana/python3.10-with-poetry

**Comment by hoishing** [comment]
@Mapachana yes, indeed poetry 1.11.12 just missing some dependencies in python 3.10. Installing those dependencies with pip solved the problem, thanks ~

**Comment by TahirJalilov** [comment]
first impression of the newly installed poetry

 ✘  ~  poetry self:update
Traceback (most recent call last):
  File "/home/tahir/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/home/tahir/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/tahir/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'

my python version is 3.10.1

**Comment by PRINCEOYEBOLA** [comment]
Please I am trying using poetry on vbstudio and this is the error I encountered. Note this once worked perfectly but while trying to work on it again, the error was raised, what can I do?

"C:\Users\USER\Desktop\obed>poetry add django
Traceback (most recent call last):
  File "C:\Users\USER\.poetry\bin\poetry", line 17, in <module>
    from poetry.console import main
  File "C:\Users\USER\.poetry\lib\poetry\console\__init__.py", line 1, in <module>
    from .application import Application
  File "C:\Users\USER\.poetry\lib\poetry\console\application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'"

**Comment by hoishing** [comment]
@PRINCEOYEBOLA since poetry 1.1.12 is missing some dependencies in python3.10.1 on Windows. You may work around by installing them 
`pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`

**Comment by PRINCEOYEBOLA** [comment]
Thank you for your response. Grateful for it.

**Comment by Ben-Hampson** [comment]
> @PRINCEOYEBOLA since poetry 1.1.12 is missing some dependencies in python3.10.1 on Windows. You may work around by installing them `pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`

Thank you. I also had to do this to get poetry 1.1.12 to run in python 3.10.1 on macOS. I installed python using `pyenv`.

**Comment by dhensen** [comment]
> @PRINCEOYEBOLA since poetry 1.1.12 is missing some dependencies in python3.10.1 on Windows. You may work around by installing them `pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`

Thanks. I dont totally get why this is necesarry all of a sudden... I did not read all post... 
When installing above dependencies, `poetry shell` still did not work. In order to fix that I needed to also install `pexpect` and `shellingham`, so the complete list will be:
```pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile pexpect shellingham```

**Comment by nextmat** [comment]
If you are running into this with poetry 1.1.12 and python 3.10, [this may also help](https://github.com/python-poetry/poetry/issues/4846).

**Comment by ephes** [comment]
Experienced this today trying to upgrade from 1.1.11 to 1.1.12 on osx. "Solved" it by removing ~/.poetry and reinstalling it from scratch. Ran into it again after trying to use it in an virtualenv created by virtualfish. After "pip install poetry" inside the virtualenv it worked, but uhm.

**Comment by amberliuwong** [comment]
Just chiming in to say that the `pip install` fix above also works for Windows 11!

**Comment by Rajeeban-A** [comment]
> @PRINCEOYEBOLA since poetry 1.1.12 is missing some dependencies in python3.10.1 on Windows. You may work around by installing them `pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`

This approch working well with Windows 11 and Python 3.10.1 😂😂😂

**Comment by schlich** [comment]
I went the pip install route, and instead of typing out all the dependencies i just tried `pip install poetry` and it seemed to work fine.  YMMV

**Comment by schlich** [comment]
> @schlich, `pip install poetry` does not give the same result though. It installs poetry in your global interpreter site-packages, which should be avoided, IMO.

Fair enough.  I actually was going to invite people to criticize my method in my comment, but I forgot 😅.  I'll stick to this for now though for funsies until the 3.10 issues are fixed.

**Comment by Bobronium** [comment]
> I'll stick to this for now

Sure. 

For those who'd rather install poetry in a separate venv, I'd recommend solution mentioned in https://github.com/python-poetry/poetry/issues/553#issuecomment-1138702188:
```shell
pip install pipx-in-pipx && pipx install poetry
```
This will create two venvs: one for pipx and second for poetry, both will be available globally.

**Comment by padrepitufo** [comment]
had the issue and the fix for me was to stop using the older install as mentioned in this stackoverflow answer https://stackoverflow.com/a/69152670/2128265
