### ISSUE TITLE
Cant install tablib

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#555]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
`poetry add tablib` in an empty poetry venv will result in 

    [AttributeError]
    'NoneType' object has no attribute 'requires'

Whats wrong with that library? I can install it with pip, but poetry refuses.

**Comment by sdispater** [comment]
This is the same error as in #506.

It has already been fixed in commit 69f2f6d. I will try to cut a new release this week.

Closing for now in favor of #506.

**Comment by patarapolw** [comment]
`wordcloud` is another one. Hope it will also be fixed.
