### ISSUE TITLE
Does poetry support a src/ layout?

### ISSUE THREAD

**Issue by Tinche** [sdispater/poetry#56]
Hi,

I am considering poetry for a new project at work. Does it support having the project files in a src/ subdirectory? How do I tell it where to look for my project files?

Cheers!

**Comment by sdispater** [comment]
Currently no, unfortunately. However, this is planned and might make it in the next feature release.

I'll keep you posted.

**Comment by Tinche** [comment]
Thanks! Poetry looks very promising!

**Comment by sdispater** [comment]
It is now implemented in the `develop` branch (0bff3b1) and will be available in the next `0.9.0` release.

**Comment by sdispater** [comment]
Release `0.9.0` is out!

**Comment by pawelad** [comment]
Quick question - does it _just_ work? I was looking for info about this before I actually start converting my packages. At the moment I do something like [this](https://github.com/pawelad/pymonzo/blob/master/setup.py#L52-L53):

```
packages=find_packages(where='src'),
package_dir={'': 'src'},
```

Will Poetry just recognize that and do it for me? That would be cool : )
And if so, I think a mention in the README (docs?) would be helpful. I'd be happy to help.

**Comment by sdispater** [comment]
You can check https://github.com/sdispater/poetry/issues/92#issuecomment-387092703 to see the `src/` layout that is supported.

**Comment by ketozhang** [comment]
Please add documentations for this to the following:

https://python-poetry.org/docs/libraries/
https://python-poetry.org/docs/pyproject/#packages

**Comment by djbrown** [comment]
@ketozhang I just found the documentation: https://python-poetry.org/docs/cli/#new (see last two paragraphs).
I didn't have to change packages for my setup to work.

**Comment by epogrebnyak** [comment]
Just to repeat from the docs: 

  If you want to use a src folder, you can use the --src option:

poetry new --src my-package

**Comment by MassihEydavi** [comment]
source: https://browniebroke.com/blog/convert-existing-poetry-to-src-layout/
```
poetry new --src my-package

  packages = [
-     { include = "my_package" },
+     { include = "my_package", from = "src" },
  ]
```
