### ISSUE TITLE
Uninstall doesn't remove path

### ISSUE THREAD

**Issue by hyperknot** [sdispater/poetry#565]
- **OS version and name**: macOS 10.13.6
- **Poetry version**: latest

## Issue
I've installed Poetry using the official 
```
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```

I've uninstalled Poetry using the official
```
python get-poetry.py --uninstall
```

Poetry said it's removed from PATH.
Actually it's not.

```
export PATH="$HOME/.poetry/bin:$PATH"
```

Is still at the end of ~/.bash_profile.

**Comment by 42B** [comment]
https://github.com/sdispater/poetry/blob/5c86d1dfb6b2c8c8b15c0d9522994ee24907e81e/get-poetry.py#L685-L689

https://github.com/sdispater/poetry/blob/5c86d1dfb6b2c8c8b15c0d9522994ee24907e81e/get-poetry.py#L703-L704

**Comment by sdispater** [comment]
@42B Seems like something is missing 😅

**Comment by sdispater** [comment]
This should now be fixed.
