### ISSUE TITLE
Compare api and performance of poetry to pipenv 

### ISSUE THREAD

**Issue by cs01** [sdispater/poetry#568]
Adding a section in the readme (or perhaps a different document) that shows how each tool can be used to accomplish the same thing would be helpful to pipenv users interested in trying poetry.  

Showing performance benchmark comparisons between the two tools would also be interesting. i.e. time to generate lock files.

**Comment by vlcinsky** [comment]
Good idea. Main issue with Pipenv is that it claims to be "packaging tool" while it is not.
What pipenv (and poetry) does very well is to create, maintain and share well defined virtual environment.

Pipenv is great for application deployment. When it comes to python package (thus packaging) development, Pipenv is not the tool to use (or not the only one needed).

With poetry, packages are created easily.
If you need to define and distribute application virtual environment, poetry may do the work too by simply creating a python package for it.

**Comment by stephsamson** [comment]
A [section in the README](https://github.com/sdispater/poetry#what-about-pipenv) has been added though benchmark comparisons has not been added yet.

I'll add [this blog post by John Franey for now](https://johnfraney.ca/posts/2019/03/06/pipenv-poetry-benchmarks-ergonomics/) to show his benchmarking between Poetry and Pipenv in case someone stumbles upon this via a search engine.

For now, I will close this issue.
