### ISSUE TITLE
Virtualenv is not detected.

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#57]
virtualenv .venv
.venv/bin/pip install poetry
poetry debug:info 
Shows I have a virtualenv at /home/buriy/.cache/pypoetry/virtualenvs/myproject-py3.6

**Comment by sdispater** [comment]
You have to activate your virtualenv for it to be detected.

And you should not install `poetry` in your virtualenv but globally.

**Comment by buriy** [comment]
But you wrote in #9 that virtualenvs are properly supported... A mistake?
And anyway I want to put .venv into the project folder, not in ~/.cache/pypoetry ...

**Comment by sdispater** [comment]
But you have to activate your virtualenv for it to be picked up by `poetry`. If you do not do that `poetry` will have to create its own to work isolated.

**Comment by buriy** [comment]
And how to activate the virtualenv?
I haven't found any docs on that action so far...

**Comment by buriy** [comment]
Thanks, got it now. Would you make it work *without* a virtualenv activate?

**Comment by sdispater** [comment]
I don't see how, since `poetry` has no way of knowing where your virtualenv resides if it's not activated.

So if you don't want to activate it each time, you can let `poetry` create its own virtualenv.

**Comment by buriy** [comment]
@sdispater it is *activated* by running the poetry command from inside the virtualenv.
This can be checked like this: https://stackoverflow.com/a/42580137/217895
Or do you mean this kind of activation can be confusing?

**Comment by buriy** [comment]
And I guess #60 should help you with the python path detection for the virtualenvs .

**Comment by brettdh** [comment]
> And you should not install poetry in your virtualenv but globally.

Why? Will something break?

**Comment by buriy** [comment]
@sdispater and what about different versions of python? What if system python version is 2.7 ?
You said that poetry is only going to work with python 3.6+ .

**Comment by bersace** [comment]
@buriy for myself, i install poetry in user directory with `pip install --user`. poetry works well on Py3.5 too.

Really, poetry is like pip, just install in globally, either in /usr/local/bin or in ~/.local/bin. `npm` does it too.

**Comment by sdispater** [comment]
Commit 74614a4 in the `develop` branch adds support for `.venv` detection. It will be available in the next `0.9.0` release.

**Comment by sdispater** [comment]
@merwok Yes, I wouldn't say that `poetry` is like `pip` since you don't have to install poetry in every single virtualenv. `poetry` will detect if you already are in a virtualenv or create its own. So you only need to install it once.

**Comment by sdispater** [comment]
Release `0.9.0` is out!
