### ISSUE TITLE
Typo on https://poetry.eustace.io/

### ISSUE THREAD

**Issue by 42B** [sdispater/poetry#574]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I did a quick search through the repo but I can't seem to find the html for the main page, https://poetry.eustace.io/

`dependendency` -> `dependency` ?

![dependendency](https://user-images.githubusercontent.com/37713517/47623126-ccdfb380-dad2-11e8-8d58-9fb248e86daf.png)

**Comment by sdispater** [comment]
Thanks for reporting this. It is now fixed.

**Comment by 42B** [comment]
@sdispater 

Thanks for your time and for building `poetry`!

**Comment by kaedroho** [comment]
Hello, this seems to have returned on the homepage.

**Comment by ThibaultLemaire** [comment]
Yes, on https://python-poetry.org/. Noticed it as well.
