### ISSUE TITLE
poetry update doesn't update all dependencies

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#575]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed
- **Poetry version**: 0.12.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rominf/2fd9b94b5b469783787f96f65e225bc1

## Issue

I have `aioify` as a dependency, which in turn depends on `module-wrapper`. I committed some changes to the repository and pushed them to PyPI. When I run `poetry update` I expect `poetry` to update `module-wrapper`, but nothing happens. `pip install -U module-wrapper` works fine.

**Comment by sdispater** [comment]
This is sometimes due to the cache and Poetry does not see the new releases until the cache is invalidated.
