### ISSUE TITLE
Fails to resolve dill. How to force it to use a specific version?

### ISSUE THREAD

**Issue by buriy** [sdispater/poetry#58]
Fails to resolve dill. 
Why it has to check all these versions at all?
This takes more than 5 minutes!

pyproject.toml :
[tool.poetry]
name = "spacy-ru"
version = "0.1.2"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "*"
spacy = "^2.0"
pymorphy2 = "^0.8.0"
dill = "^0.2.7"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
ipython = "^6.3"

$ poetry install -vvv
Updating dependencies
:   0: Starting resolution (2018-04-19 23:03:24.108409)
:   0: Requested dependencies: ['dill (^0.2.7)', 'spacy (^2.0)', 'pymorphy2 (^0.8.0)', 'pytest (^3.5)', 'ipython (^6.3)']
Resolving dependencies
:   0: Getting dependencies for dill-0.2.7.1
:   0: Getting dependencies for dill-0.2.7
:   0: Creating possibility state for dill (^0.2.7) (1 remaining)
:   1: Attempting to activate [dill-0.2.7, dill-0.2.7.1]
:   1: Activated dill at [dill-0.2.7, dill-0.2.7.1]
:   1: Requiring nested dependencies ()
:   1: Getting dependencies for spacy-2.0.12.dev0
:   1: Getting dependencies for spacy-2.0.11
:   1: Getting dependencies for spacy-2.0.11.dev0
:   1: Getting dependencies for spacy-2.0.10
:   1: Getting dependencies for spacy-2.0.10.dev0
:   1: Getting dependencies for spacy-2.0.9
:   1: Getting dependencies for spacy-2.0.8
:   1: Getting dependencies for spacy-2.0.7
:   1: Getting dependencies for spacy-2.0.6
:   1: Getting dependencies for spacy-2.0.6.dev0
:   1: Getting dependencies for spacy-2.0.5
:   1: Getting dependencies for spacy-2.0.5.dev0
:   1: Getting dependencies for spacy-2.0.4
:   1: Getting dependencies for spacy-2.0.4.dev0
:   1: Getting dependencies for spacy-2.0.3
:   1: Getting dependencies for spacy-2.0.3.dev0
:   1: Getting dependencies for spacy-2.0.2
:   1: Getting dependencies for spacy-2.0.2.dev0
:   1: Getting dependencies for spacy-2.0.1
:   1: Getting dependencies for spacy-2.0.1.dev0
:   1: Getting dependencies for spacy-2.0.0
:   0: Creating possibility state for spacy (^2.0) (21 remaining)
:   2: Attempting to activate [spacy-2.0.12.dev0]
:   2: Unwinding for conflict: spacy (^2.0) to 1
:   0: Creating possibility state for spacy (^2.0) (12 remaining)
:   2: Attempting to activate [spacy-2.0.11]
:   2: Activated spacy at [spacy-2.0.11]
:   2: Requiring nested dependencies (numpy (>= 1.7.0.0), murmurhash (< 0.29.0.0, >= 0.28.0.0), cymem (< 1.32.0.0, >= 1.30.0.0), preshed (< 2.0.0.0, >= 1.0.0.0), thinc (< 6.11.0.0, >= 6.10.1.0), plac (< 1.0.0.0, >= 0.9.6.0), pathlib (*), ujson (>= 1.35.0.0), dill (< 0.3.0.0, >= 0.2.0.0), regex (== 2017.4.5.0))
:   2: Getting dependencies for dill-0.2.7.1
:   2: Getting dependencies for dill-0.2.7
:   2: Getting dependencies for dill-0.2.6
:   2: Getting dependencies for dill-0.2.5
:   2: Getting dependencies for dill-0.2.4
:   2: Getting dependencies for dill-0.2.3
:   2: Getting dependencies for dill-0.2.2
:   2: Getting dependencies for dill-0.2.1
:   2: Getting dependencies for dill-0.2
:   0: Creating possibility state for dill (< 0.3.0.0, >= 0.2.0.0) (1 remaining)
:   3: Attempting to activate [dill-0.2, dill-0.2.1, dill-0.2.2, dill-0.2.3, dill-0.2.4, dill-0.2.5, dill-0.2.6, dill-0.2.7, dill-0.2.7.1]
:   3: Found existing spec ([dill-0.2.7, dill-0.2.7.1])
:   3: Getting dependencies for pymorphy2-0.8
:   0: Creating possibility state for pymorphy2 (^0.8.0) (1 remaining)
:   4: Attempting to activate [pymorphy2-0.8]
:   4: Activated pymorphy2 at [pymorphy2-0.8]
:   4: Requiring nested dependencies (dawg-python (>= 0.7.0.0), pymorphy2-dicts (>= 2.4.0.0, < 3.0.0.0), docopt (>= 0.6.0.0))
:   4: Getting dependencies for pytest-3.5.0
:   0: Creating possibility state for pytest (^3.5) (1 remaining)
:   5: Attempting to activate [pytest-3.5.0]
:   5: Activated pytest at [pytest-3.5.0]
:   5: Requiring nested dependencies (py (>= 1.5.0.0), six (>= 1.10.0.0), attrs (>= 17.4.0.0), more-itertools (>= 4.0.0.0), pluggy (< 0.7.0.0, >= 0.5.0.0), funcsigs (*), colorama (*))
:   5: Getting dependencies for ipython-6.3.1
:   5: Getting dependencies for ipython-6.3.0
:   0: Creating possibility state for ipython (^6.3) (2 remaining)
:   6: Attempting to activate [ipython-6.3.1]
:   6: Activated ipython at [ipython-6.3.1]
:   6: Requiring nested dependencies (win-unicode-console (>= 0.5.0.0), colorama (*), appnope (*), pexpect (*), pathlib2 (*), typing (*), traitlets (>= 4.2.0.0), simplegeneric (> 0.8.0.0), pygments (*), prompt-toolkit (< 2.0.0.0, >= 1.0.15.0), pickleshare (*), jedi (>= 0.10.0.0), decorator (*), backcall (*))
:   6: Getting dependencies for numpy-1.14.2
:   6: Getting dependencies for numpy-1.14.1
:   6: Getting dependencies for numpy-1.14.0
:   6: Getting dependencies for numpy-1.14.0rc1
:   6: Getting dependencies for numpy-1.13.3
:   6: Getting dependencies for numpy-1.13.1
:   6: Getting dependencies for numpy-1.13.0
:   6: Getting dependencies for numpy-1.13.0rc2
:   6: Getting dependencies for numpy-1.13.0rc1
:   6: Getting dependencies for numpy-1.12.1
:   6: Getting dependencies for numpy-1.12.1rc1
:   6: Getting dependencies for numpy-1.12.0
:   6: Getting dependencies for numpy-1.12.0rc2
:   6: Getting dependencies for numpy-1.12.0rc1
:   6: Getting dependencies for numpy-1.12.0b1
:   6: Getting dependencies for numpy-1.11.3
:   6: Getting dependencies for numpy-1.11.2
:   6: Getting dependencies for numpy-1.11.2rc1
:   6: Getting dependencies for numpy-1.11.1
:   6: Getting dependencies for numpy-1.11.1rc1
:   6: Getting dependencies for numpy-1.11.0
:   6: Getting dependencies for numpy-1.11.0rc2
:   6: Getting dependencies for numpy-1.11.0rc1
:   6: Getting dependencies for numpy-1.11.0b3
:   6: Getting dependencies for numpy-1.10.4
:   6: Getting dependencies for numpy-1.10.3
:   6: Getting dependencies for numpy-1.10.2
:   6: Getting dependencies for numpy-1.10.1
:   6: Getting dependencies for numpy-1.10.0
:   6: Getting dependencies for numpy-1.9.3
:   6: Getting dependencies for numpy-1.9.2
:   6: Getting dependencies for numpy-1.9.1
:   6: Getting dependencies for numpy-1.9.0
:   6: Getting dependencies for numpy-1.8.2
:   6: Getting dependencies for numpy-1.8.1
:   6: Getting dependencies for numpy-1.8.0
:   6: Getting dependencies for numpy-1.7.2
:   6: Getting dependencies for numpy-1.7.1
:   6: Getting dependencies for numpy-1.7.0
:   0: Creating possibility state for numpy (>= 1.7.0.0) (1 remaining)
:   7: Attempting to activate [numpy-1.7.0, numpy-1.7.1, numpy-1.7.2, numpy-1.8.0, numpy-1.8.1, numpy-1.8.2, numpy-1.9.0, numpy-1.9.1, numpy-1.9.2, numpy-1.9.3, numpy-1.10.0, numpy-1.10.1, numpy-1.10.2, numpy-1.10.3, numpy-1.10.4, numpy-1.11.0b3, numpy-1.11.0rc1, numpy-1.11.0rc2, numpy-1.11.0, numpy-1.11.1rc1, numpy-1.11.1, numpy-1.11.2rc1, numpy-1.11.2, numpy-1.11.3, numpy-1.12.0b1, numpy-1.12.0rc1, numpy-1.12.0rc2, numpy-1.12.0, numpy-1.12.1rc1, numpy-1.12.1, numpy-1.13.0rc1, numpy-1.13.0rc2, numpy-1.13.0, numpy-1.13.1, numpy-1.13.3, numpy-1.14.0rc1, numpy-1.14.0, numpy-1.14.1, numpy-1.14.2]
:   7: Activated numpy at [numpy-1.7.0, numpy-1.7.1, numpy-1.7.2, numpy-1.8.0, numpy-1.8.1, numpy-1.8.2, numpy-1.9.0, numpy-1.9.1, numpy-1.9.2, numpy-1.9.3, numpy-1.10.0, numpy-1.10.1, numpy-1.10.2, numpy-1.10.3, numpy-1.10.4, numpy-1.11.0, numpy-1.11.1, numpy-1.11.2, numpy-1.11.3, numpy-1.12.0, numpy-1.12.1, numpy-1.13.0, numpy-1.13.1, numpy-1.13.3, numpy-1.14.0, numpy-1.14.1, numpy-1.14.2]
:   7: Requiring nested dependencies ()
:   7: Getting dependencies for murmurhash-0.28.0
:   0: Creating possibility state for murmurhash (< 0.29.0.0, >= 0.28.0.0) (1 remaining)
:   8: Attempting to activate [murmurhash-0.28.0]
:   8: Activated murmurhash at [murmurhash-0.28.0]
:   8: Requiring nested dependencies ()
:   8: Getting dependencies for cymem-1.31.2
:   8: Getting dependencies for cymem-1.31.1
:   8: Getting dependencies for cymem-1.31.0
:   8: Getting dependencies for cymem-1.30
:   0: Creating possibility state for cymem (< 1.32.0.0, >= 1.30.0.0) (1 remaining)
:   9: Attempting to activate [cymem-1.30, cymem-1.31.0, cymem-1.31.1, cymem-1.31.2]
:   9: Activated cymem at [cymem-1.30, cymem-1.31.0, cymem-1.31.1, cymem-1.31.2]
:   9: Requiring nested dependencies ()
:   9: Getting dependencies for preshed-1.0.0
:   0: Creating possibility state for preshed (< 2.0.0.0, >= 1.0.0.0) (1 remaining)
:  10: Attempting to activate [preshed-1.0.0]
:  10: Activated preshed at [preshed-1.0.0]
:  10: Requiring nested dependencies (cymem (>= 1.30.0.0, < 1.32.0.0))
:  10: Getting dependencies for cymem-1.31.2
:  10: Getting dependencies for cymem-1.31.1
:  10: Getting dependencies for cymem-1.31.0
:  10: Getting dependencies for cymem-1.30
:   0: Creating possibility state for cymem (>= 1.30.0.0, < 1.32.0.0) (1 remaining)
:  11: Attempting to activate [cymem-1.30, cymem-1.31.0, cymem-1.31.1, cymem-1.31.2]
:  11: Found existing spec ([cymem-1.30, cymem-1.31.0, cymem-1.31.1, cymem-1.31.2])
:  11: Getting dependencies for thinc-6.11.0.dev2
:  11: Getting dependencies for thinc-6.10.2
:  11: Getting dependencies for thinc-6.10.2.dev1
:  11: Getting dependencies for thinc-6.10.2.dev0
:  11: Getting dependencies for thinc-6.10.1
:   0: Creating possibility state for thinc (< 6.11.0.0, >= 6.10.1.0) (5 remaining)
:  12: Attempting to activate [thinc-6.11.0.dev2]
:  12: Unwinding for conflict: thinc (< 6.11.0.0, >= 6.10.1.0) to 11
:   0: Creating possibility state for thinc (< 6.11.0.0, >= 6.10.1.0) (2 remaining)
:  12: Attempting to activate [thinc-6.10.2]
:  12: Activated thinc at [thinc-6.10.2]
:  12: Requiring nested dependencies (wrapt (*), numpy (>= 1.7.0.0), murmurhash (>= 0.28.0.0, < 0.29.0.0), cymem (>= 1.30.0.0, < 1.32.0.0), preshed (>= 1.0.0.0, < 2.0.0.0), tqdm (>= 4.10.0.0, < 5.0.0.0), cytoolz (>= 0.8.0.0, < 0.9.0.0), plac (>= 0.9.6.0, < 1.0.0.0), six (>= 1.10.0.0, < 2.0.0.0), dill (*), termcolor (*), pathlib (>= 1.0.0.0, < 2.0.0.0), msgpack-python (*), msgpack-numpy (== 0.4.1.0))
:  12: Getting dependencies for dill-0.2.7.1
:  12: Getting dependencies for dill-0.2.7
:  12: Getting dependencies for dill-0.2.6
:  12: Getting dependencies for dill-0.2.5
:  12: Getting dependencies for dill-0.2.4
:  12: Getting dependencies for dill-0.2.3
:  12: Getting dependencies for dill-0.2.2
:  12: Getting dependencies for dill-0.2.1
:  12: Getting dependencies for dill-0.2
:  12: Getting dependencies for dill-0.2b1
:  12: Getting dependencies for dill-0.2a1
:  12: Getting dependencies for dill-0.1a1

:   0: Finished resolution (14 steps) in 0.757 seconds

                                                           
  [ValueError]                                             
  No PKG-INFO in archive: /tmp/tmpflmmr4g8/dill-0.1a1.tgz  
                                                           

Exception trace:
 /usr/local/lib/python3.5/dist-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /usr/local/lib/python3.5/dist-packages/poetry/console/application.py in do_run() at line 74
   return super(Application, self).do_run(i, o)
 /usr/local/lib/python3.5/dist-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /usr/local/lib/python3.5/dist-packages/poetry/console/commands/command.py in run() at line 22
   return super(BaseCommand, self).run(i, o)
 /usr/local/lib/python3.5/dist-packages/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /usr/local/lib/python3.5/dist-packages/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /usr/local/lib/python3.5/dist-packages/poetry/console/commands/install.py in handle() at line 40
   return installer.run()
 /usr/local/lib/python3.5/dist-packages/poetry/installation/installer.py in run() at line 73
   self._do_install(local_repo)
 /usr/local/lib/python3.5/dist-packages/poetry/installation/installer.py in _do_install() at line 171
   ops = solver.solve(request, fixed=fixed)
 /usr/local/lib/python3.5/dist-packages/poetry/puzzle/solver.py in solve() at line 42
   graph = resolver.resolve(requested, base=base)
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolver.py in resolve() at line 39
   base
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in resolve() at line 93
   self._process_topmost_state()
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _process_topmost_state() at line 158
   self._attempt_to_activate()
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _attempt_to_activate() at line 775
   self._activate_new_spec()
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _activate_new_spec() at line 821
   self._require_nested_dependencies_for(self.possibility)
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _require_nested_dependencies_for() at line 851
   len(nested_dependencies) > 0
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _push_state_for_requirements() at line 884
   possibilities = self._possibilities_for_requirement(new_requirement)
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _possibilities_for_requirement() at line 908
   self._provider.search_for(requirement)
 /usr/local/lib/python3.5/dist-packages/poetry/mixology/resolution.py in _group_possibilities() at line 942
   dependencies = self._provider.dependencies_for(possibility)
 /usr/local/lib/python3.5/dist-packages/poetry/puzzle/provider.py in dependencies_for() at line 210
   complete_package = self._pool.package(package.name, package.version)
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pool.py in package() at line 62
   package = repository.package(name, version)
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pypi_repository.py in package() at line 121
   release_info = self.get_release_info(name, version)
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pypi_repository.py in get_release_info() at line 235
   lambda: self._get_release_info(name, version)
 /usr/local/lib/python3.5/dist-packages/cachy/repository.py in remember_forever() at line 174
   val = value(callback)
 /usr/local/lib/python3.5/dist-packages/cachy/helpers.py in value() at line 6
   return val()
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pypi_repository.py in <lambda>() at line 235
   lambda: self._get_release_info(name, version)
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pypi_repository.py in _get_release_info() at line 303
   requires_dist = self._get_requires_dist_from_urls(urls)
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pypi_repository.py in _get_requires_dist_from_urls() at line 323
   return self._get_requires_dist_from_sdist(urls['sdist'])
 /usr/local/lib/python3.5/dist-packages/poetry/repositories/pypi_repository.py in _get_requires_dist_from_sdist() at line 346
   meta = pkginfo.SDist(str(filepath))
 /usr/local/lib/python3.5/dist-packages/pkginfo/sdist.py in __init__() at line 12
   self.extractMetadata()
 /usr/local/lib/python3.5/dist-packages/pkginfo/distribution.py in extractMetadata() at line 108
   data = self.read()
 /usr/local/lib/python3.5/dist-packages/pkginfo/sdist.py in read() at line 52
   raise ValueError('No PKG-INFO in archive: %s' % fqn)

install [--no-dev] [--dry-run] [-E|--extras EXTRAS]

**Comment by sdispater** [comment]
For why it takes that much time see: https://poetry.eustace.io/docs/basic-usage/#specifying-dependencies

And as to why it has to check all these versions: `poetry` has to flatten the dependency graph in order to be exhaustive so it has to retrieve information on all the packages that match dependencies and sub dependencies. Note that this will take time only the first time since later on the releases information will be cached.

That being said, the `ValueError` is actually a bug since it should skip this release. I will fix it.

**Comment by sdispater** [comment]
The value error should be fixed in the lastest version (`0.8.5`).

**Comment by buriy** [comment]
@sdispater sorry, this is fine, it doesn't try to load spacy down to 2.0.0 if ^2.0.11 is specified and found, only does it if "^2.0" is specified.
But for dependencies it does, while trying to check all versions which can meet the specs.
Still would be great if this could be avoided with "always take the latest version" or "always take the earliest version" with ***lazy*** checking for the version descriptions.

**Comment by sdispater** [comment]
@buriy This is fixed in version `0.9.0`.
