### ISSUE TITLE
Support for backported dependencies

### ISSUE THREAD

**Issue by dmfigol** [sdispater/poetry#582]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

I am writing Python 3.6+ library. I would like to use backported `dataclasses` module which is a std lib in 3.7. A similar issue would be with `enum` library backported to 3.3 from 3.4
I don't think there is currently a way to specify this conditional dependency in `pyproject.toml`
It would be great to have this feature especially since "multiple constraints dependencies" feature appeared in 0.12:
```
[tool.poetry.dependencies]
foo = [
    {version = "<=1.9", python = "^2.7"},
    {version = "^2.0", python = "^3.4"}
]
```

**Comment by sdispater** [comment]
I think something like this https://github.com/sdispater/poetry/blob/master/pyproject.toml#L40 is what you want.

**Comment by dmfigol** [comment]
Thank you. This is exactly what I needed!
Sorry for wasting your time.
