### ISSUE TITLE
`poetry update foo` updates `bar`, but doesn't update `foo`

### ISSUE THREAD

**Issue by djrobstep** [sdispater/poetry#584]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

In my pyproject.toml for my project `baz` I have a number of git dependencies specified. I push a commit to a branch one of those repositories `foo`, and want to update my project to use the latest version of that branch on the dependency.

To do that I expect to be able to simply run `poetry update foo`.

But when I run that I get bar updating, but not foo:

```
14:58 $ poetry update foo
Updating dependencies
Resolving dependencies... (110.7s)

Package operations: 0 installs, 1 update, 0 removals

Writing lock file

  - Updating bar (0.1.122 -> 0.1.123 253e012)
```

Why does the directly specified dependency not get updated, but another does? 

It seems I can't get git dependencies to update to their branch tip at all, short of recreating the virtual env entirely.

**Comment by sdispater** [comment]
This should be fixed in the latest `0.12.6` version.
