### ISSUE TITLE
Excluding file with unsupported VCS

### ISSUE THREAD

**Issue by Lothiraldan** [sdispater/poetry#585]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 28
- **Poetry version**: 0.12.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Lothiraldan/7e4c1ffde3ed90ec183ad4eb5e72a44c

## Issue

Hello, first thank you for your work on poetry, packaging in Python is something we should be better at and poetry looks very promising.

I'm trying to use poetry with one of my project https://github.com/lothiraldan/balto which will include a compiled react project. I develop the project using Mercurial and then export the repository to Github.

The first time I ran `poetry build`, I saw that the nodes_modules directory was included so I try explictly excluding it with:

```toml
[tool.poetry]
exclude = ["balto/web_interfaces/balto_react/node_modules/**/*"]
```

But it didn't help.

I start taking a look at the code and found that the `find_excluded_files` early abort in case it didn't find the VCS (in my case Mercurial). Apart from adding Mercurial support (which I may do in the future), I think excluding files shouldn't depend on projects using a supported VCS.

I applied the following diff locally to still reads the explicitely excluded files that did the trick:

```diff
diff --git a/poetry/masonry/builders/builder.py b/poetry/masonry/builders/builder.py
index 627e006..477ec8d 100644
--- a/poetry/masonry/builders/builder.py
+++ b/poetry/masonry/builders/builder.py
@@ -43,14 +43,16 @@ class Builder(object):
         # Checking VCS
         vcs = get_vcs(self._path)
         if not vcs:
-            return []
+            vcs_ignored_files = []
+        else:
+            vcs_ignored_files = vcs.get_ignored_files()
 
         explicitely_excluded = []
         for excluded_glob in self._package.exclude:
             for excluded in self._path.glob(excluded_glob):
                 explicitely_excluded.append(excluded)
 
-        ignored = vcs.get_ignored_files() + explicitely_excluded
+        ignored = vcs_ignored_files + explicitely_excluded
         result = []
         for file in ignored:
             try:
```

I can send a PR with it if the code looks correct and the behavior change is ok.

**Comment by sdispater** [comment]
Nice catch!

The patch looks good to me so feel free to make a PR and I'd gladly review it.
