### ISSUE TITLE
Can't build a distribution that has a different name from the package

### ISSUE THREAD

**Issue by jarshwah** [sdispater/poetry#587]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX
- **Poetry version**: 0.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/kogan/django-lrucache-backend/blob/master/pyproject.toml

## Issue

I maintain a package that has the name, on PyPI, of "django-lrucache-backend", but the package itself is named "lrucache_backend", and I can't build the package with the correct name. Django packages, in particular, follow this pattern quite often.

Distribution name: django_mypackage
Package name: mypackage

```
[tool.poetry]
name = "django-lrucache-backend"
```

When I try to build the package:

```
$ poetry build -vvv 
Virtualenv django-lrucache-backend-py3.6 already exists.
Using virtualenv: /Users/josh/Library/Caches/pypoetry/virtualenvs/django-lrucache-backend-py3.6
Building django-lrucache-backend (2.0.0)

[ValueError]
No file/folder found for package django-lrucache-backend

Exception trace:
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/_vendor/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/_vendor/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/commands/command.py in run() at line 72
   return super(BaseCommand, self).run(i, o)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/_vendor/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/_vendor/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/console/commands/build.py in handle() at line 27
   builder.build(fmt)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/masonry/builder.py in build() at line 19
   builder = self._FORMATS[fmt](self._poetry, self._venv, self._io)
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/masonry/builders/builder.py in __init__() at line 35
   includes=self._package.include,
 /Users/josh/.pyenv/versions/3.6.4/lib/python3.6/site-packages/poetry/masonry/utils/module.py in __init__() at line 51
   raise ValueError("No file/folder found for package {}".format(name))
```

**Comment by rfleschenberg** [comment]
I think it would be better to make the Python package / module name configurable from`pyproject.toml`, instead of deriving it implicitly from the setuptools distribution name.

**Comment by kevinkjt2000** [comment]
Robot Framework libraries have a similar convention where the names differ.  The pip packages are `robotframework-name-here` and the module names are `NameHereLibrary`.

**Comment by sdispater** [comment]
You can specify the package(s) using the [packages](https://poetry.eustace.io/docs/pyproject/#packages) key.

**Comment by kevinkjt2000** [comment]
Amazing!  Wish I had seen that sooner.  Poetry is proving to be the best
python tool I have ever had the pleasure of working with.  Now I just need
to find a donation button.
