### ISSUE TITLE
poetry fails to parse version constraint, but only with LegacyRepository

### ISSUE THREAD

**Issue by zehauser** [sdispater/poetry#588]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.13.6
- **Poetry version**: 0.12.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/zehauser/337fabdfe20662293b3eddcf113c0a55

## Issue

As best I can tell, this issue only arises with the `LegacyRepository` code path.

Steps to reproduce:
1. Copy the above gist into a `pyproject.toml` in an empty directory.
2. Run `poetry debug:resolve`. 
3. Observe the `[ValueError] Could not parse version constraint: not`
4. Remove the `tool.poetry.source` section from the above `pyproject.toml`. 
5. Run `poetry debug:resolve`.
6. Observe that all is well.   

Looks like the troublesome lines in the dist-info METADATA file are these:
```
Requires-Dist: jinja2 (>=2.6,<2.7); python_version in "3.0,3.1,3.2" and extra == 'export'
Requires-Dist: jinja2 (>=2.7,<2.8); python_version not in "3.0,3.1,3.2" and extra == 'export'
```

**Comment by zehauser** [comment]
@sdispater (or other maintainers) I should've mentioned: I'd be happy to try to debug this and make a PR, but I think I'd need some hints for where to look. :)

**Comment by sdispater** [comment]
@zehauser Thanks for wanting to contribute to the project. This has already been fixed in commit 4ae1def

The fix will be available in the next bugfix release.

**Comment by zehauser** [comment]
@sdispater: excellent. :) Thank you! I look forward to the next bugfix release, which will unblock me.

**Comment by sdispater** [comment]
Release `0.12.6` is out which fixes this issue.
