### ISSUE TITLE
I have trash in my poetry installation

### ISSUE THREAD

**Issue by who-am-1** [sdispater/poetry#594]
I have Artix Linux & I have trash in my poetry installation (from curl)

$ find .poetry/ -iname .DS_Store
.poetry/lib/poetry/.DS_Store
.poetry/lib/poetry/packages/constraints/.DS_Store
.poetry/lib/poetry/packages/.DS_Store

https://en.wikipedia.org/wiki/.DS_Store

**Comment by sdispater** [comment]
It should be fixed as of release `0.12.6`
