### ISSUE TITLE
New Version Install and Old Version Uninstall Confusion

### ISSUE THREAD

**Issue by joelruns** [sdispater/poetry#605]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I am on Mojave 10.14.1 and have 2 `poetry` versions. Originally I had 0.11.4 installed using the recommended method but when running `poetry self:update` I was getting this error:
```
[RuntimeError]        
Unable to determine poetry's path  
```
So I decided to try and use the new `get-poetry.py` installer. But now I have a 0.12.6 in my `~/.poetry` folder but when I do `pip freeze` the old 0.11.4 version is still there. Do I delete that old version just using `pip uninstall` and will that properly undo and remove all the vendorized magic the previous installer did? If I pass `--uninstall` to the current installer it doesn't seem to delete the old version in `pip`.

Thanks for the time and sorry for the nuisance.

**Comment by joelruns** [comment]
I ended up running `pip uninstall poetry` and it seems to have removed all the stuff in `site-packages` so I am guessing things went well. Closing since my problem is likely solved.

**Comment by romeopeter** [comment]
To anyone having the same issue, use Python PIP to uninstall old version of poetry. Run `python3 -m pip uninstall poetry`  and it'll handle the uninstalling process for you.
