### ISSUE TITLE
Is there a way to make IntelliJ IDEA `see` poetry projects?

### ISSUE THREAD

**Issue by CyborTronik** [sdispater/poetry#608]

**Comment by pauleikis** [comment]
What trouble are you encountering? I'm using IntelliJ and everything works fine for me.

**Comment by FelixHaller** [comment]
> What trouble are you encountering? I'm using IntelliJ and everything works fine for me.

Is the virtualenv automatically detected? What plugins are you using?

**Comment by TensorTom** [comment]
bump. For this we probably need a plugin developed.

**Comment by stephsamson** [comment]
There is a feature request already on [JetBrain's issue tracker](https://youtrack.jetbrains.com/issue/PY-30702). Please vote there! 😄
