### ISSUE TITLE
Poetry fails to install flask-cors in Docker

### ISSUE THREAD

**Issue by mvoitko** [sdispater/poetry#609]
- [+] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [+] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [+] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: python:alpine
- **Poetry version**: 0.12.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/mvoitko/fe0a1451f4616e36d810901d83ee388c

## Issue
Building Docker container fails on ```poetry install``` step with the following error:
[SolverProblemError]                                             
Because rating-engine depends on flask-cors (^3.0.6) which doesn't match any  
 versions, version solving failed.                                            
                                                                                
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]

At the same time if I change the command to ```poetry update``` everything is ok.

**Comment by sdispater** [comment]
Could you post the output of `poetry install -vvv`?

**Comment by mvoitko** [comment]
@sdispater 
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

                                                                                
[SolverProblemError]                                             
Because rating-engine depends on flask-cors (^3.0) which doesn't match any v  
ersions, version solving failed.                                              
                                                                                
Exception trace:
 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)

 /root/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)

 /root/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)

 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)

 /root/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /root/.poetry/lib/poetry/console/commands/install.py in handle() at line 57
   return_code = installer.run()

 /root/.poetry/lib/poetry/installation/installer.py in run() at line 76
   self._do_install(local_repo)

 /root/.poetry/lib/poetry/installation/installer.py in _do_install() at line 216
   ops = solver.solve(use_latest=whitelist)

 /root/.poetry/lib/poetry/puzzle/solver.py in solve() at line 38
   packages, depths = self._solve(use_latest=use_latest)

 /root/.poetry/lib/poetry/puzzle/solver.py in _solve() at line 180
   raise SolverProblemError(e)


install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]

**Comment by sdispater** [comment]
You have to execute `poetry update` as the warning tells you:

`Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.`

without updating Poetry can't find `flask-cors`.

**Comment by mvoitko** [comment]
@sdispater sounding a little bit like Captain Obvious). I have done it locally and committed updated lock file to the repository. So in Docker, the lock file is actually up to date.

**Comment by sdispater** [comment]
I cannot reproduce unfortunately. So I am out of options.

**Comment by robertlagrant** [comment]
@mvoitko you need to create a minimal example to progress this. There doesn't seem to even be a Dockerfile provided to diagnose.
