### ISSUE TITLE
Missing git exectuable should not be vivisble without -v or -vv or -vvv

### ISSUE THREAD

**Issue by metasyn** [sdispater/poetry#614]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.12.6 / docker `python:slim` (7d1f25319281)
- **Poetry version**: 0.12.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: irrelevant

## Issue

To start - thanks for the awesome package! I noticed that while I was calling `poetry build` - I get a runtime warning if there is not a git executable:

```
~/git/python-package-template master* 29s
❯ docker run -it --rm -v `pwd`:/foo --entrypoint bash python:slim
root@43a2cde16b94:/# cd /foo
root@43a2cde16b94:/foo# pip install poetry -q
root@43a2cde16b94:/foo# poetry --version
Poetry 0.12.7
root@43a2cde16b94:/foo# poetry build
Creating virtualenv python-package-template-py3.7 in /root/.cache/pypoetry/virtualenvs
Building python-package-template (0.0.1)
 - Building sdist
/usr/local/lib/python3.7/site-packages/poetry/vcs/__init__.py:19: RuntimeWarning: git executable could not be found
  "git executable could not be found", category=RuntimeWarning
 - Built python-package-template-0.0.1.tar.gz

 - Building wheel
 - Built python_package_template-0.0.1-py3-none-any.whl
root@43a2cde16b94:/foo#
```

Specifically here:
```
/usr/local/lib/python3.7/site-packages/poetry/vcs/__init__.py:19: RuntimeWarning: git executable could not be found
  "git executable could not be found", category=RuntimeWarning
```

which comes from [here](https://github.com/sdispater/poetry/blob/master/poetry/vcs/__init__.py#L19). What I'm confused about is why this is a warning? I wouldn't think that having git is required - and functionally, it seems like not having it doesn't make that much of a difference:

- https://github.com/sdispater/poetry/blob/b4333e4591ef98532852d189917838ae30322c4f/sonnet#L64

- https://github.com/sdispater/poetry/blob/bbab4e662ababe679efb143411576f845488ab06/poetry/masonry/builders/builder.py#L48

It seems like something that would maybe be a lower level of verbosity, rather than in the output of the top level of `poetry build`.

**Comment by sdispater** [comment]
Poetry uses `git` to automatically exclude VCS ignored files. And the warning is only displayed if Poetry sees `.git` directory but cannot make anything of it since no `git` executable can be found.

**Comment by metasyn** [comment]
I see - that seems like useful behavior in general - it just looks a bit weird in our CI setup - e.g. I'd like to suppress the warning so that people don't think its indicative of an error.

```
  - Installing pytest-cov (2.6.0)
  - Installing tox (3.5.3)
  - Installing python-package-template (0.0.1)
/usr/local/lib/python3.7/site-packages/poetry/vcs/__init__.py:19: RuntimeWarning: git executable could not be found
  "git executable could not be found", category=RuntimeWarning
$ poetry run doit
Skipping virtualenv creation, as specified in config file.
All done! ✨ 🍰 ✨
4 files left unchanged.
.  Linting with flake8...
.  Type checking with mypy...
.  Code formatting with black...
.  Building with poetry...
Skipping virtualenv creation, as specified in config file.
Building python-package-template (0.0.1)
 - Building sdist
 - Built python-package-template-0.0.1.tar.gz

 - Building wheel
 - Built python_package_template-0.0.1-py3-none-any.whl
/usr/local/lib/python3.7/site-packages/poetry/vcs/__init__.py:19: RuntimeWarning: git executable could not be found
  "git executable could not be found", category=RuntimeWarning
```

Missing git seems to be not problematic - but it warns regardless. In this case its a fresh checkout in a container. Is there a different way I could suppress this warning?

**Comment by sdispater** [comment]
If you remove the `.git` directory the warning should disappear.

**Comment by metasyn** [comment]
That seems tempting, but in this case, I need the .git folder at a later
point. If the warning doesn't represent a real problem, is there a reason
to surface it in normal verbosity mode?

**Comment by sdispater** [comment]
It is a problem in the sense that if you have a `.git` directory it means the project is under VCS and since Poetry relies on it to exclude files if it can't find the `git` executable there is an issue hence the warning.

**Comment by metasyn** [comment]
I see. I think that logic makes sense, overall. For my situation, it was nice that I was able to use the `python:slim` docker image out of the box - I guess I will either just install git on the image after pulling it, rename/remove .git folder, or just live with the warning, as it sounds like you're steadfast on keeping the warning there.

**Comment by kbakk** [comment]
Removing the `.git` directory may seem like a hassle, but (at least when using Dockerfile), it is one line in a `.dockerignore`. 

A `.dockerignore` in one of my projects:
```
venv
.env*
.gitignore
.gitlab-ci.yml
.git
```
