### ISSUE TITLE
Would be good to explain what `^` does in version constraints or link to its definition

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#627]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
In [these docs](https://poetry.eustace.io/docs/faq/#why-are-unbound-version-constraints-a-bad-idea), it would be good to either explain what `^` is or how it differs from `~`, since many people may not be familiar with either.

**Comment by jacebrowning** [comment]
Those _are_ explained here: https://poetry.eustace.io/docs/versions/

**Comment by cjw296** [comment]
Turns out 3hrs sleep is not enough :'( Apologies!
