### ISSUE TITLE
How can I include a long description that comes from another file?

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#628]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I use [this patter](https://github.com/Simplistix/testfixtures/blob/master/setup.py#L19-L21)n to include a chunk of ReST to use on pypi.org. Having it in a separate file lets me check it's valid ReST before submitting, and I often use README.rst to have the same thing show on github and on pypi.

How can I do this with `pyproject.toml`?

**Comment by sdispater** [comment]
I am not sure I understand. You example can be replicated with Poetry

```toml
[tool.poetry]
# ...
readme = "docs/description.txt"
```
