### ISSUE TITLE
make `poetry version` work like `npm version`

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#629]
update
------

Please see @mattyclarkson 's comment [below](https://github.com/sdispater/poetry/issues/629#issuecomment-439872811) for what this issue should be!

-----

- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Interested to see what others feel about this. I've braino'ed `poetry version` a couple of times when I meant `poetry --version`. "version" is a noun in my head, and `poetry inc_version` would be more explicit.

However, I'm well aware this might just be me, so thought I'd ask/suggest here and see what others said :-)

**Comment by cjw296** [comment]
Actually, that's not quite true, from chatting with a JS dev:

`npm version` outputs the current version of your project
`npm version minor` updates the third point
...etc...

I think that would be better for poetry too :-)

**Comment by playpauseandstop** [comment]
Run into same issue recently, as an `npm` user I expected the behavior from 
https://github.com/sdispater/poetry/issues/629#issuecomment-439128806, when `npm version` call outputs the version of the package instead of increasing it, so I propose to change `poetry version` to work same as `npm version`

**Comment by cjw296** [comment]
@mattyclarkson @abn - what do you think to @playpauseandstop 's suggestion. I like it :-)

**Comment by abn** [comment]
@cjw296 fwiw, I do not think such a change is warranted. The option `--version` follows the expectations set by all other options in poetry and `version`  is a sub-command with a default behavior enacted on the project context. While `poetry` does share similarities with `npm` both these tools cater to different ecosystems with their own conventions and practices. Python command line tool options and arguments borrow heavily from conventions established by [optparse](https://docs.python.org/3.3/library/optparse.html#module-optparse) and [argparse](https://docs.python.org/3.3/library/argparse.html). And this is anticipated quite naturally by developers working within the ecosystem. 

Speaking for myself at least, the behavior of `poetry version` as opposed to `poetry --version` is natural and expected. This should not be changed.

**Comment by cjw296** [comment]
@mattyclarkson - your description is perfect, let me update the issue title and point to your comment...

**Comment by abn** [comment]
@mattyclarkson Just to be clear, I did not mean to allude that the purpose of the `version` sub-command in these tools serve different purposes but rather the tools sometimes cater to idiosyncrasies of the ecosystems they are a part of.

I, personally, have no objection to a change that updates the default behavior and in-fact do agree that having consistent behavior across environments is the way to go.

My comment was following from the issue description requiring a rename of the sub-command to `inc_version`. That, I think is not warranted.

**Comment by cjw296** [comment]
@mattyclarkson, @abn - great, sounds like we're all on the same page: keep `poetry version` but make it display the current project's current version, and add something to explicitly do a third point increment. 

@sdispater - would you welcome a PR that made this happen?

**Comment by kbakk** [comment]
I think this issue deserves more thumb up's, given the update in the issue.

Right now I have to work around this by installing a toml library to read the pyproject.toml, and running a one-liner to get the project version. For anyone curious: 

```
python -c 'import tomlkit; print(tomlkit.parse(open("pyproject.toml").read())["tool"]["poetry"]["version"])'
```

Since what @mattyclarkson suggests is a breaking change, putting it in the 1.0 release seems fitting.

**Comment by mofahead** [comment]
poetry bump major
poetry bump minor

**Comment by stephsamson** [comment]
#1191 fixes this.
