### ISSUE TITLE
Error messages take too much space / hard to read

### ISSUE THREAD

**Issue by blueyed** [sdispater/poetry#63]
![2018-04-22-232432_353x134_escrotum](https://user-images.githubusercontent.com/9766/39100071-61721ec2-4684-11e8-9abb-74621d1e112f.png)

I think error messages should take only a single line (instead of 4+ like above).

See https://github.com/sdispater/pastel/issues/1 for the readability issue.

**Comment by blueyed** [comment]
As per https://github.com/sdispater/pastel/issues/1#issuecomment-383604180 this sounds to be a wont-fix unfortunately.

I've had some hopes regarding poetry fixing the mess with pipenv, but obfuscating error messages like this really reminds me of the CLI issues with pipenv itself.

btw: I've used click for an own project and really liked it, but always found that pipenv does not get it right.  poetry using cleo made me look briefly at it, but as for poetry's CLI it wasn't much for the better.

**Comment by blueyed** [comment]
Well, for me they are unreadable (i.e. "hidden"), and I've meant obfuscated in the sense of decorating them (with 2 lines above and below).
For me it's easier to parse
```
ERROR: foo
```

than
```

  ERROR
  foo

```

(disregarding the colors)

**Comment by sdispater** [comment]
That's a matter of preferences, I guess. I prefer how it's currently formatted so I won't change it.

But if that's what turns you off `poetry`, so be it. I just think it's a pity to disregard the features `poetry` brings just for a matter of color choice and error formatting.

**Comment by blueyed** [comment]
> I just think it's a pity to disregard the features poetry brings just for a matter of color choice and error formatting.

I agree.  That's why I am pointing them out explicitly - I think others might agree eventually - espcially when considering pastel as a lib (https://github.com/sdispater/pastel/issues/1).

And with regard to "just for a matter of color choice": it's just unreadable for me, and therefore not accessible - it's like a webpage that is not accessible (due to missing alt texts or just outputting audio by default, and not providing any text).

Anyway, I'll be watching this project and really like it for trying to fix the things with pipenv already.
