### ISSUE TITLE
`poetry shell` loses shell prompt config

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#630]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13.6
- **Poetry version**: 0.12.8

## Issue

On a Mac, when I start a shell with `poetry shell`, I lose my prompt:

```
tweedledee:carly chris$ poetry shell
Spawning shell within /Users/chris/Library/Caches/pypoetry/virtualenvs/carly-py2.7
bash-3.2$ poetry --version
Poetry 0.12.8
```

The bug is that it doesn't stay the same, I guess a really nice to have would be to append the poetry env in use:

```
tweedledee:carly chris$ poetry shell
Spawning shell within /Users/chris/Library/Caches/pypoetry/virtualenvs/carly-py2.7
tweedledee:carly [carly-py2.7] $ poetry --version
Poetry 0.12.8
```

**Comment by bjoernpollex** [comment]
This works perfectly for me - could it be that you're configuring your prompt in the [wrong shell initialization file][1]?

[1]: https://stackoverflow.com/a/415444/160206

**Comment by cjw296** [comment]
I'm doing whatever macOS does by default, if that's wrong, it might be something that new users hit...

**Comment by cjw296** [comment]
Anyway, thanks, moving stuff to `~/.bashrc` fixes this for me!
