### ISSUE TITLE
best way to start shell / work under different Pythons

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#631]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

My system python, as returned by `/usr/bin/env python` is Python 2.7, so for me, by default I get a Python 2.7 env, which is no longer what I want ;-)

Probably a non poetry question: but how would I change my system, config so that `/usr/bin/env python` return `which python3.7`?

In any case, I still need to support 2.7 and 3.6+ on most of my libraries, so it looks like I can do this by doing the following:

```
python3.7 `which poetry` shell
poetry install
```

...for a 3.7 env, and the following for a 2.7 env:

```
poetry shell
poetry install
```

Is that the best way or have I missed something?
Does this need to be in the docs somewhere or have I just missed them?

**Comment by bjoernpollex** [comment]
I think the recommended way (not sure if it's documented somewhere) is to use poetry in conjunction with [pyenv][1] (see [this comment][2]).

[1]: https://github.com/pyenv/pyenv
[2]: https://github.com/sdispater/poetry/issues/522#issuecomment-431105306

**Comment by cjw296** [comment]
Maybe I'm missing something obvious, but https://github.com/pyenv/pyenv/issues/1244?

**Comment by purificant** [comment]
[pyenv](https://github.com/pyenv/pyenv) is the way to go. On a per project basis you can create virtualenv with specific python versions as well as switch between different virtualenvs and python versions as needed with a single command.

Do not go down the path of trying to use your existing system interpreter for your project. The system interpreter is included in order to run your system, let it do that, and manage interpreter for your project separately. Frequently your operating system and your project will have conflicting requirements as far as python / virtualenv setup goes and trying work around those conflicts will just eat up your productive time.

**Comment by cjw296** [comment]
@purificant - I've found most system pythons to be sane, but sure.
The problem I have with pyenv, which I describe in  pyenv/pyenv#1244, is that attempting to build python from source all over the place seems crazy. Mac and Windows provide nice installers that have everything build the "right" way and provide a clean, base install (with things like working ssl, readline and zlib, to name a few that often go wrong...) and the various "alt" distributions provided by operating systems like RHEL and debian also provide a great base. Then there's the Pythons built and provided by the conda guys that provide great, clean, fully functional bases in user space.

How can I 'register' these with pyenv?

**Comment by purificant** [comment]
Sounds like pyenv is not a good choice for your use case.

If you require using a specific build of python, then I would create a virtual environment using that interpreter, activate it, which should point `python` to the desired version / build and then run poetry inside it. Poetry will detect that it's inside a virtual environment and install packages accordingly.

**Comment by cjw296** [comment]
Ah, true. I guess pyenv is close to what I want, but building everything seems silly. That's a rant for the pyenv tracker though, so I think I have my answer here :-)
