### ISSUE TITLE
poetry install doesn't add bin directory to PATH

### ISSUE THREAD

**Issue by rominf** [sdispater/poetry#633]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed
- **Poetry version**: 0.12.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Irrelevant

## Issue

I added my script to `tool.poetry.scripts` section. I expect that after install I will be able to run my script without using a full path to it, but it's not the case. I've found that `bin` directory is not added to `PATH`:
```
$ echo $PATH
/home/rominf/.pyenv/shims /home/rominf/.pyenv/bin /home/rominf/.local/bin/ /home/rominf/go/bin/ /home/rominf/.autojump/bin /home/rominf/.pyenv/bin /home/rominf/.local/bin/ /home/rominf/go/bin/ /home/rominf/.autojump/bin /home/rominf/.poetry/bin /home/rominf/bin /usr/local/bin /usr/bin /bin /usr/lib/mit/bin /usr/lib/mit/sbin
```
I use fish shell, but not bash, so all items in `PATH` are separated by space.

**Comment by sdispater** [comment]
How do you execute you script: with `poetry run` or after `poerty shell`?

**Comment by rominf** [comment]
Nope, I run it just by calling the Python. I thought that PATH is dynamically populated bes ne based on the current doctorin directory.

**Comment by sdispater** [comment]
That won't work. Poetry does not change your Path dynamically unless your use `run` or `shell`.

**Comment by rominf** [comment]
Ok. Got it.
