### ISSUE TITLE
exclude package from distribution

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#641]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

How can I tell poetry to exclude a package from my distribution?
Here's how I do it in setup.py:
https://github.com/cjw296/shoehorn/blob/master/setup.py#L29

**Comment by KeltonKarboviak** [comment]
It seems like the only package that is auto-discovered is the "default" package (https://poetry.eustace.io/docs/pyproject/#packages).  It's more of an opt-in system for **including** packages in a distribution.  Thus, there's no need to **exclude** a package.

However, it does seem that you can specifically exclude, as well as include, certain file patterns (https://poetry.eustace.io/docs/pyproject/#packages).

**Comment by cjw296** [comment]
Again, perfect! Thanks, I managed to miss the "pyproject" section in the docs :-)
