### ISSUE TITLE
how do I specify pypi classifiers using poetry?

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#642]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

How do I specify classifiers, particularly for frameworks, licenses and maturity, using poetry? 
Here's how I'd do it using setup.py:
https://github.com/Simplistix/testfixtures/blob/master/setup.py#L24-L31

**Comment by KeltonKarboviak** [comment]
Is this what you're looking for?

https://poetry.eustace.io/docs/pyproject/#classifiers

**Comment by cjw296** [comment]
Yep, perfect!
