### ISSUE TITLE
Cannot Uninstall Poetry on

### ISSUE THREAD

**Issue by gloc-mike** [sdispater/poetry#644]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS High Sierra 10.13.6
- **Poetry version**: 0.12.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not relevant to uninstall

## Issue

I originally installed Poetry using `curl` (release 0.12.4). It has successfully been upgraded to 0.12.8. I have decided to uninstall it now because I am suffering similar problems to others where Poetry ignores `pyenv local 3.7.1` and picks up the `brew` installed version of python 2.7.15. Anyway, when I try to uninstall Poetry using `python get-poetry.py --uninstall` I get `/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'get-poetry.py': [Errno 2] No such file or directory`.

This is also the problem if I attempt to use a different version of python.

Is there another way to uninstall it?

**Comment by sdispater** [comment]
You need to download the `get-poetry.py` file and execute:`python get-poetry.py --uninstall` or execute `POETRY_UNINSTALL=1 bash -c 'curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python'`.

There is also a `self:uninstall` command in the works but it's not ready yet.

**Comment by ekhaydarov** [comment]
The above command throws the warning of what it will do but doesnt actually do it.

I think its not just poetrys fault but also pyenvs fault. Not a great start to being an alternative to pipenv

Actually having ran those commands on all my python versions poetry still exists somewhere. Where does it live? Why does it continue to pick up the wrong python version?

**Comment by bersace** [comment]
@sdispater get-poetry.py state about self:uninstall but there running poetry self:uninstall spit CommandNotFound.

**Comment by bersace** [comment]
Note that `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python` is enough.

**Comment by GinnerskovRIF** [comment]
@bersace When running your code it only returns :
```# We are sorry to see you go!

This will uninstall Poetry.

It will remove the `poetry` command from Poetry's bin directory, located at:

$HOME/.poetry/bin

This will also remove Poetry from your system's PATH.```

**Comment by mvoitko** [comment]
Please reopen the issue

**Comment by jaepil-choi** [comment]
Check out this issue if the above instruction is not working. 

https://github.com/python-poetry/poetry/issues/2245

**Comment by acalvino4** [comment]
I ran this with my the installer with the `--uninstall` flag via my system python on ubuntu 20 and it did nothing

**Comment by vluzrmos** [comment]
> curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python

I removed it manually:

```bash
rm -rf ~/.local/share/pypoetry
rm -rf ~/.poetry
```
