### ISSUE TITLE
toml regression in pypy3(6.0.0)

### ISSUE THREAD

**Issue by extraymond** [sdispater/poetry#645]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **ubuntu 18.04**: 
- **Poetry 0.12.8**: 

## Issue

I've reported a potential regression on tomlkit [tracker](https://github.com/sdispater/tomlkit/issues/33), and this is affecting my poetry setup as well.
When In pypy3(6.0.0) and poetry version greater than 0.12.6, it will not parse the toml file correctly.

**Comment by sdispater** [comment]
It should be fixed in the latest `0.12.9` release.
