### ISSUE TITLE
Remove obsolete `install --develop` option

### ISSUE THREAD

**Issue by vlcinsky** [sdispater/poetry#647]
This issue is to track removal of `--develop` option.

It is result of #519 where @sdispater stated, the option became obsolete and is to be removed.

**Comment by vlcinsky** [comment]
Other issues may be resolved by this too:
- #207 
- #283

**Comment by neighthan** [comment]
Is it an error that `poetry list` says `develop` is Deprecated?

**Comment by jacebrowning** [comment]
@neighthan No, `develop` is deprecated in favor of `install`, which does the same thing.

**Comment by neighthan** [comment]
Ah, install _without_ the develop flag does the same as develop? Does
install with the develop flag do the same as without now?

**Comment by esciara** [comment]
`--develop` option still appears as a cli option: https://github.com/sdispater/poetry/blob/2ed53be4f7d9c86087e4a0b82984b9a718211a9b/poetry/console/commands/install.py#L15
And also still appears in the doc:
https://github.com/sdispater/poetry/blob/2f2cec03b6b14e882522f7f6042ecdafebda2ca5/docs/docs/versions.md#L111-L115
