### ISSUE TITLE
Poetry run script fails silently

### ISSUE THREAD

**Issue by hroemer** [sdispater/poetry#652]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro 18.0.0
- **Poetry version**: 0.12.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist](https://gist.github.com/hroemer/33fd79ce4712261d256d7ff2683182be)

## Issue
The changes made in #577 / #578 cause my scripts to fail silently, now.

file structure:

```bash
.
├── pack
│   ├── cli.py
│   └── __init__.py
├── poetry.lock
├── pyproject.toml
└── README.rst
``` 

[pyproject.toml](https://gist.github.com/hroemer/33fd79ce4712261d256d7ff2683182be)

run.py:

```python3
def run():
    print("run called")


if __name__ == "__main__":
    run()
```

### poetry==0.12.8

```bash
$> poetry run my-script
run called
```

### poetry==0.12.9

```bash
$> poetry run my-script
```

Any ideas?

**Comment by madig** [comment]
Hitting the same issue. Here's an example package: [testp.zip](https://github.com/sdispater/poetry/files/2599767/testp.zip)

It worked when I just had one script entry pointing to `testp:main`, but after I added `cli.py` and a second script, it stopped working...

**Comment by sdispater** [comment]
Something is definitely off.

I will investigate and get back to you.

**Comment by sdispater** [comment]
Commit c2c6f3b should fix the issue.

I will try to make a bugfix release soon.

**Comment by sdispater** [comment]
Release `0.12.10` is out and fixes this issue.
