### ISSUE TITLE
Jsonschema requires attrs, but not Poetry

### ISSUE THREAD

**Issue by MarcBoissonneault** [sdispater/poetry#653]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hi, I'm not sure how I could fix this dependency issue.

Here is my problem:
My pyproject.toml looks (almost) like this:
```
...
[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.10"
...
```

Poetry version `0.12.9`:
With the following setting: `poetry config settings.virtualenvs.create false`
When I run the following command `poetry install`
I got this output (shorted a bit):
```
$ poetry install
Installing dependencies from lock file

Package operations: 7 installs, 0 updates, 0 removals

  - Installing six (1.11.0)
  - Installing atomicwrites (1.2.1)
  - Installing attrs (18.2.0)
  - Installing more-itertools (4.3.0)
  - Installing pluggy (0.8.0)
  - Installing py (1.7.0)
  - Installing pytest (4.0.0)
```

Then if I run the following command:`poetry install --no-dev`
The output is:
```
$ poetry install --no-dev
Installing dependencies from lock file

Package operations: 0 installs, 0 updates, 7 removals

  - Removing atomicwrites (1.2.1)
  - Removing attrs (18.2.0)
  - Removing more-itertools (4.3.0)
  - Removing pluggy (0.8.0)
  - Removing py (1.7.0)
  - Removing pytest (4.0.0)
  - Removing six (1.11.0)
```
Like you can see above, `attrs` gets removed.
It's removed since it's a dependency of my "dev-dependencies" `pytest`.
But it's required by [`jsonschema` which is a dependency of `poetry`](https://github.com/sdispater/poetry/blob/master/pyproject.toml#L30).

So after this command, I cannot do anything with `poetry` since attrs was remove:
Example: 
```
$ poetry show

[ModuleNotFoundError]
No module named 'attr'

$ poetry lock

[ModuleNotFoundError]
No module named 'attr'
```

I'm not sure how I can fix that issue without being required to be on a virtual environment with poetry running on the system python.
Any idea?

Thanks.

**Comment by sdispater** [comment]
Unfortunately, Poetry does not protect its own dependencies. That's why I put a warning here https://poetry.eustace.io/docs/#installing-with-pip

To solve your issue you should use the recommended installer: https://poetry.eustace.io/docs/#installation. It installas Poetry in such a way that it is isolated from the rest of your system.

**Comment by MarcBoissonneault** [comment]
Thanks for the quick answer!
