### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by nasyxx** [sdispater/poetry#654]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave 10.14
- **Poetry version**: 0.12.9
pyproject.toml file:

```
λ cat pyproject.toml
[tool.poetry]
name = "pixiv2bg"
version = "1.0.0"
description = "Pixiv pictures to background."
authors = ["Nasy"]
license = "MIT"

[tool.poetry.dependencies]
uvloop = "^0.11.1"
aiohttp = "^3.3"
tqdm = "^4.24"
ujson = "^1.35"

[tool.black]
line-length = 79
```

## Issue
Well, when doing `poetry install`, an exception happened. I also have tried to remove the pyproject.toml and `poetry init` again, but it still failed like the result shown below. 

The project is here: https://github.com/nasyxx/pixiv2bg . Simply clone it down and `poetry install`, the exception will raise.

Here is the result:

```python
λ poetry install -vvv                  
[JSONDecodeError]             
Expecting value: line 1 column 1 (char 0)  
                                             
Exception trace:
 /usr/local/lib/python3.7/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /usr/local/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /usr/local/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /usr/local/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /usr/local/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /usr/local/lib/python3.7/site-packages/poetry/console/commands/env_command.py in initialize() at line 21
   ".".join(str(v) for v in current_env.version_info[:3])
 /usr/local/lib/python3.7/site-packages/poetry/utils/env.py in version_info() at line 128
   return tuple(self.marker_env["version_info"])
 /usr/local/lib/python3.7/site-packages/poetry/utils/env.py in marker_env() at line 144
   self._marker_env = self.get_marker_env()
 /usr/local/lib/python3.7/site-packages/poetry/utils/env.py in get_marker_env() at line 466
   return json.loads(output)
 /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py in loads() at line 348
   return _default_decoder.decode(s)
 /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in decode() at line 337
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in raw_decode() at line 355
   raise JSONDecodeError("Expecting value", s, err.value) from None

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

**Comment by nasyxx** [comment]
Hi, I guess I have solved this issue. I deleted the cache file and it works well again.

**Comment by andrecontdi** [comment]
> Hi, I guess I have solved this issue. I deleted the cache file and it works well again.

I have the same problem but I don't know what cache file or where is the cache file that you are indicating.

**Comment by Imaclean74** [comment]
I'm seeing this same issue - on Linux. And cache delete appears not to help.

**Comment by darrenleeweber** [comment]
Also bumped into this.  What is causing this?

**Comment by Imaclean74** [comment]
for me at least https://github.com/sdispater/poetry/issues/779 seems to be the root cause.  EnvBuilder create fails to copy files for some reason and leaves a partially created and nonfunctional venv.  How it fails I'm not clear on yet. However at least on my system I have a consistent repro by doing this ( code modeled on utils/env.py )

``` python
tmpdir = tempfile.mkdtemp()
path = pathlib.Path( tmpdir ) / "test"
print(f"creating temp dir in {path}")
builder = EnvBuilder(with_pip=True)
builder.create(path)
```

which gives this error 
```bash
 output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/tmp/tmp2lefjc9x/testp/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```
but it works if I flip the mode to use symlinks 

```python
builder = EnvBuilder(with_pip=True, symlinks=True)
``
and that also works after patching env.py in poetry.

note - that you only see this error on the first command that triggers venv creation. Subsequent commands will call  get_marker_env() that shells out to the python in the broken venv and gets an error string instead of a valid json block - triggering the JSONDecodeError error above.

**Comment by spebern** [comment]
I have the exact same issue. 
Clearing the cache did not work for me.
Python version: Python 3.7.3

**Comment by Imaclean74** [comment]
@spebern - even with the latest Poetry version ?  does a simple `.venv/bin/python` work as expected ?

**Comment by shabbyrobe** [comment]
I get errors that libc is missing using python:3.7-slim-stretch:

```
# .venv/bin/python
.venv/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by .venv/bin/python)
.venv/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by .venv/bin/python)
```

If I run `apt-get install libc6`, blow away .venv and re-run `poetry install`, everything works.

**Comment by adrianchung** [comment]
As per #779, I was able to get around this `python -m venv .venv` on my Mac with version 10.14.6

**Comment by laoshaw** [comment]
this occurs with 3.10-rc2 on ubuntu 20.04

**Comment by adam-grant-hendry** [comment]
I had a `.pth` file in my `venv` that remained and was referring back to a package I removed. Deleting that solved my problem. To check which file is causing the problem, you might try running

```bash
py -m pip install --upgrade pip
```

**Comment by jcowles** [comment]
also experiencing this same problem, clearing the cache does not help

**Comment by ksamuel** [comment]
I am still encountering the issue, as of May 2022. 

I don't know if there is several causes for this. However, for my particular case, I found the cause (which was not related to cache), and offered a code fix here: https://github.com/python-poetry/poetry/issues/5737

For those who wants to save time, here is the gist of it:

- I activated warnings using the PYTHONWARNINGS env vars, which triggers the JSONDecodeError
- There is a way to fix that in poetry's code, but that will have to wait until next release
- Meanwhile, you can workaround this issue by making sure PYTHONWARNINGS is set to "ignore" when you call poetry

E.G: 

```
# unix
# onliner for one call
PYTHONWARNINGS=ignore  poetry add ...
# for the whole session
export PYTHONWARNINGS=ignore  
poetry add ...
```

```
# windows
set PYTHONWARNINGS=ignore 
poetry add ...
```

If this doesn't work for you, this means the JSONDecodeError issue can have more than one cause. The fact deleting the cache works for some and not for others suggest it.
