### ISSUE TITLE
Poetry using the wrong Python version (not related to pyenv)

### ISSUE THREAD

**Issue by zmitchell** [sdispater/poetry#655]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I'm having an issue adding a package to a project because `poetry` is picking up on the wrong Python version. I'm pretty confident that something has gone awry in my system, but I'm doing my best to salvage the situation and not have to go through the whole process of installing Raspbian from scratch on this Raspberry Pi. I installed `poetry` using the recommended method (`curl ...`). Can you point me in the right direction? As mentioned in the title, I'm not using `pyenv`. All of the relevant issues I found were related to `pyenv`, so I'm not really sure how to get `poetry` to use the correct Python.

Here are some terminal outputs to help you diagnose the issue:
```
pi@widget:temp_logger$ python --version
Python 3.5.3
pi@widget:temp_logger!$ sudo python --version
Python 2.7.13
pi@widget:temp_logger$ poetry --version
Poetry 0.12.9
pi@widget:temp_logger$ poetry debug:info

Poetry
======

 * Version: 0.12.9
 * Python:  2.7.13


Virtualenv
==========

 * Python:         2.7.13
 * Implementation: CPython
 * Path:           NA


System
======

 * Platform: linux2
 * OS:       posix
 * Python:   /usr


pi@widget:temp_logger$ poetry add adafruit-blinka

[RuntimeError]
The current Python version (2.7.13) is not supported by the project (^3.5)
Please activate a compatible Python version.

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

```

**Comment by sdispater** [comment]
As you can see in `debug:info`, Poetry picks up Python 2.7.13 and not Python 3.5.3. What is the output of `which python`? Does it point to your 2.7.13 Python or 3.5.3?

**Comment by zmitchell** [comment]
Ah, here we go. It turns out `python` was aliased to `python3`, and doing `which python` uncovered that. Now `python --version` returns 2.7.13, and `which python` returns `/usr/bin/python`. So how do I get `poetry` to use Python 3 instead?

**Comment by sdispater** [comment]
@buriy Commit 94304e9 should fix your issue.

It will land in the next bugfix release.

**Comment by buriy** [comment]
@zmitchell Then, If I got it right, try reinstalling poetry. If installed with python2, it's bound to using python2 unless you use pyenv or virtualenv.

**Comment by zmitchell** [comment]
I reinstalled with Python 3 using `curl ... | python3` and it still only picks up 2.7.

**Comment by jtbeach** [comment]
In 0.12.x, poetry is not bound to the interpreter version your curl it through -- so it doesn't matter which one you install it with with. 

If `python` points to python2 and your project needs python3, you have 2 choices:

1. (preferable) Use pyenv and run `pyenv local 3.7.0` or whatever your project wants in the root folder of your project. If you have your pyenv shims setup correctly in your shell startup files, `python` will now execute Python 3.7.0 whenever `python` runs, regardless of what `python` points to globally.

2. Manually create a virtualenv with Python 3 and activate it prior to running `poetry` commands. You can use direnv or similar to make that a little more automated, but I still prefer using pyenv -- once you get used to it, it's great

**Comment by sdispater** [comment]
@buriy Release `0.12.10` is out!

**Comment by buriy** [comment]
@sdispater thanks a lot!
Option 2 mentioned by @jtbeach works again.

**Comment by asodeur** [comment]
Not sure if this is the original issue or a new Windows related issue (seeing this on 0.12.10 and 1.0.0a1).

`SystemEnv.run("python", ...)` will always use the primary system interpreter on Windows even if `poetry` is running on another one not installed in a virtual env.  This is because `SystemEnv._bin("python")` is looking for `python.exe` in `SystemEnv._bin_dir` which on Windows is `<Python root>/Scripts`, however the interpreter is there for virtual envs only. for standard Python installations the interpreter is `<Python root>/python.exe`.

Running `poetry` from inside a virtual env, ie option 2 above works fine.

**Comment by airstandley** [comment]
I've also been running into issues trying to get poetry installing to the correct version of python when no using a virtual environment (`poetry config settings.virtualenvs.create false`).

After doing some digging it looks like `SystemEnv` is still determining the binary to call by appending `sys.base_prefix`/bin to the executable name given. This approach will not work on linux systems that have versions of both python2 and python3 installed.
It seems that a system python environment should be using the system python and simply calling the binary without a specific path. At the moment there seems to be no way to get poetry to install to a linux system python3 installation without changing the `/usr/bin/python` symlink prior to running `poetry install`. This is far from ideal.

**Comment by Peque** [comment]
Using Poetry 1.0 (prerelease) seems to fix this issue:

```
poetry self:update --preview
poetry env use python3.7
```

See https://github.com/sdispater/poetry/pull/731 for more information.

**Comment by maggyero** [comment]
@Peque Well the new `poetry env` command provides an explicit way to fix the issue (which is great). But the implicit way is still broken. Poetry should implicitly install the Python version specified in the `tool.poetry.dependencies.python` property of the `pyproject.toml` file

**Comment by AntonKomar** [comment]
Me too

**Comment by sdispater** [comment]
This has been improved in the latest beta release (see #1477 for more information).

**Comment by tatianafrank** [comment]
The only thing that works for me (until i can use the new env feature) is running `pyenv shell <version>`. Unfortunately pyenv local and pyenv global dont work and my virtual environment is not getting picked up otherwise.

**Comment by AlJohri** [comment]
Upgrading to the latest beta (`1.0.0b8`) fixed the issue for me:

```
The currently activated Python version 3.7.5 is not supported by the project (^3.8).
Trying to find and use a compatible version.
Using python3 (3.8.0)
Creating virtualenv al-research-project in /Users/aljohri/Development/al-research-project/.venv
```

p.s. hi @tatianafrank!

**Comment by ekhaydarov** [comment]
None of the above works if youre trying to run poetry from crontab

**Comment by yifeikong** [comment]
Using `curl -sSL ...` to install is still broken on macOS catalina with homebrewed python3. However, using `pip3 install poetry` works for me.

**Comment by JulianFerry** [comment]
I think it would be nice to be able to specify `poetry config python-version 3.7` so that poetry generally defaults to that version of python.

For example `poetry new` should default to using that version when creating a new project. Currently I have to remember to update the python version to 2.7, which leads to some confusion when I call `poetry add` but can't access that package when I load a new python interpreter.

Currently when I do `poetry new` then edit the ***pyproject.toml*** file to `python = "^3.7"` instead of 2.7, I see the current warning message:
```
The currently activated Python version 2.7.16 is not supported by the project (^3.7).
Trying to find and use a compatible version.
Using python3 (3.7.7)
```
Which is slightly confusing since no version of python has been "activated" at this point, and I have aliased python to python3, so it is only some default poetry configuration which is incorrect.

**Comment by GabrielBB** [comment]
> Using `curl -sSL ...` to install is still broken on macOS catalina with homebrewed python3. However, using `pip3 install poetry` works for me.

This did it for me! Don't forget to remove the old poetry from your path

**Comment by johnthagen** [comment]
I'd like to echo @maggyero's comment: https://github.com/python-poetry/poetry/issues/655#issuecomment-532608560

As a first time new user, installing `poetry` using the recommended `curl` method, it was very strange to me that by default `poetry install` created a Python 2.7 virtual environment for a project marked as Python 3 in `pyproject.toml`. Especially since Python 2 is end-of-life, there is extra importance in my mind to keep this from happening on new users.

**Comment by dyerdave-cvs** [comment]
Also not using pyenv.   pip3 install poetry worked for me, whereas all the other suggestions did not.  On Amazon Linux 2, which still runs 2.7 by default.

**Comment by mtsolmn** [comment]
> If I edit the _**pyproject.toml**_ file to `python = "^3.7"` instead of 2.7, when I call `poetry add` I see the following warning message:
> 
> ```
> The currently activated Python version 2.7.16 is not supported by the project (^3.7).
> Trying to find and use a compatible version.
> Using python3 (3.7.7)
> ```
> 
> Which is slightly confusing since no version of python has been "activated" at this point, and I have aliased python to python3, so it is only the `poetry env use` configuration which is incorrect.

@JulianFerry If you have already ran `poetry install`, then a `poetry.lock` file have been created and is the reason for this issue. I do not know of any argument for `poetry add` to ignore `poetry.lock`, so you may need to delete `poetry.lock` after editing pyproject.toml.


>Poetry should implicitly create a built-in virtual environment with the Python version specified by the tool.poetry.dependencies.python property of the pyproject.toml file, not the Python version resolved by the `#!/usr/bin/env python` shebang line of the `~/.poetry/bin/poetry` script.

To give a temporary solution to @maggyero and @johnthagen, yes I agree this is really annoying. For me the best solution on Mac OS has been to manually edit the shebang line of `~/.poetry/bin/poetry` to `#!/usr/bin/env python3` and I have python3 as a symlink to my python3.8 version from homebrew. Now poetry uses my homebrew version of python to run and, equally important, now sets the python dependency of any new project as `python = "^3.8"`.

```
❯ poetry new test-demo
Created package test_demo in test-demo
❯ cd test-demo
❯ poetry env info

Virtualenv
Python:         3.8.5
Implementation: CPython
Path:           NA

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8
```

This is a relatively elegant, although inconvenient solution to the problem. But you can set it once and forget it, and can modify the shebang line for whatever version of python you want. I think that poetry should have a config option to set the python PATH for the executable it runs and a separate config option for the default dependency version of python set in `pyproject.toml` for any new project created. Even better would be more argument flags for `poetry new` to set these things per project at creation time. But this is what we have for now. Hope this helps.

**Comment by Boubsi** [comment]
Hi all
@mtsolmn Thanks for the `#!/usr/bin/env python3` hack, this is the only thing that works for me (by default any project created with the `new` command would be only python2.7 compatible, and the `poetry env use python3` command would end up with a `[NoCompatiblePythonVersionFound]` error.

An idea to prevent that would be to be able to add a tag that specifies python version when creating a new project. Something like
```bash
poetry new mypck --python_version 3.7+
```
Or at least why it does not update the pyproject.toml file when using `poetry env use python3`

**Comment by martynasoxylabs** [comment]
I solve this problem on my Mac by replacing following line
```
#!/usr/bin/env python
```
to 

 ```
#!/usr/bin/env python3.8
```
in /home/<name>/.poetry/bin/poetry file. Then it picks python3.8 automatically and there are no annoying warnings anymore.

**Comment by mafeko** [comment]
Just another copy&paste takeaway for the working solution on unix-systems:
```bash
sed -i 's/#\!\/usr\/bin\/env python/#\!\/usr\/bin\/env python3/g' ~/.poetry/bin/poetry
```

**Comment by iuriguilherme** [comment]
I have poetry version 1.1.4 installed via `pyenv exec pip --user --upgrade poetry` at **~/.local/bin/poetry** and this is the first line of that file:

```
#!/home/user/.pyenv/versions/3.9.2/bin/python3.9
```

When I attempt a `poetry install` in a project folder, it uses the system python (which is 3.5 and therefore useless).

Tried the `pyenv exec poetry` to the same result. Even `~/.local/bin/poetry` will still yeld the following error:

> SolverProblemError
> The current project's Python requirement (3.5.3) is not compatible with some of the required packages Python requirement:

**Comment by chamini2** [comment]
I still experience this, is there a new issue to subscribe to for the fix?

**Comment by dreamflasher** [comment]
Same issue here, is there any way to directly specify the python bin path for poetry?

**Comment by edgarrmondragon** [comment]
@dreamflasher `poetry env use` already takes an executable, so this might work for you:

```shell
poetry env use $(pyenv which python3.10)
```

**Comment by dreamflasher** [comment]
Thank you, but unfortunately this didn't work. I needed to add (sudo update-alternatives) a symlink to python3.9 as well as modify the poetry bin.

**Comment by V-iktor** [comment]
Still an issue.
```
python --version
Python 3.9.16
```

```
(saleor-py3.9) x@x-MacBook-Pro-2 saleor % poetry install

Current Python version (3.10.9) is not allowed by the project (~3.9).
```

**Comment by MichaelVoelkel** [comment]
Yeah exactly

**Comment by iuriguilherme** [comment]
poetry and pipenv select the python you specify on pyproject.toml or Pipfile, as long as they're findable in the PATH or similar. Those tools are not affected by pyenv shims.

**Comment by MichaelVoelkel** [comment]
I don't even have `pyenv` in path, it will give "not found". My issue was that I had Python3.9 installed and Python3.10 also. However, `python3` symlink would point to 3.10 and `python2` to 3.9. Poetry for some reason insisted, although I stated 3.10, on using `python3.9`, no clue why. It was certainly in the path BUT behind the paths in the front that pointed to 3.10.
Anyways, I removed Py3.9 for good, so that solves it

**Comment by finswimmer** [comment]
@trompx This is described in the FAQ: https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

**Comment by sumeeterito** [comment]
also still an issue for me. I am on poetry 1.5.1 and when i run 
* `poetry env use 3.7.16`
* `poetry add scikit-learn`

I get 

```
Error: 'numpy' must be installed before running the build.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py
```

you can see that the poetry environment is referencing a python 3.8.

even `poetry run python --version` yields `3.7.16`; but still it references python 3.8

**Comment by finswimmer** [comment]
@sumeeterito This issue is closed for a long  time and yours seems unrelated to me. Please open a new ticket.
