### ISSUE TITLE
Poetry fails with space in working directory

### ISSUE THREAD

**Issue by rschuetzler** [sdispater/poetry#657]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: `0.12.9`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
Similar to #199, I'm unable to use Poetry if there is a space in my path. I can't even begin using Poetry enough to create a venv. The full path to the working directory is `C:\Users\FirstName LastName\code\`. When I try running `poetry new` or `poetry init`, I get the following error:

```
~\code\poetry-test> poetry init -vvv
(null): can't open file 'C:\Users\FirstName': [Errno 2] No such file or directory
```

The issue occurs even if I create a working directory at the root `C:\poetry-test\`. Poetry seems to have an issue if it is installed inside a directory that contains a space:

```
C:\poetry-test> where.exe poetry
C:\Users\FirstName LastName\.poetry\bin\poetry
```

**Comment by sdispater** [comment]
This has been fixed in commit a920b38. However this will not be fixed for you until you install a new version.

To fix this now, in the `C:\Users\FirstName LastName\.poetry\bin\poetry.bat` file, just change this line:

```
python %USERPROFILE%\.poetry\bin\poetry %*
```

to

```
python "%USERPROFILE%\.poetry\bin\poetry" %*
```

(Note the quotes)
