### ISSUE TITLE
installation from a git repo is not working with python version other than 3.5

### ISSUE THREAD

**Issue by scilo7** [sdispater/poetry#661]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS**: Debian GNU/Linux 8.0 (jessie)
- **poetry version**: 0.12.9

## Issue

Trying to install from a private gitlab repo with python 2.7 gives this error:

```
[RuntimeError]
Unable to retrieve the package version for /tmp/pypoetry-git-xxxxxPmWHI
```

It looks like SetupReader.read_setup_py will return an empty version for a package with any python version different from 3.5 

```python
# file read_setup.py, line 68
def read_setup_py(
        self, filepath
    ):  # type: (Union[basestring, Path]) -> Dict[str, Union[List, Dict]]
        if not PY35:
            return self.DEFAULT
```
Any reason for that ?

Thanks

**Comment by sdispater** [comment]
Because AST parsing in Python 2.7 and 3.4 is different and I focused on the most recent versions for this feature since it's really complicated as it is to read a `setup.py` file without executing it.

However, if someone wants to tackle this and implement the same feature for Python 2.7 and 3.4, I'd gladly review a PR.

**Comment by tom-mi** [comment]
I'd be happy already if this would work with current python versions like 3.6 or 3.7.
Is there a reason that this feature also excludes later versions?

Thanks for looking into it.

**Comment by chaitan94** [comment]
Bumping up as there was no response yet to @tom-mi for quite a long while.

**Comment by billop** [comment]
This should be reopened since 3.6-3.8 still aren't supported. 3.5 is pretty old and will be officially completely unsupported by 2020-09-13.

**Comment by sdispater** [comment]
It works for Python >=3.5.

The if statement mentioned in the original post is correct, albeit a little misleading.

the `PY35` constraint is actually `sys.version_info >= (3, 5)`, so `not PY35` actually means 'sys.version_info < (3, 5)' which is acually what we want.
