### ISSUE TITLE
examples of how to release a package using poetry in a .travis.yml

### ISSUE THREAD

**Issue by cjw296** [sdispater/poetry#669]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The subject says it all, really. Travis CI has a built-in release for packages that have setup.py's, but I'd prefer to use poetry to release my packages when a tag is pushed!

**Comment by sdispater** [comment]
I think this is what you need: https://github.com/pyslackers/slack-sansio/blob/master/.travis.yml#L37

I didn't test it myself but this is the way it should be implemented, in my opinion.

**Comment by jtc42** [comment]
For anyone stumbling upon this issue thread, the above link is not longer available. The file can now be found at https://github.com/pyslackers/slack-sansio/blob/2adb7c285deccbbb915d3890c27dc6d9adf38a3c/.travis.yml
