### ISSUE TITLE
cant install weasyprint under Python 3.7

### ISSUE THREAD

**Issue by kakulukia** [sdispater/poetry#674]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
Im not sure if this really is a poetry issue or a bad definition of the weasyprint package, but weasyprint has 3.7 listed in its setup.cfg and is installable with pip.
https://github.com/Kozea/WeasyPrint/blob/master/setup.cfg

But still poetry print this when i want to add this package:

    The current Python version (3.7.0) is not supported by the project (3.6)
    Please activate a compatible Python version.

**Comment by sdispater** [comment]
The error means that your currently active Python is `3.7` while your project is only compatible with Python `3.6`. You should activate your Python `3.6` executable.

This has nothing to do with `weasyprint`.

**Comment by kakulukia** [comment]
oh, i read that the wrong way obviously .. 
Its weird tho - because how did i come to this status of poetry not able to do stuff due to this mismatch? I cant even install the venv that way? I bet its because i did that with an older version?

Thx for the hint tho!
