### ISSUE TITLE
Incorrect output when installing packages

### ISSUE THREAD

**Issue by moigagoo** [sdispater/poetry#68]
Package version gets printed over the word "Installing":

![](https://i.imgur.com/FDsGC4e.png)

**Comment by moigagoo** [comment]
Running on Windows, pwsh. Poetry 0.8.5.

**Comment by sdispater** [comment]
That's strange.

Could you execute the same command with the `--no-ansi` command to disable colors to see if it comes from that.

**Comment by moigagoo** [comment]
The same thing happens, only with no colors:

**Comment by moigagoo** [comment]
Can't reproduce in 0.10.2, closing,
