### ISSUE TITLE
Dependency problem when installing dynamic-rest 1.8.0 with django 2.0.7

### ISSUE THREAD

**Issue by gonvaled** [sdispater/poetry#683]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19 Tara
- **Poetry version**: Poetry 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/gonvaled/914f5fda1b55c22a161741b566e7a555

## Issue

I am not sure what is going on, since `dynamic-rest 1.8.0` is supposed to be compatible with django 2.0.7:

```
» poetry add dynamic-rest==1.8.0

Updating dependencies
Resolving dependencies... (0.2s)
                                                                                     
[SolverProblemError]                                                  
Because dynamic-rest (1.8.0) depends on Django (>=1.8,<2.0)                        
 and poetry-demo depends on Django (^2.0.7), dynamic-rest is forbidden.            
So, because poetry-demo depends on dynamic-rest (=1.8.0), version solving failed.  
                                                                                     
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

```
I am on python 3.6.5:
```
» python --version
Python 3.6.5
```

According to [dynamic-rest sources](https://github.com/AltSchool/dynamic-rest/blob/master/install_requires_python3.txt), these are the requirements for python 3:

```
Django>=1.8,<2.1
djangorestframework>=3.1.0,<3.8
inflection==0.3.1
requests
```

**Comment by mozartilize** [comment]
according to [this](https://github.com/AltSchool/dynamic-rest/blob/v1.8.2/install_requires.txt), version 1.8 does not support django 2.0

**Comment by mozartilize** [comment]
but in [release notes](https://github.com/AltSchool/dynamic-rest/releases/tag/v1.8.0), it says it supports django 2.0, lol

**Comment by gonvaled** [comment]
> according to [this](https://github.com/AltSchool/dynamic-rest/blob/v1.8.2/install_requires.txt), version 1.8 does not support django 2.0

Yes, and afaik, that is used for only python 2 (https://github.com/AltSchool/dynamic-rest/blob/master/setup.py):

```
    install_requires=open('install_requires.txt'
                          if sys.version_info.major == 2
                          else 'install_requires_python3.txt').readlines(),
```

 The relevant file for python 3 should be the one I linked above, which has:

```
Django>=1.8,<2.1
djangorestframework>=3.1.0,<3.8
inflection==0.3.1
requests
```

So, in theory this is compatible with Django 2.0 when using python3.

No idea what is going on.

I have a related issue open in the other project: https://github.com/AltSchool/dynamic-rest/issues/264

**Comment by Incanus3** [comment]
Hi,
is there any plan to having this fixed? This is currently the only blocker for our using this otherwise amazing tool.
