### ISSUE TITLE
Don't automatically update a package when its maintainer has changed

### ISSUE THREAD

**Issue by sprt** [sdispater/poetry#687]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

You may be aware of https://github.com/dominictarr/event-stream/issues/116. In short, the ownership of a widely-used NPM package was transferred to someone else, who then uploaded a malware-infected version of said package. This compromised all packages that depended on event-stream.

Now, this is something that could very well happen in the Python ecosystem with PyPI. I propose the following to try and mitigate this issue: consider maintainer changes as breaking changes, the same way major version changes are. This way, packages would never be automatically updated to a version where the maintainer has changed. What do you think?

**Comment by jacebrowning** [comment]
Is such metadata even available? Wouldn't a malicious author simply masquarade as the origional?

**Comment by sprt** [comment]
Ah that's correct, I thought PyPI's API returned the actual owners of the package, but it's basically just the `setup.py`'s content. I think the only way to get that information right now is by parsing the HTML.
