### ISSUE TITLE
`poetry config --list` looks for `~/Library/Application\ Support/pypoetry/config.toml`

### ISSUE THREAD

**Issue by keevee09** [sdispater/poetry#69]
I'm on
* OSX High Sierra 10.13.4
* Homebrew
* pyenv virtualenv
* poetry installed in a *python3.6.4* virtual environment
* using *bash* (have not tested in *fish* or *zsh*)

Inside my project folder with a `virtualenv` enabled when I attempt to run a `poetry config` command, I get a `[FileNotFound] ... [Errno 2]` error where it say's it can't find
`~/Library/Application Support/pypoetry/config.toml` (which it shouldn't be looking for, no?)

I have added bash support as suggested in poetry's github README.md

Looking in the `~/.pyenv/versions/po/lib/python3.6/site-packages/poetry` directory I found a file
`console/commands/config.py` which has a reference to `config.toml` on line 43.

`poetry config --help` and `poetry config --version` work while `--list` and `--unset` both give me the same above error.

**Comment by sdispater** [comment]
It's actually a bug in the config that does not create the necessary files (only the directory) to store configuration settings.

I will fix it and get back to you.

**Comment by jgirardet** [comment]
same thing on a ubuntu 16.04 user poetry with python 3.5 and 3.6
the config.toml is never created (or elsewhere ?)

**Comment by sdispater** [comment]
This should be fixed in version `0.8.5`
