### ISSUE TITLE
Install of a package from URL

### ISSUE THREAD

**Issue by germn** [sdispater/poetry#695]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Sometimes packages easily avaliable only by url, for example [binaries for Windows](https://www.lfd.uci.edu/~gohlke/pythonlibs/). It would be nice to be able to do something like:

`poetry add pycurl --url https://download.lfd.uci.edu/pythonlibs/h2ufg7oq/pycurl-7.43.1-cp37-cp37m-win_amd64.whl`

For example, pipenv [supports it](https://github.com/pypa/pipenv/issues/480#issuecomment-330605268) :)

**Comment by canassa** [comment]
Hi @germn 

I opened a PR to implement this feature, maybe you could take a look at it? I am looking for feedback 😄

**Comment by keunhong** [comment]
This is crucial for installing packages such as PyTorch: https://pytorch.org/ which are sometimes only distributed through a .whl file due to complicated dependencies like CUDA.

**Comment by steinnes** [comment]
I would also really appreciate this.  I often have to make custom wheels for packages I'm using, which I install via web (to avoid bloating my git repos with big ugly wheel deltas).  Just switched to poetry for one of my projects and surprised that this wasn't possible.

**Comment by sdispater** [comment]
Added in #1260
