### ISSUE TITLE
Publish to Artifactory fails with error: "415 Client Error: Unsupported Media Type"

### ISSUE THREAD

**Issue by amal-khailtash** [sdispater/poetry#708]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Red Hat Enterprise Linux Server 7.4
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not needed

## Issue
We have a local Jfrog Artifactory and PyPi image, and I have setup my projects pyproject.toml as well as configured the "tool.poetry.source" section properly:

```
[[tool.poetry.source]]
name = "artifactory"
url = "https://artifactory/api/pypi/local-pypi/simple"
```

Poetry config is also setup correctly with URL and basi-auth username/password:

~/.config/pypoetry/config.toml 
```
[repositories]
[repositories.artifactory]
url = "https://artifactory/api/pypi/local-pypi/simple"
```

~/.config/pypoetry/auth.toml 
```
[http-basic]
[http-basic.thw]
password = "<PASSWORD>"
username = "<USERNAME>"
```

When I try to publish my project artifacts, I get the following error:

```
$ poetry -vvv publish -r artifactory

Publishing project (1.1.4) to artifactory

[HTTPError]
415 Client Error: Unsupported Media Type for url: https://artifactory/api/pypi/local-pypi/simple

Exception trace:
 .venv/lib/python3.7/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 .venv/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 .venv/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 .venv/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 .venv/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 .venv/lib/python3.7/site-packages/cleo/commands/command.py in execute() at line 107
   return self.handle()
 .venv/lib/python3.7/site-packages/poetry/console/commands/publish.py in handle() at line 54
   self.option("repository"), self.option("username"), self.option("password")
 .venv/lib/python3.7/site-packages/poetry/masonry/publishing/publisher.py in publish() at line 84
   return self._uploader.upload(url)
 .venv/lib/python3.7/site-packages/poetry/masonry/publishing/uploader.py in upload() at line 97
   self._upload(session, url)
 .venv/lib/python3.7/site-packages/poetry/masonry/publishing/uploader.py in _upload() at line 181
   self._do_upload(session, url)
 .venv/lib/python3.7/site-packages/poetry/masonry/publishing/uploader.py in _do_upload() at line 203
   resp.raise_for_status()
 .venv/lib/python3.7/site-packages/requests/models.py in raise_for_status() at line 940
   raise HTTPError(http_error_msg, response=self)

publish [-r|--repository REPOSITORY] [-u|--username USERNAME] [-p|--password PASSWORD] [--build]

```

I think the problem is with how artifactory's AQL posts are treated and explained here: https://stackoverflow.com/questions/52394874/415-unsupported-media-type-in-artifactory-aql-post

Although the content looks like JSON, but content-type needs to be set to "text/plain".

**Comment by amal-khailtash** [comment]
I found out that the problem is with having the "/simple" in the repository URL.  If I remove that, I can publish my artifacts now.

**Comment by ToddG** [comment]
Worth noting that this is in the docs:
https://www.jfrog.com/confluence/display/JFROG/PyPI+Repositories

```PyPI remote repository URL

You should not include /pypi or /simple in the the PyPI remote repository URL. These suffixes are added by Artifactory when accessing the remote repository.

If you use a custom PyPI remote repository, you need to make sure it has a simple index (directory listing style) accessible by <URL>/simple.
```

**Comment by Teivaz** [comment]
This helps indeed. It would be lovely to have this as a part of the error message as it is produced (only surfaced but still) in the poetry code. It could spare some time the people who are not familiar with all the caveats of artifactory and trying this thing out.
