### ISSUE TITLE
Have a feature similar to pipenv's custom scripts shortcut

### ISSUE THREAD

**Issue by Sweenu** [sdispater/poetry#713]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I would love to see a feature similar to [pipenv's scripts](https://pipenv.readthedocs.io/en/latest/advanced/#custom-script-shortcuts)

I think it could replace basic makefiles! What do you think?

Btw, been using Poetry for a week and been loving it. Du bon boulot, merci !

**Comment by jacebrowning** [comment]
This appears to be a duplicate of https://github.com/sdispater/poetry/issues/241

**Comment by Sweenu** [comment]
oh sorry, I searched thoroughly but not well enough it seems...
I'll close this issue then.
