### ISSUE TITLE
`poetry build` builds wheel without compression

### ISSUE THREAD

**Issue by outcatcher** [sdispater/poetry#715]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 7
- **Poetry version**: 0.12.10 (Python 3.7.0 x64)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/outcatcher/fdcc2c4f69236cc561476504ade6ba19

## Issue
_This is not exactly an error, rather just unexpected behaviour, maybe should be a feature request?_

Poetry builds wheel with bigger file size than `setuptools` `setup.py` for same source and same wheel content

Reproduced on repository: https://github.com/outcatcher/poetry_not_compressing_build \
Versions of wheels are be different: 0.1.0 for `poetry` and 0.1.1 for `setup.py`

**Comment by MRigal** [comment]
Closed by #838

**Comment by sdispater** [comment]
It has been fixed in the latest `0.12.12` version
