### ISSUE TITLE
Allow add to accept package name and version as a single string

### ISSUE THREAD

**Issue by ulope** [sdispater/poetry#717]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Please allow `add` to accept the package name and version constraints in a single string. I.e. `poetry add 'something>=2.1'` instead of having to use `poetry add 'something >=2.1'`. 

This is slightly related to #429 in that it would also reduce friction for people switching over from other tools (e.g. pip).

Also there is a slight documentation bug here: Neither the [docs](https://poetry.eustace.io/docs/cli/#add) for the add command nor the command line help include any mention on how to specify version constraints in the first place.

**Comment by sdispater** [comment]
This is now possible in the latest beta release (see #1221 for more information).
