### ISSUE TITLE
Don't modify ~/.profile if `.poetry/bin` already in $PATH

### ISSUE THREAD

**Issue by garyo** [sdispater/poetry#718]
I'd like to make it easier to install poetry on all my dev machines; using the curl method always modifies `~/.profile` which is annoying since I carefully manage all my dotfiles, so I have to go around undoing that mod after installing poetry. (I add it to the path myself.)
It would be nice if `get-poetry.py` would check if `~/.poetry/bin` is already in $PATH before modifying `.profile`.
I know I can get the installer and then run it locally and answer 'n', but there's also no cmd line option for `--no-set-path` for when I want to do it silently. (I can pipe `yes n` to it on Mac & Linux, that's a workaround.)

**Comment by eblume** [comment]
@garyo something like this? ^

**Comment by garyo** [comment]
Sweet!
