### ISSUE TITLE
Packages with semvar+devnum schemas don't resolve.

### ISSUE THREAD

**Issue by jMyles** [sdispater/poetry#736]
- [ x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.10
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jMyles/8ad4b9e81ec8697669c4df8480f121c7

## Issue

A schema of seemingly increasingly popularity, especially in high-velocity projects, is the following:

`(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(-(?P<stage>[^.]*)\.(?P<devnum>\d+))`

For example: `0.2.1-alpha.26`

It appears that poetry will not install packages that have such a version specification in their history.  For example:

`poetry add eth-keys` 

results in:

```
                                                         
[ValueError]                              
Could not find a matching version of package eth-keys  
                                                         
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

...despite `eth-keys` obviously being a valid package.

**Comment by sdispater** [comment]
This is not the issue. Poetry can parse these just fine. The issue is that `eth-keys` only has prereleases so you have to add `--allow-prereleases` to `add` or specifying the constraint when adding `eth-keys`. So the two options are:

```bash
poetry add eth-keys --allow-prerelease
poetry add eth-keys:^0.2.0b3
```

However, I admit that Poetry should be a little more clever and if there are only prereleases it should select the latest one. This is something I plan on improving the next major release.

**Comment by fchorney** [comment]
What about the situation where a packages dependency only has prereleases? My solution was to just add that sub package manually, but I don't think that should be the solution.

**Comment by snow8gaia** [comment]
clever
------------------------
if there are only prereleases it should not install the **pre-release package** 


**pseudocode**
------------------------

if `latest available version` is pre-release
ignore pre-release = true
print-warning("There is a pre-release available. would you ~~like~~ dare to install it?")
