### ISSUE TITLE
Basic authentication fails if API redirects include username/password

### ISSUE THREAD

**Issue by connorbrinton** [sdispater/poetry#746]
- [ x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [ x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS Mojave
- **Poetry version**: 0.12.10

## Issue
I use a private PyPI server which supports basic HTTP authentication over HTTPS. I configure this server in Poetry with the following commands:
```
poetry config repositories.example https://pypi.example.com/reponame
poetry config http-basic.example "${USERNAME}" "${PASSWORD}"
```

In order to list package details on the server, Poetry performs a GET request with the `Authorization` header properly set. The server returns a JSON response which includes URLs pointing to additional package details. However, the URLs returned by the server are encoded with the username and password "baked-in" to the URL, as `https://<username>:<password>@pypi.example.com/reponame`. Ironically, this actually results in Poetry not sending any authentication when it attempts to follow the URLs. This results in an authentication failure, an empty sdist file and an extraction error from `TarFile.open`.

As a point of comparison, `pip` is able to handle this situation and successfully install packages from this repository.

### Cause
Poetry does not send authentication when following requests like those shown above because of [line 14 of `poetry/repositories/auth.py`](https://github.com/sdispater/poetry/blob/master/poetry/repositories/auth.py#L14), which checks to make sure that the `netloc` (which includes username, password, hostname and port) matches the repository's `netloc` before authenticating a request.

### Proposed Solutions
- Match based on `hostname` (provided by `urlparse/urllib.parse`) instead of `netloc`
- Strip alternative authentication from JSON API URLs
- Use alternative authentication from JSON API URLs if available before trying to use repository authentication

I would be happy to contribute a pull request if there is interest in any of the above solutions.

Thanks for working on Poetry! 😁

**Comment by paymog** [comment]
My company has this problem too.

**Comment by connorbrinton** [comment]
I went ahead and submitted a pull request that fixes this issue by matching based on `hostname` rather than `netloc`: #751

**Comment by connorbrinton** [comment]
By the way, it looks like this is a regression caused by commit 6c5be4b806271822fe121f1c0a5e5303bc0c1629.
