### ISSUE TITLE
poetry install unneed package

### ISSUE THREAD

**Issue by MisLink** [sdispater/poetry#752]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.1
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/MisLink/ab21e6225ff3fc199db1eaf6af2d3ee7

## Issue

I specify python version as ^3.6, then try to install some packages include celery and flower. While I install flower, an unexpected package `futures` will be installed. It's a package for python 2.7:

```
$ poetry add flower
Using version ^0.9.2 for flower

Updating dependencies
Resolving dependencies... (0.3s)


Package operations: 4 installs, 0 updates, 0 removals

Writing lock file

  - Installing babel (2.6.0)
  - Installing futures (3.1.1)
  - Installing tornado (5.1.1)
  - Installing flower (0.9.2)
```

Update:
I found 3.2.0 is the latest version of futures, this version drop the support of python 3. Poetry chose the latest version that support python3 :P

**Comment by eblume** [comment]
Interesting, I can replicate this with python 3.6. It appears that the relevant line causing `futures` to be included is:

https://github.com/mher/flower/blob/v0.9.2/setup.py#L49

(That is the only mention of `futures` I could find that made any sense as a cause.)

My debug info:
```
 test-py3.6  ~/t/test  poetry debug:info

Poetry
======

 * Version: 0.12.10
 * Python:  3.6.5


Virtualenv
==========

 * Python:         3.6.5
 * Implementation: CPython
 * Path:           /home/erich/.cache/pypoetry/virtualenvs/test-py3.6
 * Valid:          True


System
======

 * Platform: linux
 * OS:       posix
 * Python:   /home/erich/code/personal/pyenv/versions/3.6.5
```

I also tested to see if `import sys; sys.version_info < (3,0)` in 3.6.5 and of course it returns `False`.

I'm not sure why poetry is picking up `futures` as a dep here... I'll try and see if I can dig in to poetry's requirements gathering code to figure it out. (I am not a poetry maintainer/dev, so please don't let this stop anyone else from looking in to it.)

**Comment by eblume** [comment]
I also checked `pip show flower` to see what pypi thinks the requirements are::

```
 ~/t/test  pip show flower                                                                                  (731ms)  
Name: flower
Version: 0.9.2
Summary: Celery Flower
Home-page: https://github.com/mher/flower
Author: Mher Movsisyan
Author-email: mher.movsisyan@gmail.com
License: BSD
Location: /home/erich/code/personal/pyenv/versions/3.7.0/lib/python3.7/site-packages
Requires: celery, tornado, babel, pytz
Required-by: 
```

So, no luck there.

**Comment by sdispater** [comment]
Poetry does not execute the `setup.py` file and as such relies on the `requires.txt` file present in the `tar.gz` file. This file looks like this:

```
celery>=3.1.0
tornado>=4.2.0
babel>=1.0
pytz
futures
```

As you can see there is no condition on the `futures` dependency. This is due to the fact the the `flower` package does not use environment markers as defined in [PEP 508](https://www.python.org/dev/peps/pep-0508/#environment-markers) which is the recommended way of specifying conditional dependencies.

So, this is an issue upstream, and not in Poetry, and should be fixed there by specifying the `futures` dependency like so:

```
futures ; python_version < "3.0"
```

**Comment by eblume** [comment]
Didn't check the .tar.gz - good catch. Thanks!
