### ISSUE TITLE
Wheel Naming Discrepancy Prevents Installing

### ISSUE THREAD

**Issue by seglberg** [sdispater/poetry#756]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux
- **Poetry version**: Poetry 1.0.0a1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  N/A

## Issue

Building wheel packages with Poetry produces different version naming/wheel packages than `bdist_wheel` which is preventing other packages from finding it in our private index.

For example, our library package has a version set to:
```
name = "arroyo-settings"
version = "0+untagged.35.g68290c5"
```
When building it with Poetry it produces a wheel:
```
Building arroyo-settings (0+untagged.35.g68290c5)
 - Building wheel
 - Built arroyo_settings-0_untagged.35.g68290c5-py3-none-any.whl
```
When building with `setup.py bdist_wheel`:
```
arroyo_settings-0+untagged.35.g68290c5-py3-none-any.whl
```

Using the Poetry built wheel, trying to `poetry add arroyo-settings` in our second project, I get the following: https://gist.github.com/seglberg/e5521c49359ec276ac2a81c0b010af3e

**Comment by seglberg** [comment]
Ah the version in the metadata wasn't transformed `0+untagged.35.g68290c5` (with the `+`) - which is probably causing the mismatch.

**Comment by kbakk** [comment]
I see this issue as well when using poetry and devpi server - except the devpi server rejects the upload:

```sh
poetry publish --repository kristofferb_dev

Publishing my-package (0.1.3-dev0+some_branch) to kristofferb_dev
 - Uploading my-package-0.1.3.dev0+some.branch.tar.gz 100%
                                                                                                                                                                                       
[HTTPError]                                                                                                                                                             
400 Client Error: filename 'my-package-0.1.3.dev0_some.branch-py3-none-any.whl' does not contain version '0.1.3.dev0+some.branch' for url: https://<our devpi package index>/kristofferb/dev/ 
```

The issue seems to be the regex here

https://github.com/sdispater/poetry/blob/6fe7f54a83c59131d4e291084c3496a0c513cfaa/poetry/masonry/builders/wheel.py#L201

that replaces `+` with `_` in the wheel filename.
