### ISSUE TITLE
Poetry ignores extras in dev-dependencies

### ISSUE THREAD

**Issue by arxanas** [sdispater/poetry#759]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
  - Yes, Poetry 0.12.10
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
  - I believe this is similar to https://github.com/sdispater/poetry/issues/129 but not related. That one involves installing a package with different extras depending on the mode. This involves installing extras that only exist for dev-dependencies.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
  - No exception occurs.

- **OS**: macOS 10.13.16 build 17G65
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: same as below, see https://gist.github.com/arxanas/b18be992384c105b0163691c63549159

## Issue

**Expected behavior**: having optional packages in `dev-dependencies` allows them to be installed with `poetry install --extras`.
**Actual behavior**: having optional packages in `dev-dependencies` does nothing when trying to invoke `poetry install --extras`.

I want to have extras that are installable as dev-dependencies. In particular, I would like to make it possible install the fuzzing system for my project. However, it depends on Cython, which is heavyweight, and not something I would like to be installed by default when setting up the development environment.

Therefore I created a `pyproject.toml` like this, with the optional dependencies `cython` and `python-afl`, and the `fuzz` extra that would install both:

```
[tool.poetry]
name = "poetrytest"
version = "0.1.0"
description = ""
authors = ["Waleed Khan <me@waleedkhan.name>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
python-afl = {version = "^0.7.1",optional = true}
cython = {version = "^0.29.2",optional = true}

[tool.poetry.extras]
fuzz = ["cython", "python-afl"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

But when I try to install the `fuzz` extra, no packages are installed:

```
$ poetry install --extras fuzz
Installing dependencies from lock file

Nothing to install or update

  - Installing poetrytest (0.1.0)
```

If I move the optional dependencies to `dependencies` instead of `dev-dependencies` like this:

```
[tool.poetry]
name = "poetrytest"
version = "0.1.0"
description = ""
authors = ["Waleed Khan <me@waleedkhan.name>"]

[tool.poetry.dependencies]
python = "^2.7"
python-afl = {version = "^0.7.1",optional = true}
cython = {version = "^0.29.2",optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.extras]
fuzz = ["cython", "python-afl"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Then it works:

```
$ poetry install --extras fuzz
Installing dependencies from lock file


Package operations: 2 installs, 0 updates, 0 removals

  - Installing cython (0.29.2)
  - Installing python-afl (0.7.1)
  - Installing poetrytest (0.1.0)
```

But this is a problem because my actual project does not have these dependencies, even as extras.

**Comment by rmorshea** [comment]
@sdispater should there be an extra section for `[tool.poetry.dev-extras]`?
