### ISSUE TITLE
poetry add unable to find black

### ISSUE THREAD

**Issue by rajeev** [sdispater/poetry#767]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Mojave
- **Poetry version**: Poetry 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rajeev/703bd6b8b96c7b2e375aff8cc8b06079

## Issue
I'm trying to add black as a dev-dep for my project. However, poetry does not "find" black, either as a dev nor as a regular dependency. poetry add also fails with the same result.

I tried `poetry add black` [1], and tried adding it via the pyproject.toml. However, doing a `poetry search black` shows black in the results.

[1]: poetry add -vvvv
Using virtualenv: /Users/kane/Library/Caches/pypoetry/virtualenvs/test-py3.7
PyPI: 0 packages found for black *
                                                      
[ValueError]                           
Could not find a matching version of package black  
                                                      
Exception trace:
 /Users/kane/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/kane/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/kane/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/kane/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/kane/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /Users/kane/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /Users/kane/.poetry/lib/poetry/console/commands/add.py in handle() at line 69
   packages, allow_prereleases=self.option("allow-prereleases")
 /Users/kane/.poetry/lib/poetry/console/commands/init.py in _determine_requirements() at line 230
   requirement["name"], allow_prereleases=allow_prereleases
 /Users/kane/.poetry/lib/poetry/console/commands/init.py in _find_best_version_for_package() at line 266
   "Could not find a matching version of package {}".format(name)

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

**Comment by raymondhoagland** [comment]
At a glance this seems similar to https://github.com/sdispater/poetry/issues/649 -- have you tried changing your pyproject.toml to allow black to be a prerelease?

**Comment by rajeev** [comment]
Apparently, allows-prereleases works! That's weird because I searched many times for this issue, but didn't see the one named "Can not install black". Stupid me!
