### ISSUE TITLE
poetry add celery fails because kombu==4.2.2 exists as kombu==4.2.2.post1

### ISSUE THREAD

**Issue by xsduan** [sdispater/poetry#770]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10 enterprise edition
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

similar to #350.

kombu 4.2.2 only exists as 4.2.2.post1, which poetry parses as 4.2.2, and therefore it fails when it tries to install kombu==4.2.2. I don't know if this is a pip bug or "feature".

explicitly installing kombu==4.2.1 patches over this issue.

```sh
$ poetry add kombu
# ...snip...
[PackageNotFound]
Package kombu (4.2.2) not found.
# ...snip...
$ pip install kombu==
Collecting kombu==
  Could not find a version that satisfies the requirement kombu== (from versions: 0.1.0, 0.2.0, 0.9.0, 0.9.1,
# ...snip...
4.0.0rc3, 4.0.0rc4, 4.0.0rc5, 4.0.0rc6, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.2.0, 4.2.1, 4.2.2.post1)
No matching distribution found for kombu==
```

**Comment by javiersanp** [comment]
Also fails to add black

    $ poetry add black
    [ValueError]                           
    Could not find a matching version of package black

But it does with the exact version:

    $ poetry add black=18.9b0

**Comment by bertjwregeer** [comment]
@javiersanp not the same issue. `poetry add --allow-prerelease black` works just fine. Black does not yet have a none beta/alpha release. Please see https://github.com/sdispater/poetry/issues/767

**Comment by javiersanp** [comment]
Thank you for the info. Didn't know that option.

**Comment by xlanor** [comment]
Getting the same issue on macOS, with poetry 0.12.10

For now, modifying `poetry.lock` to explicitly specify kombu version to 4.2.2.post1 works
