### ISSUE TITLE
Conditional dependency at setup.py

### ISSUE THREAD

**Issue by andriyor** [sdispater/poetry#776]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 18
- **Poetry version**:  0.12.10

## Issue

After installing [python-slugify](https://github.com/un33k/python-slugify) Unidecode dependenci not installed.

**Comment by agronholm** [comment]
The setup.py in python-slugify is retarded, but check if the import there works. If it does, are you left missing something?
