### ISSUE TITLE
How to work on a dependency without overwriting

### ISSUE THREAD

**Issue by rajeev** [sdispater/poetry#778]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
I'm working on a package and I have a git repo specified as a dependency. 

How can I checkout the git repo, install it and keep it editable so that poetry update doesn't clobber all my local commits to that repo?

**Comment by jacebrowning** [comment]
One option is to check out the VCS dependency as a sibling directory to the project then depend on:

```
my_dependency = { path = "../my_dependency" }
```

**Comment by rajeev** [comment]
@jacebrowning The problem is that when I push the toml file, it will include that dep as a path dependency. Whereas I need that as a regular git/pypi dep, but temporarily need to develop it at the same time. Is there some other way that can happen? Maybe I'm doing something wrong in my dev workflow?

How would one do that in general?

**Comment by sdispater** [comment]
@rajeev Poetry does not support this and I am not sure how you would do that with the existing Python tools or even in other languages.

**Comment by rajeev** [comment]
@sdispater Would it possible for e.g., if we provide a --develop option for that?

Say our dep is 

package = {git: ...} 

then poetry would refuse the update the dep, IF "--develop package" is given as argument AND there are local commits?
