### ISSUE TITLE
Poetry-managed virtual environments do not use symlinks on Unix platforms.

### ISSUE THREAD

**Issue by chrahunt** [sdispater/poetry#779]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: latest (master)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

When poetry creates a virtual environment, it does not use symlinks on Unix platforms. Symlinks are the default on Unix platforms when creating a virtual environment with `python -m venv` as seen [here](https://github.com/python/cpython/blob/31ec52a9afedd77e36a3ddc31c4c45664b8ac410/Lib/venv/__init__.py#L368). Using symlinks instead of making a copy of the interpreter has several benefits:

1. Less disk usage (I see 28MB used for python and python3 for a virtual environment for Python 3.7.1)
2. Allows usage of `$ORIGIN` in RPATH/RUNPATH in the `python` executable which is useful for relocatable Python builds
3. Easier automatic loading of `python-gdb.py` for gdb debugging helpers

**Comment by randallpittman** [comment]
I was just wondering about this too, as I'm learning virtualenvs right now. Does poetry use its own version of `virtualenv` instead of using the Python 3.3+ `venv` module?

Workaround is to create the virtualenv with `python -m venv .venv` and then poetry will use that instead of trying to create one.

**Comment by jgirardet** [comment]
https://github.com/sdispater/poetry/blob/3dd09c2c53e39856577ac8b336d08f65791b0421/poetry/utils/env.py#L275
it's just using the standard python way. envbuilder for python3 and virtualenv for python2

**Comment by chrahunt** [comment]
@jgirardet the change would just be to align with normal `python -m venv` behavior. As seen here they select the default `use_symlinks` based on platform:

https://github.com/python/cpython/blob/d8080c01195cc9a19af752bfa04d98824dd9fb15/Lib/venv/__init__.py#L368-L371

And then here they pass the derived option from the command-line (defaulted to `use_symlinks`) to `EnvBuilder`:

https://github.com/python/cpython/blob/d8080c01195cc9a19af752bfa04d98824dd9fb15/Lib/venv/__init__.py#L404-L409

**Comment by jgirardet** [comment]
It makes sense so. i'm +1 on it

**Comment by iospera** [comment]
Doing a copy instead of a symlink breaks on OpenBSD due to the W^X protection, (typically only /usr/local has WXALLOWED enabled). Symlinking would fix this.

**Comment by Imaclean74** [comment]
at least on my linux system - this behaviour is causing venv creation from poetry to fail consistently - see https://github.com/sdispater/poetry/issues/654.  Might want to re-open this one.

**Comment by Imaclean74** [comment]
Created a PR to fix this one. Any review comments appreciated.
