### ISSUE TITLE
Specify SSL Cert for extra index server?

### ISSUE THREAD

**Issue by tdhopper** [sdispater/poetry#790]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
I am trying to use a private simple index that requires a custom SSL cert. With pip, I can use the `--cert` flag to point to the certificate. Is there an equivalent way to specify a cert in Poetry?

**Comment by tdhopper** [comment]
Looks like the solution is the same as in https://github.com/sdispater/poetry/issues/745#issuecomment-448203289; I needed REQUESTS_CA_BUNDLE to point to my certificate.

**Comment by jobec** [comment]
I'm not conviced a user should set an environment variable for an underlying package.

this should be a setting, just like [pip allows you to set it](https://pip.pypa.io/en/stable/reference/pip/?highlight=proxy#cmdoption-cert).  Both on the command line as well as globally/on a project level.
