### ISSUE TITLE
Maximum recursion depth exceeded on green install

### ISSUE THREAD

**Issue by ylectric** [sdispater/poetry#795]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS 10.14.2
- **Poetry version**:  0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [`pyproject.toml`](https://gist.github.com/ylectric/0251a0601894ae60a9b305f994df7c13)
## Issue
First of all, thank you @sdispater for working on this tool, it's amazing 👍

I found out that Poetry 0.12.10 is unable to correctly resolve the version for [`green`](https://github.com/CleanCut/green) package.
Below is a suspicious snippet from debug output of `poetry install`:
```
      1: fact: issue-795 is 0.1.0
      1: derived: issue-795
      1: fact: issue-795 depends on green (*)
      1: selecting issue-795 (0.1.0)
      1: derived: green (*)
-->   0: Duplicate dependencies for colorama
-->   0: Different requirements found for colorama (*) and colorama (>=0.2.5).
```

Could you take a look?

**Comment by ylectric** [comment]
I can confirm that Poetry 1.0.0a2 is also affected.

**Comment by AndreGuerra123** [comment]
Any updates on this?

**Comment by GjjvdBurg** [comment]
This may be an issue with the green package, because it lists ``colorama`` under ``install_requires`` in the setup command and ``colorama>=0.2.5`` under ``extras_require``. Is poetry capable of differentiating between these two?

**Comment by CleanCut** [comment]
I removed `colorama` from green's `extras_require` and release Green 2.14.1.  Everything seems to work now.  Thanks for identifying the issue, @GjjvdBurg!

**Comment by GjjvdBurg** [comment]
That's great, thanks for the quick fix!

**Comment by ylectric** [comment]
@CleanCut Thank you for fixing this!

**Comment by CleanCut** [comment]
No problem 👍
