### ISSUE TITLE
Are features and extras the same things ?

### ISSUE THREAD

**Issue by nicolas-leydet** [sdispater/poetry#8]
You mention features at to places:

> You can also specify the features you want installed by passing the --f|--features option (See Features for more info)
>
>```
>poetry install --features "mysql pgsql"
>poetry install -f mysql -f pgsql
>```

and 

>When installing packages, you can specify features by using the -E|--extras option:
>
>```
>poet install --extras "mysql pgsql"
>poet install -E mysql -E pgsql
>```

Also the `Features` (See Features for more info) link leads nowhere.

**Comment by sdispater** [comment]
Yes, they are the same thing.

I just updated the README to remove mentions of features since they no longer exist under this name.
