### ISSUE TITLE
special characters in password is not quoted

### ISSUE THREAD

**Issue by dynofu** [sdispater/poetry#803]
- [x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **macOS 10.14.2 **: 
- **Poetry 0.12.8**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

so basically it's like poetry is forming a url like http://username:password@myprivatepypi.com/simple
but if the password has special characters, it fails. the username and password should be urlencoded. 

```
import urllib.parse
password = 'wh@t:ever$'
quoted_password = urllib.parse.quote(password))
url = f"http://username:{quoted_password}@myprivatepypi.com/simple"
```

workaround is set the url directly to the one with username and password.
```
poetry config repositories.whatever http://username:{quoted_password}@myprivatepypi.com/simple
# poetry config repositories.whatever http://username:wh%40t%3Aever%24@myprivatepypi.com/simple
```

**Comment by stephsamson** [comment]
#1341 fixes this issue.
