### ISSUE TITLE
'pip extra' compatibility to install packages

### ISSUE THREAD

**Issue by aeroaks** [sdispater/poetry#806]
- [x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: Poetry 0.12.11

## Issue
I am trying to install connexion with extra dependency, which can be done using pip as follows:
    `pip install connexion[swagger-ui]`.

I tried to do the same with poetry but does not work. `poetry add  connexion[swagger-ui]` gets this

```
λ poetry add --dry-run connexion[swagger-ui]

[PackageNotFound]
Package [connexion[swagger-ui]] not found.
```
I looked into the details and it is using the `pip extra` feature to install `swagger_ui_bundle`. I have installed the required packages using `poetry add`. 

Is there a plan to support this feature?

**Comment by ulope** [comment]
It's already supported with the somewhat unusual `-E`/ `--extras` option.
#429 is a feature request to allow the square bracket syntax.
