### ISSUE TITLE
Support "Issue Tracker" url

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#808]
PYPI supports "Issue Tracker" url as follows:

```py
# setup.py
    url="https://github.com/HDE/aapns",
    project_urls={
        "Documentation": "https://aapns.readthedocs.io/en/latest/",
        "Code": "https://github.com/HDE/aapns",
        "Issue tracker": "https://github.com/HDE/aapns/issues",
    },
```

When looks like this on PYPI:
![screenshot 2019-01-18 at 16 20 44](https://user-images.githubusercontent.com/662249/51371261-073e7700-1b3d-11e9-8205-5c874a052cb2.png)

Poetry hoists `documentation` and `repository` to the top level, but not issue tracker.
If there's a canonical list of links that PYPI understands (shows icon), perhaps poetry should support all.

**Comment by chrahunt** [comment]
This would be covered by #466 in a general way.

Apart from those listed there are a lot of URLs and url names recognized by PyPI, see [here](https://github.com/pypa/warehouse/blob/5cd92a3ecff5db2d04ba4c951830deceb34ed235/warehouse/templates/packaging/detail.html#L16).

**Comment by chrahunt** [comment]
This is possible with #1137.
