### ISSUE TITLE
[Question] Why [tool.poetry] in pyproject.toml?

### ISSUE THREAD

**Issue by batisteo** [sdispater/poetry#81]
In Cargo.toml you have a `[package]` section and `[depencencies]` section by default.

Here we have `[tool.poetry]` and `[tool.poetry.dependencies]`.

Why do we have to have more verbose sections? I like when it’s straightforward.
How does it relate to the [PEP 518](https://www.python.org/dev/peps/pep-0518/)?

**Comment by sdispater** [comment]
This the specification of PEP 518 (see last paragraph of the Specification section: https://www.python.org/dev/peps/pep-0518/#id24)

**Comment by batisteo** [comment]
If I understand correctly, this verbosity will disappear as the PEP and other tools stabilize.

**Comment by cjw296** [comment]
@batisteo - no, it'll always be there as it keeps different build tools from treading on each other's config.
