### ISSUE TITLE
No module named 'pkg_resources' in json_schema - new osx install

### ISSUE THREAD

**Issue by awbacker** [sdispater/poetry#822]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.14.2
- **Poetry version**: 0.12.11
- `pyproject.toml` created by `init`, no packages added

## Issue

1. OS-X with macports & py2.7/3.6/3.7 installed (plus the various pips)
1. Installed poetry as recommended (using /opt/local/bin/python3.6 as the interpreter)
1. Added poetry to path
1. Nearly all commands crash the same way

```
$ poetry version -vvv
$ poetry debug:info -vvv
$ poetry add requests -vvv

All generate the same output:
------

[ModuleNotFoundError]
No module named 'pkg_resources'

Exception trace:
 /Users/andrew/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/andrew/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/andrew/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/andrew/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/andrew/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /Users/andrew/.poetry/lib/poetry/console/commands/env_command.py in initialize() at line 18
   current_env = Env.get(self.poetry.file.parent)
 /Users/andrew/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /Users/andrew/.poetry/lib/poetry/console/application.py in poetry() at line 55
   from poetry.poetry import Poetry
 /Users/andrew/.poetry/lib/poetry/poetry.py in <module>() at line 11
   from .json import validate_object
 /Users/andrew/.poetry/lib/poetry/json/__init__.py in <module>() at line 4
   import jsonschema
 /Users/andrew/.poetry/lib/poetry/_vendor/py3.6/jsonschema/__init__.py in <module>() at line 32
   from pkg_resources import get_distribution

debug:info
```

**Comment by awbacker** [comment]
Can anyone help with this?  I'd really like to not use Pipenv, but its kinda hard now with the way its working (and the fact that googling this helps not at all). 

I've tried reinstalling using my local interpreters 

* py3.7
* py3.6
* py2.7.15

All show the same *exact* same stacktrace.

**Comment by wzwcn** [comment]
try `pip install setuptools`
[https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources](url)

**Comment by awbacker** [comment]
Installed pip & setuptools on my p3.7 intereperter, and it works now.  

*Is this an issue with the way poetry is installed?  Or is it by design?*

It *does* rely on my local python and local system packages, which is 👎 It's clearly not installing all its dependencies in `_vendor/` and _does_ depend on the base system for a core component (setuptools!).

get-poetry.py:
> This ensure that poetry will look for its dependencies inside the _vendor directory without tampering with the base system.  

Consider my system tampered 🤣 

I had no pip installed for py3.6 and py3.7 because I _shouldnt need them_.  I _dont_ need them to do my daily work with virtualenvs (py3.x), and having them makes my setup even more confusing.  `py3 -m venv venv` and I have a working virtualenv with setuptools and pip.  No need for a system wide pip and potential issues.

**Comment by rmorshea** [comment]
I'm pretty sure `pipenv` also requires you to have `pip` installed, so I don't think using `pipenv` will solve this issue for you: https://pipenv.readthedocs.io/en/latest/install/#make-sure-you-ve-got-python-pip

**Comment by rgacote** [comment]
Another reason the pkg_resource error occurs is when you're running the wrong Python. 
I had Python 3.7.3 altinstalled and an alias of `python=/path.../bin/python3.7.3`.
However `/usr/bin/env` still found the system Python 2.7.

This became obvious when doing the poetry version -vvv command above and seeing poetry was in `_vendor/py2.7/` and not `_vendor/py3.7/`.

Ended up installing pyenv and activating 3.7.3 for the project.
