### ISSUE TITLE
Poetry should always include LICENSE/COPYING files in sdist tarballs if they exist when generating them

### ISSUE THREAD

**Issue by Conan-Kudo** [sdispater/poetry#836]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When poetry generates source distribution tarballs, it doesn't seem to include any licensing files in automatically. It should automatically include any LICENSE/COPYING files so that license compliance for Python code is possible, especially for redistribution.

This is important with Apache and GNU licenses because they require the terms to be shipped with the sources. It is important for BSD and MIT licenses, because those licenses require copyright statements of the authors and contributors to be present in the license file itself, so they are unique for each project.

**Comment by Conan-Kudo** [comment]
Ah, I guess I had assumed otherwise because of the `COPYING` file missing in a project I attempted to create an sdist on. 😳

**Comment by sdispater** [comment]
Well, to be fair, the `COPYING` file is not included automatically
