### ISSUE TITLE
Avoid unintentionally changing version when building and publishing

### ISSUE THREAD

**Issue by boyeah** [sdispater/poetry#843]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Context: I want to build and publish as part of CI/CD, with automated checks for consistent versioning across pyproject.toml, version tag in .py file, Git tag and package name.

Poetry silently modifies the project version when building with `poetry build` or `poetry publish --build ...`. This increases the risk of publishing a package where the version in code is different from the version tag on the package.

For instance, assume a project with the following files (note that this is a valid SemVer version tag):
- pyproject.toml, containing `version = "1.1.1-pre1"`
- Possibly src/__init__.py, containing `VERSION = "1.1.1-pre1"` or similar

The package subsequently built (and published to the repository if running `poetry publish --build`) will then be named `packagename-1.1.1rc1`, and contain:
- setup.py containing `'version': '1.1.1rc1'`
- pyproject.toml as possibly other files still containing `version = "1.1.1-pre1"`

I have currently found two workarounds:
- Run build and publish in separate steps, and check that the build package version is the same as the one in pyproject.toml.
- Call `normalize_version` from `poetry.utils.helpers` and inspect the output prior to build/publish.

Although this is most likely to occur for pre-release version tags, it would be nice to have a way to ensure consistent versioning and/or avoid that Poetry renames the version. Some possibilities may include:
1. Explicitly document this feature (I have searched for it in the documentation without luck, I apologize if it is there but I have overlooked it).
2. Add a command that outputs the "normalized version tag" that Poetry would end up using.
3. Add the "normalized version tag" to the output produced by `poetry check`.
4. Add a "don't normalize names" option to build/publish commands.

The version renaming is done through the function [normalize_version](https://github.com/sdispater/poetry/blob/3dd09c2c53e39856577ac8b336d08f65791b0421/poetry/utils/helpers.py#L26), which is included in the [package metadata](https://github.com/sdispater/poetry/blob/3dd09c2c53e39856577ac8b336d08f65791b0421/poetry/masonry/metadata.py#L46) used by the [builders](https://github.com/sdispater/poetry/blob/3dd09c2c53e39856577ac8b336d08f65791b0421/poetry/masonry/builders/sdist.py#L65), and called from the [uploader](https://github.com/sdispater/poetry/blob/3dd09c2c53e39856577ac8b336d08f65791b0421/poetry/masonry/publishing/uploader.py#L51).

**Comment by achow101** [comment]
I have also run into this issue. This seems like something that would cause user confusion if Git tags use one form, but the version uploaded to PyPi has the version in a different form.
