### ISSUE TITLE
I am not sure how to install discord.py rewrite with voice

### ISSUE THREAD

**Issue by eisque** [sdispater/poetry#854]
Hey there,
I want to install a dependency namely discord.py rewrite branch.
```
python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
```
what will be the equivalent for poetry?

**Comment by jacebrowning** [comment]
This is documented here: https://poetry.eustace.io/docs/versions/#git-dependencies

**Comment by bryanforbes** [comment]
You'll add this to `tool.poetry.dependencies`:

```
"discord.py" = {branch = "rewrite", git = "https://github.com/Rapptz/discord.py.git", extras = ["voice"]}
```

And then run `poetry update`

**Comment by eisque** [comment]
Thanks. Closing the issue

**Comment by monaSalih** [comment]
i try to install discord using ``` poetry add discord ``` but didnt work show this error msg 
```
static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```
