### ISSUE TITLE
How do I run a script in the root directory using poetry?

### ISSUE THREAD

**Issue by eisque** [sdispater/poetry#855]
So I have a start.py which I want to run using poetry but it's in the root directory. How can I run it?

**Comment by eisque** [comment]
'Key "callable" does not exist.' 
I get this error when I do 
```
'Key "callable" does not exist.'
```

**Comment by pawamoy** [comment]
> How can I run it?

By root I assume you refer to the root of the repository.

```
poetry run python start.py
```

If you meant to run this from deeper in the repository:

```
poetry run python $(git rev-parse --show-toplevel)/start.py
```

For your KeyError, it must be a bug in your `start.py` script.
