### ISSUE TITLE
Installing chatterbot from git is not working

### ISSUE THREAD

**Issue by eisque** [sdispater/poetry#857]
Hello there,
When I try to install chatterbot using git. It returns
```
[RuntimeError]                                                      
Unable to retrieve the package version for /tmp/pypoetry-git-chatterbot01m7cm75  
 ```
Any work around this?

**Comment by pawamoy** [comment]
Why are you closing your issues? Did you resolve them? If yes, could you share the solution in case others experience the same problems?

**Comment by eisque** [comment]
It was a dependency error. Other package that needed to be installed used pyyaml <= 4 and my project was using > 4 so I installed that project from the git repo and then reinstalled chatterbot.
