### ISSUE TITLE
can't publish depedency with wildcard "*"

### ISSUE THREAD

**Issue by jgirardet** [sdispater/poetry#86]
Poetry version 0.9.0.a2

[tool.poetry.dependencies]
pony = "*"

```
poetry publish 
400 Client Error: Invalid value for requires_dist. Error: Invalid requirement: 'p  
ony (*)'. for url: https://upload.pypi.org/legacy/ 
```
Content  build file :

METADATA :
Requires-Dist: pony (*)

PKG-INFO : 
Requires-Dist: pony (*)

setup.py :
install_requires = \\
['pony*']

**Comment by jgirardet** [comment]
same thing with : 
pony = {git = "https://github.com/ponyorm/pony.git", branch = "orm-migrations"}

**Comment by sdispater** [comment]
You can't publish a package with git dependencies.

However, regarding wildcard dependencies, this is a bug in `poetry`, since it's supposed to work.

**Comment by jgirardet** [comment]
> You can't publish a package with git dependencies.

we can't because we you don't want it to be possible with poetry  or for another reason ?

If  git dependency is transformed to  `Requires-Dist: gitpackage` all will be fine.

**Comment by sdispater** [comment]
@jgirardet I will look into it more and get back to you.
