### ISSUE TITLE
poetry add / update / install only prompts for git user details in debug mode (-vvv)

### ISSUE THREAD

**Issue by ptink** [sdispater/poetry#863]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**:0.12.10

## Issue

I was attempting to add a lib from a private repo with `poetry add myrepo --git https://myprivate.com/myrepo.git` but the "Resolving dependencies" counter was looping without prompting for details.

It wasn't until I added the -vvv flag that I was prompted to enter my git username/password.

**Comment by loganlinn** [comment]
believe this is the same as #446
