### ISSUE TITLE
Source Folder for Building

### ISSUE THREAD

**Issue by scottyHH** [sdispater/poetry#865]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I am trying to get my head around the build process of Poetry. The documentation claims that no setup.py, Manifest, etc. is needed in order to build everything. My source folder is named differently that the project and therefore the build won't start. Where can I specify the source folder location?

**Comment by sdispater** [comment]
If I understand you well, I think this is what you want: https://poetry.eustace.io/docs/pyproject/#packages

**Comment by scottyHH** [comment]
I've read the whole documentation but apparently skipped this part about the pyproject.toml.
Sorry for bothering about this...

Nevertheless thanks a lot for your quick help.
