### ISSUE TITLE
Support conditional dependencies

### ISSUE THREAD

**Issue by nbraud** [sdispater/poetry#868]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
  #776 exists, but is about the reverse (poetry ignoring conditional dependencies in a non-poetry project's `setup.py`)
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Would it be possible to support conditional dependencies, like `dataclasses; python_version < '3.7'`?
They are extremely helpful when using libraries that later became part of the stdlib.

The documentation for [`poetry add`] doesn't mention anything about this, so I assume it's not possible.

[`poetry add`]: https://poetry.eustace.io/docs/cli/#add

**Comment by jacebrowning** [comment]
It's already possible to restrict dependencies to specific versions of Python: https://poetry.eustace.io/docs/versions/#python-restricted-dependencies

**Comment by holdenweb** [comment]
It's unhelpful that the link in the above closing comment now 404s. I'm just leaving this here as an update for others also seeking this information, which is now [officially documented](https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies).
