### ISSUE TITLE
`poetry run pytest tests` cannot import current project if tests/__init__.py does not exist

### ISSUE THREAD

**Issue by mtkennerly** [sdispater/poetry#87]
Ran into this with Poetry 0.8.6. To reproduce this, you can delete `tests/__init__.py` in the Poetry project itself, then run `poetry run pytest tests`. On commit 4829967a37fc74b3b7715986867fbd2ade29b514, I get 25 failures on `ModuleNotFoundError: No module named 'poetry'`. Pytest doesn't normally require `__init__.py` files, so this is surprising.

**Comment by mtkennerly** [comment]
@moigagoo, unless I'm missing something, that page explains how Pytest works both with `test/__init__.py` ("Test modules / conftest.py files inside packages") and without it ("Standalone test modules / conftest.py files"):

> pytest will find `foo/bar/tests/test_foo.py` and realize it is NOT part of a package given that there’s no `__init__.py` file in the same folder. It will then add `root/foo/bar/tests` to `sys.path` in order to import `test_foo.py` as the module `test_foo`. The same is done with the `conftest.py` file by adding `root/foo` to `sys.path` to import it as `conftest`.

Maybe the sys.path manipulation doesn't play nicely with Poetry? For a concrete before/after example, I have [a project](https://github.com/mtkennerly/tkup) without any `tests/__init__.py` not currently using Poetry, and the tests work:

```
$ virtualenv .venv
$ . ./.venv/Scripts/activate
$ pip install -r requirements.txt
$ pip install -e .
$ pytest tests
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
rootdir: C:\GitHub\mtkennerly\tkup, inifile:
plugins: cov-2.5.1
collected 30 items

tests\test_gui.py ..............................                         [100%]

========================== 30 passed in 1.60 seconds ==========================
```

But on this branch [incorporating Poetry](https://github.com/mtkennerly/tkup/commit/5adc3610a3bff839ec08f899074ea2ee3c62f4de), the test startup fails:

```
$ git checkout feature/poetry
$ poetry run pytest tests
80
77
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: C:\GitHub\mtkennerly\tkup, inifile:
plugins: cov-2.5.1
collected 0 items / 1 errors

=================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_gui.py ______________________
ImportError while importing test module 'C:\GitHub\mtkennerly\tkup\tests\test_gui.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_gui.py:6: in <module>
    from tkup import GUI
E   ModuleNotFoundError: No module named 'tkup'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.16 seconds ===========================
```

If I create a `tests/__init__.py`, then the Poetry version works:

```
$ touch tests/__init__.py
$ poetry run pytest tests
80
77
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: C:\GitHub\mtkennerly\tkup, inifile:
plugins: cov-2.5.1
collected 30 items

tests\test_gui.py ..............................                         [100%]

========================== 30 passed in 1.35 seconds ==========================
```

**Comment by mtkennerly** [comment]
This works correctly in the latest version of Poetry (0.12.4). Looks like the fix came from 0.12.0 installing the current project in editable mode when you run `poetry install`, so now Pytest can find the current project without needing the project folder manually added to `PYTHONPATH`.

**Comment by FabricioPatrocinio** [comment]
Para quem se deparar com o problema, você deve usar o nome do diretorio raiz antes de chamar seus proprios modulos. Por exemplo, **from app_delivery.app.models import SeuModelo** ou inves de from **app.models import SeuModelo**.

**Comment by Jaakkonen** [comment]
It looks like you need to do `poetry add --dev pytest` for it to work with `poetry run pytest tests/`. Otherwise it will not be adding your project folder to the PYTHONPATH
