### ISSUE TITLE
poetry check says CC0 is not a valid license

### ISSUE THREAD

**Issue by mbello** [sdispater/poetry#871]
- [ x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
CC0 is a valid license and becomig increasingly common.

However, poetry check complains that it is not a valid one.

Autopilot (as an example), does include CC0 as a valid license.

[https://autopilot-docs.readthedocs.io/en/latest/license_list.html](https://autopilot-docs.readthedocs.io/en/latest/license_list.html)

**Comment by sdispater** [comment]
The proper license identifier is `CC0-1.0` as you can see here: https://github.com/sdispater/poetry/blob/master/poetry/spdx/data/licenses.json#L442

**Comment by mbello** [comment]
Oh, sorry and thanks for correcting me.
