### ISSUE TITLE
Discussion around PEP 582 (local __pypackages__)

### ISSUE THREAD

**Issue by ptink** [sdispater/poetry#872]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I'm a little hesitant to bring it up because the PEP (https://www.python.org/dev/peps/pep-0582/) hasn't actually been accepted yet. But it seems to have strong traction and support in most places that I've seen it discussed. 

As a **TLDR**: The PEP proposes that python automatically recognise and import packages from a local `__pypackages__` directory over user or global site-packages. The idea being that this gets rid of  the need for virtualenvs for python environment isolation as these are an annoying and complicated road block for new users (and, frankly, all users. Hence why poetry abstracts large parts of them away!).

To my mind, the PEP looks broadly promising. I have some reservations about it falling back to a system python. I worry about the ease of accidentally installing a bunch of packages globally when you meant to install them locally and how this will effect e.g. `pipx-app` that makes isolating python command line tools much easier.

However, assuming the PEP goes through it might be worth considering poetry's role (if any) in implementing this. I am unsure whether their intention is to replace the virtualenv entirely or simply serve as a lower bar to entry for new users but it's worth keeping on the radar in terms of adoption.

**Comment by danieleades** [comment]
seems to me maybe this one should be reopened. It's continuing to gain traction.

the best way for Poetry to stop people flooding to [Pyflow](https://github.com/David-OConnor/pyflow) or [PDM](https://pdm.fming.dev/) would be to abstract over the package storage, and support both the virtualenv and `__pypackages__` as strategies
