### ISSUE TITLE
poetry command not identified by powershell

### ISSUE THREAD

**Issue by hemanta212** [sdispater/poetry#874]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

**Comment by hemanta212** [comment]
I am running poetry 0.12.11 windows 10. Poetry command runs fine in command prompt but in powershell it just pops up a window saying by which program would you like to open poetry and opens a blank file.

**Comment by hemanta212** [comment]
![screenshot 63](https://user-images.githubusercontent.com/25475894/52520758-5471bc80-2c95-11e9-905d-03425b5df163.png)

**Comment by hemanta212** [comment]
I needed this functionality for vscode as I run powershell as my default terminal there. Sorry if poetry was not intended to run there.

**Comment by zmitchell** [comment]
I wonder if that’s Windows saying “I don’t know what kind of file this is”. Can you verify that the same `poetry.exe` is being executed (or attempting to be executed) in both CMD and PowerShell?

**Comment by hemanta212** [comment]
For some reason there was an empty file of unknown ext named poetry created in C:\Windows\ which powershell was refering to after I deleted it everything was normal. It may have been created as I downloaded poetry using cmd as an admin while being cd(ed) in that folder. Anyway my issue has been resolved. Thank you very much :) 👍
