### ISSUE TITLE
Cannot use the .venv python exec in an alpine image

### ISSUE THREAD

**Issue by sneko** [sdispater/poetry#885]
Hi,

I'm using Poetry 0.12 through my CI/CD pipeline with the docker image `python:3.7`. And after having installed all dependencies and make all my tests I would like to have the tiniest image possible.

So I try to copy my source code and the `pyproject.toml + .venv`inside a `python:3.7-alpine`but when running poetry it says that the `.venv/bin/python`doesn't exist. And it does!

After looking for some time, I figured out that by using the normal `python:3.7`it works well. I guess some files have been compiled for the global image and cannot be read/exec in the alpine image due to different system librairies...

Does anyone have succeed to make it working? It would be great to make my deployed image losing some weight 😄 

Thank you!

**Comment by bertjwregeer** [comment]
The alpine image uses Python compiled against a different standard C library, and as such the two are not compatible. You will want to either use alpine from the get-go, or use the `python:3.7` image.

Other options are to copy the built wheel from one image to another and re-install that inside a new `.venv` inside the Alpine image.

**Comment by sneko** [comment]
Thank you for the information @bertjwregeer . I will dig into it 😃
