### ISSUE TITLE
poetry add --dev not installing as dev dependency for git dependencies

### ISSUE THREAD

**Issue by GiancarloFusiello** [sdispater/poetry#886]
Hi @sdispater, `poetry` is a great tool that has been missing from the Python community for a long time. I wanted to point out this small bug that I hope should be an easy fix.

```bash
poetry add libero-schemas --git https://github.com/libero/schemas.git --dev
```
Installs the dependency and adds it to `pyproject.toml`:
```toml
[tool.poetry.dependencies]
lxml = "^4.3"

[tool.poetry.dev-dependencies]
libero-schemas = {git = "https://github.com/libero/schemas.git"}
```
However, in `poetry.lock` it appears to have installed as a `main` dependency rather than a `dev` dependency:
```toml
[[package]]
category = "main"
description = "Libero data model schemas"
name = "libero-schemas"
optional = false
python-versions = "*"
version = "0.0.1"

[package.source]
reference = "cebfb5fb66b3bd7b820e2cebf50f9cc471d5204c"
type = "git"
url = "https://github.com/libero/schemas.git"
[[package]]
category = "main"
description = "Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API."
name = "lxml"
optional = false
python-versions = "*"
version = "4.3.0"
```
Also notice that a blank line is missing after `[package.source]` in `poetry.lock`.

Thanks, in advance and keep up the good work.

**Comment by jimbo1qaz** [comment]
I've noticed the same issue, with no response from the developers...
