### ISSUE TITLE
Add a way to disable all caching

### ISSUE THREAD

**Issue by K900** [sdispater/poetry#887]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
We build Docker images for applications using Poetry, and want to minimize the size of the images when they are deployed to production. For that reason, it would be nice to have a Poetry-native option to disable any sort of persistent cache, be it from Poetry itself or from pip. Right now we can work around it by manually removing `~/.cache` after installing dependencies, but having Poetry support this use case would make things more convenient and remove a non-obvious cleanup step.

**Comment by tyomo4ka** [comment]
@K900 

I have this in my Dockerfile.

```
ENV POETRY_CACHE_DIR='/dev/null'
```

It seems to do what you need.

**Comment by aisk** [comment]
> `ENV POETRY_CACHE_DIR='/dev/null'`

This caused error on my machine:

```sh
❯ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing mypy (0.790): Failed

  NotADirectoryError

  [Errno 20] Not a directory: '/dev/null/artifacts/27/70/0f/dedc216f4bb804889f12f78af571efe8280e5035b50e106e0d65409504'

  at ~/.homebrew/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py:1312 in mkdir
      1308│
      1309│         Create a new directory at this given path.
      1310│         """
      1311│         try:
    → 1312│             self._accessor.mkdir(self, mode)
      1313│         except FileNotFoundError:
      1314│             if not parents or self.parent == self:
      1315│                 raise
      1316│             self.parent.mkdir(parents=True, exist_ok=True)
```

Looks like poetry try to mkdir on `/dev/null` and caused error. But set POETRY_CACHE_DIR to some other validated directories like `/tmp` work for me.

**Comment by tyomo4ka** [comment]
@aisk 

Right, I run into this as well in one of the projects. I haven't investigated yet what exactly is happening here.

Obviously, the problem is that some code is trying to make a directory in `/dev/null`, but I'm not sure why and how to avoid it.

On the rest of the projects I use it – it works just fine.

If you want to dig it deeper. Try to increase the verbosity of the poetry output. Run the same command with `-vvv` flag. Maybe it will give you a hint.

**Comment by pawelrubin** [comment]
Seems like this could be reopened
