### ISSUE TITLE
Exclude package from lockfile

### ISSUE THREAD

**Issue by vilunov** [sdispater/poetry#891]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
Hello, I'd like to propose a configuration option for excluding a certain package from the generated lockfile in order to keep it updated to latest compatible version. 

The particular use case I encountered is with the `pytz` package. I want to keep it updated to maintain the latest state of world's timezones for each build.

**Comment by jacebrowning** [comment]
Could you simply depend on `pytz = "*"` and run `$ poetry update pytz` during your builds?

**Comment by vilunov** [comment]
I could, thank you, but wouldn't it be clearer if there was an attribute for that in pyproject.toml?

**Comment by sdispater** [comment]
The main purpose of a tool like Poetry is to create a reproducible set of packages. Adding such an option would defeat the purpose. So it's highly unlikely that such an option will ever make it into Poetry.

The suggestion made @jacebrowning is the proper way to go.
