### ISSUE TITLE
Feature Request: track critical path, and provide per-dependency time cost in 'poetry update'

### ISSUE THREAD

**Issue by anadon** [sdispater/poetry#893]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Often, `poetry update` takes a long time to complete.  I'm at over 3 minutes locally.  It would be nice to see the critical path for update resolution, as well as the time it takes for each dependency to resolve.  Then a user could focus on the highest cost dependencies to save time.

**Comment by pmav99** [comment]
This time is probably spent downloading dependencies. Not sure if you or poetry can do much about it.

**Comment by anadon** [comment]
I can guarantee the time is not spent downloading any dependency packages.  And even if it were, these would be useful metrics.  This is happening right after a prior update with no package changes.

**Comment by sdispater** [comment]
If you execute the  `update` command in debug mode (`-vvv') you can see what Poetry is actually doing.
