### ISSUE TITLE
List all commands with --help flag

### ISSUE THREAD

**Issue by chdsbd** [sdispater/poetry#894]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I think it would be helpful to provide a list of valid commands with `poetry --help`, like `poetry list` does. I think this would require merging the functionality of list into the `poetry --help` command.

**Comment by sdispater** [comment]
This is already the case for the `1.0.0` prereleases. Basically the `list` command is gone and `poetry --help` displays the available commands.
