### ISSUE TITLE
Managing virtualenv

### ISSUE THREAD

**Issue by bersace** [sdispater/poetry#9]
Hi,

Something nice in npm or pipenv is the management of isolation. For now, `poetry` is global by default (not event scoped to user installation) unless a virtualenv is already created and activated.

Do you have some plan on managing isolation with poetry ?

Regards,
Étienne

**Comment by sdispater** [comment]
Yes, that's something I have in mind.

The thing is, I want to focus on dependency management and packaging/publishing before adding an extra feature as big as virtualenv management.

But that's definitely something I want to integrate to poetry.

**Comment by sdispater** [comment]
This is now supported. Poetry always works inside a virtualenv now (by creating one if needed).
