### ISSUE TITLE
Question: Ability to show what library requires library in question?  

### ISSUE THREAD

**Issue by matthewfeickert** [sdispater/poetry#900]
## Issue Checklist

- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
   - My query in Issues: `is:issue show`
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.
   - This doesn't seem to be discussed under [Commands](https://poetry.eustace.io/docs/cli/) or [FAQ](https://poetry.eustace.io/docs/faq/)

## Question

Poetry has the very nice [`show`](https://poetry.eustace.io/docs/cli/#show) command which allows for seeing the dependencies of an installed library in the environment

```
$ poetry show jupyter-nbextensions-configurator
name        : jupyter-nbextensions-configurator                                           
version     : 0.4.1                                                                       
description : jupyter serverextension providing configuration interfaces for nbextensions.

dependencies
 - jupyter_contrib_core >=0.3.3
 - jupyter_core *
 - notebook >=4.0
 - pyyaml *
 - tornado *
 - traitlets *
```

However, is there a way to get Poetry to give information going in the "opposite direction" and show what libraries in the environment required the library in the query? For example, asking `show` about `pyyaml` gives

```
$ poetry show pyyaml
name        : pyyaml                            
version     : 3.13                              
description : YAML parser and emitter for Python
```

but is it possible from asking about information **from** `pyyaml` that `jupyter-nbextensions-configurator` requires it?

The purpose of this question would be to give the ability to answer the question of "what library in my environment could have installed this other library?"

For a small environment this can easily be achieved visually by

```
poetry show --tree
```

but if you have an environment with multiple libraries with many dependencies this becomes hard to do quickly. The not smart and super hacky way that I have tried is things along the lines of

```
poetry show --tree | grep -B 100 pyyaml
```

Also, apologies if I am using the wrong search terms and this is indeed clearly documented already.

**Comment by pmav99** [comment]
You can try `pipdeptree --reverse`: https://github.com/naiquevin/pipdeptree
