### ISSUE TITLE
poetry run: unclear precedence of global vs script arguments

### ISSUE THREAD

**Issue by sgelb** [sdispater/poetry#915]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Arch Linux**
- **Poetry version 1.0.0a2**

## Issue

When running `poetry run <script> <script args>`, at least the global argument `-h` takes precidence over the script arguments. I have a project using argparse with valid arguments `-h` and `--help`. Neither of these arguments work with `poetry run ./example.py <argument>`. What does work is using `--h` (notice the double dash instead of a single one). The same problem occurs when the entry point is set in `[tool.poetry.scripts]`.

Minimal code example `test.py` that just outputs argv
```test.py
#!/usr/bin/env python
import sys
print(sys.argv)
```

Output of `poetry run ./test.py -v` is as expected: `['./test.py', '-v']`
Output of `poetry run ./test.py -V` is as expected: `['./test.py', '-V']`
But  `poetry run ./test.py -h` outputs the same as running `poetry run -h`.

**Comment by pauleikis** [comment]
I have the same issue, might dig in to create a PR to fix this
