### ISSUE TITLE
Poetry build can't find source files

### ISSUE THREAD

**Issue by berislavlopac** [sdispater/poetry#92]
I'm trying to `poetry build` a [Python project](https://github.com/berislavlopac/fig), but it fails with the message:

```
  [ValueError]                          
  No file/folder found for package fig
```

`poetry install` and `poetry update` work fine, and I can build using the standard `setup.py bdist_wheel`. I have trying adding the following to my `pyproject.toml` but no luck:

```
[package]
include = ["src/*.py"]
```

Any pointers as to what I'm doing wrong would be highly appreciated.

**Comment by berislavlopac** [comment]
Ah, I see, the package directory actually needs to have the same name as the project. Is there a way to specify a different name? Like it can be speciefied in `setup.py`, as:

```
package_dir={'': 'src'}

**Comment by monkeez** [comment]
I was wondering this also. By default it seems like if you call your project `example-project` it'll make the python package `example_project`. However, I'd rather the package be named `exampleproject`.

**Comment by sdispater** [comment]
At the moment, `poetry` looks automatically for the normalised project name as the package or module name.

Regarding a `src/` layout, this is supported in the `develop` branch and will be available in version `0.9.0`. Note, however, that `poetry` will still look for a package/module derived from the project name defined in `pyproject.toml`

**Comment by berislavlopac** [comment]
Just to make sure I understand, so the source layout will have to be something like this?

```
project/
    src/
        project/
            project.py
```

**Comment by sdispater** [comment]
Not exactly. Let's say the structure of your project is a package you would need to have something like this:

```text
my-package/
└── src/
    └── my_package/
        └── __init__.py
```

If your project is a module, it would be:

```text
my-package/
└── src/
    └── my_package.py
```

**Comment by berislavlopac** [comment]
Ah I see. Yes that makes sense.

Thanks for the explanation, I'll close this issue then and wait for `0.9.0`. :smiley:

**Comment by baggiponte** [comment]
> Not exactly. Let's say the structure of your project is a package you would need to have something like this:
> 
> ```
> my-package/
> └── src/
>     └── my_package/
>         └── __init__.py
> ```
> 
> If your project is a module, it would be:
> 
> ```
> my-package/
> └── src/
>     └── my_package.py
> ```

Just to make sure: this implies we don't have to specify *anything* about the project being in `src` in the `pyproject.toml` - because `poetry` will already know to look for your package inside `src`, am I right?

**Comment by iuriguilherme** [comment]
> Just to make sure: this implies we don't have to specify _anything_ about the project being in `src` in the `pyproject.toml` - because `poetry` will already know to look for your package inside `src`, am I right?

No, this assumption is incorrect. you need to add to the `pyproject.toml` the following:

```
[tool.poetry]
packages = [{include = "my_package", from = "src"}]
```

**Comment by novel-mistake** [comment]
> > Just to make sure: this implies we don't have to specify _anything_ about the project being in `src` in the `pyproject.toml` - because `poetry` will already know to look for your package inside `src`, am I right?
> 
> No, this assumption is incorrect. you need to add to the `pyproject.toml` the following:
> 
> ```
> [tool.poetry]
> packages = [{include = "my_package", from = "src"}]
> 

> > Just to make sure: this implies we don't have to specify _anything_ about the project being in `src` in the `pyproject.toml` - because `poetry` will already know to look for your package inside `src`, am I right?
> 
> No, this assumption is incorrect. you need to add to the `pyproject.toml` the following:
> 
> ```
> [tool.poetry]
> packages = [{include = "my_package", from = "src"}]
> ```

thx man i have been struggling 3 days hahah
