### ISSUE TITLE
Semver Resolution

### ISSUE THREAD

**Issue by vitiral** [sdispater/poetry#923]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Hey! I love the ideas and the tool.

I'm writing a general purpose package manager (github.com/vitiral/wake). For that I wanted general-purpose pkg resolution functionality. I looked at the poetry solution and it seemed messy, so I made my own.

I have working code and an architecture document and I would love your feedback!

- Architecture: https://github.com/vitiral/python-semanticversion/blob/master/ARCH_EDGES.md
- Code: https://github.com/vitiral/python-semanticversion/blob/master/tests/test_edge.py#L192

The basic idea is that I convert requirements into "edges", which are sent to the "server". The "server" returns the versions that meet those edges most closely.

I then reduce my dependency tree by filtering the versions by the specs in each dependency. I can then freely walk the tree, just keeping track of a lockfile which I clean up as I go (dynamic programming, backtracking).

It's pretty simple, and I was wondering if ya'll might be interested in making it part of poetry -- or at least drawing from some of the design ideas!

Thanks!

**Comment by sdispater** [comment]
> I looked at the poetry solution and it seemed messy

How so? Poetry uses the [PubGrub](https://github.com/dart-lang/pub/blob/master/doc/solver.md) algorithm which I invite you to read more about here: https://medium.com/@nex3/pubgrub-2fb6470504f

I am not looking to replace the current resolution which works reasonably well but thanks for your input and good luck on your project :-)

**Comment by vitiral** [comment]
Thanks for the link, that looks super cool!

**Comment by vitiral** [comment]
@sdispater the claim that is was "messy" was based on my impressions of `puzzle/` importing lots of areas of poetry. However, looking at the code it looks like version solving is actually done in `mixology/`. They both seem have to "solvers" though.

The mixology subpackage seems to have much fewer dependencies on the rest of poetry than `puzzle`. What is the difference between them?
