### ISSUE TITLE
wheel builder doesn't compress python source files

### ISSUE THREAD

**Issue by ojii** [sdispater/poetry#924]
poetry writes the metadata files using [`ZIP_DEFLATE`](https://github.com/sdispater/poetry/blob/271e995844db11a40c7c4a0b320bf9bd600db444/poetry/masonry/builders/wheel.py#L283) but the source files are [not compressed](https://github.com/sdispater/poetry/blob/271e995844db11a40c7c4a0b320bf9bd600db444/poetry/masonry/builders/wheel.py#L262). 

This is unlike [`wheel`](https://github.com/pypa/wheel/blob/24f7d3193606a371cfe830f6529adc2980aab9dd/wheel/wheelfile.py#L136-L137) which does store source files deflated. As a result poetry generated wheels can be much larger than the equivalent `bdist_wheel` generated one.

**Comment by ccosby** [comment]
Fixed in #838 that got merged today 2019-03-06.
