### ISSUE TITLE
Can't run `poetry run` in a subdirectory of a project

### ISSUE THREAD

**Issue by radix** [sdispater/poetry#93]
Hi, I have some projects which have scripts that are sensitive to the current working directory. I'd like to be able to run these scripts in a subdirectory of my python project, but `poetry run` doesn't work in that case because it can't find `./pyproject.toml`. This means I have to resort to `poetry run bash --noprofile --norc`, and then running my script in this subshell.

Would it be possible for `poetry` to search upwards until it finds a `pyproject.toml`?

**Comment by sdispater** [comment]
@radix This is already supported in the latest version (`0.9.0`)

**Comment by radix** [comment]
oh, sweet! sorry, I remembered this from a couple weeks ago and have been meaning to file it, and I finally got around to it but forgot to actually verify that it still exists... :scream: thanks @sdispater !
