### ISSUE TITLE
PyPI package metadata (sdist PKG-INFO)

### ISSUE THREAD

**Issue by ttymck** [sdispater/poetry#930]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux (4.20.12-arch1-1-ARCH)
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/ttymck/crucyble/blob/master/pyproject.toml

## Issue

I am having trouble effectively/seamlessly setting package info/metadata for PyPI uploads. This includes:
* project description (`long_description` and `long_description_content_type`)
* project classifiers

This is the current build script I am using: https://github.com/ttymck/crucyble/blob/master/bin/build.sh

It first runs `poetry build -f sdist` (i'm distributing a cython package, so sources only). Then I manually manipulate the source distribution archive (tarball) adding the readme + readme content type as well as additional classifiers (from a `etc/classifiers.txt` in source control) directly to the generated `PKG-INFO` file. I then zip the modified archive and upload it.

The issue appears to be in generating the PKG-INFO file for sdist formats. It's entirely possible I am mis-configuring my build.py or pyproject.toml, or have missed some directions regarding a setup.cfg, etc. If it is indeed a bug or requires a new feature, I would be happy to help define the requirements and work on a patch.

**Comment by orlnub123** [comment]
Surprisingly it does look like the sdist builder doesn't have feature parity with the wheel builder but I'm not sure if that's due to technical limitations of the PKG-INFO format. When comparing the two the license, description content type, and description fields seem to be missing.

**Comment by orlnub123** [comment]
Digging deeper it seems `distutils.core.setup` gets used instead of `setuptools.setup` in the generated `setup.py` which is a bit weird since it doesn't support the install_requires or python_requires arguments being passed to it. I'm guessing the `setup.py` is planned to get replaced with a `pyproject.toml` that installs via poetry which would solve this problem.

**Comment by ttymck** [comment]
Thanks for surfacing that @orlnub123 ! I'll start there and try to launch a patch and see what reaction it gets.

>  I'm guessing the setup.py is planned to get replaced with a pyproject.toml that installs via poetry which would solve this problem.

I think I've seen mention of that before. Do you know where that conversation is being had? (github issue, pypa mailing list, etc)

**Comment by orlnub123** [comment]
@ttymck I wouldn't know, it just seems like the logical thing to do since PEP 518 got implemented in pip.

**Comment by orlnub123** [comment]
I'm not sure how I missed this but the `pyproject.toml` file has always been included.

@ttymck Are you using twine to upload to PyPI? I don't think `poetry publish` has this issue.

**Comment by AndreGuerra123** [comment]
just published a package with poetry publish --build and no project description was produced although I have the README.md file in the root of project.

**Comment by orlnub123** [comment]
@AndreGuerra123 Have you specified the [readme](https://poetry.eustace.io/docs/pyproject/#readme) section in your pyproject.toml? I don't think poetry automatically detects it.

**Comment by remram44** [comment]
I ran into this. README is correctly specified, and the contents correctly appear in `setup.py` under `long_description`. However `twine check` reports:
```
Checking distribution dist/taguette-0.5.tar.gz: warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
warning: `long_description` missing.
```
Then when I upload to PyPI, no README appears.

I can confirm that there is no description in `PKG-INFO`.

**Comment by remram44** [comment]
Because of Poetry I now have a completely broken release out. I love Poetry and how it makes it simple for me to build packages, however I will not keep using it if those packages are broken.

I have built a new tarball manually, but that doesn't even fix my PyPI page. Is there a way to recover from this bug?

**Comment by sdispater** [comment]
Version `0.12.12`, which has just been released, fixes the metadata inconsistency between wheels and sdists.
