### ISSUE TITLE
Add an option for the install command to not create a virtual environment

### ISSUE THREAD

**Issue by funkyfuture** [sdispater/poetry#932]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

one of the reasons that sometimes speaks against using `poetry` for a project is its mostly hard-wired assumption that you want to use it in the context of a virtual environment.

use-cases, that deviate from that assumption,  would be the installation in a virtual machine of a CI solution where the extra overhead isn't needed (and thus a waste of resources) and the installation in a (Docker) container where a virtual environment isn't wanted.

the way to currently achieve that is

```shell
$ poetry config settings.virtualenvs.create false
$ poetry install
$ rm ~/.config/pypoetry
```

something like `poetry install --no-venv` would be more straigthforward imo.

i looked around the code, and my impression it that it isn't simple to achieve as the (not) virtual environment has already been selected at the point when `install`'s options are evaluated. maybe it should be a global option anyway, but i didn't look into that approach yet.

**Comment by sdispater** [comment]
Your use case is already mentionned here: https://poetry.eustace.io/docs/faq/#i-dont-want-poetry-to-manage-my-virtualenvs-can-i-disable-it

This is the recommended and only way to achieve what you want. Adding an option is neither desirable nor necessary, especially once #618 is implemented.

**Comment by funkyfuture** [comment]
well, i should have explicitly mentioned that i desire to use no configuration file at all in such situations (reflected in the 3rd step to deploy an application as referenced above). that makes that option both desirable and necessary.

**Comment by funkyfuture** [comment]
a sidenote regarding the context of using `poetry` to deploy into production environments: given [this overhead](https://github.com/sdispater/poetry/pull/933/files#r265990600) that is needed, a standalone script that can install a project would be superb.
