### ISSUE TITLE
Can not correctly resolve ipython's dependency from PyPI mirror

### ISSUE THREAD

**Issue by cenzhe** [sdispater/poetry#935]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04, 4.15.0-12-generic
- **Poetry version**: 0.12.11
- **python version**: 3.7.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/cenzhe/21eb5a88cb7ea29c1037438695c975c0

## Issue

I've searched around, there are many similar issues, but not quite the same. Some are solved for other problems, some are not. My problem here:

1. `poetry debug:resolve ipython -vvv` would resolve correctly when from PyPI.
2. Specifying any mirror would resolve no dependency. Output:

```
$ poetry debug:resolve ipython -vvv
Resolving dependencies...
   1: fact: cenzhe-pytoolkit is 0.1.1
   1: derived: cenzhe-pytoolkit
   1: fact: cenzhe-pytoolkit depends on ipython (*)
   1: selecting cenzhe-pytoolkit (0.1.1)
   1: derived: ipython (*)
bee: 61 packages found for ipython *
bee: The cache for ipython 7.3.0 is outdated. Refreshing.
bee: Downloading sdist: ipython-7.3.0.tar.gz
   1: selecting ipython (7.3.0)
   1: Version solving took 39.734 seconds.
   1: Tried 1 solutions.

Resolution results:

  - ipython (7.3.0)
```

I got three concerns:

1. sdispater explained the procedure of dependency resolving [here](https://github.com/sdispater/poetry/issues/301#issuecomment-405649519). Since mirrors of PyPI do not provide JSON API, it's OK the first JSON api check failed. When coming to download, why poetry is downloading the sdist instead of the wheel file? There is a `ipython-7.3.0-py3-none-any.whl` and a `ipython-7.3.0.tar.gz` file available, and the wheel file do have the correct info in `METADATA`. I assumed `pip` would download wheels in favor to sdists.
2. Following point 1, in the tarball, there is no `requires.txt` file, but there do have `setup.py` with `install_requires` and some modification code of `install_requires` for different platforms. Is it possible to check this for dependencies? I understand we wanted to enforce good practice, but is there any suggested ways to walk around the maybe "ill-behaving" packages?
3. `pip install ipython` can work just fine, BTW. I don't know how pip resolves the dependencies, maybe running the `setup.py`?

**Comment by sdispater** [comment]
This has already been fixed in commit 271e995844db11a40c7c4a0b320bf9bd600db444 which will land in the next bugfix release.

**Comment by cenzhe** [comment]
I assume it's not exactly the same problem. I just used the master code, but still downloading the sdist. Cache cleared. @sdispater

**Comment by cenzhe** [comment]
Here is how I "switched" to master code if that matters:

1. Check out the master code to `$GIT_REPO`.
2. Copied `$HOME/.poetry/lib/poetry/_vendor` to `$GIT_REPO/poetry/_vendor`.
3. Created a loader script just like `$HOME/.poetry/bin/poetry` except using a different path pointing to the git repo.
4. run from the new loader script.

To ensure using the master code, I even deleted the folder `$HOME/.poetry`.
