### ISSUE TITLE
Using poetry's resolver as a library

### ISSUE THREAD

**Issue by dgrnbrg** [sdispater/poetry#938]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hello, I am working on building better Python support for Bazel, and I'd like to use Poetry's resolver to decide what packages should be installed. Can you give me some pointers as to how to pass a set of top-level requirements to a which function and get back a set of dependencies at specific versions? I think this is done by `puzzle/solver.py`, but I'm not sure how to use this API. I'd be happy to contribute more detailed documentation if you could give me some pointers on how to use Poetry's resolver.

Thank you!

**Comment by bdangit** [comment]
@dgrnbrg poetry has an export option to get the `requirements.txt`.  ref: https://python-poetry.org/docs/cli/#export

```shell
poetry export -f requirements.txt > requirements.txt
```

**Comment by pradyunsg** [comment]
You might want to look at mixology, which is poetry's resolver in a standalone library. However, I don't think that's in sync with what poetry is using currently, so there might be some critical omissions / differences.
