### ISSUE TITLE
Resolver fails for git dependency

### ISSUE THREAD

**Issue by dmfigol** [sdispater/poetry#939]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.3
- **Poetry version**: 0.12.11

`pyproject.toml`
```
[tool.poetry]
name = "test-poetry"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.6"
nornir = { git = "https://github.com/nornir-automation/nornir", branch = "develop" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
## Issue

`poetry install` fails:
```
-> % poetry install -vvv
Using virtualenv: /Users/dmfigol/work/tmp/test-poetry/.venv
Updating dependencies
Resolving dependencies...
   1: fact: test-poetry is 0.1.0
   1: derived: test-poetry
   1: fact: test-poetry depends on nornir (*)
   1: selecting test-poetry (0.1.0)
   1: derived: nornir (*)
   1: fact: nornir (2.0.0) requires Python >= 3.6, < 3.8
   1: derived: not nornir (2.0.0)
   1: fact: no versions of nornir match !=2.0.0
   1: conflict: no versions of nornir match !=2.0.0
   1: ! nornir (!=2.0.0) is partially satisfied by not nornir (2.0.0)
   1: ! which is caused by "nornir (2.0.0) requires Python >= 3.6, < 3.8"
   1: ! thus: nornir is forbidden
   1: ! nornir (*) is satisfied by nornir (*)
   1: ! which is caused by "test-poetry depends on nornir (*)"
   1: ! thus: version solving failed
   1: Version solving took 2.356 seconds.
   1: Tried 1 solutions.
```

**Comment by techdragon** [comment]
It kind of looks like it could be related to #991 but it also looks like it could be due to the version of python not being 3.6 or higher or the lock file not matching the pyproject.toml. I would be interested to see if the output was the same for `poetry install -vvv` after running `poetry lock -vvv` since I've noticed that sometimes running `poetry lock` explicitly, seems to result in more 'correct' behaviour, but i'm not sure why.
