### ISSUE TITLE
Proposal: concise poetry run

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#940]
My colleague is working to verse our codebase, and I get to review the change.
I see that most poetry `run` invocation are:
* `poetry run python`
* `poetry run pip`
* `poetry run pytest`

I with that python, pip, pytest were first-class citizens.

That is:
`poetry run python` becomes `poetry python`
`poetry run pip` becomes `poetry pip` (arguably poetry own functionality should be used instead)
And then:
`poetry run pytest` becomes `poetry pytest`
`poetry run <entrypoint>` becomes `poetry <entrypoint>`

The last part is a little more involved, but the logic is the same, check if argument is an "executable" (python, script, package entry point), and if so, run it.

**Comment by ojii** [comment]
While originally #241 was not about this, it has now turned into a discussion about adding something like this, so this is probably a duplicate.

Note that you can also `poetry shell` to activate the virtualenv and not having to type `poetry run ...` all the time.

**Comment by hangtwenty** [comment]
I like this intent and I think it could do a lot to address #241 and an alternative to #591. 

I do have hesitations about the 'overloading' ... Something is not _quite_ Pythonic about it (i.e. namespaces are Pythonic, and this is circumventing namespacing a little bit, even though it's in a simple-enough-to-explain way)

**Comment by sdispater** [comment]
This would confusion, or even collision in some cases, so this is not something I am willing to add to Poetry
