### ISSUE TITLE
brew install poetry

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#941]
Publish poetry on Homebrew;
Update docs to include macOS: `brew install poetry`

**Comment by Djailla** [comment]
Might be tricky as poetry is linked to a Python version

**Comment by andrew-humu** [comment]
Couldn't the formula do whatever the recommended install script does now?

https://poetry.eustace.io/docs/#installation

**Comment by sdispater** [comment]
If someone wants to tackle this, they are welcome to do it but that's beyond the responsibilities of the Poetry's maintainers.

**Comment by domoritz** [comment]
I think offering a brew installation would make poetry much more useful to many developers. Yes, it's not a responsibility of the poetry maintainer but it would be super sweet if updates were available on brew without too much delay.

**Comment by AlJohri** [comment]
linking this here: https://github.com/Homebrew/homebrew-core/pull/41055
