### ISSUE TITLE
install package if not on given platform (e.g. do not install pdbpp on windows)

### ISSUE THREAD

**Issue by vlcinsky** [sdispater/poetry#942]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I want to install `--dev` dependency `pdbpp` only, if not on Windows (where it does not work well for my colleague).

Using PEP508 Environment markers would serve this purpose, but this is (not yet) supported by poetry.

According to issues, platform can be expressed, but only in positive manner.

Is there an option to say "not on win32" platform?

N.B. In long term, support for PEP508 environment markers would be great.

**Comment by hangtwenty** [comment]
@vlcinsky does it not work to put it under 'extras' instead of relying on a single concept of `dev`?

**Comment by sdispater** [comment]
Full environment markers are now supported, see #1142
