### ISSUE TITLE
Does poetry support custom tasks?

### ISSUE THREAD

**Issue by dclong** [sdispater/poetry#954]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

Both Gradle (build tool for JVM) and pybuilder (another build tool for Python) support custom tasks easily, which is convenient. Does poetry support custom tasks?

**Comment by jacebrowning** [comment]
Is this a duplicate of https://github.com/sdispater/poetry/issues/241?

**Comment by dclong** [comment]
@jacebrowning From the [doc](https://poetry.eustace.io/docs/pyproject/#scripts) scripts get installed when installing the package, so scripts are not the same as user tasks. A user task can be a short Shell/Python script do a simple work, e.g., to help you copy/upload the package to a specific location.

**Comment by jacebrowning** [comment]
Please read https://github.com/sdispater/poetry/issues/241#issuecomment-398767327, I still think this is a duplicate. 😄

**Comment by hangtwenty** [comment]
definitely a duplicate

**Comment by dclong** [comment]
@jacebrowning @hangtwenty I went over the comments in the issue #241, now I see that this is a duplicate.

**Comment by nat-n** [comment]
You can get custom tasks for poetry via a plugin like [poethepoet](https://github.com/nat-n/poethepoet)
