### ISSUE TITLE
Subdirectory property in git links

### ISSUE THREAD

**Issue by mgawino** [sdispater/poetry#961]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

Poetry does not allow for installing dependencies from a VCS repository which has .toml/setup.py file not in root directory. As an example you can do that in pip by using this command: https://stackoverflow.com/a/19516714 

Subdirectory property is not used when installing dependencies from a git repository. It looks like property can be extracted from git link: 
https://github.com/sdispater/poetry/blob/master/poetry/packages/utils/link.py#L127
but is not taken into account after checking out a git repository. (directory is not changed to specified subdirectory). Directory switch should happen here: https://github.com/sdispater/poetry/blob/master/poetry/puzzle/provider.py#L177

**Comment by finswimmer** [comment]
Duplicate of #755
