### ISSUE TITLE
Support for global configuration

### ISSUE THREAD

**Issue by funkyfuture** [sdispater/poetry#964]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

i'm in a situation where i provide environments for developers in which they can work mostly autonomously. of course i want to ensure that some good practices in that context are complied with. hence i would like a configuration for `poetry` that applies to all users of a system.

in my case it would be fine to have a `POETRY_CONFIG_LOCATION` environment variable that can point to a `poetry.toml`.

**Comment by hangtwenty** [comment]
There is already support for this.

📘 https://github.com/sdispater/poetry/blob/master/docs/docs/configuration.md#configuration

**Comment by funkyfuture** [comment]
no, that variable should point to a user specific location (on my Ubuntu it isn't set at all). one could hence `alias poetry="XDG_CONFIG_HOME=/etc poetry"`. but, nah.

**Comment by damienflament** [comment]
As stated by @hangtwenty , the user configuration file is located at `XDG_CONFIG_HOME/pypoetry/config.toml`.

As stated by the [XDG Basedir Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), `XDG_CONFIG_HOME` defaults to `~/.config` if not set.

And Poetry [does it well](https://github.com/sdispater/poetry/blob/c7e90485c5485f0c7a39084ff9d684a3a266d3db/poetry/utils/appdirs.py#L131).

The `XDG_CONFIG_HOME` does not have to be set by your Linux distribution. You have to set it explicitly if you want to use a location different from the default.

**Comment by funkyfuture** [comment]
that's not the point of this issue. i'd like to tell `poetry` a user-*un*specific location of the configuration.

**Comment by drunkwcodes** [comment]
This feature will require privilege to deploy, and the configuration will be too complex for poetry.

It seems to be for personal use by design, and the configuration is formal and scriptable.

**Comment by hangtwenty** [comment]
> that's not the point of this issue. i'd like to tell `poetry` a user-_un_specific location of the configuration.


> no, that variable should point to a user specific location (on my Ubuntu it isn't set at all). one could hence `alias poetry="XDG_CONFIG_HOME=/etc poetry"`. but, nah.

@funkyfuture you are in control of your own environment variables.  Can you give any practical reason for your "nah"? I'm not being snarky; I really think there needs to be a practical reason provided for this.

**Comment by funkyfuture** [comment]
it is not about whether i want to control my own environment variables. i want to control the `poetry` configuration of all system users.

my 'nah' expresses, that this workaround would work, but it is not a solution.

**Comment by drunkwcodes** [comment]
@funkyfuture You can achieve that with trust and group policy only...
The settings will still be over ridden by user config even when reading config twice.

**Comment by hangtwenty** [comment]
I’ve come around to agreeing with OP @funkyfuture that a POETRY_CONFIG_DIR or somesuch would make sense. I’ve recently written scripts at my day job, where it bootstraps Poetry and the config defaults we recommend. Had to do some wonky OS-specific shell scripting to make it work smoothly.
