### ISSUE TITLE
Setup script should fail gracefully if ~/.bash_profile not writeable

### ISSUE THREAD

**Issue by harrybiddle** [sdispater/poetry#966]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I just installed poetry using the `get_poetry.py` script, ran using the curl command in the docs.

However, the script failed because my `~/.bash_profile` isn't writeable (I have this deployed from version control):

```
Installing version: 0.12.11
  - Downloading poetry-0.12.11-darwin.tar.gz (7.14MB)
Traceback (most recent call last):
  File "<stdin>", line 859, in <module>
  File "<stdin>", line 855, in main
  File "<stdin>", line 328, in run
  File "<stdin>", line 462, in install
  File "<stdin>", line 610, in update_path
PermissionError: [Errno 13] Permission denied: '/Users/harry/.bash_profile'
```

This left me in a state where I wasn't sure if the script had completed or not. I made `~/.bash_profile` writeable and ran it again, and it said "Latest version already installed". I still didn't trust it all went OK, so be sure I had to uninstall and re-install!

How about we make the install script continue on a failure to update `~/.bash_profile`, and just instaed print this as a warning at the end of the script that the user needs to update their PATH themselves? (I.e. the behaviour when you answer _Modify PATH variable? ([y]/n) n_) This is the approach that brew takes, and was also suggested by @sdispater over on https://github.com/sdispater/poetry/issues/342#issuecomment-408470755.

I'd be happy to give the PR a shot myself..

**Comment by harrybiddle** [comment]
Oddly, `get-poetry.py` also fails to write to `~/.bash_profile` even if I don't ask it to update my `$PATH`...

```bash
$ python3 get-poetry.py
Retrieving Poetry metadata

Before we start, please answer the following questions.
You may simply press the Enter key to leave unchanged.
Modify PATH variable? ([y]/n) n

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path needs to be in your `PATH` environment variable,
but will not be added automatically.

You can uninstall at any time with `poetry self:uninstall`,
or by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 0.12.11
  - Downloading poetry-0.12.11-darwin.tar.gz (7.14MB)
Traceback (most recent call last):
  File "get-poetry.py", line 859, in <module>
    sys.exit(main())
  File "get-poetry.py", line 855, in main
    return installer.run()
  File "get-poetry.py", line 328, in run
    self.install(version, upgrade=current_version is not None)
  File "get-poetry.py", line 462, in install
    self.update_path()
  File "get-poetry.py", line 610, in update_path
    with open(profile, "a") as f:
PermissionError: [Errno 13] Permission denied: '/Users/harry/.bash_profile'
```

**Comment by drunkwcodes** [comment]
The bug is in https://github.com/sdispater/poetry/blob/master/get-poetry.py#L310
