### ISSUE TITLE
Installing hypothesis 4.14.0 fails

### ISSUE THREAD

**Issue by greysteil** [sdispater/poetry#972]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13.6
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: see below

## Issue
Poetry can't install the latest version of `hypothesis`. To replicate run `pyenv exec poetry lock` on the following `pyproject.toml`:

```
[tool.poetry]
description = "A test of whether poetry can install hypothesis 4.14.0"
authors = ["greysteil"]
license = "MIT"
name = "hypothesis-testing"
version = "0.1.0"

[tool.poetry.dependencies]
hypothesis = "4.14.0"
```

Installing `hypothesis` 4.13.0 works fine.  The above should work fine on Python 3.6 and 3.7, but doesn't.

**Comment by greysteil** [comment]
Actually, think this might be a problem with `hypothesis`. Closing until I can confirm.

**Comment by greysteil** [comment]
Digging in, the only change in Hypothesis between these versions is [this one](https://github.com/HypothesisWorks/hypothesis/commit/506cd872bf83b786f26aca9572dc3089686e083c). I can't see why that would break the install on Python versions other than 3.4. Any ideas?

**Comment by jacebrowning** [comment]
Can you share the error message you see?

Your `pyproject.toml` doesn't call out the supported Python versions, should it?

**Comment by greysteil** [comment]
Of course - can you not replicate?

```
[SolverProblemError]                                                                                                                            
The current project must support the following Python versions: *                                                                                            
Because hypothesis-testing depends on hypothesis (4.14.0) which requires Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, version solving failed.  
```

**Comment by jacebrowning** [comment]
Your project claims to support all versions of Python (`*` is the default), but some of your dependencies cannot meet that requirement so resolution fails.

Try adding `python = "^3.6"` under `[tool.poetry.dependencies]`.

**Comment by greysteil** [comment]
That works but this still seems like a bug, no?

**Comment by jacebrowning** [comment]
If you were to publish this package to PyPI, it would indicate that your package supports Python 3.4 (as you have not declared which versions of Python your package supports). Then, when someone attempts to install your package in a Python 3.4 virtual environment, the installation will fail because `hypothesis-testing` doesn't support Python 3.4.

Poetry is ensuring that this situation is impossible.

**Comment by greysteil** [comment]
Ah, interesting.

So how come it works fine with `4.13.0`?

```
[tool.poetry]
description = "A test of whether poetry can install hypothesis 4.14.0"
authors = ["greysteil"]
license = "MIT"
name = "hypothesis-testing"
version = "0.1.0"

[tool.poetry.dependencies]
hypothesis = "4.13.0"
```

**Comment by greysteil** [comment]
Ah, I'm guessing it's because Python 3.4 only just EOL-ed, and Poetry hasn't been updated for that? https://archives.gentoo.org/gentoo-dev-announce/message/0bc6c7dc5b4136221953622b81d24c79
