### ISSUE TITLE
--no-root behavior is inverted on latest develop

### ISSUE THREAD

**Issue by K900** [sdispater/poetry#973]
[This](https://github.com/sdispater/poetry/commit/37ec1447b3508ee0bbdb41f8e5773ed5bfae0654#diff-427299ba040b8502b4d29846e595c2d0R59) should probably be `if self.option("no-root")`, to _not_ install the root package when `--no-root` is provided.

**Comment by K900** [comment]
CC @seleem1337

**Comment by seleem1337** [comment]
Thanks! I'll create a PR shortly

**Comment by K900** [comment]
I guess we can close this now
