### ISSUE TITLE
Bad UX "poetry version"

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#987]
Every now and again, I want to know what version of `poetry` I'm using.
Typically, it's to post a big report here.
Being me (i.e. expecting "Python" to do the right thing), I run `poetry version`.
And what does it do? It changes version of the package in the directory where I happen to be 👿 

Please, please change this!

**Comment by drunkwcodes** [comment]
Do you mean renaming the subcommand like #629 said?

**Comment by dimaqq** [comment]
That would work too and solve my mis-use case.

**Comment by jacebrowning** [comment]
In that case, I think this should be closed as a duplicate.

**Comment by cjw296** [comment]
@dimaqq - yeah, please can you close and we can track on #629?

**Comment by dimaqq** [comment]
Closing in favour of #629
