### ISSUE TITLE
poetry run vs poetry script

### ISSUE THREAD

**Issue by mmerickel** [sdispater/poetry#99]
It seems to me that it's not strictly necessary for these two operations to be separate commands. I propose having `poetry run` resolving scripts first then falling back to current behavior. This would be more similar to `npm run` or `yarn run` which operate on scripts defined in package.json or scripts installed from dependencies.

I'm not clear on why they are separate now - if it's configuring entrypoints then I'd point out that in both cases I'd want the entry points to be installed incase I'm doing something like `poetry run flake8` where my project provides a flake8 plugin via entrypoint.

**Comment by sdispater** [comment]
`script` is deprecated as of release `0.10.0` and you can now use run to do the same thing.
