### ISSUE TITLE
Cancelling installation of a package does not allow it to be installed again

### ISSUE THREAD

**Issue by xelibrion** [sdispater/poetry#998]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Gentoo Linux
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/xelibrion/154868382d0147d903318dfa22c549c3/raw/9ec85e79a885c8a43694e01a9d926ff64a48b3ab/pyproject.toml

## Issue

1. Download the Gist
2. Run `poetry add torch`
3. Wait until you see `- Installing torch` message
4. Press Ctrl-C
5. Run `poetry add torch` again

### Expected behaviour
Package installation continues. 

### Observed behaviour
Received error
```
poetry-test ➜ poetry add torch                                                                                                                                                               master
                                    
[ValueError]         
Package torch is already present  
                                    
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

```

Now, I am aware that there are `poetry install` and `poetry update` commands that would alleviate the problem, it just seems that developer experience is not exactly smooth in this particular case.

**Comment by drunkwcodes** [comment]
I will write a faq if there is a wiki.
